### ISSUE TITLE
rbd-provisioner: `rbd` command hangs with insufficient configuration, no log output

### ISSUE THREAD

**Issue by briantopping** [kubernetes-incubator/external-storage#1000]
When the provisioner calls `rbd`, if the configuration is incorrect, the command hangs and no logs are generated. Without logging into the container, it is difficult to determine what is going on. 

It may be helpful if the exec could timeout and report the failure rather than simply hang.

Similarly, at a higher verbosity level, it would be helpful to print the full `rbd` command so that it could easily be tested at the rbd container command line when there are problems.

**Comment by Zyqsempai** [comment]
I can take this one.
