### ISSUE TITLE
When a node is recreated with same name but different uid, local-volume-provisioner fails

### ISSUE THREAD

**Issue by lbernail** [kubernetes-incubator/external-storage#1001]
Hello

We been facing the issue described in  #945
The solution proposed in the issue suggests to not use the node UID in the `pv.kubernetes.io/provisioned-by`
However the local-volume is actually a different one (the new local-volume will be empty). I was wondering if we could include the node-uid in the pv name hash function (https://github.com/kubernetes-incubator/external-storage/blob/784da0987c3616400c9a3b0de71bb5e0a6d58ac7/local-volume/provisioner/pkg/discovery/discovery.go#L285). We could control this behavior based on the `UseNodeNameOnly` config option

/area local-volume

**Comment by msau42** [comment]
Hi @lbernail, when a node gets recreated but the disks are actually different, then I would actually suggest you setup those disks with a uuid built into the path.  Here's some background discussion on the issue: https://github.com/kubernetes/kubernetes/issues/51431.  In GKE, we have an option (available through whitelist) that will use unique UUIDs as the disk name for this exact issue.

The danger of using node-uid in the pv name while path is still the same is that multiple pods could end up using the same disk, causing data corruption.  The provisioner itself could also end up deleting data in use when cleaning up the first PV. For example:
1. Node UID A, local PV1 at /mnt/disk1. 
2. Pod A is using PV1
3. Node gets recreated, node UID B, a new disk at the same /mnt/disk1.
4. PV2 gets created with /mnt/disk1.
5. Pod B starts using PV2.  But Pod A is still using PV1, and they're both writing to the same path = data corruption.
6. PV1 could be deleted at any time.  Local provisioner could cleanup the data from the path, even though PV2 is using the same path.

**Comment by lbernail** [comment]
Thank you for your feeback, this really makes sense
I think we'll try do it the way you suggest: don't use node-id anymore and rely on uuid-based mountpaths

**Comment by lbernail** [comment]
After thinking about it I have some quick follow-up questions on garbage collection of old PVs:
- when you said PV1 could be deleted at any time, does this mean that the local-volume-provisioner will remove PV with invalid mountpaths (and so unbind them from their existing PVC)?
- what happens to Pod A? if the node is recreated fast enough it might still be scheduled to the new node. Will the pod fail to start because the volume cannot be mounted ? If so will it be rescheduled once the old PV and PVC are garbage collected?
- if a node is really deleted and does not come back, how do you perform PV garbage collection (we have an additional controller to remove these orphan volumes but I would be interested in knowing what the usual best practices are)

Thank you again

**Comment by msau42** [comment]
> * when you said PV1 could be deleted at any time, does this mean that the local-volume-provisioner will remove PV with invalid mountpaths (and so unbind them from their existing PVC)?

I meant that the user can delete the PVC at any time (before or after the node is recreated, before or after PV2 is created)

> * what happens to Pod A? if the node is recreated fast enough it might still be scheduled to the new node. Will the pod fail to start because the volume cannot be mounted ? If so will it be rescheduled once the old PV and PVC are garbage collected?

Pod A will be able to mount the volume if: 1) PVC + PV still exists  2) the mount path still exists 3) new node has the same name

> * if a node is really deleted and does not come back, how do you perform PV garbage collection (we have an additional controller to remove these orphan volumes but I would be interested in knowing what the usual best practices are)

Yeah, it has to be an external controller that does the garbage collection since the DaemonSet cannot spawn a pod on a non-existing node.  There is definitely a lot of room for improvement in this area, especially if workloads are able to recover from a lost disk.

**Comment by msau42** [comment]
Please open a new issue in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner if you still have problems

/close
