### ISSUE TITLE
Local storage provisioner should support creating PVs with block and file system type

### ISSUE THREAD

**Issue by gnufied** [kubernetes-incubator/external-storage#1003]
In 1.12 - to use local storage with file system, it will be no longer necessary for format and mount the block devices before using them. Kubernetes can do that itself, but the PV created by local storage provisioner must have `FSType`  set.

I think configmap format used by local storage provisioner needs to be updated to support creating PVs that could be later formatted by Kubernetes.

cc @jsafrane @NickrenREN @msau42

**Comment by msau42** [comment]
This should covered by #980

**Comment by msau42** [comment]
Dup of #973

**Comment by gnufied** [comment]
heh. I am glad someone beat me to it. :-)
