### ISSUE TITLE
Adding "archiveOnDelete" option to nfs-provisioner

### ISSUE THREAD

**Issue by cloud-jeong** [kubernetes-incubator/external-storage#1004]
Dear all,
I'm trying to use nfs-provisioner to GKE cluster.

One thing we really need is the "archiveOnDelete" option such as nfs-client-provisioner.
Can you please add this feature?

Thanks.

**Comment by msau42** [comment]
Hi, can you use Retain reclaim policy to achieve a similar effect?

**Comment by cloud-jeong** [comment]
Yes. If you use the retain reclaim policy option, the directory which used for pvc will remained. Great.
However, if you move directory name within "archived" prefix then It is easy to see if it's deleted.

Thanks.

**Comment by wongma7** [comment]
Yes, this is ok with me. But unlike nfs-client it will need to default "false" instead of "true"
/area nfs

**Comment by heamaral** [comment]
It would be great If displays in the format:
namespace-pvcname...
archived-namespace-pvcname...
