### ISSUE TITLE
Provisioner for creating PVCs based on a subdirectory on a Gluster Volume

### ISSUE THREAD

**Issue by nixpanic** [kubernetes-incubator/external-storage#1007]
Looking to get more feedback about tis topic. The previous [email to sig-storage](https://groups.google.com/forum/#!msg/kubernetes-sig-storage/EqADeu8N3nw/L9zhy-LKCgAJ) did not gain any discouraging replies, though only very few in total. @humblec suggested to file a GitHub Issue instead.

# TL;DR

A proposal for a new external-storage Gluster Subvol provisioner that creates PVCs as subdirectories on an existing PVC. It is currently Gluster only, but does not have to be.

- https://github.com/nixpanic/external-storage/tree/testing/gluster/subvol/gluster/subvol
  (see the README.md and examples/README.md for more details)

# Introduction

The current external Glusterfile provisioner works quite well, and supports the features that are currently needed. However, on large scale environments (1000ths of PVs), the way of provisioning does not scale well enough. There is a lot of management overhead involved in maintaining the state of all these PVs (which are their own Gluster Volumes).

Now, GlusterFS is a filesystem, and is more optimized for filesystem operations than for volume management. With current maintained releases, Gluster supports mounting of subdirectories, very similar to NFS. By creating one (or more) large Gluster Volumes, and setting up subdirectories for each PV, the management overhead on the Gluster side reduces enormously.

In addition to this, cloning a PVC only does filesystem operations and will work when at least the majority of Gluster Storage servers is available. For Gluster Volume level cloning, all Storage servers need to be functional for synchronizing the management operations.

# Current Status

The provisioner is very loosely based on the existing gluster/file one. At the moment, standard (de)provision functionality is working quite nicely. Initial testing is being done, but the code is still being worked on.

The work in progress tree can be found here:

- https://github.com/nixpanic/external-storage/tree/testing/gluster/subvol/gluster/subvol
  (see the README.md and examples/README.md for more details)

Automated builds of the container image are enabled in Quay.io for now. The above `.yaml` uses
https://quay.io/repository/nixpanic/k8s-external-storage with tag `:testing_gluster_subvol` already.

The steps to get on with testing are pretty simple:

1. deploy the provisioner

   ```
   $ kubectl apply -f deploy/gluster-subvol-provisioner-pod.yaml
   ```
  
2a. create a regular Gluster PVC (assumes glusterfile StorageClass)  
2b. create a StorageClass pointing to the PVC and provisioner

   ```
   $ kubectl apply -f examples/class.yaml
   ```

Now everything is ready to create PVCs through the Gluster subvol provisioner.

   ```
   $ kubectl apply -f examples/claim.yaml
   ```

# Cloning Support (or, why no CSI-driver?)

One of the main initiators of this provider is to provide a fault tolerant and easy manageable way to support cloning of Gluster PVCs. Mainly without the drawbacks and limitations of using LVM and Gluster Volume snapshots.

Because there is no stable Gluster driver for CSI yet, and the CSI specification only recently has adopted cloning, the only reasonable way to implement the features is by using the external-storage API.

This storage provisioner supports the k8s.io/CloneRequest annotation that Containerized-Data-Importer (the KubeVirt CDI project) attempts to utilize.

# Future Work

The provisioner does not tie in with Gluster closely. At the moment it only knows about the PV.Spec.Glusterfs configuration and how to mount a Gluster Volume with "mount -t glusterfs ...". But this can easily be extended to other filesystems that support ReadWriteMany permissions.

I hope that this model also can be made to work through CSI. But that is something to look into at a later time. 

/assign humblec
/kind feature
/cc aglitke obnoxxx

**Comment by wongma7** [comment]
Sounds good to me.

Note there is a little bit of an effort to break the repo up since some of the things hosted here have proven they have the userbase to justify their own repos (and the process for having a kube community repo has been formalized), & it would make individual maintenance/releases easier. However I don't think I can simply link to an external repo as an endorsement since then that brings up some CLA and license trouble and such, so I have no problem merging a new provisioner.

The k8s.io/CloneRequest annotation is interesting..I think k8s.io annotations are "reserved" by convention and I'm unsure about the camelcase :) so IDK if kubevirt could pick another name to avoid future conflict.

**Comment by wongma7** [comment]
note also this sounds similar to nfs-client which just does `mkdir` in some nfs mount and not much else https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go

**Comment by aglitke** [comment]
> Sounds good to me.
> 
> Note there is a little bit of an effort to break the repo up since some of the things hosted here have proven they have the userbase to justify their own repos (and the process for having a kube community repo has been formalized), & it would make individual maintenance/releases easier. However I don't think I can simply link to an external repo as an endorsement since then that brings up some CLA and license trouble and such, so I have no problem merging a new provisioner.
> 
> The k8s.io/CloneRequest annotation is interesting..I think k8s.io annotations are "reserved" by convention and I'm unsure about the camelcase :) so IDK if kubevirt could pick another name to avoid future conflict.

Hey.  That annotation was chosen for the standalone-cinder provisioner back when it lived in this repo.  The goal was to agree on a standard annotation that all provisioners could use.  I agree it's not perhaps the best choice but it's already in-use.  Looking forward (k8s-1.13) we are looking to request cloning via a DataSource element in the PVC spec.

**Comment by nixpanic** [comment]
On Mon, Oct 01, 2018 at 04:58:12PM +0000, Matthew Wong wrote:
> Sounds good to me.

Thanks!

> Note there is a little bit of an effort to break the repo up since some of the things hosted here have proven they have the userbase to justify their own repos (and the process for having a kube community repo has been formalized), & it would make individual maintenance/releases easier. However I don't think I can simply link to an external repo as an endorsement since then that brings up some CLA and license trouble and such, so I have no problem merging a new provisioner.

Ok, it is my preference to have the provisioner as part of
external-storage. I could probably place it in its own repository under
the Gluster organization as an alternative, but would rather not.

I plan to send a PR with the provisioner today or tomorrow. You should
see a note in this issue once it is available.

**Comment by nixpanic** [comment]
There is currently no interest in adding the Gluster Subvol Provisioner to the external-storage repository. See #1013 for a bit more details.

/close
