### ISSUE TITLE
defaultFailedProvisionThreshold   looks to be  really low.

### ISSUE THREAD

**Issue by humblec** [kubernetes-incubator/external-storage#101]
This threshold value has been set to ` 5` at present in the controller.  There may be scenarios where user still create the required artifacts after firing the pvc.  for eg# creating a secret or recreating a storageclass..etc.  As there are no more attempts made for the `claim` after this failure,  it will be bad user experience  for a user/developer. Can I increase the this value to more attempts or more time waiting ?

**Comment by humblec** [comment]
@wongma7 please share your thought. I will send a patch accordingly.

**Comment by wongma7** [comment]
sure, 5 is too low for exponentialbackoff to have any effect. 10 or something would be better
