### ISSUE TITLE
how does this compare to https://github.com/jmespath/go-jmespath

### ISSUE THREAD

**Issue by schollii** [kubernetes-incubator/external-storage#1010]
how does this compare to https://github.com/jmespath/go-jmespath

**Comment by wongma7** [comment]
totally unrelated

**Comment by schollii** [comment]
I meant: how does external-storage/vendor/github.com/jmespath/go-jmespath/ compare to https://github.com/jmespath/go-jmespath? Looks like the one in external-storage is a fork, or what? But the source seems very different.

**Comment by schollii** [comment]
OK thanks. I was hoping this meant eventual jmespath support in kubectl but I was mistaken...
