### ISSUE TITLE
Consider using full disk path and just node name for generate PV names

### ISSUE THREAD

**Issue by gnufied** [kubernetes-incubator/external-storage#1014]
Currently for local-storage PVs we are using file name, node name and storage class name. We should consider removing storage class name and just use full path and node name. This will ensure that, if another copy of provisioner runs on the same node, it is unable to create PVs for same disk.

cc @msau42 @lichuqiang

**Comment by msau42** [comment]
We can't change the name without breaking backwards compatibility, it would have to be a new option.

Alternatively, is there a better way to prevent multiple provisioners from being run?  Can the operator detect that one is already running and not create a second one?

**Comment by wongma7** [comment]
maybe for 1.13 the provisioner can do some kind of leader election? I assume running more than 1 instance/daemonset on the same set of nodes is almost always a mistake

**Comment by msau42** [comment]
You would need each node to have its own leader election.

Why can't the operator detect if it has already created a daemonset?

**Comment by gnufied** [comment]
When we say "Why can't the operator detect if it has already created a daemonset" the question becomes what constitutes a daemonset. An admin can select bunch of nodes and some disks and create local storage CR that ultimately will create provisioner daemonset.  if another admin selects same nodes and disks but may be subtly different and creates the CR then it will result in creation of another daemonset which may be subtly different.

So both the daemonsets will go ahead and provision PVs with same disks. I think, the final protection should be within the provisioner itself. Detecting duplicate daemonset creation which targets same nodes and disks can be problematic.
