### ISSUE TITLE
Progress in dynamic provisioning for shared local persistent storage?

### ISSUE THREAD

**Issue by diptadas** [kubernetes-incubator/external-storage#1015]
For one of our tool, we need a shared local storage among containers running inside same/different pods. Currently, we are dealing this with `hostpath` volume. Can anyone give me an update on the progress in "Dynamic provisioning for shared local persistent storage" [feature](https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume#future-features)? Or any suggestions for a better alternative?

cc @msau42 @tamalsaha

**Comment by msau42** [comment]
Someone wrote a hostpath provisioner, which could work if you don't need capacity enforcement.

Otherwise @lichuqiang is working on a dynamic provisioner based off of lvm.

**Comment by tamalsaha** [comment]
Thanks @msau42 . Is there a repo that we can follow? Also, I saw you mention on Twitter that this will be converted to CSI driver. Any update on that?

**Comment by msau42** [comment]
https://github.com/kubernetes/community/pull/1914 currently has an outdated proposal, but will be updated.

**Comment by lichuqiang** [comment]
Sorry to confuse you folks.
I've been on vacation these days, and I'll update the proposal once I'm back to the office (by the end of next week I think).
