### ISSUE TITLE
cephfs: nonroot users inside container can not create subdirs on mounted volume

### ISSUE THREAD

**Issue by betonmoewe** [kubernetes-incubator/external-storage#1018]
Hello,

I try to use the  cephfs-provisioner for dynamic volume claims. 
The provision itself is fine, but if I try do create dirs as non-root user within the volume mount, I got "permission denied". As root user, erverything is fine. As workaround, I have mounted the cephfs filesystem too and do a chmod 777 on this newly from the provisioner dynamicly created directory.
How can I change this behaviour?
With "nfs-client" (ganesha nfs server)  everything is fine ...

Best regards
Betonmoewe

**Comment by MartinForReal** [comment]
how about changing the owner of dir using initializer? https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/

**Comment by betonmoewe** [comment]
If this were my pod, I would try it, but unfortunately I had the problem with the helmet chart for gitlab. I've currently solved it with the nfs client extension. But it would be better to have a solution with a parameter under which the mount should run.

**Comment by wongma7** [comment]
Seems related to https://github.com/kubernetes-incubator/external-storage/issues/515
/area ceph/cephfs

**Comment by whereisaaron** [comment]
@betonmoewe some charts include settings for `initContainers` or `extraInitContainers` you could propose that for gitlab chart.

https://github.com/helm/charts/blob/master/stable/mysql/values.yaml#L49-L52
```
extraInitContainers: |
  # - name: do-something
  #   image: busybox
  #   command: ['do', 'something']
```

**Comment by canadiannomad** [comment]
I kinda wish there was a way we could send the user/group for creation to the PVC via an annotation.. 
Right now I end up mounting the cephfs drive and running 
`chmod 777 .` from within the pvc-volume.
Once the pod has loaded I run `ls -n` and find out the UID/GID in use..
Then I run `chown <uid>:<gid> .; chmod 755 .`

This solves it for this PV, but then I'm just waiting for the next one.

The initContainers sounds like a reasonable solution except that it will mean that I have to take on maintaining any helm charts that don't expose it in their values.yaml

**Comment by CamelCaseNotation** [comment]
Requiring users to modify Pod specs is not an acceptable solution when kubernetes itself recommends to _not_ ever write Pods by hand. It also means any YAML used that's not written by the user exclusively is going to run into issues when that Pod inevitably tries to mount a volume which is inexplicably owned by root, which in and of itself doesn't make sense given it's not safe to run Pods as root.

**Comment by CamelCaseNotation** [comment]
@MartinForReal

**Comment by MartinForReal** [comment]
how about modifying yaml using kustomize ?
