### ISSUE TITLE
rbd mount fails inside containerized kubelet

### ISSUE THREAD

**Issue by gucki** [kubernetes-incubator/external-storage#1021]
I'm using rke to setup a kubernetes cluster. kubelet is running in a docker container. When rbd_utils.go tries to check for the rbd-nbd utils it does a `modprobe nbd`. This fails inside the container because the kernel modules are not available. This error could be avoided if rbd_utils would do a `lsmod | grep nbd` first to check if the module is already loaded.

https://github.com/rancher/rke/issues/362 suggest another way by mounting `/lib/modules` in the container. But I think checking if the module is already loaded would be a cleaner solution.

**Comment by wongma7** [comment]
Please create an issue upstream at kubernetes/kubernetes too, when kubelet is containerized it is supposed to bind mount everything needed
/area ceph/rbd
