### ISSUE TITLE
[WIP]should we add releasedTimestamp for pv

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes-incubator/external-storage#1024]
*background:*
when we create PV dynamically by storageclass and released those PV. The remained PV should be cleaned periodically.

If we want automatically delete them by released order, we need a release timestamp in PV resource object.

**Comment by wongma7** [comment]
It is the kubernetes PV controller that Releases PVs https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L801.

To make sure I understand correctly: you want to leave PVs around with `Retain` reclaim policy and clean them up later with some kind of cron job? Why not give them `Delete` reclaim policy and let the provisioner delete them?

**Comment by zhangxiaoyu-zidif** [comment]
@wongma7 in fact, we want to keep them for re-use, but if those released PVs are not reused for a long time or under disk pressure, we need to delete them by cronjob or other ways.
I need much more considerations.

**Comment by zhangxiaoyu-zidif** [comment]
cc @jian-he
