### ISSUE TITLE
Update local provisioner base image

### ISSUE THREAD

**Issue by msau42** [kubernetes-incubator/external-storage#1036]
It's old

**Comment by cofyc** [comment]
Do you mean `centos:7` base image in Dockerfile? For security?

[Latest centos image](https://hub.docker.com/r/library/centos/tags/) is `7.5.1804`, and latest `centos:7` is same as it. We can rebuild current provisioner images to use latest version, but perhaps we need to do it manually.

**Comment by msau42** [comment]
Oh ok, maybe it's a matter of pushing a new container image to update to the latest centos:7

**Comment by msau42** [comment]
I was also thinking if we want to consider using a slimmed down base image and only installing the necessary packages we need.

**Comment by cofyc** [comment]
+1
I'll try to switch to `alpine`, it's based on busybox but includes a package manager `apk`, easier to use.

**Comment by msau42** [comment]
I think kubernetes org actually discourages alpine.  This is what they recommend: https://github.com/kubernetes/kubernetes/tree/master/build/debian-base

**Comment by cofyc** [comment]
OK, I'll look at it.
