### ISSUE TITLE
Instructions to build Docker image for AWS EFS ?

### ISSUE THREAD

**Issue by bholagabbar-mt** [kubernetes-incubator/external-storage#1043]
The Dockerfile [here](https://github.com/kubernetes-incubator/external-storage/blob/09d7855e68dbfebb47f251845052e09f920b7a55/aws/efs/Dockerfile) is as follows

```
FROM alpine:3.6
RUN apk update --no-cache && apk add ca-certificates
COPY efs-provisioner /
ENTRYPOINT ["/efs-provisioner"]

```

Seems like it's unclear where to run this from. When does the [efs-provisioner.go](https://github.com/kubernetes-incubator/external-storage/blob/09d7855e68dbfebb47f251845052e09f920b7a55/aws/efs/cmd/efs-provisioner/efs-provisioner.go) file even run ? 

I am building a custom docker image to support custom domains for the EFS instead of hardcoded aws assigned domain names for EFS.

**Comment by wongma7** [comment]
Please see the makefile: https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/Makefile

We go build ./cmd/efs-provisioner and then copy the result efs-provisioner into the container root

Btw, patches to allow custom domains are welcome...a lot of people have been asking

**Comment by Tenzer** [comment]
Perhaps it would be easier to make use of a multi-stage build file, so building the image doesn't rely on having Go installed and in a specific version?

**Comment by wongma7** [comment]
yes, although multi-stage would be a lot less complicated, so I will leave this issue open to track getting that done. Also, @bholagabbar-mt , re: the root issue here, support for a custom dns.name/DNS_NAME was added so that you don't have to use hardcoded aws assigned domain names.

**Comment by bholagabbar-mt** [comment]
Great! Yeah, the custom DNS is much needed. The ‘AWS assigned domain name resolution’ option was switched off in my VPC because of which the EFS DNS couldn’t be resolved. I ended up switching to the IP address but ran into another problem. 

Finally ended up enabling the option (hoping it wouldn’t break anything, which it did not) and then used the AWS assigned DNS for the EFS file system as normal. 

With custom DNS support, I could have assigned the IP addresses of the EFS to a custom domain in my route53 and life would’ve been easier then, but I guess it’s sorted for now!

**Comment by Tenzer** [comment]
I had a go at changing the Dockerfile to be a multi stage one in https://github.com/kubernetes-incubator/external-storage/pull/1088.
