### ISSUE TITLE
re-deploying efs-provisioner causes EFS data to be deleted.  Expected?

### ISSUE THREAD

**Issue by nkrendel** [kubernetes-incubator/external-storage#1045]
I have a Terraform script that installs efs-provisioner + grafana etc.

I noticed that after I destroy + re-deploy the provisioner, the data in EFS is gone.  Is this expected?

**Comment by wongma7** [comment]
no, please share more information about what destroy + re-deploy means

**Comment by nkrendel** [comment]
I have a terraform provisioning script that creates an EKS cluster, and installs external-dns and efs-provisioner, and installs grafana, which is configured to use the EFS.  This all seems to work well, and if I delete the grafana pod, the newly created pod still sees the files in EFS.  However if I destroy the cluster and re-provision it, all the data in EFS is gone, and grafana ends up with a new/empty EFS folder.

**Comment by wongma7** [comment]
when you destroy the cluster, every object including every PVC is getting deleted right? The reclaimPolicy defaults to delete so the provisioner will clean up every PV. If grafana is consuming the EFS folder via PVC, I'm not sure how to preserve it across clusters.

**Comment by nkrendel** [comment]
I created the StorageClass with a `reclaimPolicy: Retain`.  I thought that would prevent it from cleaning up existing data?

**Comment by wongma7** [comment]
yes, you can confirm that's the case by checking that the PVs have reclaimPolicy: Retain too

**Comment by nkrendel** [comment]
The PV does have reclaimPolicy set to Retain:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                     STORAGECLASS   REASON   AGE
pvc-d140d985-de27-11e8-a52a-0a49aed46e1a   1Mi        RWX            Retain           Bound    default/efs                               aws-efs                 3d
```
Yet when I destroy the cluster, the EFS data gets wiped...  Any ideas why that is happening?

**Comment by wongma7** [comment]
It's possible if the provisioner is too old it won't respect the reclaimpolicy on the PV. what version is it? Can you try deleting a single PVC and see what happens?

**Comment by nkrendel** [comment]
I'm deploying the latest provisioner:
```
          image: quay.io/external_storage/efs-provisioner:latest
```
I did verify that deleting the PVC causes the efs data to be erased.

**Comment by wongma7** [comment]
My bad, version doesn't matter, I was thinking about reclaimpolicy on the SC...respect for reclaimpolicy on PVs has always existed.

Please check/provide the logs of the provisioner when you delete a single PVC, it must be saying things like "volume deleted" etc. Does the PV get deleted too when you delete a PVC?

**Comment by nkrendel** [comment]
The PV does not get deleted when the PVC is deleted.  It is just marked as "Released":
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                     STORAGECLASS   REASON   AGE
pvc-5283bd96-e12b-11e8-a52a-0a49aed46e1a   1Mi        RWX            Retain           Released   default/efs-2                             aws-efs                 25m
pvc-652634ce-e12e-11e8-a52a-0a49aed46e1a   1Mi        RWX            Retain           Released   default/efs-2                             aws-efs                 3m
pvc-d140d985-de27-11e8-a52a-0a49aed46e1a   1Mi        RWX            Retain           Bound      default/efs                               aws-efs                 3d
pvc-fcd6e3b7-e12a-11e8-acbf-0ed082658fa6   1Mi        RWX            Retain           Released   default/efs-2                             aws-efs                 27m
pvc-fdb26fb8-e12d-11e8-acbf-0ed082658fa6   1Mi        RWX            Retain           Released   default/efs-2                             aws-efs                 5m
```
The efs-provisioner log doesn't show anything at all when deleting the PVC.  When the pod/pvc are re-created, I see the typical messages:
```
I1105 19:13:55.094607       1 controller.go:987] provision "default/efs-2" class "aws-efs": started
I1105 19:13:55.099799       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"efs-2", UID:"f0471f52-e12e-11e8-acbf-0ed082658fa6", APIVersion:"v1", ResourceVersion:"702326", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/efs-2"
I1105 19:13:55.118111       1 controller.go:1087] provision "default/efs-2" class "aws-efs": volume "pvc-f0471f52-e12e-11e8-acbf-0ed082658fa6" provisioned
I1105 19:13:55.118133       1 controller.go:1101] provision "default/efs-2" class "aws-efs": trying to save persistentvvolume "pvc-f0471f52-e12e-11e8-acbf-0ed082658fa6"
I1105 19:13:55.124014       1 controller.go:1108] provision "default/efs-2" class "aws-efs": persistentvolume "pvc-f0471f52-e12e-11e8-acbf-0ed082658fa6" saved
I1105 19:13:55.124045       1 controller.go:1149] provision "default/efs-2" class "aws-efs": succeeded
I1105 19:13:55.124119       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"efs-2", UID:"f0471f52-e12e-11e8-acbf-0ed082658fa6", APIVersion:"v1", ResourceVersion:"702326", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-f0471f52-e12e-11e8-acbf-0ed082658fa6
```

**Comment by nkrendel** [comment]
I think I understand what you're saying...  couple of follow-up questions:
1. would what you're saying also explain why manually deleting just the PVC causes the next PVC to not show any data?  (not deleting the provisioner or the cluster, just the PVC)
2. is your recommendation then to just not use the provisioner?

**Comment by wongma7** [comment]
1. yes. For example, say the first pvc-1 points to pv-1 which has path /pv-1. When you create a new pvc-2 it points to pv-2 which has path /pv-2. Ideally if you want to reuse the data in pv-1 you would not delete pvc-1 at all, and instead remount pvc-1 in the new pod. Or you can make a copy of pv-1 and bind pvc-2 to it then mount pvc-2 in the new pod.
2. yes, in this case. The provisioner is fine for when we need data to survive pod restarts or to consume the same data in different pods. But if we need to also survive cluster recreations then it would be better to store data in a known place like "/grafana."

**Comment by nkrendel** [comment]
makes sense.  thanks a lot for your help and responsiveness!  👍

**Comment by sypticus** [comment]
Thanks, cleared up my problem as well. Seems like the provisioner could be updated to allow pathnames to be defined, which would eliminate this issue.
