### ISSUE TITLE
Delete local PV If directory not found

### ISSUE THREAD

**Issue by msau42** [kubernetes-incubator/external-storage#1052]
A use case is for cloud environments where the node can get recreated with the same name, but the disks are gone.  User can delete the PVC, and the PV will become Released. However, PV cleanup will return an error if the path doesn't exist.  What do you think of allowing PV deletion to proceed in this case?

cc @cofyc @lbernail

**Comment by cofyc** [comment]
When users recreated a node, they deleted (at least detached) all storage devices from it. Users also may remove devices or filesystems before deleting PVCs. When users reattach these storage devices to new node, they must clean up old devices if they don't want old contents to be used, whether new node shares same name with old node or not. I think they are in charge of cleaning up all devices and filesystems on old node, so it's right to proceed when path doesn't exist.

My only concern is when device has hardware problem, it may disappear and reappear again to be discovered as new PV. To prevent this, we can add `node` uuid into PV annotation, and expect PV's path must exist if deletion happens on its node. But it's rare and unlikely its PVC has been deleted in the meantime. IMO we don't need consider it now.

**Comment by msau42** [comment]
Moving issue to the new repo: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/6
