### ISSUE TITLE
[cephfs] admin and user capabilities issue in shared cephfs

### ISSUE THREAD

**Issue by ymazzer** [kubernetes-incubator/external-storage#1059]
Hi,

I'm wondering why is the `mds 'allw r path=/'` required for the admin client and for the pv client.

Using capabilities [caps1] the following way:
```
client.adminK8s
    key : [...]==
    caps: [mon] allow rwx
    caps: [osd] allow rw tag cephfs data=cephfs
    caps: [mds] allow r path=/, allow rwp path=kubernetes/myFolder
```

Everything works fine.

But using the following capabilities [caps2] fails:
```
client.adminK8s
    key : [...]
    caps: [mon] allow rwx
    caps: [osd] allow rw tag cephfs data=cephfs
    caps: [mds] allow rwp path=kubernetes/myFolder
```
with error:
```
E1113 10:22:04.202580       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-[...]" for "kubernetes-dynamic-user-[...]", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 364, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 358, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 228, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
  File "/usr/local/bin/cephfs_provisioner", line 112, in volume_client
    self._volume_client.connect(None)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 471, in connect
    self.fs.mount()
``` 
By the way, using [caps2] still allows the user to mount the folder correctly

```
$ sudo mount -t ceph -oname=kubernetes-dynamic-user-[...],secret=[...] monitor1:/kubernetes/myFolder /mnt/test1
$ ls test1
test.txt 
$ sudo mount -t ceph -oname=kubernetes-dynamic-user-[...],secret=[...] monitor1:/ /mnt/test2
mount error 13 = Permission denied
```
In a shared cephfs cluster, such capabilities [cap1] *might lead to data leakage* since any client can mount the whole cephfs volume and then at least access to other's data. Furthermore, this capability doesn't seam required since the folder creation can be within a dedicated mount in the declared volume_group 

```python
file:ceph_provisioner.py@create_share
        volume_path = ceph_volume_client.VolumePath(self.volume_group, path)

        # Create the CephFS volume
        volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
```
Am I missing something? Is there an alternative to ensure multi-tenancy in a shared cephfs?

**Comment by wongma7** [comment]
I think this is a consequence of how the python client works, it has to mount the whole fs here https://github.com/ceph/ceph/blob/master/src/pybind/ceph_volume_client.py#L479 and  http://docs.ceph.com/docs/mimic/cephfs/client-auth/ says "Note that if a client’s read access is restricted to a path, they will only be able to mount the filesystem when specifying a readable path in the mount command (see below)." The `allow r path=/`  cap is only for the admin secret for the provisioner I don't think any non-provisioner client cant use it. Also, individual volumes should be restricted by some UUID by this code here https://github.com/kubernetes-incubator/external-storage/blob/master/ceph/cephfs/cephfs_provisioner/cephfs_provisioner.py#L240

**Comment by wongma7** [comment]
I missed about the pv client, I only talked about admin client in the above comment. I am not sure if PV client needs `allow r path=/` as well, will need to investigate some more
