### ISSUE TITLE
[ceph rbd]PVC state goes on Pending state 

### ISSUE THREAD

**Issue by selvakumarnms** [kubernetes-incubator/external-storage#1062]
Hi,
I used latest code ceph rbd provisioner and my PVC goes to pending state ever and the log of rbd-provisioner is given below,
I dont see any error except coredns part.

yclaim", UID:"1b3db36d-e966-11e8-995b-5254001d8c3a", APIVersion:"v1", ResourceVersion:"51219", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/myclaim"
W1116 06:12:22.940198       1 provision.go:203] error getting coredns service: services "coredns" is forbidden: User "system:serviceaccount:kube-system:rbd-provisioner" cannot get services in the namespace "kube-system": User "system:serviceaccount:kube-system:rbd-provisioner" cannot get services in project "kube-system". Falling back to kube-dns
[root@master-r1c1 ~]# kubectl logs -n kube-system rbd-provisioner-bc956f5b4-hd7tv
I1116 06:12:04.823284       1 main.go:85] Creating RBD provisioner ceph.com/rbd with identity: ceph.com/rbd
I1116 06:12:04.825458       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/ceph.com-rbd...
I1116 06:12:22.580335       1 leaderelection.go:194] successfully acquired lease kube-system/ceph.com-rbd
I1116 06:12:22.581274       1 controller.go:631] Starting provisioner controller ceph.com/rbd_rbd-provisioner-bc956f5b4-hd7tv_8a225bbf-e966-11e8-ad1b-3e389208dfe9!
I1116 06:12:22.581400       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"ceph.com-rbd", UID:"acf207f2-e965-11e8-995b-5254001d8c3a", APIVersion:"v1", ResourceVersion:"51954", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' rbd-provisioner-bc956f5b4-hd7tv_8a225bbf-e966-11e8-ad1b-3e389208dfe9 became leader
I1116 06:12:22.781619       1 controller.go:680] Started provisioner controller ceph.com/rbd_rbd-provisioner-bc956f5b4-hd7tv_8a225bbf-e966-11e8-ad1b-3e389208dfe9!
I1116 06:12:22.781786       1 controller.go:987] provision "default/myclaim" class "fast-rbd": started
I1116 06:12:22.893706       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"myclaim", UID:"1b3db36d-e966-11e8-995b-5254001d8c3a", APIVersion:"v1", ResourceVersion:"51219", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/myclaim"
W1116 06:12:22.940198       1 provision.go:203] error getting coredns service: services "coredns" is forbidden: User "system:serviceaccount:kube-system:rbd-provisioner" cannot get services in the namespace "kube-system": User "system:serviceaccount:kube-system:rbd-provisioner" cannot get services in project "kube-system". Falling back to kube-dns

I have used ceph-ansible for deploying ceph cluster with luminous version

my ceph status command output is
[root@master-r1c1 ~]# ceph status
 ceph status
  cluster:
    id:     a659ee81-9f98-4573-bbd8-ef1b36aec537
    health: HEALTH_WARN
            Reduced data availability: 250 pgs inactive
            Degraded data redundancy: 250 pgs undersized

  services:
    mon: 1 daemons, quorum master-r1c1
    mgr: master-r1c1(active)
    osd: 1 osds: 1 up, 1 in

  data:
    pools:   1 pools, 250 pgs
    objects: 0 objects, 0B
    usage:   1.00GiB used, 8.99GiB / 10.0GiB avail
    pgs:     100.000% pgs not active
             250 undersized+peered

Note:
 I waited for more than 2hours for any timeout. But I dont see any timeout message in the rbd provisioner logs.

is there anyway to check where it might went wrong?
kindly help me in this regard.

**Comment by selvakumarnms** [comment]
some more inputs regarding this issue,
I have enabled ceph monitoring on master and ceph osd on the compute where block devices are exposed
block devices details,
[root@compute-r1c1 ceph]# lsblk
NAME                                                                                        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
vda                                                                                         252:0    0   20G  0 disk
├─vda1                                                                                      252:1    0  300M  0 part /boot
├─vda2                                                                                      252:2    0    1G  0 part
└─vda3                                                                                      252:3    0 18.7G  0 part
  └─root_vg01-lv_01                                                                         253:0    0 18.7G  0 lvm  /
vdb                                                                                         252:16   0   10G  0 disk
└─ceph--aa238d5a--0995--4882--81e6--403bdf2c7386-osd--data--5da25df4--f808--4253--98fe--b20a1af0e9a7
                                                                                            253:1    0   10G  0 lvm

**Comment by itsecforu** [comment]
How did u solve it?

**Comment by yankunsam** [comment]
It occurs in my environment,Is there some solutions?
