### ISSUE TITLE
Rename nfs directory to nfs-server

### ISSUE THREAD

**Issue by jonaskello** [kubernetes-incubator/external-storage#1079]
It seems like the `nfs` directory in this repo contains what in the helm chart is called [`nfs-server-provisioner`](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner). If this is true I would suggest renaming the `nfs` directory in this repo to`nfs-server` to make it more clear what it is and align the naming with the helm chart.

As a side-note, when I was looking for what in my mind is a "nfs provisioner" I was actually looking for the `nfs-client` provisioner, not the `nfs` provisioner. Took me some time to figure this out and I think clearer naming would have helped.

**Comment by wongma7** [comment]
I agree, but it is probably too late to rename the directory else we break links and such. Most people are interested in nfs-client, but the "nfs-server" one was written first so it took the nfs name. There is probably a way to improve the README, to say something like 'you may be looking for...' or a brief comparison of the two. I will work on inserting something into both READMEs

**Comment by msau42** [comment]
@wongma7 aren't we going to split out each of the external provisioners to independent repos?

**Comment by wongma7** [comment]
@msau42 oh yeah...I need to clean up issues/PRs first, will start kicking things out after holidays I think

**Comment by geerlingguy** [comment]
Yeah, I spent a little while implementing the `nfs` provisioner, then realized it was meant for provisioning an nfs server _inside_ the cluster, when I really wanted the `nfs-client` provisioner which is used if you already have NFS available outside the cluster.

Would be nice to help others prevent that mistake—at least something in the README, maybe an aside like:

> If you already have an NFS server and would like to provision volumes on it, use the `nfs-client` provisioner.
