### ISSUE TITLE
Break up this repo into individual kubernetes-sigs/sig-storage* ones

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#1083]
There is a nice and quick process for getting a repo in kubernetes-sigs/ now. We already have https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner and https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner.

Track the work for the rest here.

**Comment by cofyc** [comment]
I'm going to break out ceph (cephfs & rbd) provisioner.

**Comment by cofyc** [comment]
Submitted a request https://github.com/kubernetes/org/issues/324

**Comment by alcohol** [comment]
Can anyone contribute to this, or..? If so, I would like to volunteer for extracting the `nfs` provisioner.

**Comment by Zyqsempai** [comment]
I also would like to take part in this action. I can take care of AWS provisioner.

**Comment by wongma7** [comment]
Thanks for interest, migration work after I've copy/pasted the provisioner's directory from here into the root of the new repo might be to: setup dependencies (vendor), make sure it builds, find/replace broken links. But before then I need to request the repos.

About the nfs provisioner: what should it be called? This is an opportunity to differentiate it from nfs-client. I am leaning toward 'nfs-ganesha-provisioner' to make it clear that it is running a ganesha server.

**Comment by alcohol** [comment]
Are you exporting with history btw? It would be very nice to preserve git commit history for the files being exported.

**Comment by alcohol** [comment]
> bout the nfs provisioner: what should it be called? This is an opportunity to differentiate it from nfs-client. I am leaning toward 'nfs-ganesha-provisioner' to make it clear that it is running a ganesha server.

While I agree that it would make sense to differentiate it more clearly from the nfs-client provisioner, I am not sure if making the specific daemon implementation part of the repository name is a good idea long term. I definitely have no objections though. Alternatively I would suggest nfs-daemon or nfs-userspace-daemon. I'll leave the decision making up to you :-)

**Comment by klausenbusk** [comment]
FYI: The Digitalocean provisioner is [deprecated](https://github.com/kubernetes-incubator/external-storage/blob/2f0b6d4637099369d8d8f3e22fcd10a212daca3d/digitalocean/README.md) and should be removed at some point (1.14 maybe?).

**Comment by kmova** [comment]
openebs is moving towards CSI. Once that is available, will raise an PR to deprecate it here.

**Comment by tsmetana** [comment]
I attempted for some more comprehensive overview of what is still relevant in this repo:

EFS provisioner: deprecated by CSI: https://github.com/aws/aws-efs-csi-driver
CephFS provisioner: deprecated by CSI: https://github.com/ceph/ceph-csi
DigitalOcean provisioner: deprecated by CSI:https://github.com/digitalocean/csi-digitalocean
Flex: deprecated by CSI (?), there even exists a CSI adapter: https://github.com/kubernetes-csi/drivers/tree/master/pkg/flexadapter
GlusterFS provisioner: deprecated by CSI https://github.com/gluster/gluster-csi-driver
Gluster Block provisioner: deprecated by CSI https://github.com/gluster/gluster-csi-driver
iSCSI targetd provisioner: no CSI equivalent I'd know of
Local volume static provisioner: deprecated, new upstream at https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
NFS client / NFS provisioner: no CSI equivalent (there is a CSI driver for statically provisioned NFS volumes only)
OpenEBS: no CSI equivalent found (there is some dead attempt at https://github.com/openebs/csi-openebs)
Snapshots: deprecated by CSI -- part of the spec, some drivers already include snapshotting support.

Looks like only NFS and OpenEBS are still relevant. The rest probably deserves a deprecation notice.
