### ISSUE TITLE
nfs provisioner recommended way

### ISSUE THREAD

**Issue by sluetze** [kubernetes-incubator/external-storage#1091]
Hi,

https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/deployment.md

states that 

> The recommended way is running it as a single-instance stateful app, where you create a Deployment/StatefulSet and back it with some persistent storage like a hostPath volume

a little later there is

> In Kubernetes - StatefulSet of 1 replica
The procedure for running a stateful set is identical to that for a deployment, above, so wherever you see deployment there, replace it with statefulset. The benefit is that you get a stable hostname. Note that the service cannot be headless, unlike in most examples of stateful sets.

Thus the default way requires more energy. This may result in lazy people doing the wrong things (like me :P).

If wished, I can make changes to the deployment.md so that:
* the explicit description is for statefulset
* a short "replace" anouncement for deployment is inserted

Rgds
--sluetze

**Comment by wongma7** [comment]
Those changes sgtm. It will be good to have 1 clear recommended way even if in practice the difference is not huge
