### ISSUE TITLE
[ceph rbd] Add support for erasure encoded volumes

### ISSUE THREAD

**Issue by spuder** [kubernetes-incubator/external-storage#1096]
Ceph rbd supports optional erasure encoding of pools. When using erasure encoding the pool must be tagged as ec42 ad a second pool must be made that references the first pool as a data-pool. 

>Using EC pools with RBD
To mark this as an RBD pool, first tag it accordingly:
`$ ceph osd pool application enable rbd ec42`
RBD can store image data in EC pools, but the image header and metadata still needs to go in a replicated pool.  Assuming you have the usual pool named “rbd” for this purpose,
`$ rbd create rbd/myimage --size 1T --data-pool ec42`
The image can then be used normally just like any other image, except that all of the data will be stored in the “ec42” pool instead of “rbd” pool.  Note that the clients must be using the Luminous (or newer) version of librbd; older releases of Ceph (e.g., Jewel) do not support the data pool feature.

https://ceph.com/community/new-luminous-erasure-coding-rbd-cephfs/

**Comment by bjwschaap** [comment]
/remove-lifecycle rotten
Any updates on this? We need it....

**Comment by sagor999** [comment]
/reopen
/remove-lifecycle rotten

Any updates on this?
