### ISSUE TITLE
[cephfs] permission denied while accessing pvc from pod

### ISSUE THREAD

**Issue by hniedlich** [kubernetes-incubator/external-storage#1099]
Hi,

Can you guys provide me with informations about cephfs provisioner. 
Im using `Openshift Origin v3.11`, I have succesfully deployed provisioner, the pvc and pv are created dynamically without problems. 
The only problem is that every time pod mounts pvc, it has always "permission denied" to this mount. 

Every time I can see that pvc has `root:root 755` rights, shouldn't it be inherited from `fsGroup` and `runAsUser`?

Is this provisioner working for someone in production? I need to transition to some clustered filesystem because RBD does not provide mounting same share across many nodes.

**Comment by YKWeyer** [comment]
Hi @hniedlich, did you find a solution? 

It looks similar to a couple of known bugs (https://github.com/kubernetes-incubator/external-storage/issues/515, https://github.com/kubernetes-incubator/external-storage/issues/1018), have you tried one of the suggested workarounds? (initContainers chowning the folders, setting `runAsUser:0`, using NFS)
