### ISSUE TITLE
[nfs-provisioner] ProvisioningFailed - error creating export for volume - in overlay2

### ISSUE THREAD

**Issue by Ichthyostega** [kubernetes-incubator/external-storage#1101]
Not sure if this is a duplicate or known problem; any hints appreciated...

Basically...
  
- I used deployment.yaml
- **image**: `quay.io/kubernetes_incubator/nfs-provisioner:latest`
- made it use a PVC which is satisfied by _default storage_.
- right now I am testing in a local **kubeadm-dind** running on Docker 18.09 on Debian/stable
- here in this setup, the _default storage_ is satisfied by a Volume with `StorageClass` **`local-storage`** into a local path on one of the nodes
- setup the Roles according to rbac.yaml
- got the Deployment to run and installed a custom `StorageClass`
- a PVC against this storage class activates the Provisioner, but then runs into the problem

Now I am quite confused what/where the actual error is. Some of the warnings might be misleading. Any Idea what actually goes wrong here?

from the POD:

    Warning  ProvisioningFailed    2s (x4 over 77s)  cluster.local/hiv-glowlight-nfs-server-provisioner_nfs-provisioner-fb65c5f4c-264pb_91ec361c-1871-11e9-ad21-46466a55d3ce
    failed to provision volume with StorageClass "hiv-glowlight-storage":
    error creating export for volume: error exporting export block 
    EXPORT
    {
      Export_Id = 1;
      Path = /export/pvc-1b74988c-1872-11e9-b8a1-66fcae199a83;
      Pseudo = /export/pvc-1b74988c-1872-11e9-b8a1-66fcae199a83;
      Access_Type = RW;
      Squash = no_root_squash;
      SecType = sys;
      Filesystem_id = 1.1;
      FSAL {
        Name = VFS;
      }
    }
    : error calling org.ganesha.nfsd.exportmgr.AddExport:
    0 export entries in /export/vfs.conf added
    because (invalid param value) errors. Details:
      Config File (/export/vfs.conf:44): 1 validation errors in block EXPORT
      Config File (/export/vfs.conf:44): Errors found in configuration block EXPORT
    Mounted By:  test-pod

From the Ganesha-Log in `/export`

    15/01/2019 03:03:17 : epoch 5c3d4c89 : nfs-provisioner-fb65c5f4c-264pb : nfs-ganesha-22[dbus_heartbeat] vfs_lookup_path :FSAL :CRIT :Could not get handle for path /export/pvc-1b74988c-1872-11e9-b8a1-66fcae199a83, error Operation not supported
    15/01/2019 03:03:17 : epoch 5c3d4c89 : nfs-provisioner-fb65c5f4c-264pb : nfs-ganesha-22[dbus_heartbeat] init_export_root :EXPORT :CRIT :Lookup failed on path, ExportId=1 Path=/export/pvc-1b74988c-1872-11e9-b8a1-66fcae199a83 FSAL_ERROR=(Operation not supported,95)
    15/01/2019 03:03:17 : epoch 5c3d4c89 : nfs-provisioner-fb65c5f4c-264pb : nfs-ganesha-22[dbus_heartbeat] gsh_export_addexport :EXPORT :CRIT :0 export entries in /export/vfs.conf added because (invalid param value) errors
    15/01/2019 03:03:17 : epoch 5c3d4c89 : nfs-provisioner-fb65c5f4c-264pb : nfs-ganesha-22[dbus_heartbeat] dbus_message_entrypoint :DBUS :MAJ :Method (AddExport) on (org.ganesha.nfsd.exportmgr) failed: name = (org.freedesktop.DBus.Error.InvalidFileContent), message = (0 export entries in /export/vfs.conf added because (invalid param value) errors. Details:
    Config File (/export/vfs.conf:44): 1 validation errors in block EXPORT
    Config File (/export/vfs.conf:44): Errors found in configuration block EXPORT
    )

`sh-4.4# mount` yields:

    overlay on / type overlay (rw,relatime,lowerdir=/dind/docker/overlay2/l/VGQORDTD7PVC36FBOJLYUTVVGQ:/dind/docker/overlay2/l/DIEQNAICRGXCMNLVELMJPSO7V7:/dind/docker/overlay2/l/U4N7ZQNU7EDJY6GKS3NRAN34E2:/dind/docker/overlay2/l/S6WVH7VCJB5AKNAINF2XBN7LW6:/dind/docker/overlay2/l/CIXUNAWB7FPX2U6THQAME25MIO:/dind/docker/overlay2/l/I23VRLDNXWNMYLITUOSE2ER7RQ:/dind/docker/overlay2/l/G5EM3MGDMVBEH4RLJSPBFAP23X,upperdir=/dind/docker/overlay2/e4218e651b8f31c6b45be04ce77514ccf75f45e3d1faa8181389531e054a94ea/diff,workdir=/dind/docker/overlay2/e4218e651b8f31c6b45be04ce77514ccf75f45e3d1faa8181389531e054a94ea/work)
    proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
    tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755)
    devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
    sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
    tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755)
    cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
    cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
    cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
    cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
    cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
    cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
    cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset)
    cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
    cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
    cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
    mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
    overlay on /export type overlay (rw,relatime,lowerdir=/Werk/Box/DockZ/overlay2/l/TTUI22UF54CTXPV25CEKN5JG5L:/Werk/Box/DockZ/overlay2/l/R7W7LWEUZHQDPAQSVWUMSU2ZCI:/Werk/Box/DockZ/overlay2/l/ZROZOGSH7JWXEOKTOMTM64AUBT:/Werk/Box/DockZ/overlay2/l/24WIR34XSZ7YXJWSEELV4ODS5G:/Werk/Box/DockZ/overlay2/l/4WSUTMOEPJMZ5EUC3A3BIHPZPW:/Werk/Box/DockZ/overlay2/l/4JJCVY2MZS4JQRTERMXWC4QSQM:/Werk/Box/DockZ/overlay2/l/P7LPK2GOLEGV5EAUHQO6L2AOE4:/Werk/Box/DockZ/overlay2/l/NZDFNCSFIQLZ3YHAID2WFA5NEA:/Werk/Box/DockZ/overlay2/l/N24XHSHRMMHYL62IJR6ZXSUOVH:/Werk/Box/DockZ/overlay2/l/RWBJB7IGVSKD57FD6SQ3CLHBCB:/Werk/Box/DockZ/overlay2/l/RYEUIQNCKVQD3DC7JUM6CKFCMT:/Werk/Box/DockZ/overlay2/l/CCZSX26YW7KSCM5CRZE2RALQ34:/Werk/Box/DockZ/overlay2/l/C7WL7HZUVCGM33UHMYSABWX6K3:/Werk/Box/DockZ/overlay2/l/FLUPHURUCAP4NHAFPYI3BUEUP6:/Werk/Box/DockZ/overlay2/l/VMQQL3IRKLP6WNAYRYXVI4QAIA:/Werk/Box/DockZ/overlay2/l/LST3VMQNDB4YADBETXJJSMMEW7:/Werk/Box/DockZ/overlay2/l/5AO5KF3TIBWDHUMF5IBAYZB2PZ:/Werk/Box/DockZ/overlay2/l/QQTNATO2M7BZ7POYHGDC5RTSV7:/Werk/Box/DockZ/overlay2/l/E7PDLEPEXDV23FTYJEOKNPKHKB:/Werk/Box/DockZ/overlay2/l/NLABFVUKPUTTV56KHL27AGYSVX:/Werk/Box/DockZ/overlay2/l/Y2E76G2V5M5BEYKXK3T3N35XOX:/Werk/Box/DockZ/overlay2/l/CZY6DBHGB7N2J7WGKNUCFJOGUN:/Werk/Box/DockZ/overlay2/l/22GR5M4RT24OCMJBQ73GC5RK2B:/Werk/Box/DockZ/overlay2/l/6JQSBIG47PKSJJFSW2SWPPLBQH:/Werk/Box/DockZ/overlay2/l/I32RFQXMVA3VC4W6TRYORPO3OQ:/Werk/Box/DockZ/overlay2/l/Z7BMS272XM6CJCZE3K2QT4L7TX:/Werk/Box/DockZ/overlay2/l/YQAZL43UN4Y2EUIPWN6OWJ3M2O,upperdir=/Werk/Box/DockZ/overlay2/7e9c7160a8cf7af92059eea6ae41ffb21c30f0799ba646e7b3a533783bbcddad/diff,workdir=/Werk/Box/DockZ/overlay2/7e9c7160a8cf7af92059eea6ae41ffb21c30f0799ba646e7b3a533783bbcddad/work)
    /dev/sdb2 on /dev/termination-log type ext4 (rw,relatime,stripe=32722,data=ordered)
    /dev/sdb2 on /etc/resolv.conf type ext4 (rw,relatime,stripe=32722,data=ordered)
    /dev/sdb2 on /etc/hostname type ext4 (rw,relatime,stripe=32722,data=ordered)
    /dev/sdb2 on /etc/hosts type ext4 (rw,relatime,stripe=32722,data=ordered)
    shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
    tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,relatime)
    proc on /proc/asound type proc (ro,relatime)
    proc on /proc/bus type proc (ro,relatime)
    proc on /proc/fs type proc (ro,relatime)
    proc on /proc/irq type proc (ro,relatime)
    proc on /proc/sys type proc (ro,relatime)
    proc on /proc/sysrq-trigger type proc (ro,relatime)
    tmpfs on /proc/acpi type tmpfs (ro,relatime)
    tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755)
    tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755)
    tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755)
    tmpfs on /proc/sched_debug type tmpfs (rw,nosuid,size=65536k,mode=755)
    tmpfs on /sys/firmware type tmpfs (ro,relatime)

**Comment by Ichthyostega** [comment]
seems to be related to my local setup (running on kubeadm-dind).

Just fired up a cluster at DigitalOcean and there everything works as expected.
Could create several Pods sharing a PVC with `ReadWriteMany`, and the storage ends up in a subdirectory below `/exports` on the Provisioner

**Comment by wongma7** [comment]
right, it will not work with overlay fs, only ext3/4/xfs. Seems a limitation of dind
/area nfs

**Comment by ddurham2** [comment]
@Ichthyostega, you said you successfully got nfs working at DigitalOcean?  I've be trying for days, and while I think I'm close, I've had to hack the node's resolve.conf just to get a pod to be able to try and contact the nfs server.  Could you please post (github?) whatever you've done that has been successful?
