### ISSUE TITLE
[nfs-provisioner] ProvisioningFailed - getting dbus session bus: user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by ogre0403** [kubernetes-incubator/external-storage#1107]
Hi, 

I try to build my own nfs-provisioner image using this [Dockerfile](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/deploy/docker/Dockerfile), and deploy to my on-prome kubernetes follow this [guide](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/deployment.md#in-kubernetes---deployment-of-1-replica). 

I will get this error when I try to create my claim, but it works when I change to use official image `quay.io/kubernetes_incubator/nfs-provisioner:latest`. 

Does anyone can help us ?

Thanks.  

```
I0122 09:36:34.620949       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"nfs", UID:"303c918b-1e29-11e9-af89-801844ea1638", APIVersion:"v1", ResourceVersion:"33173577", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "example-nfs": error creating export for volume: error exporting export block
EXPORT
{
        Export_Id = 1;
        Path = /export/pvc-303c918b-1e29-11e9-af89-801844ea1638;
        Pseudo = /export/pvc-303c918b-1e29-11e9-af89-801844ea1638;
        Access_Type = RW;
        Squash = no_root_squash;
        SecType = sys;
        Filesystem_id = 1.1;
        FSAL {
                Name = VFS;
        }
}
: error getting dbus session bus: user: Current not implemented on linux/amd64
```

**Comment by wongma7** [comment]
try compiling with CGO_ENABLED? I have never seen this error

/area nfs
