### ISSUE TITLE
nfs-client how to get metrics of the container's usage of the mount?

### ISSUE THREAD

**Issue by rrichardson** [kubernetes-incubator/external-storage#1112]
I'm trying to get basic stats about the container and its usage of the nfs-mount that it provisioned via nfs-client.  Looking at `kubelet_container_*` provides information about some storage classes, but apparently not about `nfs-client`

I set `metrics-port` hoping to get some details, but that only provides details about the provisioner itself.  

I also looked at network bandwidth for the container but that doesn't appear to include the data sent to/from the mount, which is fine, but I need to know where to find it.

**Comment by wongma7** [comment]
this is not recorded anywhere, theoretically it could do this via polling

/area nfs-client

**Comment by iridian-ks** [comment]
I'm wondering what the options are for monitoring nfs persistent volume usage? I'm wanting to show disk usage in Grafana and alert in Alertmanager. I think one requirement is the ability to tie the persistent volume to the pod it's being used by. Some research shows that metrics have to be implemented by the storage class, but it's understandable if there's a technical limitation here.

Open to other options or explore what other people have done here.
