### ISSUE TITLE
efs-provisioner pod stuck at ContainerCreating status

### ISSUE THREAD

**Issue by dayyehm** [kubernetes-incubator/external-storage#1117]
Events:
  Type     Reason                 Age   From                                     Message
  ----     ------                 ----  ----                                     -------
  Normal   Scheduled              8m    default-scheduler                        Successfully assigned default/efs-provisioner-6598fbc7cf-gqlz6 to ip-192-168-10-151.ec2.internal
  Normal   SuccessfulMountVolume  8m    kubelet, ip-192-168-10-151.ec2.internal  MountVolume.SetUp succeeded for volume "default-token-mwgz7"
  Warning  FailedMount            5m    kubelet, ip-192-168-10-151.ec2.internal  MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-61986581.efs.us-east-1.amazonaws.com:/pvs /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume
Output: Running scope as unit run-8319.scope.
mount.nfs: Connection timed out
  Warning  FailedMount  3m  kubelet, ip-192-168-10-151.ec2.internal  MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-61986581.efs.us-east-1.amazonaws.com:/pvs /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume
Output: Running scope as unit run-8570.scope.
mount.nfs: Connection timed out
  Warning  FailedMount  1m  kubelet, ip-192-168-10-151.ec2.internal  MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-61986581.efs.us-east-1.amazonaws.com:/pvs /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume
Output: Running scope as unit run-8802.scope.
mount.nfs: Connection timed out
  Warning  FailedMount  1m (x3 over 5m)  kubelet, ip-192-168-10-151.ec2.internal  Unable to mount volumes for pod "efs-provisioner-6598fbc7cf-gqlz6_default(0b06a48c-26ed-11e9-81f1-169db6252968)": timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-gqlz6". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-mwgz7]

kubelet logs : 
==============================================
1-169db6252968)"), skipping: timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-xvwth". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-mwgz7]
Feb 02 13:08:40 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:08:40.865325   22831 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/nfs/31387999-26df-11e9-81f1-169db6252968-pv-volume\" (\"31387999-26df-11e9-81f1-169db6252968\")" failed. No retries permitted until 2019-02-02 13:10:42.865280616 +0000 UTC m=+12477.548246393 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"pv-volume\" (UniqueName: \"kubernetes.io/nfs/31387999-26df-11e9-81f1-169db6252968-pv-volume\") pod \"efs-provisioner-6598fbc7cf-xvwth\" (UID: \"31387999-26df-11e9-81f1-169db6252968\") : mount failed: exit status 32\nMounting command: systemd-run\nMounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/31387999-26df-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-61986581.efs.us-east-1.amazonaws.com:/pvs /var/lib/kubelet/pods/31387999-26df-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume\nOutput: Running scope as unit run-7560.scope.\nmount.nfs: Connection timed out\n\n"
Feb 02 13:09:52 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:09:52.648857   22831 kubelet.go:1640] Unable to mount volumes for pod "efs-provisioner-6598fbc7cf-xvwth_default(31387999-26df-11e9-81f1-169db6252968)": timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-xvwth". list of unmounted volumes=[pv-volume default-token-mwgz7]. list of unattached volumes=[pv-volume default-token-mwgz7]; skipping pod
Feb 02 13:09:52 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:09:52.648904   22831 pod_workers.go:186] Error syncing pod 31387999-26df-11e9-81f1-169db6252968 ("efs-provisioner-6598fbc7cf-xvwth_default(31387999-26df-11e9-81f1-169db6252968)"), skipping: timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-xvwth". list of unmounted volumes=[pv-volume default-token-mwgz7]. list of unattached volumes=[pv-volume default-token-mwgz7]
Feb 02 13:18:34 ip-192-168-10-151.ec2.internal kubelet[22831]: I0202 13:18:34.671316   22831 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-mwgz7" (UniqueName: "kubernetes.io/secret/0b06a48c-26ed-11e9-81f1-169db6252968-default-token-mwgz7") pod "efs-provisioner-6598fbc7cf-gqlz6" (UID: "0b06a48c-26ed-11e9-81f1-169db6252968")
Feb 02 13:18:34 ip-192-168-10-151.ec2.internal kubelet[22831]: I0202 13:18:34.671400   22831 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pv-volume" (UniqueName: "kubernetes.io/nfs/0b06a48c-26ed-11e9-81f1-169db6252968-pv-volume") pod "efs-provisioner-6598fbc7cf-gqlz6" (UID: "0b06a48c-26ed-11e9-81f1-169db6252968")
Feb 02 13:20:37 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:20:37.572299   22831 kubelet.go:1640] Unable to mount volumes for pod "efs-provisioner-6598fbc7cf-gqlz6_default(0b06a48c-26ed-11e9-81f1-169db6252968)": timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-gqlz6". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-mwgz7]; skipping pod
Feb 02 13:20:37 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:20:37.572347   22831 pod_workers.go:186] Error syncing pod 0b06a48c-26ed-11e9-81f1-169db6252968 ("efs-provisioner-6598fbc7cf-gqlz6_default(0b06a48c-26ed-11e9-81f1-169db6252968)"), skipping: timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-gqlz6". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-mwgz7]
Feb 02 13:20:45 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:20:45.754851   22831 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/nfs/0b06a48c-26ed-11e9-81f1-169db6252968-pv-volume\" (\"0b06a48c-26ed-11e9-81f1-169db6252968\")" failed. No retries permitted until 2019-02-02 13:20:46.254815648 +0000 UTC m=+13080.937781408 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"pv-volume\" (UniqueName: \"kubernetes.io/nfs/0b06a48c-26ed-11e9-81f1-169db6252968-pv-volume\") pod \"efs-provisioner-6598fbc7cf-gqlz6\" (UID: \"0b06a48c-26ed-11e9-81f1-169db6252968\") : mount failed: exit status 32\nMounting command: systemd-run\nMounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-61986581.efs.us-east-1.amazonaws.com:/pvs /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume\nOutput: Running scope as unit run-8319.scope.\nmount.nfs: Connection timed out\n\n"
Feb 02 13:22:53 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:22:53.648780   22831 kubelet.go:1640] Unable to mount volumes for pod "efs-provisioner-6598fbc7cf-gqlz6_default(0b06a48c-26ed-11e9-81f1-169db6252968)": timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-gqlz6". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-mwgz7]; skipping pod
Feb 02 13:22:53 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:22:53.648814   22831 pod_workers.go:186] Error syncing pod 0b06a48c-26ed-11e9-81f1-169db6252968 ("efs-provisioner-6598fbc7cf-gqlz6_default(0b06a48c-26ed-11e9-81f1-169db6252968)"), skipping: timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-6598fbc7cf-gqlz6". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-mwgz7]
Feb 02 13:22:57 ip-192-168-10-151.ec2.internal kubelet[22831]: E0202 13:22:57.294088   22831 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/nfs/0b06a48c-26ed-11e9-81f1-169db6252968-pv-volume\" (\"0b06a48c-26ed-11e9-81f1-169db6252968\")" failed. No retries permitted until 2019-02-02 13:22:58.294029012 +0000 UTC m=+13212.976994786 (durationBeforeRetry 1s). Error: "MountVolume.SetUp failed for volume \"pv-volume\" (UniqueName: \"kubernetes.io/nfs/0b06a48c-26ed-11e9-81f1-169db6252968-pv-volume\") pod \"efs-provisioner-6598fbc7cf-gqlz6\" (UID: \"0b06a48c-26ed-11e9-81f1-169db6252968\") : mount failed: exit status 32\nMounting command: systemd-run\nMounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-61986581.efs.us-east-1.amazonaws.com:/pvs /var/lib/kubelet/pods/0b06a48c-26ed-11e9-81f1-169db6252968/volumes/kubernetes.io~nfs/pv-volume\nOutput: Running scope as unit run-8570.scope.\nmount.nfs: Connection timed out\n\n"

**Comment by weisjohn** [comment]
I had this happen as well, you must make sure your the Security Group that your nodes are in are allowed to access that EFS resource.

**Comment by dayyehm** [comment]
I have my security groups configured correctly, I don't thinks this is the issue , I'm using older AMI from 10-2018 will test with different AMI

**Comment by nrawling** [comment]
This definitely happened to me. When I created the EFS mounts, I accidentally selected the DEFAULT SG which (of course) was locked down.

**Comment by wongma7** [comment]
see https://docs.aws.amazon.com/efs/latest/ug/accessing-fs-create-security-groups.html for security group info

if possible, try also to ssh into a node and mount efs yourself, to narrow down if it is a kubernetes/container specific issue or affects the whole node

/area aws/efs

**Comment by chrisdcmoore** [comment]
We've been seeing this too - when two or more pods which use the same NFS share get scheduled to the same node, occasionally both will get stuck in `ContainerCreating`. SSHing into the node and running `ps aux` shows a bunch of `mount` and `mount.nfs` processes which, if killed, allow normality to resume (both pods successfully create within the next 30 seconds or so).

Next time this happens to us, what artefacts from k8s and the node would be useful to aid in debugging this? :)

**Comment by momer** [comment]
> We've been seeing this too - when two or more pods which use the same NFS share get scheduled to the same node, occasionally both will get stuck in `ContainerCreating`. SSHing into the node and running `ps aux` shows a bunch of `mount` and `mount.nfs` processes which, if killed, allow normality to resume (both pods successfully create within the next 30 seconds or so).
> 
> Next time this happens to us, what artefacts from k8s and the node would be useful to aid in debugging this? :)
> 
> Update: I've just realised this GitHub issue pertains to the EFS provisioner, whereas we're seeing this with a plain old `nfs` PV, so I think maybe I'm in the wrong place?

@chrisdcmoore I'm experiencing the same using an `nfs` volume mount which is actually an `efs`

Insane.

Wonder what's causing it to hang on those instances in some scenarios?

**Comment by yvinap** [comment]
please check [1075](https://github.com/kubernetes-incubator/external-storage/issues/1075)
