### ISSUE TITLE
Vendoring might need to be looked at ... Runtime errors in glusterfs   due to duplicate flags initialized 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-incubator/external-storage#1120]
I was able to build these containers using `make container` but then, i got this : 

```
[root@ip-10-0-1-136 glusterfs]# kubectl logs gluster-dynamic-provisioner-k8gdp
/glusterfs-simple-provisioner flag redefined: log_dir
panic: /glusterfs-simple-provisioner flag redefined: log_dir
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000a0120, 0x1487fe0, 0x1fdde10, 0x1311701, 0x7, 0x133aa2f, 0x2f)
	/root/.gimme/versions/go1.11.linux.amd64/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc0000a0120, 0x1fdde10, 0x1311701, 0x7, 0x0, 0x0, 0x133aa2f, 0x2f)
	/root/.gimme/versions/go1.11.linux.amd64/src/flag/flag.go:708 +0x8a
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.InitFlags(0xc0000a0120)
	/home/centos/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:411 +0x7b
main.main()
	/home/centos/go/src/github.com/kubernetes-incubator/external-storage/gluster/glusterfs/cmd/glusterfs-simple-provisioner/main.go:42 +0x6a
```

After hacking around some, noticed that theres a bunch of top level vendor dirs

```
../../../external-storage/repo-infra/vendor/github.com/golang/glog/glog.go://	-log_dir=""
../../../external-storage/repo-infra/vendor/github.com/golang/glog/glog_file.go:// var logDir = flag.String("log_dir2", "", "If non-empty, write log files in this directory")
../../../external-storage/vendor/github.com/golang/glog/glog.go://	-log_dir=""
../../../external-storage/vendor/github.com/golang/glog/glog_file.go:var logDir = flag.String("log_dir", "", "If non-empty, write log files in this directory")
../../../external-storage/vendor/k8s.io/klog/klog.go://	-log_dir=""
../../../external-storage/vendor/k8s.io/klog/klog.go:	flagset.StringVar(&logging.logDir, "log_dir", "", "If non-empty, write log files in this directory")
```

So , i figured I'd gut em all... and then, compilation failed b/c the deps were missing, so i used `dep` to ensure all the dependencies, and then everything was happy, except that they types on GlusterfsPersistentVolume were off:

```
pkg/volume/provision.go:117:5: cannot use r (type *"github.com/kubernetes-incubator/external-storage/gluster/glusterfs/vendor/k8s.io/api/core/v1".GlusterfsVolumeSource) as type *"github.com/kubernetes-incubator/external-storage/gluster/glusterfs/vendor/k8s.io/api/core/v1".GlusterfsPersistentVolumeSource in field value
```

So, finally, made a tiny change #1119  , which seemed to fix the issue....

**Comment by jayunit100** [comment]
This is fixable looks like if you simply swap out `klog` for `glog` as an import .  
``` 
  200  vi vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/controller/controller.go 
  201  vi ./vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/gidallocator/gidallocator.go
  202  vi ./vendor/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/util/util.go
```

my other PR around Vendoring didnt solve this problem, so i closed it.

**Comment by jayunit100** [comment]
Ill make some PR's into the sig-storage-lib-external-provisioner repo to fix that , per conv w @dims

**Comment by jayunit100** [comment]
Ok, so once this merges , https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/25 , maybe can try updating deps in here.

**Comment by humblec** [comment]
@jayunit100 I think the easiest fix would be just reverting the changes in https://github.com/kubernetes-incubator/external-storage/pull/1114/files . Are you able to overcome this error once you revert the above mentioned PR ?

**Comment by humblec** [comment]
> @jayunit100 I think the easiest fix would be just reverting the changes in https://github.com/kubernetes-incubator/external-storage/pull/1114/files . Are you able to overcome this error once you revert the above mentioned PR ?

hmmm.. may be this revert is not required and the issue reported here should be solved by https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/25 . Isnt it @wongma7 @jayunit100 ?

**Comment by humblec** [comment]
For safer side I have filed https://github.com/kubernetes-incubator/external-storage/pull/1122

**Comment by jayunit100** [comment]
@humblec ok cool, that sounds like a good way forward 

I also created an image from this branch, that is working for me , `https://hub.docker.com/r/jayunit100/glusterfs-simple-provisioner`  can be slotted in as needed.

**Comment by humblec** [comment]
> @humblec ok cool, that sounds like a good way forward
> 
> I also created an image from this branch, that is working for me , `https://hub.docker.com/r/jayunit100/glusterfs-simple-provisioner` can be slotted in as needed.

@jayunit100 are you saying after reverting pr#1114, things are working fine ?
