### ISSUE TITLE
Does NFS provisioner support resizing?

### ISSUE THREAD

**Issue by fr0der1c** [kubernetes-incubator/external-storage#1142]
I use NFS provisioner to provision PersistentVolume for my MongoDB. Recently, I found the volume is going to out of space. So I searched and found https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/. This requires underlying storage provider support. I'm wondering if NFS provisioner support this? If not, is there any possible way to adjust the size of the volume?

**Comment by wongma7** [comment]
no it does not, note quota i.e. the size of the volume is not enforced, you can request a 1 GiB volume but use more than 1 GiB. this is a limitation for nfs

**Comment by fr0der1c** [comment]
OK. Thanks for your reply. Maybe this should be put into readme?

**Comment by wongma7** [comment]
yes, agree

**Comment by limbuu** [comment]
@fr0der1c i had almost same issue. But, i used gce-pd for storage using nfs server. Now, the configured size of storage is totally consumed. Is there any way around to resize the storage or any way to fix the problem?

**Comment by ankitjain87** [comment]
I was also looking for this, I just wanted to know if there any update on this? 

If not, is there a plan to support this feature?

**Comment by ThomasSonck** [comment]
+1
