### ISSUE TITLE
glusterblock-provisioner with arbiter volume support?

### ISSUE THREAD

**Issue by rezie** [kubernetes-incubator/external-storage#1146]
The file storage version of gluster has support for enabling arbiter volumes via the `volumeoptions` StorageClass option, but it doesn't look like this is the case for block storage. This is currently possible via `heketi-cli`:

```
sh# heketi-cli volume create --name=block-test --gluster-volume-options="user.heketi.arbiter true" --size=1 --block
```
```
sh# heketi-cli volume list --server=https://heketi-storage.glusterfs.svc:8443 -I
Id:2ecbbe172090a9fa5bfbf9df5028f49a    Cluster:d1b667140f3314d0a6f6f507cd06e10f    Name:block-test [block]
```

Is there a reason why glusterblock doesn't support that parameter?

**Comment by humblec** [comment]
@rezie by arch, block volumes are created on top of file volume and we call it as "block hosting volume" , its kind of a one time creation with a size like "512G" or so and next block hosting volume will only be created only when block hosting volume is full with block volumes. The options on block hosting volume is also controlled via a group profile in general while heketi create block hosting volume.  iic, if you create a block volume by heketi-cli commmand as shown above, arbiter feature looks to be a no-op for me, I will crosscheck and come back.. 

Thanks @wongma7 for assigning this issue :)

**Comment by kristvanbesien** [comment]
I have another customer that would like to see arbiter support for block hosting. We tried a command similar to the one in the first comment above, but got an error message in stead...

So it is not working.

Is it possible to create the volume by hand in a different way?
