### ISSUE TITLE
Why does the name of folers created by nfs provisoner carry random codes？

### ISSUE THREAD

**Issue by CanvaChen** [kubernetes-incubator/external-storage#1149]
When I recreate gitlab-ce,folder name like this:
```
default-gitlab-ce-data-pvc-d7cedc6c-465c-11e9-b609-28f10e40b1af/
default-gitlab-ce-data-pvc-fc57ad42-465a-11e9-b609-28f10e40b1af/
default-gitlab-ce-etc-pvc-d7d704ec-465c-11e9-b609-28f10e40b1af/
default-gitlab-ce-etc-pvc-fc59f28b-465a-11e9-b609-28f10e40b1af/
default-postgresql-pvc-d7c1b2ce-465c-11e9-b609-28f10e40b1af/
default-postgresql-pvc-fc525f9d-465a-11e9-b609-28f10e40b1af/
default-redis-pvc-d7c56732-465c-11e9-b609-28f10e40b1af/
default-redis-pvc-fc556b4c-465a-11e9-b609-28f10e40b1af/
```
But I want it to be this:
```
gitlab-ce-data/
gitlab-ce-etc/
postgresql/
redis/
```
How can I do?

**Comment by wongma7** [comment]
it creates a folder for every pvc. so if you want to keep a stable gitlab-ce-data/ directory, you should have multiple pods use that same pvc. Or you should bypass nfs-provisioner altogether: manually create a directory gitlab-ce-data/, manually create some pv's with server: $SERVER, path: gitlab-ce-data/, and use those instead.

**Comment by CanvaChen** [comment]
@wongma7  thank you
