### ISSUE TITLE
[iscsi] Push latest iscsi-controller image with fix for Issue 591

### ISSUE THREAD

**Issue by ron1** [kubernetes-incubator/external-storage#1152]
Push latest iscsi-controller image with Fix https://github.com/kubernetes-incubator/external-storage/pull/857 for Issue https://github.com/kubernetes-incubator/external-storage/issues/591.

**Comment by w1ndy** [comment]
/remove-lifecycle stale
The latest image is still 2 years ago :(

**Comment by Queuecumber** [comment]
/remove-lifecycle stale

@wongma7 can we get this taken care of?

**Comment by Queuecumber** [comment]
/remove-lifecycle stale

Still not fixed afaik

@wongma7

**Comment by wongma7** [comment]
Done, there is a v0.0.6 now https://quay.io/repository/external_storage/iscsi-controller?tab=tags

**Comment by Queuecumber** [comment]
Thanks @wongma7
