### ISSUE TITLE
Add capacity as a field in volumesnapshotdata resource

### ISSUE THREAD

**Issue by mittachaitu** [kubernetes-incubator/external-storage#1155]
**FEATURE REQUEST**
## Description
We should evaluate snapshotdata size while restoring the snapshot to the new persistent volume claim.

 **Scenario:**
1) User deployed the application and took the snapshot of the volume.
2) Using the above-created volumesnapshotdata trying to restore a data to new PVC then we should evaluate the size of the PVC with snapshot data size then allow for volume creation.

**Comment by tsmetana** [comment]
This provisioner is already obsoleted by the CSI snapshots. I don't think it's worthwhile to implement new features in it.
