### ISSUE TITLE
How to create limited storage PVC with efs-provisioner

### ISSUE THREAD

**Issue by tiendungitd** [kubernetes-incubator/external-storage#1162]
Since pod access to EFS will have unlimited storage, so is there any way to limit the storage?
Let say I want some pod only use maximum 2GiB

> I noticed when creating the claim it has request for a really small amount of storage?
> The storage section size is a requirement because most other PersistentVolumes need it. Every pod accessing EFS will have unlimited storage. I use 1Mi to remind my self it's unlimited.
Thanks.

**Comment by michaelconnor00** [comment]
:+1:

**Comment by wongma7** [comment]
Not possible as far as I know
