### ISSUE TITLE
[efs-provisioner][aws/efs] What version should I use?

### ISSUE THREAD

**Issue by luarx** [kubernetes-incubator/external-storage#1163]
There are some versions for `efs-provisioner`project but **I am not sure which I should use**.

Can I use the version `efs-provisioner-v2.2.0-k8s1.12` on a `k8s-1.10 cluster`?

**Comment by luarx** [comment]
Hey, any update on this?

**Comment by wongma7** [comment]
Yes. It's backwards compatible. Tagging images like that was not the best idea.
