### ISSUE TITLE
[snapshot-provisioner] support the storageClass.mountOptions parameter

### ISSUE THREAD

**Issue by M0nsieurChat** [kubernetes-incubator/external-storage#1165]
Hello,

Here is a storage class definition using the snapshot provisioner of GCP
```
$ kubectl get sc snapshot-promoter-fast-noatime -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: snapshot-promoter-fast-noatime
mountOptions:
- noatime
parameters:
  type: pd-ssd
provisioner: volumesnapshot.external-storage.k8s.io/snapshot-promoter
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

The `mountOptions` parameter is covered by this PR : https://github.com/kubernetes/community/pull/771

It seems like the parameter mountOptions is not taken into account by the provisioner when attaching the disk to the pod

```
root@testnoatimesnapshot-riak-0:/var/lib/riak# cat /etc/mtab | grep /dat
/dev/sdl /data/riak ext4 rw,relatime,data=ordered 0 0
```

Is there anything we're doing wrong for that use case ?

Cheers,

**Comment by tsmetana** [comment]
Hello, you're right, the mount options are ignored when creating new volumes from snapshots. This provisioner is obsoletef by CSI, so I'm not sure anybody will want to implement new features into it.

**Comment by M0nsieurChat** [comment]
Hi,
Thanks for answering ! Do you know if there is an alternative being CSI compliant regarding a snapshot operator compatible with the major cloud providers ?

**Comment by tsmetana** [comment]
Some overview of the existing CSI driver is here: https://kubernetes-csi.github.io/docs/drivers.html. Note that new features are being added constantly. Also note that even this controller/provisioner had very limited backend support (AWS, GCE, Gluster, hostpath).

**Comment by M0nsieurChat** [comment]
Thank you.
For future readers of this issue, please note that the Snapshot feature needs the `VolumeSnapshotDataSource` Feature Gate, which is still in Alpha since Kubernetes 1.12

For users running on GKE, I guess we still need to wait for the feature to move from Alpha to Beta in 1.14 (current stable on GKE is 1.13)

https://kubernetes.io/blog/2018/10/09/introducing-volume-snapshot-alpha-for-kubernetes/
