### ISSUE TITLE
Cannot use efs-provisioner with EFS instance installed on a peered region

### ISSUE THREAD

**Issue by claudod** [kubernetes-incubator/external-storage#1166]
As the doc state clearly in the "Prerequisites" section, it's required to have:
> An EFS file system in your cluster's region

And indeed, I cannot successfully run efs-provisioner on my eu-west-3 based EKS cluster, pointing to an EFS eu-west-1 based instance, even if I have a peering between my 2 regions

AWS allows to mount an EFS volume created on region A, even on a region B, as long as there's a peering between A and B. It's a pity that efs-provisioner does not support this feature. Is there any plan to make that happen in the future ? Or is any trick I can use to make it work with the current version ?

**Comment by wongma7** [comment]
The provisioner simply does a mount of `file-system-id.efs.aws-region.amazonaws.com`. What error do you see?
