### ISSUE TITLE
why my pv not created on aws/eks?

### ISSUE THREAD

**Issue by charlie-charlie** [kubernetes-incubator/external-storage#1177]
Hi there,
I followed the instruction(made necessary changes), but efs-provisioner in ContainerCreating, because pv-volume not create. pvc  in Pending state. scratching head, no findings.
Did anyone run into same issue?
I logged into eks ec2 node, I can manually mount the efs. 
thanks

**Comment by charlie-charlie** [comment]
check pvc log, here is why no pv created:
Normal  ExternalProvisioning  6s (x4 over 27s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "example.com/aws-efs" or manually created by system administrator

**Comment by quickbooks2018** [comment]
Same issue here
