### ISSUE TITLE
PVC location for a specific pod

### ISSUE THREAD

**Issue by amruthapbhat** [kubernetes-incubator/external-storage#1188]
Hi,

Initially we were using EBS for PVC, where in we were able to see the new pvc that gets created in the Volume section in AWS.

Now i have changed that for EFS and that also creates a pvc for a specific pod. 

Could you please let me know where i can see this storage that gets created in the aws console.

Regards,
Amrutha

**Comment by wongma7** [comment]
They won't show in they console because each one is a directory in a single EFS filesystem. You can mount the EFS filesystem into one of your EC2 nodes and look around though.
