### ISSUE TITLE
[cephfs-provisioner] PVC creation shouldn't fail if the ceph user secret already exists

### ISSUE THREAD

**Issue by fcgravalos** [kubernetes-incubator/external-storage#1192]
[cephfs-provisioner] When using `deterministicNames: true` creating a PVC, deleting it and creating it afterwards may fail because the ceph user secret already exists.

This could be solved by just doing:

```
apierrors "k8s.io/apimachinery/pkg/api/errors"
[...]
if err != nil && !apierrors.IsAlreadyExists(err) {
                klog.Errorf("Cephfs Provisioner: create volume failed, err: %v", err)
                return nil, fmt.Errorf("failed to create secret")
 }
```
I'm glad to do a PR with this, I'm just having a hard time building the provisioner due to this:

https://github.com/kubernetes-incubator/external-storage/issues/1150

If you help me sort this out I could test it in my own clusters.

**Comment by fcgravalos** [comment]
@humblec Did you finally take a look at this?

**Comment by humblec** [comment]
@fcgravalos you can try this PR https://github.com/kubernetes-incubator/external-storage/pull/1122 to resolve #1150 and then send a PR with the fix for this issue.

**Comment by fcgravalos** [comment]
Thanks @humblec I'll try that out later and submit a PR if I manage to fix it

**Comment by fcgravalos** [comment]
hey @humblec I merged your PR in my fork and I was able to test my changes :). It works! I'm moving forward with a PR :)

**Comment by fcgravalos** [comment]
@humblec you were assigned to the PR :) 

If we merge it, we'll merge your changes to fix the build too :)
