### ISSUE TITLE
Failed to pull image quay.io/external_storage/efs-provisioner:latest

### ISSUE THREAD

**Issue by rkamisetti792** [kubernetes-incubator/external-storage#1193]
we are trying to create aws efs-provisioner.

error: pod unable to pull the image
cause: docker registry doesn't exists

Failed to pull image "quay.io/external_storage/efs-provisioner:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://quay.io/v2/: EOF

**Comment by xieyanker** [comment]
maybe your docker is not normal, please check your docker.

**Comment by mausch** [comment]
fwiw `docker pull quay.io/external_storage/efs-provisioner:latest` works fine here.
