### ISSUE TITLE
[efs-provisioner][aws/efs] Is this obsolete?

### ISSUE THREAD

**Issue by mausch** [kubernetes-incubator/external-storage#1195]
Now that there's https://github.com/kubernetes-sigs/aws-efs-csi-driver , is https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs obsolete?

**Comment by chrisvdb** [comment]
Would also be interested to know if aws-efs-csi-driver is now preferred for new setups.

**Comment by wongma7** [comment]
Not yet. The EFS CSI driver can't do dynamic provisioning yet. It's being designed, please help steer the design in https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/6. For example, what do/don't you like about this provisioner that we can fix by starting fresh in the CSI driver?

When the migration path is clearer, we'll document it here. (That goes for other provisioners in this repo as well, but I've not been following them closely enough that I can announce/document anything with confidence.)
