### ISSUE TITLE
Permissions as environment variable in NFS provisioner

### ISSUE THREAD

**Issue by knightdave** [kubernetes-incubator/external-storage#1201]
Hi,
I would like to add possibility to change put chmod and chown as environment variables in NFS provisioner instead of hardcoded 0777 in lines [69](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go#L69) and [72](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go#L72) . 

It's useful when PVs are stored in NFS endpoint , that is not dedicated only for k8s .

**Comment by wongma7** [comment]
Yes, it can be done. See also EFS which sets 771 by default https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/cmd/efs-provisioner/efs-provisioner.go#L200

**Comment by tam203** [comment]
@wongma7 Just to confirm - you are saying it would be possible to develop the code to add this option/functionality. And you are *not* saying it's currently possible to do this with the provisioner as is?

**Comment by wongma7** [comment]
@tam203 it is not currently possible.
