### ISSUE TITLE
EFS Provisioner - not persisting between namespaces

### ISSUE THREAD

**Issue by mlaythe** [kubernetes-incubator/external-storage#1206]
I'm trying to use one EFS instance in several namespaces. I deployed the controller to the `default` namespace. I deployed a few pods in the `default` namespace and I was able to successfully mount the EFS drive to the pods. 

I also mounted it to another pod running in a different namespace by creating a `PersistentVolumeClaim` with `storageClassName` defined to link it to the EFS instance (https://github.com/kubernetes-incubator/external-storage/issues/1097). 

However, the files aren't synced between the two mounts. I can create files in one namespace that aren't visible to another pod in another namespace. Any clue why this could be happening? Thanks!

**Comment by wongma7** [comment]
Every PersistentVolumeClaim (namespaced) gets its own PersistentVolume (non-namespaced/cluster-scoped).

If you'd like pods to share data in an EFS provisioner-created PV they must use the same PVC but that's not possible in different namespaces. So you must manually create a PV. Something like this:

Namespace A: pod A <-> PVC A <-> PV A-1
Namespace B: pod B <-> PVC B <-> PV A-2 which has the same NFS spec as PV A-1

**Comment by wongma7** [comment]
For example, say PV A-1 points to the path /asdf in the EFS volume. Then PV A-2 must point to the same path.

The EFS provisioner is not doing any magic, if you inspect the PVs you will understand that each refers to a different path in the EFS file system

**Comment by mlaythe** [comment]
Awesome, thank you for the help!!!!
