### ISSUE TITLE
NFS-provisioner is unable to mount export-volume 

### ISSUE THREAD

**Issue by Tehacz** [kubernetes-incubator/external-storage#1216]
Hi i am trying to set up NFS-provisioner with statefulset, however the pod is stuck in "ContainerCreating" and when i describe the pod i get the following:

```
Warning  FailedMount  5m42s  kubelet, k8s-worker-01  MountVolume.SetUp failed for volume "export-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/9a2e33cb-eb10-4d3c-bbc5-8cc533fe6d44/volumes/kubernetes.io~nfs/export-volume --scope -- mount -t nfs IP/path /var/lib/kubelet/pods/9a2e33cb-eb10-4d3c-bbc5-8cc533fe6d44/volumes/kubernetes.io~nfs/export-volume
Output: Running scope as unit run-20707.scope.
mount.nfs: access denied by server while mounting IP/Path

```
Any idea how can i fix this problem? I am trying to connect to external storage outside kubernetes cluster.

**Comment by boeremak** [comment]
Have you tried mounting it from a regular machine first? See if that works.

**Comment by adityagu0910** [comment]
getting same error and also not able to run from regular machine 

`systemd-run --description="Kubernetes transient mount for /var/lib/kubelet/pods/3b355135-0192-11ea-ad82-00505681e351/volumes/kubernetes.io~nfs/pvc-0e50225d-018f-11ea-ad82-00505681e351" --scope -- mount -t nfs nas.gsic-sus.net:/mnt/default-pool/icp/temp/volumes/vault-audit-wise-parrot-vault-0-pvc-0e50225d-018f-11ea-ad82-00505681e351 /var/lib/kubelet/pods/3b355135-0192-11ea-ad82-00505681e351/volumes/kubernetes.io~nfs/pvc-0e50225d-018f-11ea-ad82-00505681e351
Running scope as unit run-22768.scope.
mount.nfs: mount point /var/lib/kubelet/pods/3b355135-0192-11ea-ad82-00505681e351/volumes/kubernetes.io~nfs/pvc-0e50225d-018f-11ea-ad82-00505681e351 does not exist`
