### ISSUE TITLE
Is this project dead and/or deprecated?

### ISSUE THREAD

**Issue by hunternins** [kubernetes-incubator/external-storage#1218]
I spoke with one of the maintainers (i.e. for `nfs-server-provisioner`) today, Jan, (who is the only person of the three listed on this project who could be reached on the Slack channel), and I was informed that the project/repo is deprecated. Does this just apply to the `external-storage` sub-project, or the `kubernetes-incubator` project as a whole?

```
Sponsor: Clayton (@smarterclayton)
Champion: Jan (@jsafrane) & Brad (@childsb)
SIG: sig-storage
```

**Comment by hunternins** [comment]
It also appears that 3x open issues related to the ones listed below have been open for weeks, and at least one of them just being auto-closed.

```
Linked: Discussion from Kubernetes.io: https://discuss.kubernetes.io/t/in-cluster-nfs-servers/7553
Linked: Slack Discussion: https://kubernetes.slack.com/archives/C09QZFCE5/p1565790548212000
Linked: Helm chart issue: https://github.com/helm/charts/issues/16323
Linked: Core issue: #1205
```

**Comment by wongma7** [comment]
It applies to both. The provisioners in here are deprecated in favor of CSI plugins which can also do provisioning + more. kubernetes-incubator I think has been replaced by the kubernetes-sigs system.

It doesn't mean nothing is being maintained, but it is best-effort. e.g. I've tried to help with helm chart issues previously but I don't maintain the chart and know little about helm.

**Comment by hunternins** [comment]
@wongma7 Thank you. For all intents and purposes, the specific features I was using (i.e. NFS-related) are end-of-life.
