### ISSUE TITLE
AWS EFS provisioner not working after restart

### ISSUE THREAD

**Issue by dhineshbabuelango** [kubernetes-incubator/external-storage#1222]
Hi All, We are using AWS EKS, we have deployed the efs provisioner in istio 

everytime when we restart thje worker nodes, all other pods getting started automatically only the efs provisioner is getting failed with the below error. we scale down the replica and scale up but nothing is working

F0912 02:55:09.259139       1 efs-provisioner.go:293] Error getting server version: an error on the server ("") has prevented the request from succeeding

**Comment by venkatalolla** [comment]
@dhineshbabuelango Can you share the pod logs, events, system logs and also run the `kubectl version --v=7` and share the information here to further investigate the error.
