### ISSUE TITLE
Creating RAID-0 with local SSDs on GCP

### ISSUE THREAD

**Issue by nyurik** [kubernetes-incubator/external-storage#1223]
When creating a PV from the GCP's local SSDs, is it possible to merge them into a logical array?  The `mdadm` utility does not seem to be available inside the Google's container-optimized OS, and I am not quite sure how the `quay.io/external_storage/local-volume-provisioner` image used inside the [gce/provisioner_generated_gce_ssd_count.yaml](https://github.com/kubernetes-incubator/external-storage/blob/master/local-volume/provisioner/deployment/kubernetes/gce/provisioner_generated_gce_ssd_count.yaml) can be used to create a logical RAID0 array from several local SSDs.  Thanks!

**Comment by nyurik** [comment]
I was able to

**Comment by msau42** [comment]
Looks like you found https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/65, which has more details on how to do this.
/close
