### ISSUE TITLE
Ownership and permission on NFS PV

### ISSUE THREAD

**Issue by martin2176** [kubernetes-incubator/external-storage#1232]
Feature request:
Instead of having 777 and root:root on the NFS PV directory, would be great if there is an option to set uid:gid , permission mode bits and setgid bit on the directory created by the NFS client provisioner. This will improve security posture and effectively utilizing runasuser and runasgroup, supplmental groups in pod security policy for access .
 
Implementation request:
Support it via annotation to PVC spec. This will allow PVC to be created with different permissions using same storage class.
 If this is not possible, support it as a parameter to Storage class.

**Comment by chinmaya-n** [comment]
We are dealing with the exact same issue when trying to install JFrog XRay. It does not like the global permission of 777 on Postgres and other application data directories.

I would love to have a fix for this one.

**Comment by chinmaya-n** [comment]
We may have fixed this problem by only using posix permissions on the NFS share (basically removed the existing windows permission, it had dual permissions set).
