### ISSUE TITLE
Build v2.3.0 of efs-provisioner fails to start

### ISSUE THREAD

**Issue by markAcomm** [kubernetes-incubator/external-storage#1233]
We were just doing a rolling update on our cluster and this pulled a new image of quay.io/external_storage/efs-provisioner:latest (only 7 hours old). This new version failed to start up on our cluster with the following output: 

```
/efs-provisioner flag redefined: log_dir
panic: /efs-provisioner flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000094120, 0x159ed00, 0x214fe70, 0x13da152, 0x7, 0x1405662, 0x2f)
	/usr/local/go/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc000094120, 0x214fe70, 0x13da152, 0x7, 0x0, 0x0, 0x1405662, 0x2f)
	/usr/local/go/src/flag/flag.go:708 +0x8a
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.InitFlags(0xc000094120)
	/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:411 +0x7b
main.main()
	/go/src/github.com/kubernetes-incubator/external-storage/aws/efs/cmd/efs-provisioner/efs-provisioner.go:275 +0x3c
```
When we reverted back to the prior version: v2.2.0-k8s1.12 the efs-provisioner was able to run successfully. 

Was there potentially something wrong with the build? Or is it possible we have something configured incorrectly?

**Comment by martymh** [comment]
Likewise for us.

The latest image is failing to start and is in a crash loop backoff: v2.3.0, sha256:15ddb18ffb9598841c4987f3ba0ef89dc175b137d2ee529bb647e1ae5e8939cd

The previous image appears to working fine: v2.2.0-k8s1.12, sha256:c12dae08925371318ae8a6de2e21a27c581f1d8bbd59876e8ae4292d36e0a300

**Comment by mozimos** [comment]
I also was able to start pod using v2.2.0-k8s1.12 but encountered an error after a few seconds:

F1009 11:10:29.773957       1 efs-provisioner.go:293] Error getting server version: Get https://10.100.0.1:443/version?timeout=32s: dial tcp 10.100.0.1:443: i/o timeout

**Comment by xwang2713** [comment]
Got the same with quay.io/external_storage/efs-provisioner:latest
A month ago the latest version worked. Guess it was updated recently

**Comment by richstokes** [comment]
```
/efs-provisioner flag redefined: log_dir
panic: /efs-provisioner flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000094120, 0x159ed00, 0x214fe70, 0x13da152, 0x7, 0x1405662, 0x2f)
	/usr/local/go/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc000094120, 0x214fe70, 0x13da152, 0x7, 0x0, 0x0, 0x1405662, 0x2f)
	/usr/local/go/src/flag/flag.go:708 +0x8a
github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog.InitFlags(0xc000094120)
	/go/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/klog/klog.go:411 +0x7b
main.main()
	/go/src/github.com/kubernetes-incubator/external-storage/aws/efs/cmd/efs-provisioner/efs-provisioner.go:275 +0x3c
```

**Comment by richstokes** [comment]
@wongma7 Did the correct build get pushed to latest please? So we know if/when we should be good to try again?

**Comment by wongma7** [comment]
@richstokes I just moved the tag so that latest should point to the previous version. Sorry for the delay.

**Comment by richstokes** [comment]
Thanks! It's starting up OK now 👍

**Comment by szmytson** [comment]
Would it be possible to bump the version of alpine to 3.10 as well? (See https://github.com/kubernetes-incubator/external-storage/pull/1219)

**Comment by wongma7** [comment]
v2.4.0 is out with the crash fix AND the alpine bump. It works on my end, but would appreciate if any brave person would like to give it a try before I close this issue. https://quay.io/repository/external_storage/efs-provisioner?tab=tags

**Comment by whereisaaron** [comment]
v2.4.0 is working for me so far @wongma7 👍
No crash and dynamic provisioning and mounting all good with EKS 1.14.
