### ISSUE TITLE
NFS-client writes new volume subdir to wrong export if a static NFS volume exists

### ISSUE THREAD

**Issue by dacleyra** [kubernetes-incubator/external-storage#1242]
NFS server with two exports
```
/data        10.0.0.0/8(rw,sync,no_wdelay,no_root_squash,insecure,fsid=0)
/ifs/kubernetes 10.0.0.0/8(rw,sync,no_wdelay,no_root_squash,insecure,fsid=0)
```

A pre-existing static NFS PV & PVC is created and bound to the image-registry Pod  

NFS-Client Provisioner is configured  

When a new Pod & PVC  is created, the provisioner writes the new volume subdir to the /data export instead of /ifs/kubernetes export, causing the mount.nfs to fail on on the new Pod with file not found, as it is trying to mount ip:/ifs/kubernetes/subdir

**Comment by realModusOperandi** [comment]
According to [this article](https://www.suse.com/support/kb/doc/?id=7010672), different exported paths should have different fsid values.

I was seeing some similar behavior with my PVs and changing the fsid resolved the issue (as far as I can tell.)
