### ISSUE TITLE
redundant Kubernetes serviceaccount declaration in nfs-client manifests

### ISSUE THREAD

**Issue by jeanfabrice** [kubernetes-incubator/external-storage#1249]
Both [nfs-client/deploy/rbac.yaml](/kubernetes-incubator/external-storage/blob/master/nfs-client/deploy/rbac.yaml) and [nfs-client/deploy/deployment.yaml](/kubernetes-incubator/external-storage/blob/master/nfs-client/deploy/deployment.yaml) declares the nfs-client-provisionner ServiceAccount

While this redundancy may not be a problem when feeding kubectl with manifests, it leads to conflicts error when declaring both file as resources  in a kustomization.yaml  Kustomize file and running a build :
```yaml
$ cat base/kustomization.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- external-storage/nfs-client/deploy/rbac.yaml
- external-storage/nfs-client/deploy/deployment.yaml
```

```sh
$ kustomize build base/
2019/11/02 17:34:13 got file 'deployment.yaml', but '/Users/jeanfabrice/Development/infra@home/kubernetes/nfs-client-provisioner-system/base/external-storage/nfs-client/deploy/deployment.yaml' must be a directory to be a root
Error: accumulating resources: merging resources from 'external-storage/nfs-client/deploy/deployment.yaml': may not add resource with an already registered id: ~G_v1_ServiceAccount|~X|nfs-client-provisioner
```

Shouldn't the serviceaccount declaration be stripped off the rbac.yaml file ? This would also be consistent with the [nfs/deploy/kubernetes/deployment.yaml](/kubernetes-incubator/external-storage/blob/master/nfs/deploy/kubernetes/rbac.yaml) manifest

**Comment by yuvipanda** [comment]
@jeanfabrice I don't see a serviceaccount in https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/deploy/deployment.yaml anymore

**Comment by jeanfabrice** [comment]
yes, you are right. 2e997251ecf771ffff46c57391ca8876a911ddc6 fixed this months ago
