### ISSUE TITLE
CEPH RBD Provisioner Creates PV that fails to attach

### ISSUE THREAD

**Issue by davesargrad** [kubernetes-incubator/external-storage#1256]
I have setup a CEPH cluster. Independent of that I have followed processes found online to setup RBD provisioning.

The process I've followed is found here:
https://medium.com/velotio-perspectives/an-innovators-guide-to-kubernetes-storage-using-ceph-a4b919f4e469

This has largely worked. I have a "fast-rbd" storage class as follows:
![image](https://user-images.githubusercontent.com/48793689/68869465-34a97200-06c7-11ea-8485-1bb5fd446a69.png)

I've created the various resources required for provisioning:
![image](https://user-images.githubusercontent.com/48793689/68869578-66223d80-06c7-11ea-849d-faaa4ff09368.png)

I've created the secrets to access ceph properly.
![image](https://user-images.githubusercontent.com/48793689/68869633-80f4b200-06c7-11ea-9d0b-e2929f8b1e73.png)

I am able to create PVC's that successfully bind to the PV created by the provisioner

![image](https://user-images.githubusercontent.com/48793689/68869693-97027280-06c7-11ea-8b40-83796a9b7c74.png)

However, the pod that I create fails to attach to the volume:
![image](https://user-images.githubusercontent.com/48793689/68869745-aa154280-06c7-11ea-805c-5a3848cd50ad.png)

Looking at the pod in more detail I see the following
![image](https://user-images.githubusercontent.com/48793689/68869827-cb762e80-06c7-11ea-8375-06d8badf5af0.png)

Googling the warning: 

> fail to check rbd image status with (executable file not found in $path)

I find various hits online including this [one](https://github.com/kubernetes-incubator/external-storage/issues/1002)

It would seem that others have struggled with this. I dont fully understand the resolution described here. I am looking for guidance relative to getting past this problem

I believe the problem is that the running container does not include "rbd" in its path. Its not clear to me how this is properly resolved.

Guidance/Advice would be appreciated.
Dave

**Comment by davesargrad** [comment]
I am trying an CephFS provisioner instead of an RBD provisioner. 

The PVC is not even binding:
![image](https://user-images.githubusercontent.com/48793689/68882732-c0c69400-06dd-11ea-838a-04b718e4cc41.png)

Here is my cephfs provisioner
![image](https://user-images.githubusercontent.com/48793689/68882780-d20fa080-06dd-11ea-806d-be975d9cb085.png)

The corresponding claim:
![image](https://user-images.githubusercontent.com/48793689/68882811-e2278000-06dd-11ea-8a9c-f1e782d5b812.png)

The provisioner and other resources
![image](https://user-images.githubusercontent.com/48793689/68882877-f79caa00-06dd-11ea-9969-f67c24f03c2e.png)

and the secrets:
![image](https://user-images.githubusercontent.com/48793689/68882946-1bf88680-06de-11ea-9e9b-7357af799d93.png)


I'm just not sure how to debug this.

**Comment by davesargrad** [comment]
The yaml I use to create resources:
`kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-provisioner
  namespace: cephfs
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kube-dns","coredns"]
    verbs: ["list", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-provisioner
subjects:
  - kind: ServiceAccount
    name: cephfs-provisioner
    namespace: cephfs
roleRef:
  kind: ClusterRole
  name: cephfs-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cephfs-provisioner
  namespace: cephfs
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cephfs-provisioner
  namespace: cephfs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cephfs-provisioner
subjects:
- kind: ServiceAccount
  name: cephfs-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cephfs-provisioner
  namespace: cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cephfs-provisioner
  namespace: cephfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cephfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cephfs-provisioner
    spec:
      containers:
      - name: cephfs-provisioner
        image: "quay.io/external_storage/cephfs-provisioner:latest"
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/cephfs
        - name: PROVISIONER_SECRET_NAMESPACE
          value: cephfs
        command:
        - "/usr/local/bin/cephfs-provisioner"
        args:
        - "-id=cephfs-provisioner-1"
      serviceAccount: cephfs-provisioner
`

**Comment by wongma7** [comment]
Your node needs to have the rbd binary installed and in $PATH.

**Comment by davesargrad** [comment]
> Your node needs to have the rbd binary installed and in $PATH.

Hi @wongma7 
Thanks for the reply.

Which node are you referring to? Are you saying that the K8S worker node needs this? This seems a bit odd. It seems to place a burden on the worker node that is specific to RBD.

On a different note, can you take a look at my comment above. I am trying an alternative use of CEPHFS, rather than RBD. For some reason the CEPHFS provision fails to persistent volume. 

I was wondering how the provisioner knows which pool to use. With the RBD provisioner, I explicitly specify a pool. However with the CEPHFS provisioner I only specify a claimRoot "/pvc-volumes". Its not clear to me how this root is mapped to a CEPH resource.

**Comment by davesargrad** [comment]
I'll write up my question about CEPHFS on a separate issue. I dont want it to get lost here. I'll keep this one focused on RBD.

**Comment by davesargrad** [comment]
Wow. I got RBD working. On Centos all i needed to do was 
`yum install centos-common`

**Comment by hellofuturecyj** [comment]
do not close this issue, for it not fix yet

**Comment by kifeo** [comment]
Hi, 
I had the same issue.
on debian installing the ceph-common package on the node resolved the issue
