### ISSUE TITLE
Help getting CEPHFS working

### ISSUE THREAD

**Issue by davesargrad** [kubernetes-incubator/external-storage#1258]
I am trying to get CEPHFS working. The procedure I am following is the one found [here](https://medium.com/velotio-perspectives/an-innovators-guide-to-kubernetes-storage-using-ceph-a4b919f4e469). The procedure follows the section on RBD.

![image](https://user-images.githubusercontent.com/48793689/68949088-4baf9900-0787-11ea-870e-bc4debba65b7.png)

I've struggled with the process, and I have one outstanding issue. I am documenting the process in this issue, hopefully for the benefit of others, but also because I'd like help relative to the final issue.

I already have a CEPH cluster up, and a seperate K8S cluster, and running.

![image](https://user-images.githubusercontent.com/48793689/68949272-ae089980-0787-11ea-87d0-05abad54e9e1.png)

The steps are as follows:

1.  Create the namespace: kubectl create ns cephfs
2.  Create the secret: kubectl create secret generic ceph-secret-admin --from-literal=key="AQDJtspdXMyJLRAAZrRBzSyGR2rG5UqLHuDnAw==" -n cephfs
3.  Create the provisioner: kubectl create -n cephfs -f Ceph-FS-Provisioner.yaml
4.  Create the storage class: kubectl create -f Ceph-FS-StorageClass.yaml
5. Create a PVC: kubectl create -f Ceph-FS-PVC.yaml

I've updated the Ceph-FS-Provisioner.yaml to be consistent with K8S 1.16 (e.g. Deployment no longer in extensions/v1beta1, and now has a selector tag)

Further details as follows. The key I am using in step 2:
![image](https://user-images.githubusercontent.com/48793689/68948258-80225580-0785-11ea-97b0-e4447b339de9.png)

![image](https://user-images.githubusercontent.com/48793689/68948444-e60edd00-0785-11ea-8bd0-c8cbe51d947c.png)

The creation of the provisioner (step 3):
![image](https://user-images.githubusercontent.com/48793689/68948531-10609a80-0786-11ea-9215-6b7e832747a2.png)

The creation of the storage class (step 4): 
![image](https://user-images.githubusercontent.com/48793689/68948585-325a1d00-0786-11ea-97eb-7cbd0e25e679.png)

Note that this storage class is defined as follows:
![image](https://user-images.githubusercontent.com/48793689/68948634-4c93fb00-0786-11ea-81b1-5f8676279072.png)

Specifically it uses a claimRoot /pvc-volumes

When I try to create the PVC it never binds.

![image](https://user-images.githubusercontent.com/48793689/68948697-6fbeaa80-0786-11ea-9b7d-d313787d6dd7.png)

![image](https://user-images.githubusercontent.com/48793689/68948721-7b11d600-0786-11ea-8f63-ccfec75530df.png)

My provisioner pod:
![image](https://user-images.githubusercontent.com/48793689/68948752-8cf37900-0786-11ea-9ff8-8416e7995860.png)

Its description: 
![image](https://user-images.githubusercontent.com/48793689/68948793-a694c080-0786-11ea-8030-08896df06718.png)

I dont quite understand the claimRoot /pvc-volumes. I have not exported this from CEPH. I am guessing that I need to based on the comment I see [here](https://kubernetes.io/docs/concepts/storage/volumes/#cephfs)

![image](https://user-images.githubusercontent.com/48793689/68948952-05f2d080-0787-11ea-85ba-ca8f688dc5a7.png)

Do I need to export "/pvc-volumes" and if so, does someone know the command for this?

Thanks.

As an aside, the tail end of the log on the provisioner pod 
![image](https://user-images.githubusercontent.com/48793689/68949435-02137e00-0788-11ea-83cd-89a8e758f03e.png)

**Comment by kkostin** [comment]
Hi, look at this:
https://github.com/kubernetes-incubator/external-storage/issues/941#issuecomment-418971539

**Comment by davesargrad** [comment]
@kkostin Ty. I eventually got CEPH RBD working. If I ever need to revisit CEPH FS then I am sure I'll reference this issue.

For now I'll close it.
