### ISSUE TITLE
nfs-client-provisioner - Set username and password as parameters

### ISSUE THREAD

**Issue by ricardo-aspira** [kubernetes-incubator/external-storage#1265]
When using the image quay.io/external_storage/nfs-client-provisioner:latest, we can specify parameters as **PROVISIONER_NAME**, **NFS_SERVER** and **NFS_PATH**.

In case my NFS export requires an username/password authentication, I am not be able to use that area.

Is there any reason for not providing this kind of function?
If not, would it be possible to add to the roadmap or it is complicated and wouldn't bring advantages?

Thanks very much.

**Comment by lucwillems** [comment]
https://unix.stackexchange.com/questions/341854/failed-to-pass-credentials-to-nfs-mount
there is no  username/password for NFS. it assumes host access control.
