### ISSUE TITLE
rbd-provisioner image on quay.io is outdated

### ISSUE THREAD

**Issue by lxs137** [kubernetes-incubator/external-storage#1267]
Latest image of rbd-provisioner on quay.io is released at [2018.9](https://quay.io/repository/external_storage/rbd-provisioner?tab=tags). 

I want to create a Block PVC, which is supported in PR #1156. 

THX

**Comment by elemental-lf** [comment]
@lxs137 the crowd has moved on to `ceph-csi`. I'm currently building my own images, see https://github.com/elemental-lf/external-storage.  My repository contains all the latest changes which are related to Ceph from this repository. I've also changed some small things myself, so you should probably review what I've done:

* Any non-protected snapshots are purged before trying to remove an image. 
* PVs which have already lost their backing RBD image for some reason can be deleted and won't error indefinitely.
* All recent RBD image features and not only `layering` are supported. (But remember that you'll need support for this on the client side, too.)

Container images are built automatically:

* `docker.io/elementalnet/cephfs-provisioner:0.4.0`
* `docker.io/elementalnet/rbd-provisioner:0.4.0`

I'm using my own versioning, `0.4.0` is the latest version as of today. I can't guarantee that I'll keep maintaining this as I'll move on to `ceph-csi` too,  eventually. But currently I'm still using them in production.

**Comment by lxs137** [comment]
@elemental-lf  I think `csi` solution is too complex and buggy, the provisioner is enough for me. I will try your provisioner image. THX.
