### ISSUE TITLE
'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": fork/exec /usr/local/bin/cephfs_provisioner: invalid argument

### ISSUE THREAD

**Issue by longqidong** [kubernetes-incubator/external-storage#1269]

**Comment by longqidong** [comment]
use cephfs_provisioner  to create pvc, pvc can not be provisioned ,make errors:
[root@control-1 rbac]# kubectl describe pvc claim -n paas-dev
Name:          claim1
Namespace:     paas-dev
StorageClass:  cephfs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"claim1","namespace":"paas-dev"},"spec":{"accessMode...
               volume.beta.kubernetes.io/storage-provisioner: ceph.com/cephfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age                    From                                                                                      Message
  ----     ------                ----                   ----                                                                                      -------
  Normal   Provisioning          3m26s (x5 over 7m11s)  ceph.com/cephfs_cephfs-provisioner-574c84468d-l2qx9_f34f1650-368a-11ea-ab92-3a265dee8862  External provisioner is provisioning volume for claim "paas-dev/claim1"
  Warning  ProvisioningFailed    3m26s (x5 over 7m11s)  ceph.com/cephfs_cephfs-provisioner-574c84468d-l2qx9_f34f1650-368a-11ea-ab92-3a265dee8862  failed to provision volume with StorageClass "cephfs": fork/exec /usr/local/bin/cephfs_provisioner: invalid argument
  Normal   ExternalProvisioning  71s (x26 over 7m11s)   persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "ceph.com/cephfs" or manually created by system administrator

and the cephfs_provisioner logs :
r: invalid argument, output: 
W0114 07:15:19.510976       1 controller.go:746] Retrying syncing claim "paas-dev/claim1" because failures 3 < threshold 15
E0114 07:15:19.510995       1 controller.go:761] error syncing claim "paas-dev/claim1": failed to provision volume with StorageClass "cephfs": fork/exec /usr/local/bin/cephfs_provisioner: invalid argument
I0114 07:15:19.511016       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"paas-dev", Name:"claim1", UID:"8b8874e9-df41-4d6c-94b1-84d8e0a64061", APIVersion:"v1", ResourceVersion:"23305650", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": fork/exec /usr/local/bin/cephfs_provisioner: invalid argument
I0114 07:17:19.511193       1 controller.go:987] provision "paas-dev/claim1" class "cephfs": started
I0114 07:17:19.513861       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"paas-dev", Name:"claim1", UID:"8b8874e9-df41-4d6c-94b1-84d8e0a64061", APIVersion:"v1", ResourceVersion:"23305650", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "paas-dev/claim1"
E0114 07:17:19.515725       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-e69ed80e-369d-11ea-ab92-3a265dee8862" for "kubernetes-dynamic-user-e69ed844-369d-11ea-ab92-3a265dee8862", err: fork/exec /usr/local/bin/cephfs_provisioner: invalid argument, output: 
W0114 07:17:19.515768       1 controller.go:746] Retrying syncing claim "paas-dev/claim1" because failures 4 < threshold 15
E0114 07:17:19.515791       1 controller.go:761] error syncing claim "paas-dev/claim1": failed to provision volume with StorageClass "cephfs": fork/exec /usr/local/bin/cephfs_provisioner: invalid argument
I0114 07:17:19.515811       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"paas-dev", Name:"claim1", UID:"8b8874e9-df41-4d6c-94b1-84d8e0a64061", APIVersion:"v1", ResourceVersion:"23305650", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": fork/exec /usr/local/bin/cephfs_provisioner: invalid argument

**Comment by baoroushi** [comment]
me too -_-||

**Comment by windayski** [comment]
Check your secret. The secret needs to be base64 encoded.

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
