### ISSUE TITLE
nfs-provisioner v2.3.0: deployment.yaml does not contain all needed port for v2.3.0 quay image

### ISSUE THREAD

**Issue by radtriste** [kubernetes-incubator/external-storage#1277]
related to https://github.com/kubernetes-incubator/external-storage/issues/1262

Image has been updated on [Quay](https://quay.io/repository/kubernetes_incubator/nfs-provisioner?tag=v2.3.0&tab=tags) to v2.3.0 but [deployment.yaml](https://github.com/kubernetes-incubator/external-storage/blob/nfs-provisioner-v2.3.0/nfs/deploy/kubernetes/deployment.yaml) on nfs-provisioner-v2.3.0 tag does not include the latest port(s).

**Comment by radtriste** [comment]
service and deployment are missing some TCP/UDP ports.
using current master is ok, but the tag should contain the correct deployment.yaml

**Comment by appunni-dishq** [comment]
Is this still pending ?

**Comment by radtriste** [comment]
this is pending. The fix mentioned in this issue is only in our internal repository and not on this one.
nothing has changed on our side.

**Comment by radtriste** [comment]
do we have an update for this ?
Planning a 2.3.1 or something ?

For now we use the 2.2.2 as workaround ...

**Comment by appunni-dishq** [comment]
I am using 2.3.0 it is working. Using the stable/nfs-server-provisioner

**Comment by radtriste** [comment]
What is `stable/nfs-server-provisioner` ?

When you try to setup deploy in kubernetes the [deployment.yaml](https://github.com/kubernetes-incubator/external-storage/blob/nfs-provisioner-v2.3.0/nfs/deploy/kubernetes/deployment.yaml), the pod is startgin well.
But when requesting a new volume storage, you get an error into the nfs-provisioner that some port are unavailable.

This is because the [quay image](https://quay.io/repository/kubernetes_incubator/nfs-provisioner?tag=v2.3.0&tab=tags) is needing much more opened ports on deployment/service than before:
https://github.com/kubernetes-incubator/external-storage/compare/nfs-provisioner-v2.3.0...master
(look for `nfs/deploy/kubernetes/deployment.yaml`). Those latest ports from master need also to be on _deployment.yaml_ from nfs-provisioner-v2.3.0 tag ... Else it does not work.

**Comment by appunni-dishq** [comment]
It's a helm chart for setting up a nfs server provisiner for dynamic PV provisioning with PVC . I think they have updated the ports properly in their template.

**Comment by radtriste** [comment]
Could we correct the deployment.yaml as well ?
We are not using helm on our side

**Comment by duanwei33** [comment]
@radtriste, agree with you, seems the port part in [deployment.yaml with nfs-provisioner-v2.3.0 tag](https://github.com/kubernetes-incubator/external-storage/blob/nfs-provisioner-v2.3.0/nfs/deploy/kubernetes/deployment.yaml) should be updated as [master](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/deploy/kubernetes/deployment.yaml).

**Comment by wongma7** [comment]
I don't want to retroactively move the git tag but that is an option. Alternatively, I plan to make a patch to remove the port checking altogether and release 2.3.1 since technically it was a breaking change and it should not have gone out in a release

**Comment by radtriste** [comment]
Good for me for a 2.3.1

**Comment by radtriste** [comment]
@wongma7 any planned date on that 2.3.1 tag ?

**Comment by misko566** [comment]
I have same problem but.
Combination of  image "quay.io/kubernetes_incubator/nfs-provisioner
  tag: v2.2.2" in Values file and "stable/nfs-server-provisioner" as chart worked for me. 

Combination of v2.2.2 and downloaded stable chart from "github/helm/charts/stable" also didn't work.

**Comment by capusta** [comment]
probably same: https://github.com/kubernetes-incubator/external-storage/issues/1282

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
