### ISSUE TITLE
[local-volume] Detect capacity of mount points

### ISSUE THREAD

**Issue by ddysher** [kubernetes-incubator/external-storage#132]
In alpha release, static provisioner should post PV with capacity field; we'll start with standard linux utilities.

**Comment by ddysher** [comment]
ref https://github.com/kubernetes-incubator/external-storage/pull/135

**Comment by msau42** [comment]
How accurate do we want to be with the capacity?

I ran on GCE with local SSDs, which are 375GB.  The actual PV created has this capacity, which is a little unreadable.
    storage: 367238044Ki

**Comment by ddysher** [comment]
Yeah, quantity package will use the best unit without losing precision.  Considering disk space is usually quite large, how about we default to GB and give the option for user to change to smaller unit?

If we prefer so, we should call out in the doc that this is a rounded down number.

**Comment by msau42** [comment]
I'm fine with rounding to GB

**Comment by ianchakeres** [comment]
@ddysher & @msau42 - approximately how much of the total space is reserved by the file system? I'm wondering if the amount is generally smaller than rounding errors. Re: https://github.com/kubernetes-incubator/external-storage/pull/154#discussion_r121831808

**Comment by ddysher** [comment]
@ianchakeres sorry for late reply.  It depends on the type of file system. For ext file system, it defaults to 5%, and this is reserved to root users.  For xfs, it defaults to 5% or 8192 fsb, whichever is smaller.  I didn't look at other fs.

So for xfs, it's possible the reserved space is smaller than rounding errors. What's the problem do you foresee?

**Comment by ianchakeres** [comment]
@ddysher - I'm just wondering whether users care and will understand the nuance of the FSAvailableBytes calculation when compared with the other FSInfo available calculation, especially after rounding. My intuition says that we probably need only one method/definition of available, and I'd love your advice on which one is the right definition/calculation.

**Comment by ianchakeres** [comment]
@ddysher - we might want to add a RoundDownSize method to kubernetes/pkg/volume/util.go, like the RoundUpSize function on line 261 - https://github.com/kubernetes/kubernetes/blob/38837b018bf2a9215653054c2ec59636c0ba9440/pkg/volume/util.go#L261

**Comment by msau42** [comment]
I would prefer to be consistent with what the kubernetes system is reporting in the fs volume metrics.

**Comment by ddysher** [comment]
@ianchakeres sounds good!

@msau42 @ianchakeres  are u suggestion we change capacity to whole capacity of the volume? what's the use case for fs.go in kubernetes?  AFAICT, in kubernetes, you can reserve space using command line options in kubelet, but we don't have this.  This means what we get from availableByte is the actual reported value; while in kubernetes, what you get from available is for capacity, and what we mean by available here is called allocatable (which is capacity minus admin reserved) in kubernetes.

My point is that I do agree there is a difference between the meaning of `available` here and kubernetes, but I don't think we can directly use it for our case. Maybe we can change available to allocatable?

**Comment by msau42** [comment]
In kubernetes, each volume plugin can report fs usage metrics, so for each volume, it can tell you used and available capacity.  That's where these fs utils are being used.  So I think we should be consistent with what we are reporting to the user through these metrics.

The allocatable feature is more about reserving local root partition space for the kubernetes system.

**Comment by ddysher** [comment]
interesting to know.  I briefly scanned `pkg/volume` searching for usage related metrics, but it doesn't seem there is any volume plugin reporting the value.  Also, based on storage roadmap, reporting value is yet to be done. Did I miss anything?
> each volume plugin can report fs usage metrics

**Comment by msau42** [comment]
There's NewMetricsDu and NewMetricsStatFS that use util.GetFsInfo.  They are used by emptydir, secrets, gcepd, aws ebs, azure file, flocker, and portworx volumes.

The volume metrics feature in the roadmap is different.  It's more about how many times mount, attach are called.

**Comment by ddysher** [comment]
By metrics, I mean PVC capacity usage :)   If it's already used, then we can just use it then.

**Comment by msau42** [comment]
@ddysher @ianchakeres can this be closed?

**Comment by ianchakeres** [comment]
@msau42 @ddysher -  I think we can close this issue.

**Comment by ddysher** [comment]
Yes, we can close it.
