### ISSUE TITLE
[ProvisionController] Deprovision upon PV deletion

### ISSUE THREAD

**Issue by zcahana** [kubernetes-incubator/external-storage#151]
Currently, the only path that triggers deprovisioning (i.e., `Provisioner.Delete()`) is when a dynamically provisioned PV is marked as released (and has `ReclaimPolicy: Delete`).
For cases where a PV is directly deleted by a user (say, accidently by an admin), the `Provisioner.Delete()` call will never be invoked for that PV, which may lead to dangling storage assets at the physical storage provider.

Here's a rough proposal of how to address this:
1. Extend the `ProvisionController` to intercept PV deletions (of its particular storage class and provisioner name).
2. Upon PV deletion, if the PV is bound, and its referenced PVC exists (not deleted), invoke `Provisioner.Delete(pv)`.

**Comment by wongma7** [comment]
This is definitely an issue, but I think our hands are somewhat tied. We can't deviate much from how upstream does things else we risk breaking user expectations. Deleting the PVC is seen as the "proper" way to do things, deleting bound PVs is almost always a mistake. A pod can still be using the PVC->PV->asset even if the PV in the chain is deleted, so we can't always delete the storage asset when its PV is deleted.

IMO the best solution is to have Kubernetes prevent deleting bound PVs in the first place: https://github.com/kubernetes/kubernetes/issues/33355 but we won't have it for 1.5-7 

So theoretically when a PV is deleted and in Bound state we could try to figure out if the PVC is being used by any pod and if not, delete the storage asset. If the PVC is still being used, leave the storage asset dangling like before. WDYT about this?

We could also log Bound PVs being deleted to help admins clean up.

**Comment by zcahana** [comment]
My thinking is that deleting a bound PV *should* be allowed, as long as the PVC is not currently in-use by a pod (e.g., for an admin to "replace" the actual storage fullfilling a specific claim). I'd expect this validation to be done at the k8s API layer, and reading kubernetes/kubernetes#33355 (as well as kubernetes/kubernetes#45143), I get the impression that this indeed will be handled upstream.

> We could also log Bound PVs being deleted to help admins clean up.
That might raise security issues, if PVs have secrets stored in them. I'm not sure if that's normally the case, or PVs usually reference Secret (as in API objects) to get credentials for the storage service. Either way, this seems to break RBAC.

**Comment by wongma7** [comment]
The "replace" storage for a claim use-case is not possible because when a PVC's PV is deleted, it enters the irrecoverable `Lost` state. I don't think such a thing will ever be implemented as it would be a major change in the PVC+PV lifecycle. The "official" recommendation is probably to just delete the PVC+PV and create a new PVC+PV with same name, as unpleasant as that is.

Agreed there are security issues. I believe the story there is that PVs should have a reference to a secret and that only non-admin users should ever be able to read the PV/secret.

Anyway I'm okay with keeping this issue open to track and +1 upstream efforts around this area.

**Comment by zcahana** [comment]
Good point about the irrecoverability of the PVC.
So, given that the "replace" use case is impossible, it's indeed seems best to disallow deletion of any bound PV.
