### ISSUE TITLE
Need to add event list permission to ClusterRole

### ISSUE THREAD

**Issue by pragkent** [kubernetes-incubator/external-storage#152]
When I tested my volume provisioner based on this library, I found some error in logs.

```logs
I0608 12:34:49.601544       1 controller.go:854] cannot start watcher for PVC default/test-nfs: User "system:serviceaccount:kube-system:persistent-volume-provisioner" cannot list events in the namespace "default". (get events)
E0608 12:34:49.601580       1 controller.go:667] Error watching for provisioning success, can't provision for claim "default/test-nfs": User "system:serviceaccount:kube-system:persistent-volume-provisioner" cannot list events in the namespace "default". (get events)
```

And then I found List invocation [here](https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L986).

I think we need to add `event` `list` permission to the ClusterRoles for all provisioners based on
this library.

I can help to submit a pull request if needed.

**Comment by wongma7** [comment]
You are right, I think it is present in some but missing from others. Please do feel free to make a PR, otherwise I'll have time to fix it tomorrow
