### ISSUE TITLE
Unable to specify mountOptions in the parameters of storageclass definition

### ISSUE THREAD

**Issue by rprav007** [kubernetes-incubator/external-storage#158]
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
   name: nfs
provisioner: storage-nfs.aws.event-cloud.net/nfs
parameters:
   gid: none
   rootSquash: "false"
   mountOptions:
      server: 172.16.185.20
      path: /data

This YAML file does not work. Not sure how to specify the mount option so the NFS drive can be mounted when volumes are requested by this storage class. The documentation does not provide any examples for this.

Any help will be much appreciated.

Thanks
-Praveen

**Comment by wongma7** [comment]
The following works for me:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: example-nfs
provisioner: example.com/nfs
parameters:
  mountOptions: "soft"
```

Your mountOptions looks blank to me, can you post it again? It should be a quoted comma-separated string.

I will add an example to the documentation, sorry for that!

**Comment by wongma7** [comment]
Note also this is new to v1.0.8

**Comment by rprav007** [comment]
`kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
   name: nfs
provisioner: storage-nfs.aws.event-cloud.net/nfs
parameters:
   gid: none
   rootSquash: "false"
   mountOptions: "172.16.185.20:/data"`

I want to specific a specific server and mount path just like
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.16.185.20
    path: "/data"`

The provisioner is not picking up my storageclass definition parameters for some reason

**Comment by wongma7** [comment]
Ok I see; server and path are not valid options, https://github.com/kubernetes-incubator/external-storage/tree/master/nfs runs as a standalone server. If you want the provisioner to create export directories in an existing NFS server, you must use https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client.

**Comment by wongma7** [comment]
mountOptions refers to https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options which is just a mechanism to add extra options after "mount server:path...". Server:path is determined by the provisioner and filled into every PV it provisions like so:

```yaml
  nfs:
    server: 172.16.185.20
    path: "/data/pvc-asdf"
```

If you have time to chat more about what you want to achieve, find me @mawong on slack!

**Comment by rprav007** [comment]
@wongma7 - Thanks a bunch for the prompt responses. The nfs-client did the trick. Sorry for having logged this as an issue. 

Appreciate it

Thanks
-Praveen

**Comment by wongma7** [comment]
No problem, that's what issues are made for! :)
