### ISSUE TITLE
Library consumers do not have access to some upstream volume util functions

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#165]
Come up a couple times now but some volume util functions people expect to have available when writing volume plugins/provisioners are not automatically copied to client-go and so not readily available to us https://github.com/kubernetes/kubernetes/blob/38837b018bf2a9215653054c2ec59636c0ba9440/pkg/volume/util.go

We have copied `RoundUpSize` to a util package. We can keep copying them on an as-is needed basis or look into refactoring things upstream such that the functions we need are automatically copied to client-go

**Comment by msau42** [comment]
Yeah, I would look into refactoring so we can get the functions into client-go

**Comment by caesarxuchao** [comment]
The future k8s.io/pkg repository seems to be a better home. See https://github.com/kubernetes/kubernetes/issues/48209#issuecomment-313870481.

client-go shouldn't contain type specific helper functions.

**Comment by wongma7** [comment]
SGTM! I'm all on board with having more purposeful repos & moving away from 'have everything arbitrarily in client-go' :)
