### ISSUE TITLE
[nfs-client-provisioner] PV stuck in pending state

### ISSUE THREAD

**Issue by msi88** [kubernetes-incubator/external-storage#174]
Hi,

currently i'm trying to get the nfs-client-provisioner running on a Raspberry Pi Kubernetes cluster. I could already sucessfully deploy the provisioner in an ARM compatible docker container (see https://gitlab.com/rpikube/nfs-provisioner-arm32v7 for details). During claiming a PV with the nfs-client-provisioner i encountered 2 issues.

1. The name of the PV has to be ${pvName} instead of ${namespace}-${pvcName}-${pvName} because otherwise i get stucked in an endless loop because it tries to provision the PV again and again (because it tries to find a PV with the name ${pvName} instead of ${namespace}-${pvcName}-${pvName} in controller.go). I could solve this issue by modifing the pvName from
`pvName := strings.Join([]string{pvcNamespace, pvcName, options.PVName}, "-")` to `pvName := options.PVName`

2. The second problem is that the PV and PVC stucks in pending state without any errors. I enabled verbose logging as well but there seems to be nothing wrong (see [nfs-client-provisioner.txt](https://github.com/kubernetes-incubator/external-storage/files/1083319/nfs-client-provisioner.txt)). The directory gets sucessfully created on the NFS server with permissions 777 owned by nobody:nogroup

I also attach the [deployment.txt](https://github.com/kubernetes-incubator/external-storage/files/1083321/deployment.txt) which contains everything to setup the nfs client provisioner including rbac authorization and psp.

Any help would be appreciated.
Thanks

**Comment by msi88** [comment]
Kubernetes v1.6.4 (installed with kubeadm)
nfs-client-provisioner built from master

**Comment by wongma7** [comment]
1. is indeed an error although it's kind of harmless, nice catch I will fix it.
2. We need to check the kubernetes controller-manager logs to see why the PV and PVC are not getting bound. They look correct to me, they should get bound

```json
{
  "kind": "PersistentVolume",
  "apiVersion": "v1",
  "metadata": {
    "name": "pvc-d5dcab66-5437-11e7-bfac-b827eba95799",
    "selfLink": "/api/v1/persistentvolumespvc-d5dcab66-5437-11e7-bfac-b827eba95799",
    "uid": "d629e1ed-5437-11e7-bfac-b827eba95799",
    "resourceVersion": "119028",
    "creationTimestamp": "2017-06-18T15:07:25Z",
    "annotations": {
      "pv.kubernetes.io/provisioned-by": "rpikube/nfs"
    }
  },
  "spec": {
    "capacity": {
      "storage": "1Mi"
    },
    "nfs": {
      "server": "172.16.0.1",
      "path": "/mnt/ssd/pvc-d5dcab66-5437-11e7-bfac-b827eba95799"
    },
    "accessModes": [
      "ReadWriteMany"
    ],
    "claimRef": {
      "kind": "PersistentVolumeClaim",
      "namespace": "default",
      "name": "test-claim",
      "uid": "d5dcab66-5437-11e7-bfac-b827eba95799",
      "apiVersion": "v1",
      "resourceVersion": "119023"
    },
    "persistentVolumeReclaimPolicy": "Delete",
    "storageClassName": "nfs-client-provisioner"
  },
  "status": {
    "phase": "Pending"
  }
}

{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "test-claim",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/persistentvolumeclaims/test-claim",
    "uid": "d5dcab66-5437-11e7-bfac-b827eba95799",
    "resourceVersion": "119321",
    "creationTimestamp": "2017-06-18T15:07:24Z",
    "annotations": {
      "control-plane.alpha.kubernetes.io/leader": "{\"holderIdentity\":\"c2451b1c-5437-11e7-8392-32bb363c78cf\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2017-06-18T15:07:24Z\",\"renewTime\":\"2017-06-18T15:09:23Z\",\"leaderTransitions\":0}",
      "volume.beta.kubernetes.io/storage-class": "nfs-client-provisioner"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteMany"
    ],
    "resources": {
      "requests": {
        "storage": "1Mi"
      }
    }
  },
  "status": {
    "phase": "Pending"
  }
}
```

**Comment by msi88** [comment]
Hi,

thanks for the answer. Please see the log 
[kube-controller-manager.txt](https://github.com/kubernetes-incubator/external-storage/files/1087558/kube-controller-manager.txt).

I guess the problem is that the persistent volume binder is not enabled:
`{"log":"W0620 08:34:15.749212       1 controllermanager.go:546] \"persistentvolume-binder\" is disabled\n","stream":"stderr","time":"2017-06-20T08:34:17.025253666Z"}`

**Comment by msi88** [comment]
Maybe it's related to https://github.com/kubernetes/kubernetes/issues/46770

**Comment by wongma7** [comment]
Check your arguments to `kube-controller-manager`, specifically --controllers. It must have "-persistentvolume-binder" in it, which should be removed

https://kubernetes.io/docs/admin/kube-controller-manager/

--controllers stringSlice                                           A list of controllers to enable.  '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named 'foo'.
All controllers: attachdetach, bootstrapsigner, certificatesigningrequests, cronjob, daemonset, deployment, disruption, endpoint, garbagecollector, horizontalpodautoscaling, job, namespace, node, persistentvolume-binder, podgc, replicaset, replicationcontroller, resourcequota, route, service, serviceaccount, serviceaccount-token, statefuleset, tokencleaner, ttl
Disabled-by-default controllers: bootstrapsigner, tokencleaner (default [*])

**Comment by msi88** [comment]
Thanks alot for your support. After removing "-persistentvolume-binder" everything works as expected!
