### ISSUE TITLE
`seccomp` when running NFS-provisioner with the k8s Deployment

### ISSUE THREAD

**Issue by nieldw** [kubernetes-incubator/external-storage#176]
The documentation for running the NFS-provisioner using Docker includes this line:

> If you are using Docker 1.10 or newer, it also needs a more permissive seccomp profile: unconfined or deploy/docker/nfs-provisioner-seccomp.json

How does this affect you when running with Kubernetes and Docker 1.10 or newer? Do you need to add the more permissive seccomp profile as well?

**Comment by wongma7** [comment]
No need because kubernetes at the moment by default runs everything unconfined: https://github.com/kubernetes/kubernetes/issues/20870 so the nfs server should just work

**Comment by nieldw** [comment]
OK great. Thanks.
