### ISSUE TITLE
build Error "ceph/cephfs/cephfs-provisioner.go "

### ISSUE THREAD

**Issue by zhwenh** [kubernetes-incubator/external-storage#187]
I Build ceph/cephfs/cephfs-provisioner.go show this Errors:
/usr/local/go/bin/go build -i -o /private/var/folders/52/6kn6f9fx0jl1cqzdb6nt2mf80000gn/T/Build_cephfs_provisioner_go_and_rungo -gcflags "-N -l" /Users/GoProjects1/src/kubernetes-incubator/external-storage/ceph/cephfs/cephfs-provisioner.go

ceph/cephfs/cephfs-provisioner.go:63: cannot use cephFSProvisioner literal (type *cephFSProvisioner) as type controller.Provisioner in return argument:
	*cephFSProvisioner does not implement controller.Provisioner (wrong type for Delete method)
		have Delete(*"kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".PersistentVolume) error
		want Delete(*"k8s.io/client-go/pkg/api/v1".PersistentVolume) error
ceph/cephfs/cephfs-provisioner.go:67: cannot use cephFSProvisioner literal (type *cephFSProvisioner) as type controller.Provisioner in assignment:
	*cephFSProvisioner does not implement controller.Provisioner (wrong type for Delete method)
		have Delete(*"kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".PersistentVolume) error
		want Delete(*"k8s.io/client-go/pkg/api/v1".PersistentVolume) error
ceph/cephfs/cephfs-provisioner.go:136: cannot use options.PersistentVolumeReclaimPolicy (type "k8s.io/client-go/pkg/api/v1".PersistentVolumeReclaimPolicy) as type "kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".PersistentVolumeReclaimPolicy in field value
ceph/cephfs/cephfs-provisioner.go:137: cannot use options.PVC.Spec.AccessModes (type []"k8s.io/client-go/pkg/api/v1".PersistentVolumeAccessMode) as type []"kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".PersistentVolumeAccessMode in field value
ceph/cephfs/cephfs-provisioner.go:139: cannot use "kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".ResourceName("kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".ResourceStorage) (type "kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".ResourceName) as type "k8s.io/client-go/pkg/api/v1".ResourceName in map index
ceph/cephfs/cephfs-provisioner.go:139: cannot use options.PVC.Spec.Resources.Requests["kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".ResourceName("kubernetes-incubator/external-storage/vendor/k8s.io/client-go/pkg/api/v1".ResourceStorage)] (type "k8s.io/apimachinery/pkg/api/resource".Quantity) as type "kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/api/resource".Quantity in map value
ceph/cephfs/cephfs-provisioner.go:309: cannot use clientset (type *"kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes".Clientset) as type "k8s.io/client-go/kubernetes".Interface in argument to controller.NewProvisionController:
	*"kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes".Clientset does not implement "k8s.io/client-go/kubernetes".Interface (wrong type for Apps method)
		have Apps() "kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes/typed/apps/v1beta1".AppsV1beta1Interface
		want Apps() "k8s.io/client-go/kubernetes/typed/apps/v1beta1".AppsV1beta1Interface

**Comment by wongma7** [comment]
What version of go are you using? And what is your GOPATH? /Users/GoProjects1?
