### ISSUE TITLE
Failed to pull image quay.io/external_storage/local-volume-provisioner-bootstrap 

### ISSUE THREAD

**Issue by metal3d** [kubernetes-incubator/external-storage#202]
I'm trying to use local-volume provisionner on our openshift installation but the bootsrapper refuse to start with ErrImagePull

And actually:

```
# docker pull quay.io/external_storage/local-volume-provisioner-bootstrap
Using default tag: latest
Trying to pull repository quay.io/external_storage/local-volume-provisioner-bootstrap ... 
manifest unknown: manifest unknown
```
Any help ?

**Comment by ddysher** [comment]
I think the image is not pushed yet @msau42

**Comment by metal3d** [comment]
Right, the quay.io repo is empty.

Anyway, It seems it cannot run on openshift. Some configuration are not usable.

I tried to create daemonsets from local-volume provisionner directory and some role binding cannot be set. It's way difficult to understand how to launch it like that. I will maybe create a new issue to have answers on OpenShift integration, and to help (if I can) to document this work.

**Comment by ddysher** [comment]
If you are using bootstrapper, then there's no need to use artifacts from provisioner directory.  i don't have permission to push image to quay.io, @msau42 can help on that i believe.

sadly we don't have bandwidth to test it with openshift right now; please go head create an issue, and we can try to make it work. :)

**Comment by metal3d** [comment]
@ddysher strangely, using provisionner directory, I now can be able to launch daemonset (after creating configmap and so on...)

I only have a problem on right (serviceaccount cannot read persistent volumes, but I will find wich scc to apply). So, for "Openshift", I will create a mini doc and try to provide you how I did.

For now, I will not use bootsrapper... :)

**Comment by ddysher** [comment]
@metal3d thx!

You don't have to use bootstrapper if it works, it's just a convenient pod for configuring provisioner.  And actually, you don't have to use provisioner if you can manually create PVs, it's just a convenient daemonset to create PVs :)

**Comment by metal3d** [comment]
What I need is a provisionner because we want to launch Galera database with direct access on disk. And because we use statefullsets, we only can use volume claims.

To be able to not create PV's manually for each projects, we need something that create PV's automatically   with host afinity. If that daemonset can work, we will be able to let our user create Galera without any intervention by our side. And trust me, it's very important for us :)

At this time I don't find which scc to apply to let local-volume-admin to be able to list/create pv's (system:persistent-volume-provisioner doesn't exists on openshift, I only can apply system:node at this time)

BTW: thanks for you help and quick replies

**Comment by ddysher** [comment]
Yeah, it's very important and that's why it's there :)

**Comment by msau42** [comment]
I just pushed the latest bootstrapper, so you should see it now.

@ddysher can you add an example configmap to the provisioner directory, in case people want to use the provisioner directly instead of using the boostrapper?

**Comment by metal3d** [comment]
@msau42 it seems that no configmap is used when using provisionner directly, am I wrong ?

**Comment by metal3d** [comment]
It pulls now, but it is unusable on openshift, role bindings are not the same. See #204 for correct roles to apply. So, at this time, I can close that issue that was only for the "pull" problem.

Thanks a lot

**Comment by msau42** [comment]
If no configmap is specified, then it will fall back to default settings of using storageclass "local-storage" and hostdir "/mnt/disks".  If you want to specify something else, then you need to provide a configmap

**Comment by metal3d** [comment]
@msau42 I tried and the daemonset only takes care of the volumes instruction, I tried to change configMap, giving bad configuration, good configuration, redeploying daemonset, and it never used values that are inside configMap.

Maybe I did something wrong, but I thought that the configMap were use by de "deployer" to configure volumes. That's why I needed to change provsionner daemonset to change volumes.

**Comment by ddysher** [comment]
You'll also need to update daemonset volume mount for provisioner to see the mounts.

Default works because it the example daemonset has the mount in its yaml file:
```
        volumeMounts:
        - name: discovery-vol
          mountPath: "/local-disks"
      volumes:
      - name: discovery-vol
        hostPath:
          path: "/mnt/disks"
      serviceAccount: local-storage-admin
```

**Comment by metal3d** [comment]
@ddysher actually that's what I meant. Sorry for my bad english if I was not clear :)

**Comment by ddysher** [comment]
oh, now i understand, sorry i didn't read very carefully
