### ISSUE TITLE
Define which scc and role to apply on openshift

### ISSUE THREAD

**Issue by metal3d** [kubernetes-incubator/external-storage#204]
Hi,

As seen in #202 I'm trying to apply installation to an openshift cluster.

At this time, I can use daemonset from provisionner but an error says me (in logs) that local-volume-admin is not auhorized to list (and so, later, I guess, to create) persistent volumes.

This is how I'm creating my serviceaccount:

```
oc create serviceaccount local-storage-admin
oc adm policy add-scc-to-user privileged -z local-storage-admin
oc adm policy add-cluster-role-to-user system:node -z local-storage-admin
```
Note that system:persistent-volume-provisioner dosen't exists on openshift.

Thanks for your help.

PS: If I can use it on OpenShift, I will try to provide a documentation on how to deploy on that cluster system

**Comment by ddysher** [comment]
Does everything work once you bind service account to system:node?

**Comment by metal3d** [comment]
No it doesn't, I've finally found wich are the roles to apply:

- `system:node`
- `system:pv-attach-detach-controller`
- `system:pv-binder-controller`
- `system:pv-provisioner-controller`
- `system:pv-recycler-controller`

I know have a new problem, each pods says:

```
Found new volume at host path "/mnt/disks/d10" with capacity 6280970240, creating Local PV "local-pv-31b5888"
E0628 09:58:02.875045       1 discovery.go:153] Error creating PV "local-pv-31b5888" for volume at "/mnt/disks/d10": PersistentVolume "local-pv-31b5888" is invalid: spec: Required value: must specify a volume type
```

New issue ? or I should just rename this one to "integrate inside openshift" ?

**Comment by metal3d** [comment]
Note: bootstrapper is unusable because rolebindings are not the same for openshift.

My last problem is https://github.com/kubernetes-incubator/external-storage/issues/204#issuecomment-311614839

**Comment by wongma7** [comment]
OpenShift doesn't have the kube-side local volume API yet so it won't recognize local PVs. I'm not sure it will be made available in 3.6 either since it's still alpha in upstream. So even though the local volume provisioner is external we're still reliant on things existing on the kube/openshift side.

**Comment by ddysher** [comment]
Yeah, you'll need to have local volume API for it to work, as @wongma7 said, it is not strictly external.

**Comment by metal3d** [comment]
It's a pitty for me... I'm using openshift 1.5.1 so this is not usable. Our Galera works on GlusterFS right now, but as we are using statefulsets I thought that I will be able to write data on hostPath.

Without any provisionner, I really don't know how to create PVs and to be sure that PVC will bind PV on current host.

Bad news so...

**Comment by metal3d** [comment]
@ddysher yes right, but local-volume api should work on k8s 1.7 while openshift (right now) uses 1.5.

**Comment by wongma7** [comment]
there will be support on openshift side for local volume soon (1yr later)
/area local-volume
