### ISSUE TITLE
External provisioners should validate PVC AccessModes

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#207]
I think only gluster/block may needs changing...@humblec should it reject PVC with RWM? https://github.com/kubernetes/kubernetes/pull/47274

**Comment by humblec** [comment]
@wongma7 yes, I need to reject that in gluster block

**Comment by humblec** [comment]
https://github.com/kubernetes-incubator/external-storage/pull/306

**Comment by humblec** [comment]
@wongma7 Can you please close this issue?

**Comment by wongma7** [comment]
I need to check other provisioners first

**Comment by humblec** [comment]
ah.. yes :)
