### ISSUE TITLE
Vendored package needs updating

### ISSUE THREAD

**Issue by dhirajh** [kubernetes-incubator/external-storage#230]
Requesting the update of the package golang.org/x/sys/unix which has been vendored. The update has the BLK* constants needed for some of the block device work happening in local volume.

**Comment by wongma7** [comment]
Sounds good to me! can run `glide up -v` and `glide-vc --use-lock-file` to pick up updates

**Comment by wongma7** [comment]
closing; I'm going to be updating docs on the way we are doing vendoring, has come up a lot recently, and could maybe explore a better/easier way.
