### ISSUE TITLE
Instructions on CLA seem to be outdated

### ISSUE THREAD

**Issue by dhirajh** [kubernetes-incubator/external-storage#233]
I followed the instructions to get a CCLA from this document

https://github.com/kubernetes-incubator/external-storage/blob/master/CONTRIBUTING.md

Even though I had a CLA setup with Linux Foundation (in prep for k8s core work), I was surprised to note that this document required a Google Project CLA. I went and got one processed by my company. However, when the travis build ran for my PR, it complained that I didn't have a CLA from Linux Foundation to submit a PR. So it looks like the CCLA link in  the document is outdated. You really need a Linux Foundation CLA just like in k8s core work.

**Comment by ianchakeres** [comment]
I suspect these are the instructions that should be followed - https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ

Linux Foundation = CNCF - https://identity.linuxfoundation.org/projects/cncf
