### ISSUE TITLE
type PersistentVolume moved to k8s.io/api/core/v1

### ISSUE THREAD

**Issue by pospispa** [kubernetes-incubator/external-storage#234]
The external provisioner library uses the `PersistentVolume` type in https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/volume.go#L32
and imports it from `k8s.io/client-go/pkg/api/v1` in https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/volume.go#L22

However, the `type PersistentVolume` was added to `k8s.io/api/core/v1` in commit https://github.com/kubernetes/api/commit/791c59f81232d13df6852a4858611cdb7774b9ca
and was remove from `k8s.io/client-go/pkg/api/v1` in commit https://github.com/kubernetes/client-go/commit/d82cfb70ddc9faa25f41e39a8f73d7ccd20d7a55

The external provisioner library shall be adapted to the above changes.

**Comment by pospispa** [comment]
@wongma7 @tsmetana please, do you agree that the above adaptation is necessary and that it should be done asap?

**Comment by wongma7** [comment]
Yes, this should be fixed by https://github.com/kubernetes-incubator/external-storage/pull/221 ! Thanks to @kokhang for keeping on top of k8s api changes
