### ISSUE TITLE
Data in PVC cannot be accessed after pod restart

### ISSUE THREAD

**Issue by mmaquevice** [kubernetes-incubator/external-storage#236]
Hey,

I have a problem with my data in my PV created by `nfs-provisioner`:
If data exists before I start my pod, this data cannot be accessed by my pod.

If I execute `chown -R root: mydata` inside my pod where `mydata` is mapped to the PV mount folder, it works. But if the pod restarts, I have to reexecute the command...

Any idea ?

Thanks

**Comment by wongma7** [comment]
Hm, could you show the permissions of `mydata` inside your pod before and after you chown it? `ls -l` or `stat` it? If you are root inside the pod you should have permissions to do anything. Are you using any of the parameters here? https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/usage.md#parameters

**Comment by mmaquevice** [comment]
Thanks for your help.

I do not use any parameters in my storage class.

Inside my pod `mydata` belongs to `nobody nogroup` (UID and GUI 65534), whereas in my server the files belongs to `root`.

It's like there was a `root_squash` option enabled.

Thanks

**Comment by wongma7** [comment]
ftr there's a rootsquash parameter
/area nfs
