### ISSUE TITLE
cross k8s clusters for sharing storage

### ISSUE THREAD

**Issue by wjin** [kubernetes-incubator/external-storage#245]
Current CephFS plugin creates a random 'share name' when provisioning every time. If we could configure pvc parameters (path in a filesystem) in the future, we may use the given name when provisioning.

Therefore we could create the same pvc/pv in different k8s clusters and all of them are related to the same 'path' in a filesystem. 

The benefit is that we may share storage in different k8 clusters, this is useful in k8s cluster federation.

**Comment by wongma7** [comment]
there is now an option to make the shares deterministic, pls open a new issue if you've any questions
