### ISSUE TITLE
Add initial support for openebs provisioner

### ISSUE THREAD

**Issue by satyamz** [kubernetes-incubator/external-storage#277]
[OpenEBS](https://github.com/openebs/openebs) is containerized storage for containers. We want to add openebs provisioner for the kubernetes. We're currently pushing code to https://github.com/openebs/external-storage on`openebs-provisioner-init` branch. Looking forward to your thoughts.

Thanks! 
Satyam

**Comment by humblec** [comment]
@satyamz once its in a better shape and after sanity testing, make a WIP PR in this repo.  You can add me and Matthew as reviewers.

**Comment by satyamz** [comment]
@humblec  I have updated code as per comments were given by you. However, I am neither able to add label WIP nor able to add reviewer.
Thanks.

**Comment by humblec** [comment]
@satyamz nm, I am on it. Thanks

**Comment by satyamz** [comment]
Initial support for OpenEBS Provisioner has been added (PR #315). Therefore, closing this issue.
