### ISSUE TITLE
PVC deletion is not deleting associated PV

### ISSUE THREAD

**Issue by akgunjal** [kubernetes-incubator/external-storage#28]
I am using NFS provisioner for dynamic provisioning. When I delete PVC, the PV status changes to "Failed" and hence the PV deletion does not happen. I see logs as below from controller.

**volume "pvc-d4e8daaf-0592-11e7-9057-4223abc40265" no longer needs deletion, skipping**

 Adding some more info from my debugging of the incubator code at https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L423

I see the PV status is changing to "Failed" upon PVC deletion. Hence the above condition fails which prevents PV deletion.

I have opened a BUG in kubernetes community for PV status issue. But should the incubator allow deletion of PV in case of "Failed" status as well.

https://github.com/kubernetes/kubernetes/issues/43138

**Comment by wongma7** [comment]
Are there any events on the PV that say why it is failed? Can check with "kubectl describe pv"

In 1.4 kubernetes was mistakenly setting pvs to failed and we have a special case for it, maybe there is a regression in 1.5.3

**Comment by akgunjal** [comment]
Pasting describe output

kubectl describe pv pvc-9477aa66-0966-11e7-9bdf-ceb69dea9b3d
Name:		pvc-9477aa66-0966-11e7-9bdf-ceb69dea9b3d
Labels:		CapacityGb=20
		Iops=2
		Username=IBM02SEV1186049_8
		path=IBM02SEV1186049_8data01
		server=fsf-dal1001b-fz.adn.networklayer.com
		volumeId=21273453
StorageClass:	ibmc-file-bronze
Status:		Failed
Claim:		default/claim1-bronze
Reclaim Policy:	Delete
Access Modes:	RWX
Capacity:	20Gi
Message:	no volume plugin matched
Source:
    Type:	NFS (an NFS mount that lasts the lifetime of a pod)
    Server:	fsf-dal1001b-fz.adn.networklayer.com
    Path:	/IBM02SEV1186049_8/data01
    ReadOnly:	false
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  51m		51m		1	{persistentvolume-controller }			Warning		VolumeFailedDelete	no volume plugin matched

**Comment by akgunjal** [comment]
I just below logs in my pod where this provisioner is running.

I0315 10:25:10.635103       1 controller.go:841] scheduleOperation[delete-pvc-85e0f872-0969-11e7-9364-9266a6eaa48f[9dfe7cd8-0969-11e7-9364-9266a6eaa48f]]
I0315 10:25:10.700651       1 controller.go:800] volume "pvc-85e0f872-0969-11e7-9364-9266a6eaa48f" no longer needs deletion, skipping

**Comment by akgunjal** [comment]
Subscribing @npramod

**Comment by wongma7** [comment]
@akgunjal thanks. What is the name of the storage class provisioner? i.e. its `provisioner` field. I think the issue is that it's prefixed with "kubernetes.io" and that causes kubernetes to incorrectly look for an in-tree provisioner.

Technically we're not "allowed" to use kubernetes.io annotations, plugin names, provisioner names, etc. I'll document this visibly somewhere.

**Comment by akgunjal** [comment]
@wongma7 : Yes. our provisioner name is "provisioner: kubernetes.io/ibmc-file"

So is that the cause of our issue? But as I said it works occassionally and fails sometimes so the behavior is not consistent

**Comment by wongma7** [comment]
yep, it seems like a race between how quickly the provisioner deletes the PV while it's still 'Released' v.s. kubernetes finishes searching for an in-tree plugin and sets the PV to 'Failed'

I say in a couple of places to name your provisioner "like" kubernetes.io/aws-ebs and that's misleading, I'll go around the docs and fix this now.

**Comment by akgunjal** [comment]
Thanks @wongma7 
I will fix the provisioner name to not use "kubernetes.io" as prefix.

**Comment by wongma7** [comment]
my edits are done, tx

**Comment by akgunjal** [comment]
@wongma7 : The fix is working now as I could verify.
