### ISSUE TITLE
[iscsci-provisioner] Need updated roles for Openshift 3.6

### ISSUE THREAD

**Issue by woopla** [kubernetes-incubator/external-storage#284]
Hello,

I'm following the [README for the iscsi-targetd provisioner](https://github.com/kubernetes-incubator/external-storage/blob/master/iscsi/targetd/README.md) on an Openshift Origin 3.6.0 install, and I cannot get past the provisioner pod install stage, because all the `system:pv-*` roles have been removed (see this [comment ](https://github.com/openshift/origin/issues/15752#issuecomment-322020633) in the issue I opened with Openshift).

What's the updated way of doing things?

Thanks,

Clément

**Comment by wongma7** [comment]
Please try the new "persistent-volume-provisioner" role. It's still possible it's missing a permission that targetd needs, so if you run into troubles please post the provisoner logs.

**Comment by woopla** [comment]
thanks @wongma7! This seems to be working - I have another unrelated problem (see #288), so it can't be 100% sure.

The README needs an update I guess :)

Cheers,

Clément
