### ISSUE TITLE
Error "failed to create volume: gluster block command failed"

### ISSUE THREAD

**Issue by jhou1** [kubernetes-incubator/external-storage#297]
While I was trying to use gluster block provisioner, the volume wasn't created, the console log of the `glusterblock-provisioner` container was:

```
I0816 06:26:54.493049       1 controller.go:1068] scheduleOperation[provision-default/claim1[721d8868-824b-11e7-bf7e-0050569fb5aa]]
E0816 06:26:54.493102       1 controller.go:1075] Error scheduling operaion "provision-default/claim1[721d8868-824b-11e7-bf7e-0050569fb5aa]": Failed to create operation with name "provision-default/claim1[721d8868-824b-11e7-bf7e-0050569fb5aa]". An operation with that name failed at 2017-08-16 06:26:09.4997438 +0000 UTC. No retries permitted until 2017-08-16 06:27:13.4997438 +0000 UTC (1m4s). Last error: "glusterblock: failed to create volume: gluster block command failed".
``` 

As I was reading https://github.com/gluster/gluster-block, I thought the command should be `gluster-block` instead of `gluster block`?

**Comment by jhou1** [comment]
@humblec PTAL, thanks

**Comment by humblec** [comment]
@jhou1 the issue is different, its a setup issue, we will work on this tomo.

**Comment by humblec** [comment]
@jhou1 iic, this works with proper configuration. Can you please confirm ? accordingly I will close this or keep it open.

**Comment by jhou1** [comment]
This works with proper configuration, I'll close it, thank you.
