### ISSUE TITLE
Kubeconfig argument is into dockerfile with glusterfs provisioner

### ISSUE THREAD

**Issue by theikkila** [kubernetes-incubator/external-storage#300]
GlusterFS block provisioner Dockerfile contains kube-config as default argument effectively preventing it's usage straight away with provided example  deployment file (https://github.com/kubernetes-incubator/external-storage/blob/master/gluster/block/deploy/deployment.yaml).

This configuration panics the pod on start and takes it into crashloop.

I think it should be preferable to make it work without that argument and probably also write about it into readme.

https://github.com/kubernetes-incubator/external-storage/blob/master/gluster/block/Dockerfile#L21
ping @humblec

**Comment by wongma7** [comment]
@humblec way I see it, we can either: remove Dockerfile's hardcoded CMD/args and let the documentation handle it, or modify the deployment manifest to override the CMD/args. Whichever you think is better UX

**Comment by humblec** [comment]
@theikkila @wongma7 yeah, I am planning to remove the CMD from dockerfile for now and will udpate the README. The patch is on the way. Thanks

**Comment by humblec** [comment]
@wongma7 filed https://github.com/kubernetes-incubator/external-storage/pull/305

**Comment by humblec** [comment]
@wongma7 Can you please close this issue ?

**Comment by theikkila** [comment]
Ok, resolved! Thanks everybody
