### ISSUE TITLE
[local-volume] How to create a storage class to hold the disks provide by local-volume-provisioner

### ISSUE THREAD

**Issue by jenningsloy318** [kubernetes-incubator/external-storage#319]
Hi all, 
I am using  local-volume-provisioner via `local-storage-daemonset.yaml`  to provide the local volumes, but how to create storage class to hold them, what 's the value of `provisioner:  ` in storage class spec ?

**Comment by ianchakeres** [comment]
The configmap map defines the local-storage storageclasses, see https://github.com/kubernetes-incubator/external-storage/blob/master/local-volume/bootstrapper/README.md. @msau42 - please correct me if I'm wrong.

In the example below, the following storage classes exist: local-fast, local-slow, and local-storage.

```
kind: ConfigMap
metadata:
  name: local-volume-config
  namespace: kube-system
data:
  "local-fast": |
    {
      "hostDir": "/mnt/ssds",
      "mountDir": "/local-ssds"
    }
  "local-slow": |
    {
      "hostDir": "/mnt/hdds",
      "mountDir": "/local-hdds"
    }
  "local-storage": |
    {
      "hostDir": "/mnt/disks"
    }
```

**Comment by msau42** [comment]
HI @jenningsloy318, you don't actually need to create a StorageClass object.  Just set the names in the static provisioner configmap, and your PVCs to match.

**Comment by jenningsloy318** [comment]
@msau42 

But I use local-volume-provisioner  to create a daemonset to provide the local storage. how to achieve this.

**Comment by msau42** [comment]
The local storage provisioner does not work the same way as other provisioners.  It is a static provisioner, not a dynamic one.

You need to precreate the volumes on each node ahead of time.  Then launch the provisioner daemonset with the configmap that tells the provisioner where all your local disks are mounted.  The daemonset will automatically create PVs for the volumes it finds under those directories, and also clean them up and recreate the PV once the PVC is deleted.

Please see the detailed steps outlined [here](https://github.com/kubernetes-incubator/external-storage/blob/master/local-volume)

**Comment by msau42** [comment]
@jenningsloy318 were you able to figure out how to use the local storage static provisioner?

**Comment by msau42** [comment]
Please reopen if you still see an issue.
