### ISSUE TITLE
EFS provisioner does not work when in a different Availability Zone

### ISSUE THREAD

**Issue by bonovoxly** [kubernetes-incubator/external-storage#320]
When either the provisioner or a pod requesting an EFS PVC is NOT in the same AZ as the EFS mount point, the DNS name will not resolve and will result in output similar to the following:

```
Output: mount.nfs: Failed to resolve server fs-aaaaaaaa.efs.us-east-1.amazonaws.com: No address associated with hostname
```

The DNS name for a mount point is `az.fs-aaaaaaaa.efs.us-east-1.amazonaws.com`, when attempting to reference it from another AZ (link http://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html) .

What is the recommended configuration when Kubernetes nodes are distributed across availability zones? Should pods that require EFS be forced in the same AZ as the EFS mount point (nodeselector)?

Would it be possible to support adding the AZ to the mount point DNS name?

**Comment by wongma7** [comment]
It should work, Amazon claims that instances across zones can access it as long as they're in the same region and VPC. Is there a "mount target" in every AZ http://docs.aws.amazon.com/efs/latest/ug/accessing-fs.html?

**Comment by bonovoxly** [comment]
Ugh.  apologies.  Closing the ticket.

@wongma7 thank you very much. I forgot to add mount targets to each subnet in the different AZ. Doh.
