### ISSUE TITLE
gluster-block provisioner creates CHAP secret in any namespace

### ISSUE THREAD

**Issue by rootfs** [kubernetes-incubator/external-storage#321]
Since iSCSI PV references CHAP secret in the Pod's (or Claim's) namespace. gluster-block thus tries to create secret in [any namespace](https://github.com/kubernetes-incubator/external-storage/blob/master/gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go#L322). This will bring risk if gluster-block provisioner is compromised and overrides secrets used by kubernetes.

@liggitt

**Comment by liggitt** [comment]
more importantly, it exposes and gives control over the CHAP secret to the PVC-creating user, when the details of that should be hidden from them

**Comment by humblec** [comment]
Thanks @rootfs , I will adopt the changes in the provisioner once the iscsi pv spec is in . Also reviewing your refactor ISCSI PV PR.
