### ISSUE TITLE
k8s.io/client-go/pkg/api/v1 doesn't exist

### ISSUE THREAD

**Issue by mattdornfeld** [kubernetes-incubator/external-storage#324]
The hostpath [example](https://github.com/kubernetes-incubator/external-storage/tree/master/docs) for creating an external provisioner references a Goland package k8s.io/client-go/pkg/api/v1. This package doesn't seem to exist

```
go get k8s.io/client-go/pkg/api/v1
```

Returns an error saying it can't find the package. I think the package was possibly moved? Maybe the example could also be updated?

**Comment by wongma7** [comment]
Yes, sorry the example has not been updated for some months and in that time kubernetes has split its code across many repos, like https://github.com/kubernetes/api. I will try to update it tomorrow.

**Comment by mattdornfeld** [comment]
@wongma7 Thanks! I tried tracking down all of the packages myself but I keep getting errors. I appreciate it.

**Comment by wongma7** [comment]
Hm I'm debating postponing updating it some more because kubernetes 1.8 is around the corner and I can then update the whole repo in one go.

If you use glide https://github.com/kubernetes-incubator/external-storage/blob/master/docs/demo/hostpath-provisioner/Makefile#L23 (pretty much necessary when working with kube libraries) then it should find the old package and compile fine, is that okay?

**Comment by cnighojkar** [comment]
any update on this?

**Comment by wongma7** [comment]
You must use glide as documented for it to work. I will be updating
everything this or next week if you’d prefer to wait for that

**Comment by cnighojkar** [comment]
@wongma7  Thanks for the Update , actually we use godep.
Also i am trying to unmarshal the pod json to an object so that i can pass the object(*v1.Pod) to the function  **clientset.CoreV1().Pods("default").Create(*v1.Pod)**
is there any other way i can achieve this?

**Comment by wongma7** [comment]
try ioutil.ReadFile() and json.Unmarshal

**Comment by cnighojkar** [comment]
Thanks , @wongma7  , it worked.
I realized later that this way i am recreating kubectl functionality . Somewhere in the kubectl code i can call direct methods to create Pod , ReplicationController , Services etc.
I am browsing the kubectl library but could not find the correct method to be called.

Any thing you can direct me towards?

**Comment by wongma7** [comment]
not sure, closing issue for now, tutorial is quite outdated but should always work because glide
