### ISSUE TITLE
External Controller should support `Retain` volume reclaim policy

### ISSUE THREAD

**Issue by xingzhou** [kubernetes-incubator/external-storage#326]
As patch https://github.com/kubernetes/kubernetes/pull/47987 is merged, I think we can support `Retain` policy in external-storage.

https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L785

I'm working on a patch on this.

/cc @wongma7

**Comment by xingzhou** [comment]
@wongma7, the kubernetes/api repo does not contain the latest for `ReclaimPolicy` field? is that possible to update that repo?

**Comment by wongma7** [comment]
Seems the sync is broken again https://github.com/kubernetes/test-infra/issues/4080. IMO we just have to wait, I'll keep an eye on it. The alternative is patching k8s.io/api ourselves which is a lot of work

**Comment by wongma7** [comment]
@xingzhou kubernetes/api has been updated https://github.com/kubernetes/api/blob/f30e293246921de7f4ee46bb65b8762b2f890fc4/storage/v1/types.go#L51

**Comment by xingzhou** [comment]
yeap, thx @wongma7, I'll carry on the patch

**Comment by boomshadow** [comment]
Greetings! First off, I love everything you all are doing. Thanks so much. I see that #304 and #331 are merged in. Any word on getting 'retain' added in? I'd love to add that in for my EFS provisioning :)

**Comment by d-mcd** [comment]
Any movement on this one? Just began using EFS provisioning a few days ago and today realized there did not appear to be a way to retain; after pvc deleteition. Thx Guys!

**Comment by xingzhou** [comment]
@d-mcd and @boomshadow, just saw your comments, sorry for the late response. Please take a look at my latest comments in the PR.

The main code for supporting retain policy has been merged in another PR, and this feature only support K8s higher than v1.8. Would you please take a trial on this feature and let me know if anything not work correctly? thx

**Comment by nrobert13** [comment]
not sure if we should discuss this further here or in the PR, so will paste a link to my comment in the PR , https://github.com/kubernetes-incubator/external-storage/pull/392#issuecomment-370848257

**Comment by wongma7** [comment]
done. (late...but done)
