### ISSUE TITLE
efs Provisioner and GID

### ISSUE THREAD

**Issue by snoby** [kubernetes-incubator/external-storage#328]
Using the documentation provided I have a working EFS provisioner.  When I go to use a pod that mounts the claim that has been created with the EFS provisioner I'm told that permission is denied.
( the pod that I'm running ins Consul)
```bash
Error starting agent: Failed to configure keyring: mkdir /var/lib/consul/serf: permission denied
```
When I mount the same claim in a pod that is running as root I can add and read files from the share, however as soon as I exec into this pod I'm greeted with the message:
`groups: cannot find name for group ID 2004`

so the volume ( just like in the instructions) has been provisioned with a GID of 2004.  However it seems the supplemental group doesn't work with all containers. The consul container is an alpine based image, perhaps they don't support the supplemental group ID...

Reading the documentation in the nfs provisioner 
 https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/usage.md 
is there a way with the efs provisioner to pass in `gid: none` ?  If so how would you do it?
Thanks,

**Comment by wongma7** [comment]
Do you know where to find the dockerfile? What is the image tag?

The limitation of kubernetes per-container GID assignment is that the GID can only be "applied to the first process run in each Container" https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#access-control so that's why it doesn't work for every container image, because some of them have weird entrypoints where things fork off or they voluntarily give up `root` or something.

I will have to implement a way to opt-out of GID allocation to deal with this, I probably won't call it `gid: none` but it will be along those lines yes.

The `groups: cannot find name for group ID 2004` message is probably okay.

**Comment by snoby** [comment]
Ah interesting, that is exactly what is happening with the processes... so I'm using this consul guide
(kube-vault-consul)[https://sqbu-github.cisco.com/tropo-operations/kube-vault-consul]
and the deployment is using this the official consul container: consul:0.7.2 with the following arguments:
```
         args:
            - "agent"
            - "-ui"
            - "-node=consul-1"
            - "-data-dir=/var/lib/consul"
            - "-server"
            - "-bootstrap-expect=3"
            - "-advertise=$(CONSUL_1_SERVICE_HOST)"
            - "-rejoin"
            - "-client=0.0.0.0"
            - "-config-dir=/etc/consul"

```
and more importantly here is the image on dockerhub
https://hub.docker.com/_/consul/
and it clearly says:
>Consul always runs under dumb-init, which handles reaping zombie processes and forwards signals on to all processes running in the container. We also use gosu to run Consul as a non-root "consul" user for better security. 

So the GID assignment isn't getting past dumb-init.

**Comment by wongma7** [comment]
As of `v0.1.2`/`latest` you may set `gidAllocate: "false"` in your storageClass parameters to disable GID allocation and give directories 777 permissions instead of the too-restrictive 771.

Good troubleshooting, let me know if this is a suitable workaround.

**Comment by glennschmidt** [comment]
It would be good if the storage GID was also exposed to the container as an environment variable. Then people building their own containers could choose to add other users to the group at runtime (eg. using an init container or an entrypoint script)

**Comment by wongma7** [comment]
imo all configuration should be via storage class but I'm not sure, feel free to open an rfe issue
/area aws/efs
