### ISSUE TITLE
Need a consistent dynamic provisioner versioning strategy

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#369]
| provisioner  | current version |
| ------------- | ------------- |
| aws/efs  | v0.1.x |
| ceph/cephfs  | v0.1.x |
| ceph/rbd  | v0.1.x |
| gluster/block | v1.0.x |
| gluster/glusterfs | v0.1.x |
| iscsi/targetd | v0.0.x |
| nfs-client | v2.0.x |
| nfs | v1.0.x |
| openebs | n/a |

(local-volume/snapshot are not exclusively external dynamic provisioners and so not being discussed here)

The current way to find out what versions of a provisioner are compatible with what versions of Kubernetes is to determine the version of the library the provisioner uses. E.g. aws/efs v0.1.2 follows lib v3.0.0-beta.2, whose release notes say it is "Compatible with kubernetes v1.5.x, v1.6.x, v1.7.x".

**Issues:**

Forwards-compatibility with kube:
Kube 1.8 is coming soon, and because it includes storageclass.reclaimpolicy and storageclass.mountoptions, the current provisioners will *not* be compatible with it as they will not be able to respect those fields. The versioning needs to somehow express that version X of provisioner Y is only compatible with versions of kube up to and including version 1.Z.

Backwards-compatibility with kube:
I think breaking backwards compatibility is preventable and highly unlikely to happen.

Backwards-compatibility with itself:
Provisioners may remove parameters or change behavior somehow, so the versioning needs to express that updating from version A of provisioner Y to version B of provisioner Y is a breaking change e.g. it requires editing storageclasses.

**Idea**

Adopt the conventions:
* Append the latest kubernetes version for which a provisioner is compatible to its version/tag.
v1.0.0-kube1.8

* Continue to "release" provisioners by simply tagging them. Continue to maintain individual CHANGELOG.md files (and don't put release notes in the GItHub releases page)

* Continue to allow provisioners to manage their own versioning. For the ones that I am primarily responsible for, I will try to put them all at v1.0.0 in the near future. Should they break compatibility with themselves, they'll increment the major version. I'm debating just using 2 digits (vX.Y) and dropping semver though, because it's probably unnecessary to have a minor version.

**Comment by wongma7** [comment]
@childsb

**Comment by wongma7** [comment]
btw @jsafrane you had some thoughts somewhere I think the block storage proposal (it is too huge, I can't find your comment :( ) about how we should deal with kubernetes adding things like volumeType and external provisioners not being able to notice them, that is maybe relevant, so wdyt? IT's the same situation with storagecalss.reclaimpolicy and storageclass.mountoptions

**Comment by jsafrane** [comment]
I probably need to submit a real proposal upstream how we're going to add new features to external provisioning like mount options.

**Comment by wongma7** [comment]
Ok sgtm, no rush :)))

**Comment by jsafrane** [comment]
volumeType is in class.parameters so provisioners can start supporting it as they want. This leaves us only with mountOptions. There were no other PV/PVC/StorageClass changes, right?

**Comment by wongma7** [comment]
StorageClass reclaimpolicy the library needs to be updated and every
provisioner a new release

**Comment by humblec** [comment]
@wongme @jsafrane  other than the individual tagging of provisioners, what about having a release for this repo mapped to kube release from 1.8 onwards?

**Comment by wongma7** [comment]
I will still version the library using github releases. like right now we are at 2.0.0 and I will release 3.0.0 say next week with 1.8 updates

I think we will need to make an announcement of some sort on sig-storage about this

**Comment by pospispa** [comment]
@wongma7 IMHO, both minimum and maximum supported K8s versions may be included in the tag, e.g. `v1.0.0-kube1.5-kube1.7`.

What about verification? Should an external provisioner be verified only against the latest K8s version or against all K8s versions it supports?

**Comment by wongma7** [comment]
verification is difficult. Currently the nfs provisioner, and so our library, is going through e2e tests both here (1.5, 1.6, and soon 1.8) and on kubernetes (all versions we run the dynamic provisioning tests), so any provisioners using our library are in a sense "verified" to interface correctly with kubernetes. This doesn't protect them from their own implementation bugs, which are the responsibility of the author via unit tests, etc.

I don't think we need minimum because it should *always* be 1.5. We have already said external provisioner is beta, breaking backwards compatibility is pretty much impossible.

Also I guess we could say "k8s" instead of "kube."

And regarding library versioning, I'm considering making it align exactly with kube, i.e. this next version will be both v3.0.0 and v1.8.0, and from then on we will be in lockstep with kube versioning so that kube 1.9 maps to library 1.9, etc. etc.

**Comment by pospispa** [comment]
> Also I guess we could say "k8s" instead of "kube."

I agree.

> And regarding library versioning, I'm considering making it align exactly with kube, i.e. this next version will be both v3.0.0 and v1.8.0, and from then on we will be in lockstep with kube versioning so that kube 1.9 maps to library 1.9, etc. etc.

This should make it obvious. I'm for it.
