### ISSUE TITLE
Troubles with new PVC.spec.storageClassName attribute

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-incubator/external-storage#37]
I'm testing Kubernetes 1.6 with quay.io/kubernetes_incubator/nfs-provisioner:v1.0.3 and the provisoner does not work when I use ask for a StorageClass in my PVC using `PVC.spec.storageClassName`.

Ok, it's a new attribute, the provisioner does not know about it. On the other hand, I would expect that my PVC gets provisioned when I fill both beta annotation and `storageClassName` on the PVC. Instead the provisioned pod logs this;

```
I0317 12:51:25.840945       1 controller.go:841] scheduleOperation[lock-provision-e2e-tests-volume-provisioning-h2s0q/pvc-403m7[fa73f5db-0b0f-11e7-865f-42010af00002]]
E0317 12:51:29.408723       1 leaderelection.go:274] Failed to update lock: PersistentVolumeClaim "pvc-403m7" is invalid: spec: Forbidden: field is immutable after creation
E0317 12:51:33.052046       1 leaderelection.go:274] Failed to update lock: PersistentVolumeClaim "pvc-403m7" is invalid: spec: Forbidden: field is immutable after creation
E0317 12:51:37.407035       1 leaderelection.go:274] Failed to update lock: PersistentVolumeClaim "pvc-403m7" is invalid: spec: Forbidden: field is immutable after creation
```

It seems the provisioner reads the PVC (with `storageClassName` attribute) and tries to write it back **without** the attribute and it gets rejected.

I am not sure about client-go release schedule, an update would probably fix it (and use `v1.GetPersistentVolumeClaimClass` to get the class both from beta annotation and from the attribute).

My PVC:
```
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: myclass-external
      volume.beta.kubernetes.io/storage-provisioner: example.com/nfs
    creationTimestamp: 2017-03-17T12:48:11Z
    generateName: pvc-
    name: pvc-403m7
    namespace: e2e-tests-volume-provisioning-h2s0q
    resourceVersion: "11148"
    selfLink: /api/v1/namespaces/e2e-tests-volume-provisioning-h2s0q/persistentvolumeclaims/pvc-403m7
    uid: fa73f5db-0b0f-11e7-865f-42010af00002
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1500Mi
    storageClassName: myclass-external
  status:
    phase: Pending
```

**Comment by wongma7** [comment]
Thanks for detailed investigation 👍

client-go update issue: https://github.com/kubernetes/client-go/issues/147

In short it looks to me that it's blocked by the repo sprawl hell, I'll work on this as soon as they update
