### ISSUE TITLE
Add optional method to rename the pvs to custom name

### ISSUE THREAD

**Issue by satyamz** [kubernetes-incubator/external-storage#371]
Need the optional method to rename pvc to some useful/meaningful name.  More discussion on this https://github.com/kubernetes-incubator/external-storage/pull/357

**Comment by djdevin** [comment]
This would be great. Currently we name it based on the OpenShift project name and project names will never be re-used. Makes it easier for backups and auditing as well, also disaster recovery.

For a more public cloud though the current approach is fine, but it would be nice if it was configurable to omit any sort of randomly generated folder name.

**Comment by satyamz** [comment]
Yes! Waiting for @wongma7 's reply for next steps.

**Comment by wongma7** [comment]
The next step is to add it. I promised to get it started a while ago but dropped the ball.

End of week after this at the latest is when it will be done and the next version of the library released.

**Comment by wongma7** [comment]
that last comment did not age well

https://github.com/kubernetes-incubator/external-storage/pull/612 seems to be what we want, needs review

/area lib
