### ISSUE TITLE
Local provisioner can delete a volume while it's still in use

### ISSUE THREAD

**Issue by msau42** [kubernetes-incubator/external-storage#398]
If user deletes PVC, and PV becomes released, the provisioner will start the deletion process, regardless of if a pod is still using it.

Ideally, I would like to solve this by preventing PVC from being deleted in the first place because I don't think checking mounts is reliable.  You can check that no mounts exist, and start the deletion, but a Pod could mount in between that time.

/area local-volume

**Comment by ianchakeres** [comment]
This issue is related to https://github.com/kubernetes/kubernetes/issues/45143.

**Comment by msau42** [comment]
This is solved in 1.10 with PVC and PV finalizers

/close
