### ISSUE TITLE
iscsi: use glog instead of Sirupsen/logrus

### ISSUE THREAD

**Issue by nak3** [kubernetes-incubator/external-storage#399]
Since `scsi/target` uses `Sirupsen/logrus` instead of `glog` for its logging library, users cannot adjust the log level of glog. This means that it is not possible to see info level log under `external-storage/lib/`. (I'm sorry if there is a secret trick to adjust.)

~~~
# ./iscsi-controller -h
...
Flags:
      --log-level string   log level (default "info")
~~~

c.f rdb-provisioner
~~~
# ./rbd-provisioner -h
Usage of ./rbd-provisioner:
  ...
  -v value
    	log level for V logs
~~~

When debuging iscsi provisioner or when understanding the behavior of provisioner, I would like to see verbose level log. Especially `lib/controller/` has many log of glog.Info.

Is there any reason why iscsi/targeted maintainers want to use logrus instead of glog?

**Comment by raffaelespazzoli** [comment]
//assign
please assign this to me.

**Comment by raffaelespazzoli** [comment]
hi @nak3 
I have been looking at this issue. glog is initialized with go flags, while I'm using viper/cobra for my command line flag parsing. I am not familiar with these libraries and I don't see an easy way to read a flag as a viper flag and make it available to glog as a go flag. Do you know how this can be done?

**Comment by nak3** [comment]
I am thinking that _"an easy way to read a flag as a viper flag and make it available to glog as a go flag"_ is not possible.

However, if we take a similar approach, something like _"to make go flag available for the command line, and then add viper flag to make it also available"_ is possible with `pflag.CommandLine.AddGoFlagSet(flag.CommandLine)`. I wrote an example so how about this approach?

https://gist.github.com/nak3/78a32817a8a3950ae48f239a44cd3663
