### ISSUE TITLE
glusterblock-provisioner: volume size incorrect in gluster-block mode

### ISSUE THREAD

**Issue by dtschan** [kubernetes-incubator/external-storage#404]
The `glusterblock-provisioner` seems to calculate volume size incorrectly in `gluster-block` mode. I created a volume using the [provided pvc](/kubernetes-incubator/external-storage/blob/e611f9034e57d64859d09810186d1973263af246/gluster/block/examples/glusterblock-mode/claim1.yaml) and `gluster-block` 0.2.1. The resulting volume has a size of 2 bytes instead of 1 GiB (1024^3 bytes).
The cause seems to be in [glusterblock-provisioner#L185](/kubernetes-incubator/external-storage/blob/e611f9034e57d64859d09810186d1973263af246/gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go#L185) where the volume size is rounded to the next GB (1000^3 bytes), presumably because Heketi expects volume size in Gigabytes. The result is then passed to the `gluster-block` binary on [glusterblock-provisioner.go#L362](https://github.com/kubernetes-incubator/external-storage/blob/e611f9034e57d64859d09810186d1973263af246/gluster/block/cmd/glusterblock-provisioner/glusterblock-provisioner.go#L362). However `gluster-block` expects the volume size in bytes or with an appropriate unit like `GB`. Please note that `gluster-block` currently treats `GB` as 1024^3 bytes.

**Comment by rootfs** [comment]
@humblec

**Comment by humblec** [comment]
@dtschan you are correct on your analysis, however in heketi mode this is not an issue because we append `G` when we send the command to `gluster-block` , however I missed to append `G` in `gluster-block` mode . Working on a patch

**Comment by humblec** [comment]
@dtschan This is fixed with above mentioned PR, I am closing this issue and please feel free to revert if its not fixed. Thanks for filing the issue and happy hacking.
