### ISSUE TITLE
[local-volume] PV capacity is hard to read

### ISSUE THREAD

**Issue by msau42** [kubernetes-incubator/external-storage#405]
Can we round the capacity to the closest Mi or Gi?

```
NAME                CAPACITY      ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM     STORAGECLASS    REASON    AGE
local-pv-12898ae3   366318976Ki   RWO            Delete           Available             local-storage             3m
```

**Comment by ianchakeres** [comment]
I'm planning to round down the capacity number put into the local volume's PV.

For volumes over 10Gi, I will round down to the nearest 1Gi. 
For volumes smaller than 10Gi and larger than 10Mi, I will round down to the nearest 1Mi.
For volumes smaller than 10Mi, I will provide actual capacity. These volumes capacity will be displayed in displayed Ki.
