### ISSUE TITLE
CephFS root path

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-incubator/external-storage#406]
I would like to share one cephfs with multiple k8s instances. Currently, it places all pv's under /volumes/kubernetes/xxx

Could we make '/volumes/kubernetes/' specified on the cephfs-provisioner cli to be overridable so we can make directories non overlapping?

This is kind of the opposite of issue #245

**Comment by rootfs** [comment]
@kfox1111 do you have any use case for overriding the default top level directory?

**Comment by kfox1111** [comment]
two k8s clusters sharing one cephfs?
