### ISSUE TITLE
Capacity is not limited for PVC

### ISSUE THREAD

**Issue by adawolfs** [kubernetes-incubator/external-storage#407]
Hello
I'm actually testing your implementation for nfs-provisioner but I have issues exceeding limits for PV, causing that just one mount can consume all the storage

Can you let me know if it's currently supported and if it's help me to make it work?

**Comment by wongma7** [comment]
No, it's not supported, capacities and quotas must be enforced at the underlying filesystem level. 

There is an extremely limited option to integrate with xfs project-level quotas, see the section on quotas here https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/deployment.md#outside-of-kubernetes---container

**Comment by adawolfs** [comment]
Thanks @wongma7 I'll take a look!
