### ISSUE TITLE
[local-volume] PVs created for local volume should inherit the node's region, zone and hostname information

### ISSUE THREAD

**Issue by dhirajh** [kubernetes-incubator/external-storage#409]
A Local PV has some of the same labelling needs as the node it resides on. In particular, having these labels inherited from the node would be very useful to the local PVs:

failure-domain.beta.kubernetes.io/zone
failure-domain.beta.kubernetes.io/region
kubernetes.io/hostname

**Comment by mikegrass** [comment]
Can the set of labels to propagate from the node to the local PVs be configurable? Different environments may be using their own labeling strategy on nodes for identifying failure domains.

**Comment by msau42** [comment]
Sounds good to me.  Configurable is also better.

/cc @msau42

**Comment by dhirajh** [comment]
Configurable would be a nice approach here. It would allow the default behavior to be the same as what we have today

**Comment by msau42** [comment]
Hey @dhirajh, what is the use case for putting selectors on the PVC?  I'm thinking instead that you would put selectors on your StatefulSet, and that would restrict the set of nodes (and therefore PVs) that we can bind the PVC to.

**Comment by dhirajh** [comment]
@msau42 can you clarify this approach bit? I thought a pvc would bind to suitable pv first based on the constraints expressed in the pvc. In which case even if there are selectors on the stateful set it wouldn’t influence the pvc to pv binding. I thought this was a limitation in the current local volume implementation.

**Comment by msau42** [comment]
Yes, but the scheduler work I'm doing in 1.9 is going to flip that.  We will evaluate Pod and PVC constraints at the same time.  So once this change is in, then I think any workload placement constraints should be driven from the Pod

**Comment by dhirajh** [comment]
@msau42 right, the use case for selectors is only for the interim between now and whenever the user community feels comfortable upgrading to 1.9. But setting that aside, for the long term, I think the ability to inherit labels from the node is valuable for management of local volumes. It will make the task of querying available storage in a given rack or zone or region quite easy with the right labels from the cli.

**Comment by msau42** [comment]
Ok yes, querying based on labels is useful.  Thanks!

**Comment by dhirajh** [comment]
Fixed and merged in #414
