### ISSUE TITLE
support for new api objects in external-storage

### ISSUE THREAD

**Issue by sbezverk** [kubernetes-incubator/external-storage#418]
Recently new objects were added to api, example SecretReference or RBDPersistentVolumeSource etc.. These objects are needed for RBD and CephFS provisioners.  When I bump up the apimachinery version to make these new objects available, the compile process fails with large number of errors.  I would appreciate any guidance here.

**Comment by rootfs** [comment]
@wongma7

**Comment by wongma7** [comment]
Let’s merge https://github.com/kubernetes-incubator/external-storage/pull/392 first, it may make things easier for you

**Comment by wongma7** [comment]
I’m now continuing work in https://github.com/kubernetes-incubator/external-storage/pull/419

K8s repos have tags now so it will be much easier to avoid the “bump and all hell breaks loose” situation by ensuring all the repos have the same tag,
