### ISSUE TITLE
[openebs] Changing maya-apiserver namespace crashes provisionner

### ISSUE THREAD

**Issue by mafzst** [kubernetes-incubator/external-storage#424]
If we change the namespace of `maya-api-server-service` service in the deployment file, the provisionner pod won't start.

Here the log from the pod :
```
maya_api.go:61] Error getting maya-api-server IP Address: services "maya-apiserver-service" not found
```

I think the namespace name is hardcoded in [`maya_api:59`](https://github.com/kubernetes-incubator/external-storage/blob/master/openebs/pkg/v1/maya_api.go#L59). 

Should it be defined in an environment variable?

**Comment by satyamz** [comment]
Hi @mafzst, 
I have fixed the problem where `openebs-provisioner` will go into `Error` state in the https://github.com/openebs/openebs/issues/245 , I'll soon send PR here. 
I'll also fix different `namespace` issue too. Thanks, for the suggestion. I will reference this issue in the PR.

**Comment by mafzst** [comment]
Any news @satyamz?

**Comment by satyamz** [comment]
Yes! Error handling is managed in the PR #451  along with some more refactoring.

**Comment by mafzst** [comment]
Yes but what about changing Maya api server namespace?

**Comment by satyamz** [comment]
Hi @mafzst , PR #456  will allow openebs-provisioner to read namespace as a env variable. If env variable is not set then it'll take `default` namespace.

**Comment by mafzst** [comment]
@satyamz Perfect :+1:
