### ISSUE TITLE
Clean up cephfs provider Docker image

### ISSUE THREAD

**Issue by mcronce** [kubernetes-incubator/external-storage#441]
While exploring the cephfs storage provider for personal use, I noticed a couple things:

- The Dockerfile doesn't run a `yum clean all`, which (from testing) inflates the uncompressed image size by ~103MB
- The default `CMD` is set to `chmod o+x /usr/local/bin/cephfs_provisioner` - the Deployment manifest overrides the command, but I noted that `cephfs-provisioner.go` relies on being able to exec `/usr/local/bin/cephfs_provisioner`, so it seems most likely that this is a mistake.  Do note that that file is provided from inside this repo, and does have 755 permissions already, so everything should already work regardless.

I have changes in master on https://github.com/mcronce/external-storage that correct both of these things.  If the proposed changes are accepted I will submit a PR.

**Comment by wongma7** [comment]
Sounds good to me, please submit a PR 👍 , it's best we follow convention.

**Comment by mcronce** [comment]
Done - thanks!
