### ISSUE TITLE
Snapshot requires GCE deployment example

### ISSUE THREAD

**Issue by dippynark** [kubernetes-incubator/external-storage#444]
The examples in `/snapshot/deploy` only cover AWS and HostPath. An example is also needed for GCE.

**Comment by tsmetana** [comment]
OK. There are some issues reported about the current examples. I will have to re-test with the newer version of kubernetes. I'll try to add GCE on the list too.

**Comment by tsmetana** [comment]
I think we forgot to close this one -- the GCE deployment has been added quite some time ago...

**Comment by dippynark** [comment]
@tsmetana thanks, sorry for my lack of replies on this one
