### ISSUE TITLE
NFS Provisioner - "Invalid Argument" errors with certain write patterns

### ISSUE THREAD

**Issue by abrenneke** [kubernetes-incubator/external-storage#447]
A little related to #223.

Kubenetes version: 1.8.1
NFS Provisioner version:  v1.0.8

Basically, I cannot use the [kube-registry](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry) with the NFS Provisioner. NFS 4.2, 4.1, 4.0, and 3.0 all error when pushing images to the registry. The exact error in the kube-registry logs:

```
err.code=unknown err.detail="filesystem: readdirent: invalid argument" err.message="unknown error" go.version=go1.7.6
```

`readdirent: invalid argument` is the only info I have to go on.

Reproduction:

- Set up the NFS provisioner, set up the kubernetes image registry backed by a dynamic persistent volume that the provisioner sets up.
- Push an image to your registry (it's through the nginx ingress for us if that matters)

I had other "Invalid Argument" errors, but switching to NFS 3 fixed them. This one still remains. Something about how the registry writes or reads files I guess.

**Comment by Paxa** [comment]
Having same problem, how did you switch to NFS 3?

**Comment by SneakyMax** [comment]
@Paxa by editing the `StorageClass` like so:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: etc
parameters:
  mountOptions: vers=3
provisioner: etc
```

**Comment by wongma7** [comment]
See https://github.com/kubernetes-incubator/external-storage/issues/762#issuecomment-397717051 for my comment on these hard-to-debug problems

**Comment by Queuecumber** [comment]
It might be a good idea to add this to the official storage class yaml (https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/deploy/kubernetes/class.yaml). None of my pods were able to write until I added `vers=3` to the mount options

**Comment by LoicMahieu** [comment]
Maybe related to https://serverfault.com/a/724463
