### ISSUE TITLE
standalone-cinder: should not create secret for each iSCSI pvc

### ISSUE THREAD

**Issue by wenjun93** [kubernetes-incubator/external-storage#448]
As in current code, will create secret for each iSCSI pvc with connection data, however, the secret content is same for all pvc in most cases, so I think we may create only one secret for iSCSI volumetype pvc. I think we can get the connection data from cinder and compare with existing secrets, and use existing secret if they are same. Thought?@aglitke thanks.

**Comment by wenjun93** [comment]
Also, I'd like to add function of creating pv/pvc with existing cinder volume, instead of creating new cinder volume, for in some cases it's needed like provision pv with snapshot cinder volume. We can add annotation in pvc like "pv.kubernetes.io/provision-volume: false"

**Comment by aglitke** [comment]
Sure.  I think reuse of an existing secret is a good idea.  In that case we need to be careful about reference counting so that we remove a secret only after its last associated iscsi pv is removed.

**Comment by aglitke** [comment]
The volumeID annotation is a fantastic idea!  Actually, I have it on my list to write a proposal for several related annotations to enable provisioning via clone and/or snapshot.  In those cases, the provisioner could clone an underlying volume to a new volume and use the created clone to satisfy the request.  What do you think?

**Comment by wenjun93** [comment]
@aglitke
For the reusing of existing secret, I did some change in my test environment and tested it, PR link https://github.com/kubernetes-incubator/external-storage/pull/452. I change some interfaces in the code somehow, not sure if it's accepted : )
 For the volumeID annotation in pvc, it would be great to add volume clone/snapshot function into this, I think it may be like [external-storage/snapshot](https://github.com/kubernetes-incubator/external-storage/tree/master/snapshot) right? And for my proposal, I mean in our use case, we have an already existing snapshot, it's a cinder volume, in order to use standalone-cinder, it's necessary to create pv with this existing volumeID, I think this is also a common usage in some cases. The PR link https://github.com/kubernetes-incubator/external-storage/pull/453.
Would you please kindly review these two PRs or assign someone else, I think it still needs improvement, thanks for your time.

**Comment by wenjun93** [comment]
Also, for the first question, after some testing, I think maybe it's not necessary to teardown secret each time, because handling secret reference may have some problems when standalone-cinder crashes or restarts. We may let standalone-cinder create an secret, and do not teardown when delete pvc, and newly created pvc will reuse the existing secret if the secret data is the same, otherwise it will create a new secret, what's your opinion?

**Comment by aglitke** [comment]
On Mon, Nov 13, 2017 at 6:38 AM, Gao, Wenjun <notifications@github.com>
wrote:

> Also, for the first question, after some testing, I think maybe it's not
> necessary to teardown secret each time, because handling secret reference
> may have some problems when standalone-cinder crashes or restarts. We may
> let standalone-cinder create an secret, and do not teardown when delete
> pvc, and newly created pvc will reuse the existing secret if the secret
> data is the same, otherwise it will create a new secret, what's your
> opinion?
>

My main concern for handling of api objects such as secrets is that it
should try to be maintenance free as possible to the cluster admin.  I
would rather incur a bit of overhead by adding/removing a secret each time
if it would prevent us from leaking secret objects over time.  You have
said that we expect the same credentials to be used each time.  Could you
provide some documentation or code reference that proves this?  Are the
credentials constant per initatorName?  Are they keyed to the cinder volume
type?  Are they shared globally for all volumes serviced by a single volume
driver?

-- 
Adam Litke

**Comment by wenjun93** [comment]
@aglitke Thanks, for different backend volume types, the ways of credential are different, like ceph rbd, we create secret contains keyring manually, and for iSCSI volume types, it depends on the volume provider. I've confirmed, it depends on volume backend, for I'm using solidfire as volume provider, and for each project it returns same authentication, while for other volume provider, it may be different, the authentication is not supposed to be same either for each volume or project. You are correct.: )
My concern is that if we create a number of iscsi pvc, then a large number of secret will be created, it's not elegant way I think, but I've no other better solutions currently. How do you think?

Another thing I want to mention is that the authentication for a iscsi volume may vary overtime, (though rarely happened), we cannot guarantee the secret data when provision the volume is always correct, so it's necessary to acquire the username and password from cinder when attach/detach, `os-brick` and `nova` both use this way. Just mention this, for k8s native iscsi volume plugin is using static secret data when attach/detach.

**Comment by jianglingxia** [comment]
you mean the iscsi volume type need create a secret?now my problem is that the volume not attached the k8s minion,because i do not create a secret?

i create the standalone provisioner deployment and then i create the storageclass pvc then :
standalone-cinder-provisioner-7c4649c886-drhst   1/1     Running   0          8s

pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3   1Gi        RWO            Delete           Bound         kube-system/keystone-sc-pvc-2   standard                29m

 iscsi:
    initiatorName: iqn.2018-01.io.k8s:a13fc3d1cc22
    iqn: iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54
    iscsiInterface: default
    lun: 1
    targetPortal: 19.19.19.252:3260
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound


and the volume is in-use:
| b4889dad-e30f-4dc7-8a18-4780c6e084dc | d8f6da95565d443e92a80537c554f83b |   in-use  | cinder-dynamic-pvc-d0f8fbc7-36b4-11e9-9c18-0242ac100504 |   1   |    iscsi    |  false   |    False    |                                                      None                

but fdisk -l in k8s minion there no device,can help me ?

**Comment by wenjun93** [comment]
Can you provide more details? You can use `iscsiadm -m session` to see if the session is established

--
Thanks,
Wenjun

**Comment by jianglingxia** [comment]
sorry,but why my k8s master print the command :
[root@hpa-vm:/home/ubuntu]$ iscsiadm -m session
iscsiadm: No active sessions.
maybe can not established ,is my k8s minion must install iscsi client?
but there has
 [root@hpa-vm:/home/ubuntu]$ iscsi
iscsiadm     iscsid       iscsi-iname  iscsistart   iscsiuio  
@wenjun93 can you help me?thanks

**Comment by jianglingxia** [comment]
[root@hpa-vm:/home/ubuntu]$ kubectl get po -n kube-system
NAME                                             READY   STATUS    RESTARTS   AGE
standalone-cinder-provisioner-7c4649c886-drhst   1/1     Running   0          17h

the pv is
[root@hpa-vm:/home/ubuntu]$ kubectl get pv -w
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                           STORAGECLASS   REASON   AGE
pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3   1Gi        RWO            Delete           Bound         kube-system/keystone-sc-pvc-2   standard                17h

and the pv information 
[root@hpa-vm:/home/ubuntu]$ kubectl get pv  pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    cinderVolumeId: 677a77ff-40db-4949-b906-d92557bbe548
    pv.kubernetes.io/provisioned-by: openstack.org/standalone-cinder
    standaloneCinderProvisionerIdentity: openstack.org/standalone-cinder
  creationTimestamp: "2019-02-22T18:01:20Z"
  finalizers:
  - external-provisioner.volume.kubernetes.io/finalizer
  - kubernetes.io/pv-protection
  name: pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3
  resourceVersion: "6825100"
  selfLink: /api/v1/persistentvolumes/pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3
  uid: dbc64284-36cb-11e9-a0a3-002dc92800b3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: keystone-sc-pvc-2
    namespace: kube-system
    resourceVersion: "6825074"
    uid: d67338e7-36cb-11e9-a0a3-002dc92800b3
  iscsi:
    initiatorName: iqn.2018-01.io.k8s:a13fc3d1cc22
    iqn: iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54
    iscsiInterface: default
    lun: 1
    targetPortal: 19.19.19.252:3260
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound

**Comment by jianglingxia** [comment]
i think maybe must type this below two command:
[root@localhost:/home/ubuntu/iscsi]$ iscsiadm -m discovery -t st -p 10.2.1.54
10.2.1.54:3260,132 iqn.2099-01.cn.cm:p.spr11-74:4a:a4:00:e6:80

[root@localhost:/home/ubuntu/iscsi]$ iscsiadm -m node -p 10.2.1.54 -l

then the device attached the k8s minion and create the pod use the pvc mount the container?

but i think the two step dynamic by kubernetes ?

**Comment by jianglingxia** [comment]
the pod kubelet log is:
I0223 19:51:51.830207   26609 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-xmcch" (UniqueName: "kubernetes.io/secret/686ab774-3761-11e9-a0a3-002dc92800b3-default-token-xmcch") pod "iscsi" (UID: "686ab774-3761-11e9-a0a3-002dc92800b3")
E0223 19:51:51.830368   26609 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/iscsi/19.19.19.252:3260:iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54:1\"" failed. No retries permitted until 2019-02-23 19:51:52.330308191 +0800 CST m=+168899.810258476 (durationBeforeRetry 500ms). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3\" (UniqueName: \"kubernetes.io/iscsi/19.19.19.252:3260:iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54:1\") pod \"iscsi\" (UID: \"686ab774-3761-11e9-a0a3-002dc92800b3\") "
I0223 19:51:52.331877   26609 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3" (UniqueName: "kubernetes.io/iscsi/19.19.19.252:3260:iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54:1") pod "iscsi" (UID: "686ab774-3761-11e9-a0a3-002dc92800b3")

E0223 19:51:59.574293   26609 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/iscsi/19.19.19.252:3260:iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54:1\"" failed. No retries permitted until 2019-02-23 19:52:00.07422285 +0800 CST m=+168907.554173124 (durationBeforeRetry 500ms). Error: "MountVolume.WaitForAttach failed for volume \"pvc-d67338e7-36cb-11e9-a0a3-002dc92800b3\" (UniqueName: \"kubernetes.io/iscsi/19.19.19.252:3260:iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54:1\") pod \"iscsi\" (UID: \"686ab774-3761-11e9-a0a3-002dc92800b3\") : open /sys/class/iscsi_host: no such file or directory"
can you help me ?@wenjun93
