### ISSUE TITLE
nfs-provisioner : kubernetes 1.6 asks for `storageClassName` instead of annotations

### ISSUE THREAD

**Issue by kaiwu** [kubernetes-incubator/external-storage#45]
as per the [doc](https://kubernetes.io/docs/user-guide/persistent-volumes/#persistentvolumeclaims), storageClass by annotations will no longer be supported in future releases

**Comment by wongma7** [comment]
thanks, I release `v1.0.5` tag today. `latest` tag should already work.

**Comment by wongma7** [comment]
Done, please use `v1.0.5` tag and reopen if it still fails

**Comment by kaiwu** [comment]
i confirm v1.0.5 image caters both `storageClassName` and annotation `volume.beta.kubernetes.io/storage-class`, thanks.
