### ISSUE TITLE
Need a better name for Gluster Simple Provisioner

### ISSUE THREAD

**Issue by humblec** [kubernetes-incubator/external-storage#450]
GlusterFS simple provisioner is kind of confusing users and we would need to reconsider this name. Eventhough I started discussion on this before this  PR merge, somehow missed to get addressed. This name can invite confusion even when we move the provisioners out of kube source. @wongma7 @yuanying @jsafrane @rootfs  any thoughts on this ?

**Comment by wongma7** [comment]
now there's both glusterfs and gluster file
