### ISSUE TITLE
Make efs-provisioner to respect custom DNS alias instead of dns name produced by efs service

### ISSUE THREAD

**Issue by venth** [kubernetes-incubator/external-storage#465]
Hi,

I would like to use an alias DNS instead of dns name produced by efs. Unfortunately efs-provisioner combines `filesystemId` with `aws region` and a static part of the dns name to produce full FQDN.

Please consider to enhance efs-provisioner by an argument like: efs_dns_name which by default is empty. When this argument is provided then efs-provisioner uses it and if it's empty then combines  `filesystemId` with `aws region` and a static part of the dns name to produce full FQDN.

What do you think about this proposal?

**Comment by wongma7** [comment]
yes, i agree this is needed, see also: https://github.com/kubernetes-incubator/external-storage/issues/422#issuecomment-340129702

**Comment by venth** [comment]
It seems that I’ve created a duplicate.

**Comment by wongma7** [comment]
close as dupe, work on it there
