### ISSUE TITLE
Move from glide to dep

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#475]
dep is production-ready and supposedly better. it also has vendor pruning built in so we can use that instead of having people use the third-party glide-vc tool to keep the vendor dir size down

**Comment by MartinForReal** [comment]
I'm glad to help

**Comment by wongma7** [comment]
fyi @MartinForReal https://github.com/kubernetes-incubator/external-storage/pull/533/files was WIP but nobody was around to review it. ping @hzxuzhonghu sorry nobody could review it, we can continue working on it now as I will be available.

**Comment by wongma7** [comment]
thank you again to @MartinForReal for your offer and @hzxuzhonghu for writing and updating the gopkg.toml, this is done!
