### ISSUE TITLE
[local-volume] Enhance LV provisioner to allow use of kubeconfig file for API access

### ISSUE THREAD

**Issue by dhirajh** [kubernetes-incubator/external-storage#479]
Currently, the PV provisioner only allows in-cluster config mechanism to access API server. This is a request to enhance the provisioner and give it the option to use a kubeconfig file based access to the API.

**Comment by msau42** [comment]
Can this be closed?

**Comment by dhirajh** [comment]
Yes. It has been fixed with the pr #480
