### ISSUE TITLE
[local-volume] How do you add a mount point atomically?

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes-incubator/external-storage#482]
If I do `sudo mkdir /mnt/disks/foo && sudo mount /mnt/disks/foo`, local-volume-provisioner is too quick, it finds the volume before it's mounted and sets its size to the free space of /mnt/disks rather than the free space of /mnt/disks/foo.    I have to prepend it with `kubectl delete pod local-volume-provisioner-4rk7v &&`.

I got it working, but it seems like an awkward workflow, so hopefully there's a better way, and it should be probably be documented because I imagine it would be an FAQ.

**Comment by jsafrane** [comment]
/close

Fixed by #499
