### ISSUE TITLE
Snapshot: support clone

### ISSUE THREAD

**Issue by rootfs** [kubernetes-incubator/external-storage#485]
Currently snapshot controller and provisioner serve the use case where snapshot is a immutable data backup and PVs promoted from snapshots are new volumes from the backup.

Cinder and many storage backend support volume clone (creating volumes directly from another volume if solurce_volid is provided, see [Cinder API](https://developer.openstack.org/api-ref/block-storage/v3/index.html#volumes-volumes) ). 

Clone is a use case for simplifying volume provision, it needs just one API call to create a new volume. The intermediary immutable backup is no longer needed.

@tsmetana

**Comment by tsmetana** [comment]
I wonder if we could make this universal... Perhaps using again PVC with annotation (referencing the original PV/PVC): such claim would then be satisfied by the provisioner by creating a new clone PV. And we could "fake" this operation on backends that don't support the direct cloning. Would it make sense?

**Comment by tsmetana** [comment]
We talked about this one a bit. Cloning is a different operation from snapshotting. So for the backends which support the clone operation natively there should exist a special controller allowing to clone the PV directly. Snapshots might come as part of a workaround solution for those storage backends not supporting cloning directly. Still there is nothing to do on the snapshot controller or provisioner side. I would close this issue (nobody seems to want to discus about it here anyway).
