### ISSUE TITLE
[local-volume] Replace bootstrapper with spec generation using templates

### ISSUE THREAD

**Issue by msau42** [kubernetes-incubator/external-storage#487]
The local provisioner daemonset spec is complex and error prone because hostpath volumes and discovery configuration have to be configured consistently.  The bootstrapper pod tried to simplify this by auto generating the daemonset spec and automatically launching it.  But this method somewhat hides the daemonset spec and makes it hard to customize and add enhancements.

Instead, I think a better approach would be to have a script that takes in the config, and generates a daemonset spec based off of a template.  Then users could easily customize the generated spec as needed.

**Comment by msau42** [comment]
To be more precise, the inputs would be:
* a configuration file, perhaps yaml? i'm not very picky here
    * the config would include everything that the local volume configmap supports: storageclass mappings, node labels, etc.
    * also optional parameters for the service account that should be used for the provisioner

the generated specs should include:
* daemonset
* configmap

**Comment by sbezverk** [comment]
as a possible solution for templating I would consider 'helm' which would generate daemonset and configmap specs based on user's input config in yaml format and on provided "standard" templates.

**Comment by msau42** [comment]
My only reservation about helm is the requirement to install the server-side tiller component.  Really, we just want the templating part and not the deployment.

Would this work? It looks like a client-side only helm templating plugin.
https://github.com/technosophos/helm-template

**Comment by sbezverk** [comment]
@msau42 tiller is need only if you want to deploy rendered templates, if I remember right helm template command does not require tiller, but I will double check it.

**Comment by msau42** [comment]
Or this?
http://helm.readthedocs.io/en/latest/generate-and-template/
