### ISSUE TITLE
Packages not available.

### ISSUE THREAD

**Issue by careermonk** [kubernetes-incubator/external-storage#49]
The referenced all packages were not available.

- package: k8s.io/client-go
  version: 7615377
  subpackages:
  - kubernetes
  - kubernetes/typed/core/v1
  - pkg/api
  - pkg/api/v1
  - pkg/apis/storage/v1
  - pkg/apis/storage/v1beta1
  - rest
  - tools/cache
  - tools/clientcmd
  - tools/record

For example, following were not found the commit: 7615377

  - pkg/api/resource
  - pkg/api/testapi
  - pkg/api
  - pkg/api/v1

**Comment by wongma7** [comment]
I think these packages are from nfs/test/e2e and you are trying to build that right? Nfs/test/e2e has its own glide.yaml and glide.lock at the moment, run "glide install -v" inside nfs/test/e2e and you should get the needed packages

**Comment by narkarum** [comment]
No.

In the master branch of external-storage, glide has:

package: k8s.io/client-go
version: 7615377
subpackages:
kubernetes
kubernetes/typed/core/v1
pkg/api
pkg/api/v1
pkg/apis/storage/v1
pkg/apis/storage/v1beta1
rest
tools/cache
tools/clientcmd
tools/record

But all these packages were not available in 7615377 commit of k8s.io/client-go

**Comment by wongma7** [comment]
Hmm that's not what I see. https://github.com/kubernetes/client-go/tree/76153773eaa3a268131d3d993290a194a1370585/kubernetes

if they didn't exist at that commit, I wouldn't be able to build anything

**Comment by wongma7** [comment]
fyi I have been getting a lot of errors from glide tonight like
```
[ERROR]	Failed to install: https://cloud.google.com/go Not Found
```
so maybe that's it? the CI is getting the same errors

**Comment by narkarum** [comment]
Yeah correct. I see same errors.

**Comment by wongma7** [comment]
It may take multiple tries but one should eventually work. Since me, you, and CI are all getting the same errors today, I guess we have to blame google's servers and wait until they fix it

**Comment by wongma7** [comment]
transient error, now resolved.
