### ISSUE TITLE
NFS-Client - Exceed requested capacity

### ISSUE THREAD

**Issue by davistran86** [kubernetes-incubator/external-storage#501]
Hi guys, I'm using nfs-client provisioner for testing dynamic provisioning in openshift. I saw that even if I create a PVC with 1Mi, the pod still can create 1Gi file inside mount folder? is it a bug or not ? If not is there anyway to limit it ?

**Comment by msau42** [comment]
Kubernetes does not enforce any capacity isolation.  It is up to the storage provider to provide that capability

**Comment by davistran86** [comment]
ok thanks 👍 then what's the point of putting requested capacity inside of a claim :(

**Comment by msau42** [comment]
There are other volume types that do provide capacity isolation so capacity is useful in those cases.  If your nfs server is provided as a service, then it can also be possible to dynamically launch an nfs server with the exact capacity you need.

**Comment by davistran86** [comment]
thanks a lot @msau42 :). I'm having issue with adding and replacing nodes in glusterfs with heketi so I thought nfs was good to do dynamic provisioning instead of glusterfs :(, I'll try to find other solution..
