### ISSUE TITLE
cephfs and rbd provisioners need an example RBAC

### ISSUE THREAD

**Issue by farcaller** [kubernetes-incubator/external-storage#504]
Now that almost everyone is running with RBAC on, we need a sample RBAC file. The last time I checked `system:persistent-volume-provisioner` cluster role wasn't enough for cephfs to work.

**Comment by rootfs** [comment]
@farcaller see https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/rbd/deploy/rbac

**Comment by farcaller** [comment]
Right, sorry, it's there for rbd, but not for cephfs.

**Comment by rootfs** [comment]
it should work for both, making it at ceph directory makes more sense

**Comment by cofyc** [comment]
@farcaller @rootfs 
CephFS provisioner RBAC files are provided in https://github.com/kubernetes-incubator/external-storage/pull/523/.
