### ISSUE TITLE
efs-provisioner pod error "rpc.statd is not running but is required for remote locking"

### ISSUE THREAD

**Issue by mickengland** [kubernetes-incubator/external-storage#506]
When trying to initialize the efs-provisioner pod I get the following error:

>  Running in chroot, ignoring request. mount.nfs: rpc.statd is not running but is required for remote locking. mount.nfs: Either use '-o nolock' to keep locks local, or start statd. mount.nfs: an incorrect mount option was specified

----
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-rancher3", GitCommit:"772c4c54e1f4ae7fc6f63a8e1ecd9fe616268e16", GitTreeState:"clean", BuildDate:"2017-11-27T19:51:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

Host OS: Ubuntu 16.04.2 LTS

$ uname -a
Linux k8-ubuntu-host-e1 4.4.0-1020-aws #29-Ubuntu SMP Wed Jun 14 15:54:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ sudo docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

**Comment by wongma7** [comment]
Try ` sudo systemctl start rpc-statd ` on the host. Not sure why it is defaulting to nfs v3 mount but that requires rpc.statd to be running on all the hosts/nodes

**Comment by mickengland** [comment]
Thanks that worked.
