### ISSUE TITLE
nfs-client rbac example is out of date as of kubernetes 1.8

### ISSUE THREAD

**Issue by rpeltola** [kubernetes-incubator/external-storage#507]
https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client/deploy/auth

apiVersion needs to be rbac.authorization.k8s.io/v1 instead of rbac.authorization.k8s.io/v1alpha1

**Comment by wongma7** [comment]
yes, not only that but some others have outdated yamls.
/assign

**Comment by musse** [comment]
@wongma7 I fixed the outdated manifests with #656.
