### ISSUE TITLE
[aws-efs] Clarification on how to set reclaim policy to "retain" 

### ISSUE THREAD

**Issue by snoby** [kubernetes-incubator/external-storage#508]
Hi,
I'm having difficulties understanding how to setup my Persistent volume claims to be of policy
`   persistentVolumeReclaimPolicy: Retain `
When I manually allocate the PV I put this tag in the PV, not the PVC.  However since i'm allowing efs-provisioner to dynamically allocate all my claims for me from one EFS PV I'm confused as to how I set this flag.  The Persistentvolume-v1-core seems to indicate that it should be in this spec. Where in the suggested [manifest.yaml](https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/deploy/manifest.yaml) file should I place this key?

Additionally:
When I deploy the stock manifest.yaml (same one as above) the GUID that is assigned to the share is 2001, will all shares from efs provisioner be this value?  Or will it increment based on the next PVC?  How should I know how to setup my deployments with the efs provisioner on how to set the 

```
 securityContext:
        supplementalGroups: [2001]

```
additional setting that I had to set in my test deployment so that I can write and read from this mounted volume?

thanks!

**Comment by boomshadow** [comment]
See #326

**Comment by wongma7** [comment]
should work now
