### ISSUE TITLE
cephfs-provisioner not respecting securityContext

### ISSUE THREAD

**Issue by loganasherjones** [kubernetes-incubator/external-storage#515]
Hello. I'm not really sure if this is even supposed to work with the cephfs-provisioner or not, but I'm running into a problem that I _think_ should be solved by using the cephfs-provisioner. 

**What Happened?** - I created a `StorageClass` and then created a `Pod` which set a `fsGroup` and `runAsUser` in its `securityContext` and then get a Permission Denied error when the pod starts up because the provisioner creates the volume as `root:root`. 

**What did you expect to happen?** - I expected the volume to be created with the pod's `fsGroup` and `runAsUser` ids.

**Versions** 
- ceph - luminous
- kubernetes - 1.8.4
- cephfs-provisioner - 0.1.2

**Steps to Recreate** Get the `cephfs-provisioner` running, create a `StorageClass` and then attempt to create a `Pod` with `fsGroup` and `runAsUser` set.

Let me know if you need any more information!

**Comment by dosmachko** [comment]
@loganasherjones I've faced same issue. Were you able to find any workaround on this issue ?
I was also thinking on moving to rook.io but seems it's not a production ready solutions. 

Thanks.

**Comment by Adriien-M** [comment]
I have the same issue, and for now, the only solution is to run the container with root user :
```
securityContext:
    runAsUser: 0
```

**Comment by loganasherjones** [comment]
Yeah @dosmachko, @Adriien-M's suggestion is the only way I know we can get around it. We had several problems with the ceph-fs provisioner though, so we use static volume mounts a lot more now.

**Comment by wongma7** [comment]
What we need is supplemental groups similar to how it is implemented in the efs provisioner. It creates volumes with a special gid annotation such that when a pod uses a volume it automatically is added to that gid.

To explain why seemingly nothing happens with fsgroup and runasid:
kubernetes ignores fsgroup here because cephfs is shared storage potentially read by multiple pods & it doesn't make sense for a single pod to "take over" the volume by chowning it to its fsgroup.
Similarly there is no functionality in kubernetes to chown volumes to the value of `runasid`, permissions are always treated in terms of groups

**Comment by wongma7** [comment]
@cofyc is it still true that pods cannot read from cephfs provisioned shares unless they run as root? we actually have an internal bug to that effect, want to confirm that with the changes over the last month this issue still persists.

**Comment by SolarisYan** [comment]
@wongma7 Yes, it's still true that pods cannot read from cephfs provisioned shares unless they run as root,
 I've faced same issue now

**Comment by LuckySB** [comment]
workaround: use initcontainer for chown mountpoint

https://github.com/helm/charts/pull/7870

@wongma7 
cephfs-provisioner may chown RunAsUser:fsgroup,when create directory in cephfs for volume ?
only when created. If directory exists - do nothing

**Comment by twelfthdoctor** [comment]
Hello. Is this problem already solved in kubernetes 1.12 ?
