### ISSUE TITLE
digitalocean: Document common tweaks required for a working setup

### ISSUE THREAD

**Issue by klausenbusk** [kubernetes-incubator/external-storage#531]
/area digitalocean

Per #529, for `kubeadm` and `bootkube` setups, the `flexvolume` dir need to be accessible for `kube-controller-manager` for a working setup (the volume won't attach if not).

`bootkube` also require adding a `DIGITALOCEAN_ACCESS_TOKEN` env variable to `kube-controller-manager`, as `kube-controller-manager` run as nobody and as so can't read the `do_token` file.

**Comment by klausenbusk** [comment]
Per: https://github.com/kubernetes-incubator/external-storage/issues/571

* Document CoreOS required change (change of flexvolume dir)
  * Document that `kube-controller-manager` (`kubeadm` only?) need to use the `/usr/share/ca-certificates` instead of `/etc/ssl/certs` due to symlinks.
* Add RBAC policy (see https://github.com/kubernetes-incubator/external-storage/issues/572)

cc @lloeki

**Comment by lloeki** [comment]
I was faced with a silent mount failure. The only available log was on the pod:

```
Unable to mount volumes for pod "postgres-deployment-8b4fd44dc5-4rjw9_www(591133ae-0692-11e3-bfd9-22337054e03c)": timeout expired waiting for volumes to attach/mount for pod "www"/"postgres-deployment-8b4fd44dc5-4rjw9". list of unattached/unmounted volumes=[postgres-persistent-storage]
```

Volume was attaching correctly, just not mounting. Took me *two hours* before I thought about looking into the node's kubelet logs:

```
journalctl -xn -u kubelet.service
```

Turns out I forgot to set `--volume-plugin-dir=` on a node's kubelet args.

It's a bit more general than digitalocean, but I thought that may be worth mentioning somewhere.

**Comment by Kiura** [comment]
@lloeki, could you please tell me how you added --volume-plugin-dir and where/which config?

**Comment by lloeki** [comment]
@kiura the systemd service file. If you're using kubeadm:

```
mkdir -p /etc/kubernetes/kubelet-plugins/volume/exec
sed -i -e 's#\(KUBELET_EXTRA_ARGS=\)#\1--volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec #' /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
```
