### ISSUE TITLE
[efs-provisioner] gid ranges with multiple StorageClasses, how does it work?

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/external-storage#541]
The gidAllocate and ginMin/gidMax ranges are per-StorageClass settings.

How does it work if two StorageClasses enable gidAllocate but specify overlapping gid ranges? Will the same gid get allocated twice? Or does the efs-provisioner avoid repeats globally?

**Comment by wongma7** [comment]
the same gid will get allocated twice, it does not avoid global repeats.

**Comment by whereisaaron** [comment]
Makes sense. Thanks for clearing that up. I suggest you add a sentence to the 'parameters' discussion or FAQ.

**Comment by whereisaaron** [comment]
Added PR #542 to add a FAQ covering this @wongma7, hope that's ok.

**Comment by whereisaaron** [comment]
Sorted. Thanks for merging the PR @wongma7.
