### ISSUE TITLE
ProvisionController support for SharedInformers

### ISSUE THREAD

**Issue by zcahana** [kubernetes-incubator/external-storage#546]
Hi,

I'd like to propose extending the [`ProvisionController`](https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L69) to optionally use [`SharedInformers`](https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L42) instead of "private" informers. This will support use-cases where other application components (e.g., the [`Provisioner`](https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/volume.go#L29) implementation) need to access PersistentVolumes / PersistentVolumeClaims / StorageClasses.

If this sounds relevant and reasonable, I'd be happy to work on that.

**Comment by wongma7** [comment]
yes, sounds good to me 👍
