### ISSUE TITLE
standalone-cinder: support rbd feature disable

### ISSUE THREAD

**Issue by wenjun93** [kubernetes-incubator/external-storage#547]
see [#57960](https://github.com/kubernetes/kubernetes/issues/57960), if cinder configuration of rbd feature is more than kernel can support, I'm thinking if it is necessary to disable the features after provisioning. thoughts? @aglitke

**Comment by wongma7** [comment]
reopen if still an issue, seems it's hard to solve https://github.com/kubernetes/kubernetes/issues/57960#issuecomment-366254208
