### ISSUE TITLE
openebs test broken

### ISSUE THREAD

**Issue by dmick** [kubernetes-incubator/external-storage#548]
with unittests.sh:

```
$ ./unittests.sh 
Running unit tests in ./openebs/pkg/v1
# github.com/kubernetes-incubator/external-storage/openebs/pkg/v1
./maya_api_test.go:140: too many arguments in call to EvaluateCreateVolume
	have (OpenEBSVolumeTest, string, string)
	want (OpenEBSVolumeInterface, "github.com/kubernetes-incubator/external-storage/openebs/types/v1".VolumeSpec)
FAIL	github.com/kubernetes-incubator/external-storage/openebs/pkg/v1 [build failed]
```

This appears to be because of 5987173052a4ea37225b1dbc2f414117c9f5719d, which changed the signature of an internal test function from 
```EvaluateCreateVsm(ovi OpenEBSVolumeInterface, vname string, size string) (string, error)```
to
```EvaluateCreateVolume(ovi OpenEBSVolumeInterface, vs mayav1.VolumeSpec) (string, error)```

but did not change the call arguments:

```                message, err := EvaluateCreateVolume(c.ovt, c.vname, c.size)```

@satyamz

**Comment by prateekpandey14** [comment]
Thanks @dmick for raising the issue, i will raise a PR to fix this the test.
