### ISSUE TITLE
helm template generation for local storage provisioner fails

### ISSUE THREAD

**Issue by aetimmes** [kubernetes-incubator/external-storage#551]
I'm trying to follow the procedures for bare metal local storage provisioning detailed here: https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume. 

I'm stuck on creating the provisioner resource. I run:
`helm template ./helm/provisioner --set engine=baremetal > ./provisioner/deployment/kubernetes/provisioner_generated.yaml`
and try to run 
`kubectl create -f ./provisioner/deployment/kubernetes/provisioner_generated.yaml` 
but I receive the error 
`error: error converting YAML to JSON: yaml: line 14: did not find expected key`.

[provider_generated.yaml.txt](https://github.com/kubernetes-incubator/external-storage/files/1621268/provider_generated.yaml.txt)
[values.yaml.txt](https://github.com/kubernetes-incubator/external-storage/files/1621269/values.yaml.txt)

If I de-indent the lines directly following line 14, the daemonset and configmap get created, but given the manual intervention i don't know if all the information that needs to be in that template is actually present.

**Comment by aetimmes** [comment]
The above was detailed in #sig-storage on the k8s slack with @sbezverk and @msau42.

**Comment by sbezverk** [comment]
@aetimmes Please check proposed solution.

**Comment by aetimmes** [comment]
Looks like it works! The provisioner is complaining that I don't have the LocalVolume feature gate enabled but it's definitely finding the volumes, at least:

```0112 18:21:30.577253       1 discovery.go:207] Found new volume of volumeType "file" at host path "/data/default/vol1" with capacity 8269524992, creating Local PV "local-pv-2b27b2b0"```

**Comment by aetimmes** [comment]
I'll figure out the feature gating business on my own - feel free to close this. Thanks!
