### ISSUE TITLE
Validation of AWS Snapshot example failing

### ISSUE THREAD

**Issue by screeley44** [kubernetes-incubator/external-storage#558]
Env: single node K8 cluster created from local-up-cluster.sh (1.10 dirty) running on AWS us-east-1d

Following the Snapshot AWS example, using the latest deployment.yaml, the controller and provisioner from the deployment seem to run fine.

```
kubectl get pods
NAME                                   READY     STATUS    RESTARTS   AGE
snapshot-controller-7bb857f5dc-s9hvk   2/2       Running   0          47s
```

But when I get to the step where I actually create the snapshot (snapshot.yaml) from my PV/PVC, I don't think it is working and didn't find anything obvious in the logs to indicate why it is failing:

```
kubectl get volumesnapshot,volumesnapshotdata -o yaml --namespace=myns

apiVersion: v1
items:
- apiVersion: volumesnapshot.external-storage.k8s.io/v1
  kind: VolumeSnapshot
  metadata:
    clusterName: ""
    creationTimestamp: 2018-01-11T01:34:22Z
    generation: 0
    labels:
      SnapshotMetadata-PVName: pvc-351f5fc3-f66f-11e7-9ee7-0eef3fbd31d8
      SnapshotMetadata-Timestamp: "1515634526910793155"
    name: snapshot-demo
    namespace: myns
    resourceVersion: "1178"
    selfLink: /apis/volumesnapshot.external-storage.k8s.io/v1/namespaces/myns/volumesnapshots/snapshot-demo
    uid: 8d39e74c-f66f-11e7-9ee7-0eef3fbd31d8
  spec:
    persistentVolumeClaimName: ebs-pvc
    snapshotDataName: ""
  status:
    conditions: null
    creationTimestamp: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Of course when I try to promote the snapshot, it fails, probably because it doesn't exist:

```
kubectl create -f snapshot-claim.yaml

# kubectl get pvc -n myns
NAME                            STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
ebs-pvc                         Bound     pvc-351f5fc3-f66f-11e7-9ee7-0eef3fbd31d8   4Gi        RWO            slow                25m
snapshot-pv-provisioning-demo   Pending                    
```

**Comment by screeley44** [comment]
cc @tsmetana

**Comment by tsmetana** [comment]
I had some problems running the deployment in AWS too and I suspect there is a problem with cloud provider. It's possible to get the output from the controller with 'docker logs' -- the snapshot binaries are quite verbose.

Thanks for reporting -- I will take a look at it.

**Comment by tsmetana** [comment]
I think I found the problem: the upstream images don't contain valid CA certificates. Either I will use some bigger base image or copy the CA files manually from the system. Whichever is lesser evil.

**Comment by wongma7** [comment]
fixed
