### ISSUE TITLE
NFS demo does not work with kubernetes 1.4.0

### ISSUE THREAD

**Issue by spicku** [kubernetes-incubator/external-storage#568]
I followed the NFS provisioner demo, and I'm facing following issue. I'm using k8s version 1.4.0 and nfs provisioner image - quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8
I am using host path volume for testing -> hostPath: 
                                                path: /tmp/hostpath-nfs-storage

Here are details -->

Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

all of the pods(NFS Provisioner, tomcat pod) launched correctly, and the PV and PVCs are created and bound properly :

PODS - 
NAME                            READY     STATUS    RESTARTS   AGE
nfs-dynamic-tomcat-pod          1/1       Running   0          1h
nfs-provisioner-1528905-a4ghg   1/1       Running   0          2d

PVC - 
NAME              STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
nfs-dynamic-pvc   Bound     pvc-6a3be5e4-ff54-11e7-b2ef-0200033502b5   1Mi        RWX           1h

PV - 
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                     REASON    AGE
pvc-6a3be5e4-ff54-11e7-b2ef-0200033502b5   1Mi        RWX           Delete          Bound     default/nfs-dynamic-pvc             1h

StorageClass - 
NAME          TYPE
example-nfs   nfs-provisioner

Inside tomcat pod, volume is mounted properly.
10.100.151.2:/export/pvc-6a3be5e4-ff54-11e7-b2ef-0200033502b5 on /mnt1 type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.1.1.42,local_lock=none,addr=10.100.151.2)

but manually trying to do anything on that volume doesn't work:

root@nfs-dynamic-tomcat-pod:/mnt1# touch test.txt
touch: setting times of 'test.txt': No such file or directory

Here is stroageclass yaml file ->
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: example-nfs  
provisioner: nfs-provisioner
parameters:  
  mountOptions: "vers=4.2"

I have also tried adding the rootSquash(rootSquash: "true") and gid parameters in the storageclass, but it did not work. 
I tried changing NFS version - 4.1, 4.0, 3.0 , but no luck. 

I can create the file inside the same path directly from the host path location or from nfs provisioner container /export path. However one noticable point is 
owner and groupowner for the files is shown as nobody/nogroup.
root@nfs-dynamic-tomcat-pod:/mnt1# ls -ltr
total 0
-rw-r--r--. 1 nobody nogroup 0 Jan 22 10:41 direct-host-path-file.txt
-rw-r--r--. 1 nobody nogroup 0 Jan 22 10:43 nfs-provisioner-file.txt

This issue is similar to other issue -> https://github.com/kubernetes-incubator/external-storage/issues/223
However as per resolution on that issue, it at least worked for NFS 3.0 version. For me its not working for any of the NFS version.

Am i missing anything? Do i need to change/check anything on NFS server running inside NFS provisioner?
Any pointers/inputs to solve this issue would be really helpful.

Thanks in advance,
picku

**Comment by wongma7** [comment]
No, you're not missing anything. The only potential fix is to try different NFS versions and you did that. Sorry, these issues are difficult to debug. I recommend you stand up a simple nfs server and use the nfs-client provisioner, it is more stable

/area nfs
