### ISSUE TITLE
rbd support for secret namespace

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-incubator/external-storage#570]
Upstream fixed rbd to support specifying a namespace where the rbd secrets can be read in the created PV's. The external provisioner here needs to support the same option to fully finish the functionality. We would much rather use an external provisioner then the internal one.

**Comment by kfox1111** [comment]
The relevant upstream issue: https://github.com/kubernetes/kubernetes/issues/54432

**Comment by sbezverk** [comment]
@wongma7 Any chance you could push latest API changes? We are still missing RBDPersistentVolumeSource definition.

**Comment by cofyc** [comment]
I created a PR (https://github.com/kubernetes-incubator/external-storage/pull/552) few days ago. It requires k8s.io/api@1.9.

**Comment by kfox1111** [comment]
@wongma7 any idea when the updated kubeapi will land?

**Comment by cofyc** [comment]
@childsb @kfox1111 This can be closed, https://github.com/kubernetes-incubator/external-storage/pull/552 was merged.

**Comment by kfox1111** [comment]
@cofyc awesome. thank you. Did it make it into a release yet, or are we still waiting on that?

Thanks,
Kevin
