### ISSUE TITLE
Snapshot API support for external providers

### ISSUE THREAD

**Issue by prateekpandey14** [kubernetes-incubator/external-storage#574]
Currently Snapshot API only supports In-tree `VolumeSource` providers to determine the plugin name.
means there is no way to determine the out-tree providers, where PV is dynamically provisioned by external-provisioners.
/area snapshot

/cc @tsmetana @rootfs @msau42 @xing-yang

**Comment by xing-yang** [comment]
Thanks @prateekpandey14 for opening this issue.  We are investigating this issue and will be addressing it.
