### ISSUE TITLE
CephFS,Gluster Block: statefulness

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#58]
@rootfs @humblec we have to implement a way for CephFS & Gluster Block provisioners to maintain state (across restarts) https://github.com/kubernetes-incubator/external-storage/blob/master/ceph/cephfs/cephfs-provisioner.go#L61 <- this old method won't survive restarts since it's generated at runtime. First you have to decide if your provisioner needs to maintain state at all? Like, whose PVs should it be allowed to Delete? If it restarts can it still Delete the PVs it Provisioned before it restarted, or will those PVs be left dangling?

To see what I am talking about, please see https://github.com/kubernetes-incubator/external-storage/tree/master/docs#running-multiple-provisioners-and-giving-provisioners-identities. In not so many words, I am basically talking about the same thing as the "unique name" in the CSI proposal https://docs.google.com/document/d/1JMNVNP-ZHz8cGlnqckOnpJmHF-DNY7IYP-Di7iuVhQI/edit#heading=h.6r2wd16r05z7 which allows a plugin to associate a given "storage space" with itself in case of failure. In the same way, our external provisioners have to be able to associate themselves with given "storage spaces."

In our case, Kubernetes won't decide a "unique name" for us, so we have to decide if we need one, and then if so generate & maintain it *ourselves.*

**Comment by rootfs** [comment]
Yes that makes senses. I see you use an identify file, it is a good solution. I'll use a command line option to pass the identity.

**Comment by humblec** [comment]
@wongma7 Indeed make sense. Thanks for the pointer 👍 . I will get it done for gluster block provisioner.
