### ISSUE TITLE
Need support for endpoint  /metrics

### ISSUE THREAD

**Issue by utkarshmani1997** [kubernetes-incubator/external-storage#585]
There is need of endpoint `/metrics` such that provisioner pods can be monitored via Prometheus.Currently after discovering pods in target (Prometheus browser) it shows status as down.There should be endpoint metrics so that it can be discovered in Prometheus's target.

**Comment by wongma7** [comment]
similar issue: https://github.com/kubernetes-incubator/external-storage/issues/81

https://github.com/kubernetes-incubator/external-storage/pull/796 will solve this, needs review
