### ISSUE TITLE
CephFS share name with '-' failed with Operation not permitted

### ISSUE THREAD

**Issue by larryck** [kubernetes-incubator/external-storage#589]
Hi,  I'm using Kubernetes v1.6.7 with the cephfs storageclass on arm64 servers. My ceph version is 10.1.2.  I create a pvc provisioned with the cephfs storageclass and mount it with ceph fuse ( I backported it from the latest kubernetes version), but the pv keeps mount-failed. I test the following case:

> root@node1:/mnt# ceph auth caps client.kubernetes-dynamic-user-20c4fc31-0a38-11e8-9189-1c83411ea7c8 mon "allow r" mds "allow r,allow rw path=/volumes/kubernetes/test-kubernetes" osd "allow rw pool=cephfs_data"

> root@node1:/mnt# ceph-fuse  -n client.kubernetes-dynamic-user-20c4fc31-0a38-11e8-9189-1c83411ea7c8 -k /mnt/target.keyring  test-fuse/ -r /volumes/kubernetes/test-kubernetes
> ceph-fuse[365765]: starting ceph client
> 2018-02-05 15:25:52.776489 7f79fa9000 -1 init, newargv = 0x122ac67e0 newargc=11
> ceph-fuse[365765]: ceph mount failed with (1) Operation not permitted
> ceph-fuse[365763]: mount failed: (1) Operation not permitted

but when I change the dir-name from "test-kubernetes" to "test_kubernetes", it works ok.
> ceph auth caps client.kubernetes-dynamic-user-20c4fc31-0a38-11e8-9189-1c83411ea7c8 mon "allow r" mds "allow r,allow rw path=/volumes/kubernetes/test_kubernetes" osd "allow rw pool=cephfs_data"

> root@node1:/mnt# ceph-fuse  -n client.kubernetes-dynamic-user-20c4fc31-0a38-11e8-9189-1c83411ea7c8 -k /mnt/target.keyring  test-fuse/ -r /volumes/kubernetes/test_kubernetes
> ceph-fuse[365456]: starting ceph client
> 2018-02-05 15:25:30.267014 7fa0ed2000 -1 init, newargv = 0x1451a67e0 newargc=11
> ceph-fuse[365456]: starting fuse

so I replace '-' with '_' of the share name in file cephfs/cephfs-provisioner.go

```
// Provision creates a storage asset and returns a PV object representing it.

func (p *cephFSProvisioner) Provision(options controller.VolumeOptions) (*v1.PersistentVolume, error) {

        if options.PVC.Spec.Selector != nil {

                return nil, fmt.Errorf("claim Selector is not supported")

        }

        cluster, adminID, adminSecret, mon, err := p.parseParameters(options.Parameters)

        if err != nil {

                return nil, err

        }

        // create random share name

        share := fmt.Sprintf("kubernetes-dynamic-pvc-%s", uuid.NewUUID())

        **//add by tanck
        share = strings.Replace(share, "-", "_", -1)**
```
and pvs provisioned by cephfs storageclass can mount correctly in my kubernetes cluster.

**Comment by rootfs** [comment]
cc @zhangxiaoyu-zidif for ceph-fuse

**Comment by wongma7** [comment]
what if /volumes/kubernetes/test-kubernetes is in quotes, could it be a bug in ceph-fuse cli? Looks strange to me.
