### ISSUE TITLE
[aws-efs] Helm chart for efs-provisioner

### ISSUE THREAD

**Issue by whereisaaron** [kubernetes-incubator/external-storage#606]
Hi @wongma7, thank you very much for your work on EFS Provisioner. It has been working great for me.

I could not find a good `helm` chart for deploying `efs-provisioner` to clusters, so I [prepared one](https://github.com/whereisaaron/charts/tree/master/incubator/efs-provisioner) that deploys `efs-provisioner` and optionally a StorageClass.

I guess the right place for this is the 'kubernetes/charts' project, and I have [created a PR there to add it to the 'incubator' charts](https://github.com/kubernetes/charts/pull/3233).

Please take a look and let me know if it is a suitable chart. If you like it, please endorse the [PR](https://github.com/kubernetes/charts/pull/3233). I am sure the author's endorsement will help it get reviewed 😄

**Comment by michaelajr** [comment]
Looking fo this as well! Would be great to have!

**Comment by whereisaaron** [comment]
Hi @michaelajr @wongma7, the EFS Provisioner Helm chart has just gone stable

  https://github.com/kubernetes/charts/tree/master/stable/efs-provisioner

So you can now deploy efs-provisioner to a cluster with as little as:
```
helm install stable/efs-provisioner --set efsFileSystemId=fs-12345678 --set awsRegion=us-east-2
```
and all currently available configuration options can be set using Helm [deployment values](https://github.com/kubernetes/charts/tree/master/stable/efs-provisioner#configuring).
