### ISSUE TITLE
CephFS: Need to update readme

### ISSUE THREAD

**Issue by jhou1** [kubernetes-incubator/external-storage#61]
According to https://github.com/kubernetes-incubator/external-storage/blob/master/ceph/cephfs/README.md, the command to start CephFS provisioner is  `docker run -ti -v /root/.kube:/kube --privileged --net=host  cephfs-provisioner /usr/local/bin/cephfs-provisioner -master=http://127.0.0.1:8080 -kubeconfig=/kube/config -id=cephfs-provisioner-1`.

When the docker run command is executed, the following error is shown:

```
docker run -ti -v /root/.kube:/kube --privileged --net=host  cephfs-provisioner /usr/local/bin/cephfs-provisioner -master=http://127.0.0.1:8080 -kubeconfig=/kube/config -id=cephfs-provisioner-1
F0406 05:55:45.198882       1 cephfs-provisioner.go:285] Failed to create config: invalid configuration: [unable to read client-cert /var/run/kubernetes/client-admin.crt for myself due to open /var/run/kubernetes/client-admin.crt: no such file or directory, unable to read client-key /var/run/kubernetes/client-admin.key for myself due to open /var/run/kubernetes/client-admin.key: no such file or directory, unable to read certificate-authority /var/run/kubernetes/server-ca.crt for local due to open /var/run/kubernetes/server-ca.crt: no such file or directory]
```

Need to add `-v /var/run/kubernetes:/var/run/kubernetes` to it. For example: `docker run -ti -v /root/.kube:/kube -v /var/run/kubernetes:/var/run/kubernetes --privileged --net=host  cephfs-provisioner /usr/local/bin/cephfs-provisioner -master=http://127.0.0.1:8080 -kubeconfig=/kube/config -id=cephfs-provisioner-1`

**Comment by wongma7** [comment]
@rootfs , looks like this happens when kubeconfig references a cert by path, should be documented

**Comment by wongma7** [comment]
@humblec i think gluster needs the same small doc update. something like: If the kubeconfig references a cert by path, the container must be able to access it, like via a Docker volume "-v /var/run/kubernetes:/var/run/kubernetes"

**Comment by rootfs** [comment]
my bad, doc is out of sync with the [original](https://github.com/rootfs/cephfs-provisioner)
