### ISSUE TITLE
CephFS: PV aren't auto deleted.

### ISSUE THREAD

**Issue by jhou1** [kubernetes-incubator/external-storage#62]
The PV provisioned by CephFS provisioner can not be automatically deleted when the PVC is deleted.

```
# kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
c1        Bound     pvc-0ea9f6de-1a8c-11e7-b3c3-0050569f3e08   1Gi        RWO           cephfs         8m

# kubectl delete pvc c1
persistentvolumeclaim "c1" deleted

# kubectl get pvc
No resources found.

# kubectl get pv pvc-0ea9f6de-1a8c-11e7-b3c3-0050569f3e08
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM        STORAGECLASS   REASON    AGE
pvc-0ea9f6de-1a8c-11e7-b3c3-0050569f3e08   1Gi        RWO           Delete          Bound     default/c1   cephfs                   9m

**Comment by wongma7** [comment]
Hmmm this is a weird one, why is the PV still in bound state? That's kubernetes'/openshift's PV controller's job, when the PVC is deleted it should go from Bound->Released. WDYT @rootfs?

**Comment by rootfs** [comment]
my bad, doc is out of sync with the [original](https://github.com/rootfs/cephfs-provisioner)

**Comment by rootfs** [comment]
didn't see it here

```console
# _output/bin/kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS   AGE
claim1    Bound     pvc-54f271b0-1b9d-11e7-9a06-000d3a185cfe   1Gi        RWX           cephfs         14m
# _output/bin/kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM            STORAGECLASS   REASON    AGE
pvc-54f271b0-1b9d-11e7-9a06-000d3a185cfe   1Gi        RWX           Delete          Bound     default/claim1   cephfs                   14m
# _output/bin/kubectl delete pvc claim1
persistentvolumeclaim "claim1" deleted
# _output/bin/kubectl get pv
No resources found.
```

**Comment by rootfs** [comment]
@jhou1 did you create and delete using the same provisioner? with recent provisioner identity change, delete may not happen if the pv was created by provisioners with other id

**Comment by jhou1** [comment]
> did you create and delete using the same provisioner? with recent provisioner identity change, delete may not happen if the pv was created by provisioners with other id or old id

@rootfs sorry I didn't quite get it, how can I know that I was using a different provisioner? I had just kept the provisioner container running as soon as my kuberentes cluster was up.

**Comment by wongma7** [comment]
was etcd issue; will be fixed by https://github.com/kubernetes/kubernetes/pull/44396!
