### ISSUE TITLE
Does EFS provisioner support "rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2" as documented by AWS ?

### ISSUE THREAD

**Issue by etsangsplk** [kubernetes-incubator/external-storage#621]
AWS EFS Doc recommends certain settings (see below), where does efs provisioner gets its settings to align with AWS recommendation? Or in case user need to change, how to?

e.g.:

$  sudo mount -t nfs -o **nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2** mount-target-DNS:/mike  /home/mike
doc:
https://docs.aws.amazon.com/efs/latest/ug/accessing-fs-nfs-permissions-per-user-subdirs.html#accessing-fs-nfs-permissions-per-user-subdirs-auto-mount-on-reboot

**Comment by wongma7** [comment]
the latest version should have nfsvers=4.1 at least, the rest I'm told will be default https://github.com/kubernetes-incubator/external-storage/pull/807

You can't change it right now but there is an issue open to let you do it with StorageClass.mountOptions https://github.com/kubernetes-incubator/external-storage/issues/810 let's talk about it there

/area aws/efs
