### ISSUE TITLE
MountOptions ignored in nfs-client-provisioner

### ISSUE THREAD

**Issue by JasperZ** [kubernetes-incubator/external-storage#629]
Hey,
I'm currently working with the nfs-client(-provisioner). I deployed it as described in the readme and i can see the created folder for the PersistentVolume on the NFS server. My problem is that I have to use NFS version 3. Therefore I tried adding the mountOptions for the StorageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: freenas-nfs-storage
parameters:
  mountOptions: "vers=3.0,nfsvers=3"
mountOptions:
  - vers=3.0
  - nfsvers=3
provisioner: storage.zhc.x64.me/persistent-volumes
```
Since I wasn't sure I tried it under parameters and directly, but both attemts lead to a PersistantVolume: without the specified options.
PersistentVolumeClaim:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: freenas-nfs-storage
```
Dynamicly generated PersistentVolume:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: storage.zhc.x64.me/persistent-volumes
  creationTimestamp: 2018-02-27T20:45:42Z
  name: pvc-2d476ed3-1bff-11e8-ac43-22cbbb3b00bb
  resourceVersion: "8352"
  selfLink: /api/v1/persistentvolumes/pvc-2d476ed3-1bff-11e8-ac43-22cbbb3b00bb
  uid: 2d67b92f-1bff-11e8-ac43-22cbbb3b00bb
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test-claim
    namespace: default
    resourceVersion: "8342"
    uid: 2d476ed3-1bff-11e8-ac43-22cbbb3b00bb
  nfs:
    path: /mnt/datacenter_250GB/kubernetes/development/persistent-volumes/default-test-claim-pvc-2d476ed3-1bff-11e8-ac43-22cbbb3b00bb
    server: storage.zhc.x64.me
  persistentVolumeReclaimPolicy: Delete
  storageClassName: freenas-nfs-storage
status:
  phase: Bound
```

Am I doing something wrong or did I miss something obvious?

**Comment by nrobert13** [comment]
same here, as long as I can see in the client-provisioner source, the mountoptions is not passed to the persistentvolume structure created by provisioner:
line 72-89 : https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go
should pass MountOptions like in line 464 : https://github.com/kubernetes/kubernetes/blob/060a66ae20393c66f70374836b64d350e0073b10/pkg/apis/core/types.go

it's just a guess though ...

**Comment by wongma7** [comment]
@nrobert13 you are correct, there needs to be a line copying mountoptions from storageclass.mountoptions to pv.mountoptions

**Comment by fabiorauber** [comment]
Just noticed the same behavior trying to mount NFS version 3 volumes.

**Comment by travisghansen** [comment]
Out of curiosity, does anyone know if the mount options provided are supposed to **replace** entirely, or be **appended** to mount options by the provisioners?

**Comment by wongma7** [comment]
this should be fixed in the latest version

there is no rule/guidance as to mount options, so it's up to the provisioner to reconcile storageclass.mountoptions with whatever default mountoptions it wants to set on its PVS
