### ISSUE TITLE
Snapshot plugin Init() parameter should be more generic

### ISSUE THREAD

**Issue by disrani-px** [kubernetes-incubator/external-storage#643]
Right now it takes cloudprovider.Interface as a param. But snapshots can be taken for non-cloud providers too. So can that be changed to interface{} type or something more generic?

/area snapshot

**Comment by rootfs** [comment]
do you have a use case for that?

**Comment by disrani-px** [comment]
The use case is for non-cloud storage providers which want to take local snapshots.

**Comment by tsmetana** [comment]
We already have a hostpath plugin... It basically ignores the Init() parameter. I would also be curious about a specific use-case that would need this. Not that I'm against: just want to figure out what should the interface look like. We should not make the interface more complicated.

**Comment by disrani-px** [comment]
Actually, the hostpath ignoring the parameter is a good example. Passing in cloudprovider info for that doesn't really serve a purpose. 
My use case is using this for snapshots in Portworx, which doesn't need the cloudprovider parameters interface either to take local snapshots.

Maybe pass in an interface{} type so that out of tree plugins can pass in arbitrary parameters according to their need?

**Comment by tsmetana** [comment]
If it buys us Portworx plugin... Let's do the interface{} and give it some pretty name to make it more readable. @rootfs what do you think?
