### ISSUE TITLE
refactor snapshot to use shared infromer and versioned client

### ISSUE THREAD

**Issue by wackxu** [kubernetes-incubator/external-storage#644]
Snapshot uses CRD to define resources such as `VolumeSnapshot` and  `VolumeSnapshotData` .  We should follow the pattern https://github.com/kubernetes/sample-controller to implement our code and make it more readable and clear.

**Comment by tsmetana** [comment]
Yes, the controller needs to be refactored. I'm only afraid it's not so urgent yet, especially with the CSI proposal under way.

**Comment by wackxu** [comment]
@tsmetana I was working on it and almost finish it. I like to post a pr since `Add Snapshot Support in CSI Spec` is in review.
