### ISSUE TITLE
NFS provisioning better documentation

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/external-storage#649]
Had major difficulty following the example due to `ServiceAccount` not being in the default `nfs/deploy/kubernetes/deployment.yaml` file.

This wasn't outlined in the `Quickstart` guide, and only here:

https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/deployment.md

Within an in-line paragraph.

The `deployment.md` also only describes how to deploy the actual deployment.yaml file, but does not continue with the how-to on deploying `claim.yaml`, etc.

I'd suggest perhaps putting it in bullet points instead to emphasize it?

Suggestions:

 - Cleanup `deployment.md` file to emphasize what's required before deployment (authorization rbac, psp)
 - Further examples / how-to pass the deploying deployment/statefulset/daemonset
 - Perhaps adding `ServiceAccount` parameter to the `deployment.yaml` file or at least emphasizing it in the Quickstart guide rather than having to hunt through the documentation on how to do it.

**Comment by wongma7** [comment]
It is hard. I am not a good technical writer. PR's welcome. I don't disagree about putting the sa and deployment in the same file

/area nfs
