### ISSUE TITLE
Document required IAM permissions

### ISSUE THREAD

**Issue by deitch** [kubernetes-incubator/external-storage#666]
When running the provisioner, I get:

```
W0312 15:36:22.418068       1 efs-provisioner.go:86] couldn't confirm that the EFS file system exists: AccessDeniedException: User: arn:aws:sts::xxxxxx:assumed-role/ROLENAME/xxxxxx is not authorized to perform: elasticfilesystem:DescribeFileSystems on the specified resource
	status code: 403, request id: xxxxxx
```

I dug through the code, and it appears to use the AWS API to see if it can get to the filesystem [here](https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/cmd/efs-provisioner/efs-provisioner.go#L84)

The documentation doesn't list that this is a requirement. It is fine as a requirement - actually makes sense - but needs to be added to the docs.

**Comment by wongma7** [comment]
It is not technically a requirement, only a warning just as a sanity check that it's actually working in an efs-mounted directory vs local. the docs are quite long now so it's somewhat hidden at the bottom since it's optional https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs#optional-aws-credentials-secret

**Comment by wongma7** [comment]
either way I'd be open to rewording the warning so it's less scary

**Comment by deitch** [comment]
> only a warning just as a sanity check that it's actually working in an efs-mounted directory vs local.

Ah, got it. I had misunderstood. I had thought of it as an error, but looking now, I see that it is a warning `W0312`. I also see that despite the message, it works just fine.

Yeah, I think some doc rewording would be helpful. 

In theory, since I am running it on ec2, and I have the right IAM roles and policies set up, should it not just pick them up? I am unsure how the aws sdk for go figures out that it is running on ec2 and gets the credentials, probably looking for http://169.254.169.254/latest/meta-data/ . Ah, but if I am not running the efs-provisioner container in the host network namespace, then it will not see it.

**Comment by wongma7** [comment]
PR for rewording is welcome, I'm not sure how myself. You are right, the provisioner needs quite a bit of info to figure it out, which is why this stuff is optional and downgraded to a warning

/area aws/efs

**Comment by bcatubig** [comment]
@wongma7 ran into this today. Should this sanity check be removed?

**Comment by wallyqs** [comment]
Same here, so it is a harmless error?
