### ISSUE TITLE
[nfs-provisionner] Too many open files

### ISSUE THREAD

**Issue by sdurrheimer** [kubernetes-incubator/external-storage#67]
Hi there,

We recently encounter a "Too many open files" wit the NFS-provisionner. It seems like the ganesha nfs-server is using some sort of file descriptor cache which can be a real issue when you have some nfs volumes with a loot of files.

There is currently no easy/direct way to specify the `ulimit` for the nfs provisionner and/or control the ganesha FD cache.

```
E0407 08:23:57.125652       1 controller.go:578] Failed to provision volume for claim "default/redis-session-datadir" with StorageClass "nfs-fast": error creating export for volume: error exporting export block 
EXPORT
{
Export_Id = 4;
Path = /export/pvc-40d9e46a-1b6b-11e7-9c28-0050568e35fd;
Pseudo = /export/pvc-40d9e46a-1b6b-11e7-9c28-0050568e35fd;
Access_Type = RW;
Squash = no_root_squash;
SecType = sys;
Filesystem_id = 4.4;
FSAL {
Name = VFS;
}
}
: error calling org.ganesha.nfsd.exportmgr.AddExport: Error while parsing /export/vfs.conf because of (token scan) errors. Details:
Config File (<unknown file>:0): new file (/export/vfs.conf) open error (Too many open files), ignored
```

Is this a known issue ?

**Comment by wongma7** [comment]
Well we should be prefacing our start of Ganesha with a 'ulimit', but that requires the container to be privileged for it to have any effect. I will investigate implementing this

Alternatively, running with the docker ulimit argument may bypass the issue.

**Comment by wongma7** [comment]
What value do you get for output of `ulimit -n` when run inside the container? I get the max 1024*1024 which is what ganesha wants to set itself.(`sudo prlimit --pid <ganesha.nfsd PID>` on the host machine also says 1024*1024)

**Comment by sdurrheimer** [comment]
`ulimit -n` in the nfs-provisioner container gives me `65536`.

**Comment by wongma7** [comment]
I am working on a fix here https://github.com/kubernetes-incubator/external-storage/pull/72, I'm pushing it to `latest` tag if you want to try it.

It *appears* to work, I still need to test it. And the extra syscall may result in additional requirements for CAP_ADD and/or seccomp, need to test that too.

**Comment by wongma7** [comment]
The only thing that needs to be done is: add the capability - SYS_RESOURCE to either `docker run` or securityContext.capabilities.add . I will update the docs when I release the next version including this fix, it is going to just be in the `latest` tag for now

**Comment by sdurrheimer** [comment]
Thank you, I will try to test this.
