### ISSUE TITLE
cannot get volumeMode for volume

### ISSUE THREAD

**Issue by shenshouer** [kubernetes-incubator/external-storage#670]
I used `quay.io/external_storage/rbd-provisioner:latest` in k8s v1.9.3 and v1.9.4, got the error:
```
kubelet[23346]: E0315 17:37:25.654189   23346 desired_state_of_world_populator.go:273] Error processing volume "pvc" for pod "test-pod_default(bad74ece-2832-11e8-b890-246e96778ca4)": cannot get volumeMode for volume: pvc-a0d098b6-2832-11e8-b890-246e96778ca4
```

worked for k8s v1.8.2

Anyone who know how to do ?

**Comment by ianchakeres** [comment]
@shenshouer - `volumeMode` is part of the alpha feature-gate `BlockVolume`. Have you purposely enabled this feature-gate or all alpha feature-gates?

FYI: @jsafrane

**Comment by shenshouer** [comment]
@ianchakeres Tks, It worked fine for me when  I enabled the feature-gates on apiserver and kubelet
