### ISSUE TITLE
Ceph rbd: Unable to mount volumes for pod "test-pod_default(70d0fcd8-2db0-11e8-9e47-ecf4bbdbf21c)": timeout expired waiting for volumes to attach/mount for pod "default"/"test-pod". list of unattached/unmounted volumes=[pvc]

### ISSUE THREAD

**Issue by dunv-viosoft** [kubernetes-incubator/external-storage#678]

**Comment by dunv-viosoft** [comment]
I am trying to create pod on kuberenetes

**Comment by nagapavan** [comment]
I believe you have configured DNS name with following Syntax.
`yourEFSsystemID.efs.yourEFSregion.amazonaws.com`
Please confirm: `yourEFSsystemID` value follows the syntax "availabilityZone.fileSystemId"
I had the problem resolved by suffixing availabilityZone

**Comment by dunv-viosoft** [comment]
Hi nagapavan,  I used kubernetes and ceph storages on bare metal

**Comment by nagapavan** [comment]
@dunv-viosoft Ok. The error suggests the connectivity problem. I am not familiary with Ceph Storage.

**Comment by dunv-viosoft** [comment]
Ok, Thanks @nagapavan

**Comment by ikamman** [comment]
I have the same problem using DigitalOcean Block Storage and version Kubernetes 1.10.0
The volume itself has been created but there is a problem with attaching it to the node.

**Comment by wongma7** [comment]
If possible, when you see this error preserve kubelet logs (of the kubelet the pod is running on) and controller manager logs, those may have more information on why mount it timed out, otherwise it is hard to debug.

/area ceph/rbd
