### ISSUE TITLE
[Question] Can CSI help this project

### ISSUE THREAD

**Issue by gyliu513** [kubernetes-incubator/external-storage#68]
Just a question here, as the CNCF is working on CSI https://docs.google.com/document/d/1JMNVNP-ZHz8cGlnqckOnpJmHF-DNY7IYP-Di7iuVhQI/edit , want to know if the CSI can help this project? Or we already considered this in roadmap?

**Comment by wongma7** [comment]
Kubernetes wants out-of-tree volume plugins and most likely csi will dictate what they end up looking like. 

Volume plugins are provision+mount+attach, and the current state for out-of-tree plugins is: this project's external provisioning stuff handles provision and flex volumes 1.6 handles mount+attach. The current kubernetes-side interface for provisioning/create is not really an interface designed to begin with, it's more just a consequence of the way the PV controller works. The flex interface is not quite stable.

So yes csi will help, it will define a proper interface for volume plugins apparently designed from the "ground up". This project is will adapt to whatever interface kubernetes ends up implementing.

**Comment by gyliu513** [comment]
Good to know, thanks @wongma7
