### ISSUE TITLE
aws-efs provisioner not working

### ISSUE THREAD

**Issue by raviada** [kubernetes-incubator/external-storage#681]
efs-provisioner Container is not starting up, I see the following error. I used deploy/manifest.yaml by replacing the appropriate values. When I was searching for this error, it was suggested to install ```nfs-utils```. Is this package missing?

```MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/e439eafa-2e13-11e8-8502-0a6cd68e025e/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs us-east-1a.fs-2bd61963.efs.us-east-1.amazonaws.com:/ /var/lib/kubelet/pods/e439eafa-2e13-11e8-8502-0a6cd68e025e/volumes/kubernetes.io~nfs/pv-volume Output: Running scope as unit run-r1c1ce1387c43484fa785328677805b18.scope. mount: wrong fs type, bad option, bad superblock on us-east-1a.fs-2bd61963.efs.us-east-1.amazonaws.com:/, missing codepage or helper program, or other error (for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program) In some cases useful info is found in syslog - try dmesg | tail or so.```

**Comment by nachimehta** [comment]
run `sudo apt-get install nfs-common` on your nodes

**Comment by raviada** [comment]
Thank you nachimehta, I was able to run that command on all the nodes in my cluster. Now I am not getting that error, however I am not able to mount the efs.

```Unable to mount volumes for pod "efs-provisioner-68f565bd75-tx4wk_wso2(665d35f1-2e55-11e8-8502-0a6cd68e025e)": timeout expired waiting for volumes to attach/mount for pod "wso2"/"efs-provisioner-68f565bd75-tx4wk". list of unattached/unmounted volumes=[pv-volume]```

Both efs file system and kube cluster are in the same VPC and AZ. I am not sure why it is getting timeout. Are there any setting on efs or nodes I have to do, port configurations etc?

Thanks for your help earlier.

**Comment by nachimehta** [comment]
You also need to have the right ElasticFileStorage policy assigned to your cluster. That might be your problem. I haven't encountered this error.

I also have a problem where the VolumeClaims won't bind, they are just stuck in "pending" state.

**Comment by raviada** [comment]
I added an inbound rule for NFS on the security group
```aws ec2 authorize-security-group-ingress --group-id {SecurityGroupId} --protocol tcp --port 2049 --source-group {SecurityGroupId} --group-owner {OwnerId}```

where as securitygroupid is the sg of EFS.

that got rid the above error.

now efs-provisioner container starts, but when I look at the container logs I am seeing this.

```E0323 06:47:56.393308       1 reflector.go:201] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:412: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:wso2:default" cannot list persistentvolumes at the cluster scope```

is this something related to assigning ElasticFileStorage policy to the cluster? how do I do this?

thanks for resonding so fast.. I am stuck here for a while

**Comment by nachimehta** [comment]
Yes that looks like a policy problem. Try logging into your node and manually mounting on the box itself first.

**Comment by raviada** [comment]
Hi nachimehta, I got the provisioner working now, but PVC status is still says pending. Any ideas?

**Comment by nachimehta** [comment]
That’s exactly the place I’m stuck. I’ll let you know if I make any progress today.

**Comment by nachimehta** [comment]
Can you post your manifest.yml? I think I've found the answer. The provisioner name needs to match in both the PVC and the Storage-Class

**Comment by raviada** [comment]
Thank you, that was it. I changed the name in one place but not in the claim, I corrected it, its working now.

**Comment by nachimehta** [comment]
Great, glad it worked for you. You should close the PR then.

**Comment by raviada** [comment]
thanks for all the help
