### ISSUE TITLE
local-volume: provisioner image v2.1.0: User Guide fails 

### ISSUE THREAD

**Issue by tobiajo** [kubernetes-incubator/external-storage#685]
Using k8s 1.9 on baremetal.

When generating manifests according to the User Guide example: https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume#user-guide

And then deploying the provisioner, there is some error in the PV:s automatically created for found volumes. I get the following error with provisioner image `v2.1.0`:
```
I0326 15:47:11.251910       1 discovery.go:253] Found new volume of volumeMode "Filesystem" at host path "/mnt/disks/katt" with capacity 1023303680, creating Local PV "local-pv-9de1517a"
E0326 15:47:11.256576       1 discovery.go:277] Error creating PV "local-pv-9de1517a" for volume at "/mnt/disks/katt": PersistentVolume "local-pv-9de1517a" is invalid: metadata.annotations: Required value: Local volume requires node affinity
```
That is a failed call to `APIUtil.CreatePV(pvSpec)` or in other words; the k8s API complains about the generated PV manifest.

I see that it is much code changes in involved source files since the README was last updates, so maybe it is just that the README that is not up to date?

Anyhow I can successfully follow the User Guide if i change the version of `quay.io/external_storage/local-volume-provisioner` in the generated manifests to `v2.0.0`. Then I get "better" output:
```
I0326 15:50:15.333118       1 discovery.go:207] Found new volume of volumeType "file" at host path "/mnt/disks/katt" with capacity 1023303680, creating Local PV "local-pv-9de1517a"
I0326 15:50:15.349776       1 cache.go:55] Added pv "local-pv-9de1517a" to cache
I0326 15:50:15.350360       1 discovery.go:225] Created PV "local-pv-9de1517a" for volume at "/mnt/disks/katt"
I0326 15:50:15.359884       1 cache.go:64] Updated pv "local-pv-9de1517a" to cache
```

**Comment by msau42** [comment]
Hi, v2.1 0 uses the beta nodeAffinity API by default, which is only available starting 1.10.  You need to pass the alpha API flag into the provisioner if you want to use v2.1.0 against an older cluster.

Unfortunately my readme updates have not been merged yet.
https://github.com/kubernetes-incubator/external-storage/pull/613

**Comment by msau42** [comment]
@tobiajo Updated README and CHANGELOG for v2.1.0 has been merged.  Could you try those new instructions and see if it works?

**Comment by tobiajo** [comment]
@msau42 I don't understand what the following implies:

> Running provisioner v2.1.0 or later against a Kubernetes cluster prior to v1.10 requires setting the `useAlphaAPI` configMap parameter to use the alpha API.

What configMap?

**Comment by msau42** [comment]
When you deploy the provisioner, you also have to specify the configmap it uses.  That configmap needs to set the useAlphaAPI flag to get the provisioner to work on K8s < 1.10.

The other alternative I am thinking, which probably will be a lot easier to document and understand, is to say provisioner v2.1.0 only works with K8s >= 1.10

**Comment by tobiajo** [comment]
IMO that depends on if the Helm chart aspires to be backwards compatible. Since we in this case needs to manually modify a manifest templated with Helm.

**Comment by msau42** [comment]
Yeah, I'm thinking in general, it's going to get too difficult to document all the different compatibility behaviors between provisioner version and K8s versions.  The local pv feature in general depends on many other independent features with their own timelines, and I think trying to support all the permutations is going to be difficult for developers to maintain and document, and also for users to understand.

**Comment by tobiajo** [comment]
I agree, but is there any reason why the `useAlphaAPI` flag is not included in the Helm chart? It would also be good to include the StorageClass in the chart. I think the README can be cut back in favour for an up-to-date Helm chart.

**Comment by msau42** [comment]
Ah I see what you mean.  @NickrenREN or @sbezverk could one of you look into adding the new `useAlphaAPI` flag and an example StorageClass into the helm chart?

**Comment by msau42** [comment]
Cleaning up the README here: https://github.com/kubernetes-incubator/external-storage/pull/690

But let's still update the helm chart too for the new options and StorageClass.
