### ISSUE TITLE
[local-volume] Documentation and easier way to update provisioner version throughout the repo

### ISSUE THREAD

**Issue by ianchakeres** [kubernetes-incubator/external-storage#701]
We should simplify the process of updating documentation, configuration, and examples when we update the local-volume provisioner version

For example, we recently moved from v2.0.0 to v2.1.0 and yet some of our input for code generation and example code referenced the wrong version or `latest`.

This issue could be resolved with documentation, refactoring (e.g. making image versions configurable in our helm charts), and other means.

**Comment by msau42** [comment]
Migrating to https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/9
