### ISSUE TITLE
Provisioner interface does not pass StorageClass parameters to Delete

### ISSUE THREAD

**Issue by KnicKnic** [kubernetes-incubator/external-storage#703]
The provisioner interface passes the StorageClass parameters into Provision, but does not pass them into delete. Is there a reason for this? Is there a case where sometimes there is not the ability to pass the StorageClass parameters into delete? 

What is the recommendation if these parameters are needed? 

1. Put the parameters you need to delete in the volume object during provisioning?
2. Query the class parameters during delete?
3. Other?

**Comment by msau42** [comment]
Can you comment on your use case for what StorageClass parameters you need at delete time?  StorageClass parameters have primarily been used to specifying creation options.  During deletion, all the information necessary should be in the PV object.

**Comment by KnicKnic** [comment]
When carving out storage on a remote server I need to know the local path on the server to carve it out from. So I put that in the StorageClass, I also need to know that same local path to remove the resource from the pool when freeing the data. 

I assumed since the data was already available on the storage class to just pass it again during delete. But I can instead duplicate it on the PV. 

This makes sense to me now that I think about it for longer, in that the information will live to cleanup the resource even if someone removes the storage class.
