### ISSUE TITLE
[efs-provisioner] Support TLS encryption

### ISSUE THREAD

**Issue by gtie** [kubernetes-incubator/external-storage#725]
AWS have released an EFS mount helper that enables encryption in transit - https://aws.amazon.com/blogs/aws/new-encryption-of-data-in-transit-for-amazon-efs/

Using the "tls" option (where supported) be implemented and documented.

**Comment by gregsidelinger** [comment]
Is any work being done on this as I have a requirement to enable TLS in order to use EFS in kube?

**Comment by wongma7** [comment]
Not yet. I have not had the time to see how the mount helper works. Kubernetes is the one mounting shares, not the provisioner, and I don't think it's currently possible to tell it to mount with `-t efs` instead of `-t nfs`, so changes may be needed upstream.

**Comment by wongma7** [comment]
If it proves impossible, something like an EFS CSI driver that bundles the mount helper and calls NodePublish with `mount -t efs` will need to be written. I wonder if anybody is working on that.

**Comment by wongma7** [comment]
Amazon is writing a CSI driver https://github.com/aws/aws-efs-csi-driver

**Comment by nano2nd** [comment]
Was support for this ever added?

**Comment by Vlaaaaaaad** [comment]
@nano2nd yup, in https://github.com/kubernetes-sigs/aws-efs-csi-driver which is kind of the evolution of the efs-provisioner.
