### ISSUE TITLE
[glusterfs-simple-provisioner] docker image has a problem.

### ISSUE THREAD

**Issue by singhwx** [kubernetes-incubator/external-storage#729]
Docker version is 1.13.1.
Docker images is [quay.io/external_storage/glusterfs-simple-provisioner:latest].
I used the docker image to find the error.The error is as follows：
standard_init_linux.go:178: exec user process caused "no such file or directory"

**Comment by ianchakeres** [comment]
FYI: @yuanying

**Comment by yuanying** [comment]
I already fixed this issue, but docker image isn't updated. https://github.com/kubernetes-incubator/external-storage/pull/314

**Comment by ianchakeres** [comment]
@wongma7 - can you please update the docker image?

**Comment by wongma7** [comment]
updated today, https://quay.io/repository/external_storage/glusterfs-simple-provisioner?tab=tags
