### ISSUE TITLE
[glusterblock-provisioner] gluster-block mode has a problem.

### ISSUE THREAD

**Issue by singhwang** [kubernetes-incubator/external-storage#731]
This is what it says in the document:
gluster-block mode : This is an experimental or test mode on which the provisioner will directly talk to gluster-block utility or command line interface of gluster-block.

Preliminary judgment, gluster-block utility is not installed in the docker image [quay.io/external_storage/glusterblock-provisioner:latest]. I found the following wrong information in my use. Personally, I feel that this way can not be realized.Because gluster-block needs to be executed in containers running with gluster-blockd processes, and gluster-blockd depends on glusterd. It needs to be clustered in glusterfs. Do we need to add containers running the program to the glusterfs cluster? If I am wrong in understanding, ask the professional to correct.

The following wrong information is :
**E0417 08:39:31.133443       1 glusterblock-provisioner.go:387] command &{gluster-block [gluster-block create block-test/dept-dev_default_claim1_d8f53aaa-421a-11e8-8d03-965ec404bb2b ha 3 192.168.1.167 1GB --json] []  <nil>   [] <nil> <nil> <nil> <nil> 0xc4202d2e40 false [] [] [] [] <nil> <nil>} failed,exec: "gluster-block": executable file not found in $PATH**

**Comment by wongma7** [comment]
@humblec strange error '"gluster-block": executable file not found in $PATH'

/area gluster/block
