### ISSUE TITLE
 Unable to mount volumes for pod

### ISSUE THREAD

**Issue by ikamman** [kubernetes-incubator/external-storage#732]
I have problem with attaching volume to the pod, error:

` Unable to mount volumes for pod "task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)": timeout expired waiting for volumes to attach or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]`

I use DigitalOcean BS and Kubernates 1.10.0. The volumes were provisioned but is problem with mouinting them to the pod.

journalctl -u kubelet:

`

Apr 18 14:08:14 one-worker-1 kubelet-wrapper[874]: E0418 14:08:14.350339     874 nestedpendingoperations.go:267] Operation for "\"flexvolume-external-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\"" failed. No retries per
mitted until 2018-04-18 14:10:16.350287248 +0000 UTC m=+5062.605695579 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\" (UniqueName: \"flexvolume-ext
ernal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\") pod \"task-pv-pod\" (UID: \"ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3\") "
Apr 18 14:09:52 one-worker-1 kubelet-wrapper[874]: E0418 14:09:52.807550     874 kubelet.go:1635] Unable to mount volumes for pod "task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)": timeout expired waiting for volumes to attach
or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]; skipping pod
Apr 18 14:09:52 one-worker-1 kubelet-wrapper[874]: E0418 14:09:52.808591     874 pod_workers.go:186] Error syncing pod ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3 ("task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)"), skipping: timeout
expired waiting for volumes to attach or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]
Apr 18 14:10:04 one-worker-1 kubelet-wrapper[874]: W0418 14:10:04.885784     874 plugin-defaults.go:32] flexVolume driver external-storage/digitalocean: using default GetVolumeName for volume pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3
Apr 18 14:10:16 one-worker-1 kubelet-wrapper[874]: I0418 14:10:16.437649     874 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3" (UniqueName: "flexvolume-e
xternal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3") pod "task-pv-pod" (UID: "ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3")
Apr 18 14:10:16 one-worker-1 kubelet-wrapper[874]: E0418 14:10:16.444120     874 nestedpendingoperations.go:267] Operation for "\"flexvolume-external-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\"" failed. No retries per
mitted until 2018-04-18 14:12:18.444064013 +0000 UTC m=+5184.699472336 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\" (UniqueName: \"flexvolume-ext
ernal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\") pod \"task-pv-pod\" (UID: \"ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3\") "
Apr 18 14:12:07 one-worker-1 kubelet-wrapper[874]: E0418 14:12:07.810221     874 kubelet.go:1635] Unable to mount volumes for pod "task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)": timeout expired waiting for volumes to attach
or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]; skipping pod
Apr 18 14:12:07 one-worker-1 kubelet-wrapper[874]: E0418 14:12:07.811333     874 pod_workers.go:186] Error syncing pod ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3 ("task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)"), skipping: timeout
expired waiting for volumes to attach or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]
Apr 18 14:12:18 one-worker-1 kubelet-wrapper[874]: I0418 14:12:18.515150     874 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3" (UniqueName: "flexvolume-e
xternal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3") pod "task-pv-pod" (UID: "ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3")
Apr 18 14:12:18 one-worker-1 kubelet-wrapper[874]: E0418 14:12:18.521109     874 nestedpendingoperations.go:267] Operation for "\"flexvolume-external-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\"" failed. No retries per
mitted until 2018-04-18 14:14:20.52104056 +0000 UTC m=+5306.776448881 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\" (UniqueName: \"flexvolume-exte
rnal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\") pod \"task-pv-pod\" (UID: \"ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3\") "
Apr 18 14:12:19 one-worker-1 kubelet-wrapper[874]: W0418 14:12:19.823900     874 plugin-defaults.go:32] flexVolume driver external-storage/digitalocean: using default GetVolumeName for volume pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3
Apr 18 14:14:20 one-worker-1 kubelet-wrapper[874]: I0418 14:14:20.578729     874 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3" (UniqueName: "flexvolume-e
xternal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3") pod "task-pv-pod" (UID: "ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3")
Apr 18 14:14:20 one-worker-1 kubelet-wrapper[874]: E0418 14:14:20.584132     874 nestedpendingoperations.go:267] Operation for "\"flexvolume-external-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\"" failed. No retries per
mitted until 2018-04-18 14:16:22.584058402 +0000 UTC m=+5428.839466710 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\" (UniqueName: \"flexvolume-ext
ernal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\") pod \"task-pv-pod\" (UID: \"ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3\") "
Apr 18 14:14:22 one-worker-1 kubelet-wrapper[874]: E0418 14:14:22.803642     874 kubelet.go:1635] Unable to mount volumes for pod "task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)": timeout expired waiting for volumes to attach
or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]; skipping pod
Apr 18 14:14:22 one-worker-1 kubelet-wrapper[874]: E0418 14:14:22.804595     874 pod_workers.go:186] Error syncing pod ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3 ("task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)"), skipping: timeout
expired waiting for volumes to attach or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]
Apr 18 14:14:35 one-worker-1 kubelet-wrapper[874]: W0418 14:14:35.884904     874 plugin-defaults.go:32] flexVolume driver external-storage/digitalocean: using default GetVolumeName for volume pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3
Apr 18 14:16:22 one-worker-1 kubelet-wrapper[874]: I0418 14:16:22.598989     874 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3" (UniqueName: "flexvolume-e
xternal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3") pod "task-pv-pod" (UID: "ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3")
Apr 18 14:16:22 one-worker-1 kubelet-wrapper[874]: E0418 14:16:22.604595     874 nestedpendingoperations.go:267] Operation for "\"flexvolume-external-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\"" failed. No retries per
mitted until 2018-04-18 14:18:24.604534563 +0000 UTC m=+5550.859942884 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\" (UniqueName: \"flexvolume-ext
ernal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\") pod \"task-pv-pod\" (UID: \"ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3\") "
Apr 18 14:16:38 one-worker-1 kubelet-wrapper[874]: E0418 14:16:38.803787     874 kubelet.go:1635] Unable to mount volumes for pod "task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)": timeout expired waiting for volumes to attach
or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]; skipping pod
Apr 18 14:16:38 one-worker-1 kubelet-wrapper[874]: E0418 14:16:38.804803     874 pod_workers.go:186] Error syncing pod ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3 ("task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)"), skipping: timeout
expired waiting for volumes to attach or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]
Apr 18 14:16:52 one-worker-1 kubelet-wrapper[874]: W0418 14:16:52.861744     874 plugin-defaults.go:32] flexVolume driver external-storage/digitalocean: using default GetVolumeName for volume pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3
Apr 18 14:18:24 one-worker-1 kubelet-wrapper[874]: I0418 14:18:24.673427     874 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3" (UniqueName: "flexvolume-e
xternal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3") pod "task-pv-pod" (UID: "ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3")
Apr 18 14:18:24 one-worker-1 kubelet-wrapper[874]: E0418 14:18:24.692276     874 nestedpendingoperations.go:267] Operation for "\"flexvolume-external-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\"" failed. No retries per
mitted until 2018-04-18 14:20:26.692205801 +0000 UTC m=+5672.947614125 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\" (UniqueName: \"flexvolume-ext
ernal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\") pod \"task-pv-pod\" (UID: \"ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3\") "
Apr 18 14:18:55 one-worker-1 kubelet-wrapper[874]: E0418 14:18:55.810854     874 kubelet.go:1635] Unable to mount volumes for pod "task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)": timeout expired waiting for volumes to attach
or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]; skipping pod
Apr 18 14:18:55 one-worker-1 kubelet-wrapper[874]: E0418 14:18:55.811983     874 pod_workers.go:186] Error syncing pod ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3 ("task-pv-pod_default(ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3)"), skipping: timeout
expired waiting for volumes to attach or mount for pod "default"/"task-pv-pod". list of unmounted volumes=[task-pv-storage]. list of unattached volumes=[task-pv-storage default-token-vdjnp]
Apr 18 14:19:10 one-worker-1 kubelet-wrapper[874]: W0418 14:19:10.833104     874 plugin-defaults.go:32] flexVolume driver external-storage/digitalocean: using default GetVolumeName for volume pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3
Apr 18 14:20:26 one-worker-1 kubelet-wrapper[874]: I0418 14:20:26.721815     874 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3" (UniqueName: "flexvolume-e
xternal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3") pod "task-pv-pod" (UID: "ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3")
Apr 18 14:20:26 one-worker-1 kubelet-wrapper[874]: E0418 14:20:26.730202     874 nestedpendingoperations.go:267] Operation for "\"flexvolume-external-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\"" failed. No retries per
mitted until 2018-04-18 14:22:28.730129991 +0000 UTC m=+5794.985538331 (durationBeforeRetry 2m2s). Error: "Volume not attached according to node status for volume \"pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\" (UniqueName: \"flexvolume-ext
ernal-storage/digitalocean/pvc-badc3bc8-430c-11e8-88ae-1a7ea0a0c4c3\") pod \"task-pv-pod\" (UID: \"ce5880a5-430c-11e8-88ae-1a7ea0a0c4c3\") "

`

**Comment by klausenbusk** [comment]
> @klausenbusk if you have time to look

Sure. (BTW: We should add a issue template, so people remember to add the correct label and tag the owner).

@ikamman How did you create the k8s cluster? As @wongma7 mentioned, it is probably related to the flexvolume driver.

**Comment by klausenbusk** [comment]
@wongma7 could you close this issue?

@ikamman Please try the official [DigitalOcean CSI driver](https://github.com/digitalocean/csi-digitalocean), if you still have issues. It is [recommended](https://github.com/kubernetes-incubator/external-storage/pull/858) for new clusters.
