### ISSUE TITLE
Does possible to restrict concurrent provision operations started by controller?

### ISSUE THREAD

**Issue by Nefelim4ag** [kubernetes-incubator/external-storage#733]
I use your lib/controller for writing own flex-provisioner, all works,
but one problem exist - memory usage.

While deploy apps with PVC to K8S, many not bound pvc can be created at one time.
That causes to spike memory usage by provisioner, because controller try run provision operation for **every one** not bound pvc at one time.

Example:
For one pvc at time, provisioner use ~60-80 Mb of RAM, for 10 pvc, around ~300 Mb of RAM.

I look at controller code and not found any interface to restrict count of concurrently running provision operations, does not found a way to serialize them.

Do i miss something?

Thanks, for any info.

**Comment by wongma7** [comment]
No, it's not possible and you're right it is not optimized. Scaling is a problem. Let's track general improvements here https://github.com/kubernetes-incubator/external-storage/issues/812
