### ISSUE TITLE
Local volume provisioner should persist local PV states on the node as a safety measure

### ISSUE THREAD

**Issue by dhirajh** [kubernetes-incubator/external-storage#739]
**Motivation**
The metadata stored in Kubernetes w.r.t local PVs is critical in keeping track of local volumes that are in use. They effectively hold the keys to potentially petabytes of critical data. Any loss of data in etcd due to admin or config errors (this has actually happened) of that metadata effectively causes loss of data in disks at scale. While one could argue this issue exists with other forms PVs in Kubernetes, the fact is many of those other forms of scale out storage like ceph and ebs maintain their own metadata on volumes that can potentially be used to track and recover.

This request suggests adding some minimum bookkeeping locally on the node as a safety mechanism. As shown below, by doing this minimal bookkeeping, we not only protect against the above disastrous scenario, but in addition the LV provisioner becomes smarter and is able to alert on PV transitions that happened without its normal (and expected) involvement.

**Implementation**

The LV provisioner on each node would track the following information in a local file (lets call it "ledger") for all the volumes on that node. This ledger file would be kept simple and human readable. 

- When a volume  is first discovered and PV is created for it, the PV creation is recorded in the local ledger.  
- When the PV is bound (something that the provisioner can detect already), the PV information is updated in the ledger.
- When a PV is found to be in Released state, this state change is updated in the ledger as part of the cleaning action that provisioner usually initiates at this stage.
- When a PV is deleted, the file is again updated to indicate that it was deleted as the provisioner does the PV deletion.

The ledger can be used by the PV provisioner in the following manner:

1. If the Provisioner is about to create a PV for a volume and  the ledger indicates that the last known state of a PV is "bound", then the provision will refuse to create a new PV for that volume. This is because the provisioner would have certainly updated the file entry to "deleted" state or atleast to "released" state, if the volume had made its way through the regular cleaning and PV deletion process. The fact that a PV does not exist after last being known to be in "bound" state indicates something has gone seriously wrong with the PV metadata and requires investigation by admin.

2. If the ledger records that the last known state of a PV is "released", and the provisioner discovers that no PV exists for the volume, then it could either (based on configmap setting)

    - Refuse to create a PV since the normal process was not followed.

    - Notify through log message or event or metrics that a PV is being created without the normal cleanup process. This option is set for a site if the admin is in the habit of deleting PVs when they are still being cleaned for various reasons (including errors in the cleaning process or due to the process taking too long).

3. Apart from preventing accidental re-use of PVs as shown in 1 and 2,  the admin can actually recreate PVs (in the event of metadata loss) and use the "bound" information in the ledger file to re-create the PVC bindings either manually or by writing a simple tool to do so (assuming the PVCs still exist or can be recreated).  This metadata is very valuable in threading back applications and the disks they were using before the failure. In case of a widespread loss, one could even implement such a tool to run as a daemonset to execute this recovery process across all nodes. Please note that the scope of this request **_does not_** include building such a tool. It only suggests recording the data necessary to build such a tool. 

Note that the distributed nature of storage this information (locally on each node) makes the approach fairly robust in terms of avoiding large scale loss of metadata. Also note that these changes are backward compatible - The behavior described above only kicks in when ledger entries are found. If ledger entries are absent (or if the ledger itself is absent), the provisioner behaves the way it currently does.

**Comment by dhirajh** [comment]
cc @msau42

**Comment by dhirajh** [comment]
Yes, it will have an in-memory copy, as we assume that LC provisioner is the only write. The disk access will mostly be to persist changes.

**Comment by msau42** [comment]
Migrating issue to new repo: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/11
/close
