### ISSUE TITLE
 fail to check rbd image status with: (executable file not found in $PATH), rbd output: ()

### ISSUE THREAD

**Issue by 13567436138** [kubernetes-incubator/external-storage#750]
```
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   SuccessfulMountVolume   3m                kubelet, node8           MountVolume.SetUp succeeded for volume "adminserver-key"
  Normal   SuccessfulMountVolume   3m                kubelet, node8           MountVolume.SetUp succeeded for volume "default-token-vdn9l"
  Warning  FailedScheduling        3m (x4 over 3m)   default-scheduler        pod has unbound PersistentVolumeClaims (repeated 7 times)
  Normal   Scheduled               2m                default-scheduler        Successfully assigned harbor-harbor-adminserver-0 to node8
  Normal   SuccessfulAttachVolume  2m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-8e60c71d-4ddc-11e8-8c57-002197403677"
  Warning  FailedMount             1m                kubelet, node8           Unable to mount volumes for pod "harbor-harbor-adminserver-0_harbor(8e676196-4ddc-11e8-8c57-002197403677)": timeout expired waiting for volumes to attach or mount for pod "harbor"/"harbor-harbor-adminserver-0". list of unmounted volumes=[adminserver-config]. list of unattached volumes=[adminserver-config adminserver-key default-token-vdn9l]
  Warning  FailedMount             55s (x9 over 3m)  kubelet, node8           MountVolume.WaitForAttach failed for volume "pvc-8e60c71d-4ddc-11e8-8c57-002197403677" : fail to check rbd image status with: (executable file not found in $PATH), rbd output: ()
```

**Comment by ianchakeres** [comment]
Is `rbd` installed on the host? [install-link](http://docs.ceph.com/docs/master/install/)

**Comment by 13567436138** [comment]
# [root@node1 rook]# kubectl get pod -n ceph
NAME                              READY     STATUS    RESTARTS   AGE
rbd-provisioner-bc956f5b4-r2vg4   1/1       Running   0          22h

I installed rdb provisioner,do I still need to install rbd

**Comment by 13567436138** [comment]
[root@node1 rook]# kubectl get pod -n rook-system
NAME                             READY     STATUS    RESTARTS   AGE
rook-agent-7d2tc                 1/1       Running   0          4d
rook-agent-cqfzp                 1/1       Running   0          4d
rook-agent-qjmlc                 1/1       Running   0          4d
rook-operator-5c89ff9496-fc454   1/1       Running   0          4d

[root@node1 rook]# kubectl get pod -n rook
NAME                              READY     STATUS    RESTARTS   AGE
rook-ceph-mgr0-76f46f77f6-tzl7h   1/1       Running   0          4d
rook-ceph-mon0-tpxrm              1/1       Running   0          4d
rook-ceph-mon1-cr699              1/1       Running   0          4d
rook-ceph-mon2-9hl7t              1/1       Running   0          4d
rook-ceph-osd-node2-tff9q         1/1       Running   0          4d
rook-ceph-osd-node3-l7vgs         1/1       Running   0          4d
rook-ceph-osd-node4-s8w4h         1/1       Running   0          4d
rook-tools                        1/1       Running   0          4d

**Comment by 13567436138** [comment]
use rook instead
