### ISSUE TITLE
Snapshot controller silently stops running

### ISSUE THREAD

**Issue by disrani-px** [kubernetes-incubator/external-storage#751]
Noticed that sometimes the snapshot controller silently stops watching for new objects. This causes new snapshots to be stuck in pending state until the snapshotter pod is restarted.

/area snapshot

**Comment by tsmetana** [comment]
Is there some logs or some action preceding the failure?

**Comment by disrani-px** [comment]
No, there were no messages in the log apart from the startup logs. The controller seems to start goroutines which aren't monitored and doesn't seem to log when they fail.
