### ISSUE TITLE
[nfs-client-provisioner]PVC pending state

### ISSUE THREAD

**Issue by diewuq** [kubernetes-incubator/external-storage#754]
Hi,

Currently I'm trying to get the nfs-client-provisioner running on k8s v1.10.1, and use your giving yaml for testing with rbac. As I deploy test-claim.yaml, PVC always pending with below info:

Normal  ExternalProvisioning  2m (x143 over 37m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "fuserim.pri/ifs" or manually created by system administrator

I check pod nfs-client-provisioner, it is successful:
root@k8s-master1:/data/nfs_file# kubectl logs nfs-client-provisioner-5bff76dd6c-j2mpg
I0507 07:22:12.743160       1 controller.go:407] Starting provisioner controller 5c858a43-51c7-11e8-84df-0a580af40124!
I also refer #174, link " https://kubernetes.io/docs/admin/kube-controller-manager/ " is expired , and I check with kube-controller-manager.yaml, --controllers like below:
  - --controllers=*,bootstrapsigner,tokencleaner

I don't know whether this is the issue. Anyone can help? Thanks in advance.

**Comment by futurama92** [comment]
Hi, mee too i'm stuck here, the pvc is pending state. I try both quick start and the normal mode

**Comment by dragon9783** [comment]
same issue to me, i also deploy openebs provisioner, and it work well

**Comment by wongma7** [comment]
Is that the full log of the provisioner? Can you provide it if not

/area nfs-client

**Comment by jrfeenst** [comment]
I have the same issue. The log (-v 4) shows nothing interesting:

I0625 13:00:02.214122       1 controller.go:492] Starting provisioner controller ac4f591d-7877-11e8-8e50-0a58c0a80305!
I0625 13:00:02.214962       1 reflector.go:202] Starting reflector *v1.PersistentVolumeClaim (15s) from github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:496
I0625 13:00:02.215061       1 reflector.go:240] Listing and watching *v1.PersistentVolumeClaim from github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:496
I0625 13:00:02.215163       1 reflector.go:202] Starting reflector *v1.PersistentVolume (15s) from github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:497
I0625 13:00:02.215192       1 reflector.go:240] Listing and watching *v1.PersistentVolume from github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:497
I0625 13:00:02.216170       1 reflector.go:202] Starting reflector *v1.StorageClass (15s) from github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:498
I0625 13:00:02.216273       1 reflector.go:240] Listing and watching *v1.StorageClass from github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:498
I0625 13:00:17.221821       1 reflector.go:286] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:498: forcing resync
I0625 13:00:17.229086       1 reflector.go:286] github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:496: forcing resync

**Comment by mostlyAtNight** [comment]
Hello - I have the same issue (PVC stuck in Pending state).  

Logs (for the pod) do not show much:

```
W0628 09:37:15.045679       1 efs-provisioner.go:86] couldn't confirm that the EFS file system exists: AccessDeniedException: User: arn:aws:sts::433835555346:assumed-role/eks-sandpit-01-worker-nodes-NodeInstanceRole-AZUYA99QG92C/i-06832ac3659b22ca0 is not authorized to perform: elasticfilesystem:DescribeFileSystems on the specified resource
	status code: 403, request id: d757ebaf-7ab6-11e8-901a-91e9a34a399e
I0628 09:37:15.047517       1 controller.go:492] Starting provisioner controller d75a58ef-7ab6-11e8-9ea8-66d5a8a809a1! 
```

How can I get further information to help debugging this issue?

One other thing:  I;m running on Amazon EKS (quite new) and had to install nfs-utils on the nodes as it was not installed by default.  Perhaps the issue is related and there is some other missing software there?

Kind regards, Pete

**Comment by mostlyAtNight** [comment]
Strangely it's now working as expected, things I changed:

- Set up everything (ConfigMap, Deployment, StorageClass) via a single manifest file
  - I modified the manifest file to contain the serviceAccount patch mentioned in the docs
- Did the above after deleting any leftovers from previous attempts (with the exception of the RBAC permissions modifications)
- Applied the manifest file

The PVCs now bind properly and are not stuck in the Pending state - perhaps it's something to do with the container not liking starting out in a different serviceAccount and then being subsequently patched?

...

**Comment by wongma7** [comment]
If it were a serviceAccount misconfiguration I would expect to see many permission denied errors in the log. So I am still perplexed!

**Comment by nagapavan** [comment]
stuck for me too. Describe log for PVC:
```bash

# kubectl describe pvc efs
Name:          efs
Namespace:     default
StorageClass:  aws-efs
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class=aws-efs
               volume.beta.kubernetes.io/storage-provisioner=example.com/aws-efs
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  ExternalProvisioning  1m (x62 over 16m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "example.com/aws-efs" or manually created by system administrator
```
Looks like the functionality from Documentation: `When you create a claim that asks for the class, a volume will be automatically created.`  is no longer working.

**Comment by matthieudolci** [comment]
We had the same issue with efs and eks using the aws eks Ami for the nodes, we solved it by using `amazon-efs-utils` instead of `nfs-utils`

**Comment by Youhana-Hana** [comment]
I have the same pvc pending issue

Name:          efs
Namespace:     default
StorageClass:  aws-efs
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"aws-efs"},"name":"efs","namespa..
               volume.beta.kubernetes.io/storage-class=aws-efs
               volume.beta.kubernetes.io/storage-provisioner=example.com/aws-efs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  ExternalProvisioning  1m (x61 over 16m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "example.com/aws-efs" or manually created by system administrator

**Comment by pictolearn** [comment]
I came across the same issue using KOPS.  I have followed whatever was specified in the docs and also used the following as a reference https://medium.com/@while1eq1/using-amazon-efs-in-a-multiaz-kubernetes-setup-57922e032776 but my pod file look different with an nginx instance trying to mount to the EFS cluster

```
$ kubectl describe pvc efs
Name:          efs
Namespace:     default
StorageClass:  aws-efs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"aws-efs"},"name":"efs","namespa...
               volume.beta.kubernetes.io/storage-class=aws-efs
               volume.beta.kubernetes.io/storage-provisioner=example.com/aws-efs
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  ExternalProvisioning  3m (x203 over 54m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "example.com/aws-efs" or manually created by system administrator
```
here is a sample nginx yaml which i used to test
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs
          mountPath: /usr/share/nginx/html
      volumes:
        - name: efs
          persistentVolumeClaim:
            claimName: efs
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

$ kops version
Version 1.9.1
```

**Comment by wongma7** [comment]
Can you confirm the provisioner log looks the same as above (i.e. it is basically empty) https://github.com/kubernetes-incubator/external-storage/issues/754#issuecomment-399945726 ? What if you try a newer/older image? https://quay.io/repository/external_storage/efs-provisioner?tab=tags (What version are you using now?)

**Comment by nagapavan** [comment]
I resolved the problem by creating PV volume before PVC.

**Comment by pictolearn** [comment]
I tried the same to create a PV before a PVC, did not work. Not sure if it has anything to do with the order.

**Comment by gargankur74** [comment]
I am using EKS and installed amazon-efs-utils on each individual host but still getting timeout error with mount. Attached are the logs:
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:16:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl describe pod efs-provisioner-85576f79f7-sjkcz
Name:           efs-provisioner-85576f79f7-sjkcz
Namespace:      default
Node:           ip-192-168-253-54.us-west-2.compute.internal/192.168.253.54
Start Time:     Sat, 28 Jul 2018 17:59:22 +0530
Labels:         app=efs-provisioner
                pod-template-hash=4113293593
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/efs-provisioner-85576f79f7
Containers:
  efs-provisioner:
    Container ID:   
    Image:          quay.io/external_storage/efs-provisioner:latest
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      FILE_SYSTEM_ID:         <set to the key 'file.system.id' of config map 'efs-provisioner'>     Optional: false
      AWS_REGION:             <set to the key 'aws.region' of config map 'efs-provisioner'>         Optional: false
      PROVISIONER_NAME:       <set to the key 'provisioner.name' of config map 'efs-provisioner'>   Optional: false
      AWS_ACCESS_KEY_ID:      <set to the key 'aws-access-key-id' in secret 'aws-credentials'>      Optional: false
      AWS_SECRET_ACCESS_KEY:  <set to the key 'aws-secret-access-key' in secret 'aws-credentials'>  Optional: false
    Mounts:
      /persistentvolumes from pv-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7q2p9 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  pv-volume:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    fs-04f5b0ad.efs.us-west-2.amazonaws.com
    Path:      /
    ReadOnly:  false
  default-token-7q2p9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7q2p9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From                                                   Message
  ----     ------                 ----             ----                                                   -------
  Normal   Scheduled              6m               default-scheduler                                      Successfully assigned efs-provisioner-85576f79f7-sjkcz to ip-192-168-253-54.us-west-2.compute.internal
  Normal   SuccessfulMountVolume  6m               kubelet, ip-192-168-253-54.us-west-2.compute.internal  MountVolume.SetUp succeeded for volume "default-token-7q2p9"
  Warning  FailedMount            1m (x2 over 4m)  kubelet, ip-192-168-253-54.us-west-2.compute.internal  Unable to mount volumes for pod "efs-provisioner-85576f79f7-sjkcz_default(db712b70-9261-11e8-bfd4-06810c0e8922)": timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-85576f79f7-sjkcz". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-7q2p9]
  Warning  FailedMount            1m               kubelet, ip-192-168-253-54.us-west-2.compute.internal  MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/db712b70-9261-11e8-bfd4-06810c0e8922/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-04f5b0ad.efs.us-west-2.amazonaws.com:/ /var/lib/kubelet/pods/db712b70-9261-11e8-bfd4-06810c0e8922/volumes/kubernetes.io~nfs/pv-volume
Output: Running scope as unit run-32301.scope.
mount.nfs: Connection timed out
`

**Comment by gargankur74** [comment]
I am using EKS and getting timeout error while mounting pv-volume. Attached are the logs:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:16:17Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl describe pod efs-provisioner-85576f79f7-sjkcz
Name:           efs-provisioner-85576f79f7-sjkcz
Namespace:      default
Node:           ip-192-168-253-54.us-west-2.compute.internal/192.168.253.54
Start Time:     Sat, 28 Jul 2018 17:59:22 +0530
Labels:         app=efs-provisioner
                pod-template-hash=4113293593
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/efs-provisioner-85576f79f7
Containers:
  efs-provisioner:
    Container ID:   
    Image:          quay.io/external_storage/efs-provisioner:latest
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      FILE_SYSTEM_ID:         <set to the key 'file.system.id' of config map 'efs-provisioner'>     Optional: false
      AWS_REGION:             <set to the key 'aws.region' of config map 'efs-provisioner'>         Optional: false
      PROVISIONER_NAME:       <set to the key 'provisioner.name' of config map 'efs-provisioner'>   Optional: false
      AWS_ACCESS_KEY_ID:      <set to the key 'aws-access-key-id' in secret 'aws-credentials'>      Optional: false
      AWS_SECRET_ACCESS_KEY:  <set to the key 'aws-secret-access-key' in secret 'aws-credentials'>  Optional: false
    Mounts:
      /persistentvolumes from pv-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7q2p9 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  pv-volume:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    fs-04f5b0ad.efs.us-west-2.amazonaws.com
    Path:      /
    ReadOnly:  false
  default-token-7q2p9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7q2p9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From                                                   Message
  ----     ------                 ----             ----                                                   -------
  Normal   Scheduled              6m               default-scheduler                                      Successfully assigned efs-provisioner-85576f79f7-sjkcz to ip-192-168-253-54.us-west-2.compute.internal
  Normal   SuccessfulMountVolume  6m               kubelet, ip-192-168-253-54.us-west-2.compute.internal  MountVolume.SetUp succeeded for volume "default-token-7q2p9"
  Warning  FailedMount            1m (x2 over 4m)  kubelet, ip-192-168-253-54.us-west-2.compute.internal  Unable to mount volumes for pod "efs-provisioner-85576f79f7-sjkcz_default(db712b70-9261-11e8-bfd4-06810c0e8922)": timeout expired waiting for volumes to attach or mount for pod "default"/"efs-provisioner-85576f79f7-sjkcz". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume default-token-7q2p9]
  Warning  FailedMount            1m               kubelet, ip-192-168-253-54.us-west-2.compute.internal  MountVolume.SetUp failed for volume "pv-volume" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/db712b70-9261-11e8-bfd4-06810c0e8922/volumes/kubernetes.io~nfs/pv-volume --scope -- mount -t nfs fs-04f5b0ad.efs.us-west-2.amazonaws.com:/ /var/lib/kubelet/pods/db712b70-9261-11e8-bfd4-06810c0e8922/volumes/kubernetes.io~nfs/pv-volume
Output: Running scope as unit run-32301.scope.
mount.nfs: Connection timed out

```

**Comment by tonybranfort** [comment]
For those getting
```
waiting for a volume to be created, either by external provisioner "example.com/aws-efs" or manually created by system administrator
```
If you're using rbac (which it seems kops does by default), make sure you've created a serviceAccount.  Look at the [deployment.yaml](https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/deploy/deployment.yaml) rather than the [manifest.yaml](https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/deploy/manifest.yaml). 
 
You'll also need [rbac.yaml](https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/deploy/rbac.yaml).  The readme describes this but doesn't mention the service account.

**Comment by ParaSwarm** [comment]
Sigh. This took me all day to figure out. I hope this helps someone save some time:

The issue, for me, was the default service account. It didn't have access to get endpoints. Mind you, this is a fresh EKS cluster install, not running anything special yet.

You can confirm this by exec'ing into your efs-provisioner pod with a shell (you will have to install bash since it's alpine, run "apk add --no-cache bash" and then shell in with /bin/bash). 

Once you're in, run "/efs-provisioner". You may start seeing this output:

> error retrieving resource lock default/example.com-aws-efs: endpoints "example.com-aws-efs" is forbidden: User "system:serviceaccount:default:default" cannot get endpoints in the namespace "default"

If you do, you have the same issue as I did. 

The quick fix is to give the cluster-admin role to the default service account. Of course, depending on your environment and security, you may need a more elaborate fix. If you elect to go the easy way, you can simply apply this:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-admin-rbac (or whatever)
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

After I did this, the output from the provisioner immediately became successful and started creating volumes.

**Comment by mustafaakin** [comment]
There is also RBAC configuration in the repo: https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/deploy/rbac.yaml

**Comment by geerlingguy** [comment]
@ParaSwarm - Thank you _so_ much for posting the detailed guide. Note that for me, I ran `apk add bash` (without the `--no-cache` flag) to make installing bash work without any fancy quoting or other steps.

I am running the provisioner in a namespace (`efs-provisioner`) instead of in the `default` namespace, so I am seeing:

```
E1221 22:10:38.183781      79 leaderelection.go:252] error retrieving resource lock efs-provisioner/acquia.com-aws-efs: endpoints "acquia.com-aws-efs" is forbidden: User "system:serviceaccount:efs-provisioner:default" cannot get endpoints in the namespace "efs-provisioner"
```

I am using the RBAC config from the `external-storage/aws/efs/deploy/rbac.yaml` file (with the `namespace` replaced where needed), but I'm still getting the above errors. I'm trying to debug what is wrong with the RBAC setup...

**Comment by geerlingguy** [comment]
So turns out the issue for me was related to https://github.com/kubernetes-incubator/external-storage/issues/953 — there are some missing rules in the RBAC `ClusterRole` which prevented the `efs-provisioner` service account from being able to do what it needed to do.

Adding the following lines to the rules in the `ClusterRole` fixed it for me:

```yaml
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
```

(see https://github.com/helm/charts/pull/9127/files#diff-1f3ae64e932358240df168628073a894R25)

**Comment by weisjohn** [comment]
@geerlingguy also worked for me, thanks for the great explanation!

**Comment by liozzazhang** [comment]
I think that it's your RBAC configuration issue. If you specify some _namespace_ parameters in your RBAC yaml file, you can refer to this file: https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/deploy/kubernetes/rbac.yaml.  Only specify _namespace_ parameter in ClusterRoleBinding/RoleBingding Subjects section. Also don't forget to add _endpoints_  permission in your ClusterRole resource.

**Comment by PigeonCai** [comment]
thanks

**Comment by wiltonfelix** [comment]
this working to me #65937

**Comment by marcelolima** [comment]
@liozzazhang thanks, that fixed my problem!
