### ISSUE TITLE
Import older PVs into Kubernetes cluster

### ISSUE THREAD

**Issue by kmova** [kubernetes-incubator/external-storage#755]
During the KubeCon EU Storage sessions, there were some questions/requests to enable PV recovery functionality, under the following conditions:
- Stateful applications in the cluster write the data into Persistent Volumes (that live beyond the life of the cluster)
- The cluster gets re-created for one of several ways, maybe as part of the CI/CD pipeline or ondemand job setup. However, when the cluster gets recreated, it would be nice to have the Older Persistent Volumes imported into the cluster. 
- The Stateful applications should connect to these imported volumes, if they are available instead of creating new volumes from scratch. 

Putting in this issue, to track the implementation of an add-on (say recover-pv), that could be launched as part of the cluster setup, which can scan for the PVs from the attached storage.

**Comment by msau42** [comment]
CSI has a ListVolumes call that may work for this purpose

**Comment by msau42** [comment]
One problem to think about though is the disks probably have data on them.  How do we associate them to specific PVCs and storageclasses so that they don't get accidentally used by some other workload?
