### ISSUE TITLE
Make aws-secrets optional?

### ISSUE THREAD

**Issue by andersla** [kubernetes-incubator/external-storage#76]
Thanks for providing the efs external provisioner!
I wonder if providing aws-secrets could be optional (since they only are needed for checking - and if you are confident that your setup is ok then they are not really needed?)

**Comment by wongma7** [comment]
Yes - I envisioned a bigger use for them but there's not much point in keeping them a requirement at the moment .

**Comment by andersla** [comment]
Super! Many thanks!
