### ISSUE TITLE
Can't provision a drive: Invalid character 'U'

### ISSUE THREAD

**Issue by hcabnettek** [kubernetes-incubator/external-storage#761]
If I kubectl describe the pvc, I get this error mesaage.
`Failed to provision volume with StorageClass "default": invalid character 'U' looking for beginning of value`
I used kubeadm to set up the cluster and I used flannel. I tried with and without the flannel RBAC. Same error either way. I have used `doctl` to create volumes with the same api key. I also manually added the nameserver to /etc/resolv.conf on each provisioning pod. Still no difference. I don't see any volume created in the Digital Ocean interface. The pod busy-box is always pending and the pvc is never bound. What might I be doing wrong? Sorry, kind of new to k8s. Thanks.

**Comment by hcabnettek** [comment]
/area digitalocean 
for clarity

**Comment by klausenbusk** [comment]
Could you try running `kubectl get pvc`? I'm wondering if it has something to do with the `StorageClass`? Also could you try with the SC from this PR: https://github.com/kubernetes-incubator/external-storage/pull/718

**Comment by klausenbusk** [comment]
Please either close this issue or provide more information.

`Failed to provision volume with StorageClass "default": invalid character 'U' looking for beginning of value` is probably due to https://github.com/digitalocean/godo/issues/142 which I will fix shortly.

**Comment by klausenbusk** [comment]
@wongma7 This issue also seems to be "stuck". Could you close it?

The `invalid character 'U' looking for beginning of value` error was due to a bug in godo which has been fixed (https://github.com/digitalocean/godo/pull/156). I did push a fixed version yesterday.
