### ISSUE TITLE
Keep images on quay.io/external_storage up to date

### ISSUE THREAD

**Issue by cofyc** [kubernetes-incubator/external-storage#766]
hi,

Currently, cephfs/rbd provisioner (at least I know) images on `quay.io/external_storage` are too old to use. If users want to use new features they need to build image themself. And users setup provisioners according to docs in master branch, will encounter problems because `latest` tag images not updated months ago. 

So I request:

- [x] tag a new version for rbd provisioner and push image to quay.io/external_storage
- [x] tag a new version for cephfs provisioner and push image to quay.io/external_storage
- [x] update `latest` image for rbd provisioner
- [x] update `latest` image for cephfs provisioner
- [ ] update `latest` image in CI automatically if possible (see https://github.com/kubernetes-incubator/external-storage/issues/608#issuecomment-375395984)

Previously, @wongma7 keeps images on quay.io/external_storage up to date if I'm not wrong, but I couldn't reach him now. IMO, this project is still the only place we maintain non-CSI external provisioners. Please help! 

cc @childsb @msau42 @rootfs 

Related issues:

- https://github.com/kubernetes-incubator/external-storage/issues/756
- https://github.com/kubernetes-incubator/external-storage/issues/622
- https://github.com/kubernetes-incubator/external-storage/issues/608
- https://github.com/kubernetes-incubator/external-storage/issues/598
- https://github.com/kubernetes-incubator/external-storage/issues/570

**Comment by childsb** [comment]
@wongma7 pushed the images last time, i'll see if i can get credentials from him.

**Comment by nielsole** [comment]
I see @wongma7 has been inactive for quite some time. Is there someone else who could help with this?

**Comment by wongma7** [comment]
I will work on this later today. Most of the images have permissions shared with their respective owners (we are a community :)) ), some don't. I will provide permissions to @cofyc . Also, quay will always be the authority on releases, git tags may or may not exist, hopefully each project maintains a changelog somewhere though.

**Comment by wongma7** [comment]
I have pushed https://quay.io/repository/external_storage/rbd-provisioner?tab=tags and https://quay.io/repository/external_storage/cephfs-provisioner?tab=tags . Keep in mind these include many months of changes at once. Again, apologies for the delay, having this long a period between releases kind of contradicts the supposed benefits of external provisioners. Anyway let's discuss "update latest image in CI automatically if possible " in this thread and I'll close the rest

**Comment by Phasip** [comment]
It seems like quay.io/external_storage/rbd-provisioner are outdated again.
I am bumping this issue as it was only solved temporarily.
