### ISSUE TITLE
Is there a way to set RECLAIM POLICY to "RETAIN" in the helm chart implementation?

### ISSUE THREAD

**Issue by gmflau** [kubernetes-incubator/external-storage#771]
I was running the following commands to deploy the provisioner:

$ helm template ./helm/provisioner --set engine=gke > ./provisioner/deployment/kubernetes/provisioner_generated.yaml
$ kubectl apply --username=admin --password=xxxxxx -f provisioner/deployment/kubernetes/provisioner_generated.yaml

This set my pv(s)'s Reclaim Policy to "Delete".

**Comment by msau42** [comment]
There currently isn't but it should not be difficult to add
/assign

**Comment by msau42** [comment]
@cofyc would you have time to look into this? I think we can just look at reclaimPolicy set in the storageclass

**Comment by cofyc** [comment]
@msau42 OK, I'll take this.
