### ISSUE TITLE
[NFS] Cannot write to PV from pod

### ISSUE THREAD

**Issue by Dremor** [kubernetes-incubator/external-storage#774]
I tried to use the NFS provisioner to provide persistent storage for my cluster, everything is fine, except that i cannot write inside the volume mounted directories.

Chart version : `0.1.3`
Settings: all default

I tried "many nodes read-write" as well as "single node read-write".

Here is my pod root:

```
root@ubuntu-59fd59bf9f-kjmzk:/# ls -l
total 144
drwxr-xr-x.   2 root   root    4096 Apr 17 13:41 bin
drwxr-xr-x.   2 root   root    4096 Apr 12  2016 boot
drwxr-xr-x.   5 root   root     380 May 23 12:52 dev
drwxr-xr-x.   1 root   root    4096 May 23 12:52 etc
drwxr-xr-x.   2 root   root    4096 Apr 12  2016 home
drwxr-xr-x.   8 root   root    4096 Sep 13  2015 lib
drwxr-xr-x.   2 root   root    4096 Apr 17 13:40 lib64
drwxr-xr-x.   2 root   root    4096 Apr 17 13:40 media
drwxr-xr-x.   2 root   root    4096 Apr 17 13:40 mnt
drwxr-xr-x.   2 root   root    4096 Apr 17 13:40 opt
dr-xr-xr-x. 225 root   root       0 May 23 12:52 proc
drwx------.   2 root   root    4096 Apr 17 13:41 root
drwxr-xr-x.   1 root   root    4096 May 23 12:52 run
drwxr-xr-x.   1 root   root    4096 Apr 27 23:30 sbin
drwxr-xr-x.   2 root   root    4096 Apr 17 13:40 srv
dr-xr-xr-x.  13 root   root       0 May 23 08:31 sys
drwxrwsrwx.   2 nobody nogroup 4096 May 23 12:52 test-rwm
drwxrwsrwx.   2 nobody nogroup 4096 May 23 12:52 test-rws
drwxrwxrwt.   2 root   root    4096 Apr 17 13:41 tmp
drwxr-xr-x.   1 root   root    4096 Apr 17 13:40 usr
drwxr-xr-x.   1 root   root    4096 Apr 17 13:41 var
```

I tried to create a file in both directories, without success:

```
root@ubuntu-59fd59bf9f-kjmzk:/# touch test-rws/test
touch: setting times of 'test-rws/test': No such file or directory
root@ubuntu-59fd59bf9f-kjmzk:/# touch test-rwm/test
touch: setting times of 'test-rwm/test': No such file or directory
```

I also tried to copy an existing file inside both directories, without success.

**Comment by wongma7** [comment]
this is a bug with the ganesha server when the share is mounted with nfs >= v4.2 (can't remember the exact #). Unfortunately there's not much we can do to fix it so I would recommend you set up a simple nfs server your cluster can access and use the nfs-client provisioner

**Comment by Dremor** [comment]
It is the 4.2 version which is broken.
I'm working on a fix (working internally, cleanup atm).

**Comment by Dremor** [comment]
Got it working here : https://gitlab.com/egeorget/rancher2-charts/tree/devel/nfs-provisioner/v0.1.2-rc1

**Comment by Dremor** [comment]
I've read the code for a bit. I don't understand Go very well, but the following codepath seems to be the cause:
```go
func (p *nfsProvisioner) validateOptions(options controller.VolumeOptions) (string, bool, string, error) {
	gid := "none"
	rootSquash := false
	mountOptions := ""
	for k, v := range options.Parameters {
		switch strings.ToLower(k) {
		case "gid":
			if strings.ToLower(v) == "none" {
				gid = "none"
			} else if i, err := strconv.ParseUint(v, 10, 64); err == nil && i != 0 {
				gid = v
			} else {
				return "", false, "", fmt.Errorf("invalid value for parameter gid: %v. valid values are: 'none' or a non-zero integer", v)
			}
		case "rootsquash":
			var err error
			rootSquash, err = strconv.ParseBool(v)
			if err != nil {
				return "", false, "", fmt.Errorf("invalid value for parameter rootSquash: %v. valid values are: 'true' or 'false'", v)
			}
		case "mountoptions":
			mountOptions = v
		default:
			return "", false, "", fmt.Errorf("invalid parameter: %q", k)
		}
	}
```

"mountOptions" is initialized as an empty string, before being filled by the "Parameters.mountoptions" option. Thus, in order to make it work, we have to set the  "Parameters.mountoptions" option to "vers=4.1" in order to make it work.

Changing the `mountOptions := ""` line to `mountOptions := strings.Join(options.mountOptions, ",")` may resolve this matter.

**Comment by wongma7** [comment]
yes we should default to 4.1, this has been an issue for a while so apologies for that https://github.com/kubernetes-incubator/external-storage/issues/223#issuecomment-344972640. The code be something like
mountOptions := "vers=4.1" then
mountOptions = mountOptions + "," + v
the only reason we can't use strings.Join is because mountOptions is not an array

**Comment by Dremor** [comment]
What kind of data is it ?

**Comment by wongma7** [comment]
it is a plain old comma-separated string e.g. "ro,blah,a=b"

**Comment by Dremor** [comment]
I see. I hope this will be fixed a soon as possible. ;)

**Comment by Dremor** [comment]
In another hand, would `mountOptions := options.mountOptions` be possible ? If we support directly mountOptions, there would be no need for supporting an additional parameter.
