### ISSUE TITLE
pvc deletion failed to release claim to pv for local volume (local ssd)

### ISSUE THREAD

**Issue by gmflau** [kubernetes-incubator/external-storage#779]
$ kubectl delete pvc [some-name] (managed to remove the pvc resource)

$ kubectl get pv (was showing FAILED to remove the claim)
NAME                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                    STORAGECLASS    REASON    AGE
local-ssd-pv-jtlx   375Gi      RWO            Delete           Failed      default/dse-data-dse-2   local-storage             20m
local-ssd-pv-mkvn   375Gi      RWO            Delete           Available                            local-storage             20m
local-ssd-pv-w60s   375Gi      RWO            Delete           Failed      default/dse-data-dse-1   local-storage             20m
local-ssd-pv-zdll   375Gi      RWO            Delete           Failed      default/dse-data-dse-0   local-storage             20m

$ kubectl describe pv local-ssd-pv-jtlx (showing no deletable volume plugin matched)
Name:            local-ssd-pv-jtlx
Labels:          <none>
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"local-ssd-pv-jtlx","namespace":""},"spec":{"accessModes":["ReadWriteO...
                 pv.kubernetes.io/bound-by-controller=yes
StorageClass:    local-storage
Status:          Failed
Claim:           default/dse-data-dse-2
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        375Gi
Message:         Error getting deleter volume plugin for volume "local-ssd-pv-jtlx": no deletable volume plugin matched
Source:
    Type:  LocalVolume (a persistent volume backed by local storage on a node)
    Path:  /mnt/disks/ssd0
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  VolumeFailedDelete  1m    persistentvolume-controller  Error getting deleter volume plugin for volume "local-ssd-pv-jtlx": no deletable volume plugin matched

**Comment by msau42** [comment]
Hi, are you using the local static provisioner to manage your local PVs? If not, and you are manually creating the local PVs, then you will need to manually clean up the PV when you delete the PVC.

If you are running on gke, try out the instructions here for running the static provisioner: https://cloud.google.com/kubernetes-engine/docs/concepts/local-ssd

**Comment by gmflau** [comment]
Do you mean I need to do the following if my PVs are created manually?

**Comment by msau42** [comment]
You also need to remove any data on the local ssd before you recreate the PV if you don't want the next workload to use that data.

**Comment by resouer** [comment]
@gmflau I also encountered this error recently and @msau42 's comment is exactly helpful. Would you mind to close this issue?
