### ISSUE TITLE
local-volume (local-ssd) does not support "DELETE" as RECLAIM POLICY?

### ISSUE THREAD

**Issue by gmflau** [kubernetes-incubator/external-storage#782]
My stateful was using a manually provisioned local-ssd volume using "DELETE" reclaim policy through dynamic storage provisioning.  When I was trying to remove its PVC resource, the PVC resource got removed but the underlying pv (on the local-ssd)'s deletion failed with the following error message:

$ kubectl describe pv local-ssd-pv-jtlx (showing no deletable volume plugin matched)
Name: local-ssd-pv-jtlx
Labels: 
Annotations: kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"local-ssd-pv-jtlx","namespace":""},"spec":{"accessModes":["ReadWriteO...
pv.kubernetes.io/bound-by-controller=yes
StorageClass: local-storage
Status: Failed
Claim: default/dse-data-dse-2
Reclaim Policy: Delete
Access Modes: RWO
Capacity: 375Gi
Message: Error getting deleter volume plugin for volume "local-ssd-pv-jtlx": no deletable volume plugin matched
Source:
Type: LocalVolume (a persistent volume backed by local storage on a node)
Path: /mnt/disks/ssd0
Events:
Type Reason Age From Message

Can you confirm that manual creation of pv from a locally attached ssd does not support "DELETE" reclaim policy?

**Comment by msau42** [comment]
Correct the docs mention that if you manually create a local PV, only Retain policy is supported.

**Comment by gmflau** [comment]
Thanks! Can you point me to the doc?

**Comment by gmflau** [comment]
The example showed "RETAIN".  However, the docs do not specifically call out "RETAIN" is the only policy supported.  Can you confirm if "RECYCLE" is supported?  The reason I am asking is that my StatefulSet is dynamically claiming the local ssd(s).  I would like to "recycle" the PVs (local SSDs) during my StatefulSet's decommission so that the PVs (local SSDs) will be freed up again for other workloads to claim.

**Comment by msau42** [comment]
Delete and Recycle are not supported if you manually create the PV.  If you want a recycle-like behavior, I recommend using the local static provisioner, which supports Delete and will manage the PV lifecycle for you.

The GKE docs have this note:
Note: If you delete the PersistentVolume, you need to manually erase the data from the disk.

And Kubernetes docs have this note:
Note: The local PersistentVolume requires manual cleanup and deletion by the user if the external static provisioner is not used to manage the volume lifecycle.

**Comment by gmflau** [comment]
We have another thread here - https://github.com/kubernetes-incubator/external-storage/issues/771  .  Wonder if you are going to add "RECYCLE" policy support for the local static provisioner.  Pls confirm.

**Comment by msau42** [comment]
The local static provisioner will not explicilty support the recycle policy.  But if the reclaim policy is Delete, it will do something very similar to recycle.  It will rm -rf the data on the disk, delete the PV, and then create a new PV.

**Comment by gmflau** [comment]
Sounds good!  I will give a try using "DELETE" for my test.  Thx!

**Comment by msau42** [comment]
Thanks, let me know if you have any more issues.  The GKE documentation has the all the steps needed to run the provisioner on a GKE cluster.

**Comment by discostur** [comment]
@gmflau i have the same problem but i am not able to delete the local PV now - it was provisioned with an older k8s version and now i updated to k8s 1.15.10 and i'm not able to delete it:

```
Message:         Error getting deleter volume plugin for volume "prometheus-local-pv": no deletable volume plugin matched
``` 

How can i force deletion?

I tried to updated reclaim policy from "delete" to "retain" but that is not allowed ...
