### ISSUE TITLE
[nfs-client] nfs-client-provisioner create folder with 755, not 777

### ISSUE THREAD

**Issue by jody-kpw** [kubernetes-incubator/external-storage#785]
Hi Could you make new docker image Fix issue 149 - nfs-client-provisioner create folder with 755, not 777?

fullPath := filepath.Join(mountPath, pvName)
	glog.V(4).Infof("creating path %s", fullPath)
	if err := os.MkdirAll(fullPath, 0777); err != nil {
		return nil, errors.New("unable to create directory to provision new pv: " + err.Error())
	}
os.Chmod(fullPath, 0777)

**Comment by wongma7** [comment]
image has been pushed https://quay.io/repository/external_storage/nfs-client-provisioner?tab=tags sorry for the delay

/area nfs-client

**Comment by jody-kpw** [comment]
sorry, tried it with image: quay.io/external_storage/nfs-client-provisioner:latest

still 777.
drwxrwxrwx.  2 root      root      4096 Jun 20 00:19 default-test-claim-pvc-75df3431-73dc-11e8-9a18-f4b52003bfa2

**Comment by jody-kpw** [comment]
sorry, I want to use 755.

**Comment by wongma7** [comment]
the problem is people whose containers are not allowed to run as root by cluster policy (e.g. OpenShift default) then cannot write to the share. So we can't use 755 as the default

**Comment by jody-kpw** [comment]
no problem, can't manually change it thank :)
