### ISSUE TITLE
Remove FakeAPIUtil

### ISSUE THREAD

**Issue by cofyc** [kubernetes-incubator/external-storage#786]
In local-volume, we are using a custom fake implementation `FakeAPIUtil` for testing. Perhaps, we can simply use `APIUtil` with `fake.Clientset`. 

@msau42 What do you think?

**Comment by msau42** [comment]
Yes this sounds fine if you can still keep the API tracking that FakeAPI does

**Comment by msau42** [comment]
Migrating to new repo: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/8
/close
