### ISSUE TITLE
Manila provisioner in cloud-provider-openstack

### ISSUE THREAD

**Issue by gman0** [kubernetes-incubator/external-storage#788]
There is a more up-to-date version of Manila external provisioner in [kubernetes/cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack)

[source code](https://github.com/kubernetes/cloud-provider-openstack/tree/master/pkg/share/manila)
[manifests](https://github.com/kubernetes/cloud-provider-openstack/tree/master/manifests/manila-provisioner)
[examples](https://github.com/kubernetes/cloud-provider-openstack/tree/master/examples/manila-provisioner)

Please, continue any further development over there, thanks!

**Comment by tsmetana** [comment]
@gman0 thanks a lot for the work. I will deprecate the Manila provisioner from this repository.

**Comment by gman0** [comment]
Thanks!
