### ISSUE TITLE
Support basic metrics for external-storage controller

### ISSUE THREAD

**Issue by xingzhou** [kubernetes-incubator/external-storage#81]
The idea is to add metrics exposed by external-storage controller. Some basic plan is to add a '/metrics' endpoint for the controller and expose metrics like provision time/provisioner error.

I'm working on  the detail plan and will supplement the metrics plan later with patches.

cc @wongma7, @akgunjal and @sandaymin123

**Comment by wongma7** [comment]
https://github.com/kubernetes-incubator/external-storage/pull/796
