### ISSUE TITLE
MountOptions ignored in efs-provisioner

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#810]
nfs-client equivalent: https://github.com/kubernetes-incubator/external-storage/issues/629
issue brought up here: https://github.com/kubernetes-incubator/external-storage/issues/241#issuecomment-367115636

**Comment by CH-anhngo** [comment]
tried this one with mountOptions in storageClass -port=port_number but the nfs-client doesn't seem to use `-o -port` causing mount failures
