### ISSUE TITLE
Rewrite controller

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#812]
I will fill this in later. Basically it should be rewritten to reflect current best practices

**Comment by cofyc** [comment]
I'm glad to help.

**Comment by wongma7** [comment]
doing a li'l audit of the code, here are some tasks:
* I'm not convinced the informers need changing, as far as I can tell we are using shared informers correctly, only we are initializing them ourselves instead of using the free constructed versions at e.g. coreinformers.PersistentVolumeInformer. Of course we should move to using those versions anyway just for future proof & verbosity purposes. Anyway there is not much to be done here as every provisioner instance needs its own set of informers and they can't "share" their informer cache with one another, inefficient as that is.
* Work queues. Maybe make threadiness configurable
* Make the resync period a lot higher than 15 seconds. https://github.com/kubernetes-csi/external-provisioner/issues/100#issuecomment-398420215
* Clean up retry and exponential backoff logic. Iirc something similar happened upstream. Also, our retry period is tied to resync period so we need to decouple it.
* Remove per-PVC leader election and add per-class leader election. The idea behind per-PVC was to cheaply enable "HA". I highly doubt anybody is deploying provisioners in this way. If they are, too bad! Only nfs-provisioner should be affected.
* Doing above allows us to remove all the event watching logic. Yeah we use kubernetes `events` as...an event bus. Not the best idea

I am working on work queues, resync period, & retry period. Somebody is working on leader election.

**Comment by wongma7** [comment]
Actually I'm just going to work on resync period and retry for now.

**Comment by orainxiong** [comment]
@wongma7 

I have created a PR #837 to do two following major works:
* Modify the implementation of leader election from `per-PVC` to `per-Class`   
* Leverage informer cache rather than talking directly against `API Server`

In my scenario, those are the root which cause 'external-provisioner' getting throttling.

I have no idea which is a right way to fix the problem. If any problems, please let me know. : - )
