### ISSUE TITLE
nfs-client "unable to set extended attributes on directory"

### ISSUE THREAD

**Issue by sunho** [kubernetes-incubator/external-storage#815]
I deployed nfs-client following guide and encountered this error in nfs-client-provisioner pod.
```
E0616 19:46:09.799148       1 goroutinemap.go:166] Operation for "provision-monitoring/elasticsearch-logging-elasticsearch-logging-0[86d40bd7-719b-11e8-9d44-e0d55e669edf]" failed. 
No retries permitted until 2018-06-16 19:48:11.799122607 +0000 UTC (durationBeforeRetry 2m2s). 
Error: "unable to set extended attributes on directory to provision new pv: xattr.
Set /persistentvolumes/monitoring-elasticsearch-logging-elasticsearch-logging-0-pvc-86d40bd7-719b-11e8-9d44-e0d55e669edf namespace: operation not supported"
```

I use centos and my nfs server supports nfsv4.

My /etc/exports is
```
/var/nfs   172.30.1.0/24(rw,sync,fsid=0,no_root_squash)
```

And grep nfs /proc/mounts showed me
```
172.30.1.25:/var/nfs /var/lib/kubelet/pods/56a99b50-719b-11e8-9d44-e0d55e669edf/volumes/kubernetes.io~nfs/nfs-client-root nfs 
rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=172.30.1.25,mountvers=3,
mountport=20048,mountproto=udp,local_lock=none,addr=172.30.1.25 0 0
```

**Comment by dshakey** [comment]
having this issue too.

**Comment by dshakey** [comment]
ive done some more troubleshooting and believe the issues is cause of xattr on the NFS.
testing this by running - setfattr on the NFS on the master node

> # touch test.txt
> # setfattr -n user.comment -v "some comment" test.txt
> setfattr: test.txt: Operation not supported

**Comment by dshakey** [comment]
Wonder could I rebuild the image and remove the below from the nfs-client-provisioner code? As don't see the meta data being used anywhere else.

if err := xattr.Set(fullPath, "namespace", []byte(pvcNamespace)); err != nil {
		return nil, errors.New("unable to set extended attributes on directory to provision new pv: " + err.Error())
	}

**Comment by sunho** [comment]
#671 is related to this issue. It seems like nfs doesn't support xattr officially. Were there some changes recently?

**Comment by wongma7** [comment]
Yes, I merged a PR about setting extended attributes on Friday. Please downgrade in the meantime. I will revert the change today.

**Comment by wongma7** [comment]
image pushed, should be fixed
/area nfs-client

**Comment by wongma7** [comment]
https://quay.io/repository/external_storage/nfs-client-provisioner?tab=tags
