### ISSUE TITLE
Provisioner versioning can be confusing: create compatibility table

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#819]
I have started to add a "-k8sv1.10" suffix to image tags. This can be a source of confusion. The suffix only indicates what version of the kubernetes API the image was built against. I don't know whether this is more helpful or confusing to users. It does not say whether the image is backwards-compatible with older versions. But neither would a tag of just 'v#.#.#'. **To anyone confused whether an image suffixed "-k8sv1.10" is backwards compatible: yes it is.**

Should we keep the suffixes? Is there some existing tagging convention we should follow? Kindly please +1 or -1 or comment or something.

It was suggested here https://github.com/kubernetes-incubator/external-storage/pull/807#issuecomment-397791639 we maintain a table for compatibility. I think we should put one at the top-level README (& maybe at every other README, unless they risk getting outdated). It's quite possible it will just be a bunch of check marks all the way until kubernetes 2.0, i.e. just always update to the latest image without fear no matter what kube version you're using, because I don't see backwards compatibility ever breaking. But it could still be useful. And it could be a place to make note of the additions in kubernetes that could potentially cause confusion, e.g. storageClass.reclaimPolicy (my own fault)

See also https://github.com/kubernetes-incubator/external-storage/issues/369

**Comment by msau42** [comment]
For local volumes, I added a [compatibility table](https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume#version-compatibility) and didn't include backwards compatibility for simplicity + testing matrix.  So using a newer provisioner version against an older Kubernetes version is at your own risk.
