### ISSUE TITLE
EFS-Provisioner option to not create subdir for each volume

### ISSUE THREAD

**Issue by ianseyer** [kubernetes-incubator/external-storage#821]
My goal is to create a statefulset where each member of the set has access to a single shared ReadOnlyMany volume, that gets prepopulated by a deployment before using.

I have turned to NFS, as aws ebs does not support ReadOnlyMany. However, using the efs-provisioner provisions a new directory in the nfs for each member of the set. However, I would like it to simply mount the nfs as a volume without creating a new subdirectory.

Is this possible, or am I barking up the wrong tree?

(my initial attempt to was to have a persistentvolumeclaim that just mounts an nfs pv, but i couldn't mount that more than once at a time for some reason)

**Comment by msau42** [comment]
If you use a PVC in the StatefulSet *outside* of the PVC template, then all StatefulSet instances will share the same volume.  Your initial attempt should have worked, so it may be worth further triaging that.

**Comment by midN** [comment]
That is a valid request.
Currently EFS provider creates folder for each PVC by unique name, with no option to change that.
I'd like to mount multiple PVCs in different Namespaces/Clusters under same EFS and share folder.

**Comment by midN** [comment]
https://github.com/kubernetes-incubator/external-storage/pull/1147

**Comment by midN** [comment]
Another perfect example of Issue being open for 1 year and being ignored with a valid PR addressing the issue, <3 Google

**Comment by midN** [comment]
LOL - Love Kubernetes contributers community so far 😂

**Comment by kverstr** [comment]
We also need this, reopened a ticket 🤞 
[#1328 ](https://github.com/kubernetes-incubator/external-storage/issues/1328)

**Comment by mkuendig** [comment]
would be great if we get this too! Struggling as well with those folders.
