### ISSUE TITLE
Automatic discovery of local volumes

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-incubator/external-storage#833]
There should be a way how to automatically detect a device on a node usable as a local volume without going to the node and manually mounting / symlinking it.

Users should configure used devices globally, for whole cluster, instead locally on every node.

@msau42 @ianchakeres @cofyc @dubuc @NickrenREN @dhirajh (do I miss anyone?)

**Comment by jsafrane** [comment]
I have an idea: udev already has fairly flexible matching capabilities and it can create symlinks in `/dev`. E.g. `/dev/disk/by-id` is created by udev automatically when machine boots or a new device appears.

Can we re-use these capabilities to create symlinks in say `/dev/disk/kubernetes/local`? Our "provisioner" DaemonSet could install udev rules from a ConfigMap (configured by the user) and then just wait for the symlinks to appear (in the same way it does today).

Example of the simplest udev rule to match every disk that's not `/dev/sda` and create a symlink, say `/dev/disk/kubernetes/local/sdb`, for it:

```
SUBSYSTEM=="block", KERNEL=="sd[b-z]", SYMLINK+="kubernetes/local/$NAME"
```

That's what we would use in all our demos and it looks pretty readable.

Real world example, using stable symlink name that won't change after reboot (like `/dev/disk/by-id`), matching only disks, not partitions, and separating SSDs from HDDs:

```
SUBSYSTEM=="block", KERNEL=="sd[b-z]|sd[a-z]*[^0-9]", ENV{ID_SERIAL}=="?*", ENV{ID_BUS}=="?*", ATTR{queue/rotational}=="1", SYMLINK+="local-storage/hdd/$env{ID_BUS}-$env{ID_SERIAL}"
SUBSYSTEM=="block", KERNEL=="sd[b-z]|sd[a-z]*[^0-9]", ENV{ID_SERIAL}=="?*", ENV{ID_BUS}=="?*", ATTR{queue/rotational}=="0", SYMLINK+="local-storage/ssd/$env{ID_BUS}-$env{ID_SERIAL}"
```

The only downsides I see are:

* udev rules are not nice to read or write. There is no "debugger".
* Installation of udev rules to the host from the local provisioner container might be hard. Installation itself is easy (just put a file to `/etc/udev/rules.d`), but then I need to call `udevadm trigger` on the host. I'm investigating a way how to do it safely.

Any opinions or doubts?

cc @gnufied @tsmetana

**Comment by msau42** [comment]
We already have in tree plugins calling udevadm trigger although I'm not sure if safety was thoroughly evaluated when it was added.

**Comment by jsafrane** [comment]
volume plugins typically don't run in containers (and if they do they run via nsenter?)

**Comment by msau42** [comment]
If the CSI replacement for in tree needs to still call udevadm, then this issue still needs to be solved

**Comment by msau42** [comment]
The only thing that concerns me about automatic discovery is that if you don't craft the rules correctly, you can easily expose/corrupt data you didn't intend to.  For example, if you run multiple storage plugins on one node and don't take into account the device naming for each plugin

**Comment by jsafrane** [comment]
Just for the record, `udevadm trigger` from a container is possible with these volumes:

```
docker run -ti -v /etc/udev:/etc/udev -v /run/udev:/run/udev -v /lib/udev:/lib/udev -v /dev:/dev -v /sys:/sys udev-image sh
```

* `/etc/udev`, `/lib/udev`: use host's rules during `trigger`
* `/run/udev`: access host's udev socket
* `/dev`, `/sys`: access devices and their information is /sys

And udev-image is just:
```
FROM fedora
RUN yum -y install udev
```

**Comment by jsafrane** [comment]
> The only thing that concerns me about automatic discovery is that if you don't craft the rules correctly, you can easily expose/corrupt data you didn't intend to.

Yes, that's correct. We need strong guidance and examples to match only the necessary drives, e.g. by matching non-partitioned ATA drives only, these are always local.
