### ISSUE TITLE
Upgrade to use nfs 4.1

### ISSUE THREAD

**Issue by patrickdk77** [kubernetes-incubator/external-storage#836]
I upgraded to quay.io/external_storage/efs-provisioner:v1.0.0-k8s1.10
Then rebooted a node.
But my efs mounts are still using 4.0
How do I go about upgrading correctly so that I get the 4.1 mount, or verify that it is mounted with 4.1
So far the mount options still show vers=4.0

**Comment by wongma7** [comment]
I believe any pod using a pv created pre-upgrade will need to be restarted else they'll keep the same mounts with vers=4.0 from before the upgrade

**Comment by patrickdk77** [comment]
I'm still not having any luck with this. All my mounts still exist as vers=4.0
I have deleted and recreate my pods, I have rebooted all my nodes, still every pod, even new pods I bring up, mount as 4.0

Name:           efs-provisioner-769f48695b-hdr7m
Namespace:      default
Start Time:     Mon, 30 Jul 2018 18:34:14 +0000
Labels:         app=efs-provisioner
                pod-template-hash=3259042516
Annotations:    kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container efs-provisioner
Status:         Running
IP:             100.96.7.9
Controlled By:  ReplicaSet/efs-provisioner-769f48695b
Containers:
  efs-provisioner:
    Container ID:   docker://38f2047bf18ce90d28a77ac2b45d731b871c69b105e2c730564a9c6fb2eb5e45
    Image:          quay.io/external_storage/efs-provisioner:v1.0.0-k8s1.10
    Image ID:       docker-pullable://quay.io/external_storage/efs-provisioner@sha256:5db46a114450c8ec8662bee785acd46b4e807020224f8e35a27a3f07b48108cf
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 30 Jul 2018 18:34:22 +0000

The only thing I haven't tried is creating a new pv
