### ISSUE TITLE
[DigitalOcean] After node holding persistent volume gets down, PV doesn't get recycled

### ISSUE THREAD

**Issue by bjg2** [kubernetes-incubator/external-storage#838]
/area digitalocean

I created 3-node k8s (version 1.9.4) cluster on DO, all 3 nodes are masters and they accept pods as well, with DO block storage as persistent volume. PVs were not created by k8s but reused:
```apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    Provisioner_Id: ""
    digitalocean.external-storage.incubator.kubernetes.io/VolumeID: 3479ba99-7b8a-11e8-8321-0242ac110605
    kubernetes.io/createdby: digitalocean-provisioner
    pv.kubernetes.io/provisioned-by: external/digitalocean
  labels:
    failure-domain.beta.kubernetes.io/zone: fra1
  name: test-k8s-database-volume
spec:
  storageClassName: do-storage-class
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  flexVolume:
    driver: external-storage/digitalocean
  persistentVolumeReclaimPolicy: Delete
```

I use this PV for database, I spin up the cluster, volume gets claimed and everything works. But after I bring one node down by simply turning droplet off in DO, things get messy. After some time k8s realize that node is down:
```NAME                STATUS     ROLES     AGE       VERSION   EXTERNAL-IP   OS-IMAGE                                        KERNEL-VERSION   CONTAINER-RUNTIME
test-k8s-master-0   Ready      master    1h        v1.9.4    <none>        Container Linux by CoreOS 1800.2.0 (Rhyolite)   4.14.50-coreos   docker://18.3.1
test-k8s-master-1   NotReady   master    1h        v1.9.4    <none>        Container Linux by CoreOS 1800.2.0 (Rhyolite)   4.14.50-coreos   docker://18.3.1
test-k8s-master-2   Ready      master    1h        v1.9.4    <none>        Container Linux by CoreOS 1800.2.0 (Rhyolite)   4.14.50-coreos   docker://18.3.1
```
And after some time k8s tries to spin up new pods to replace the ones on missing node:
```NAME                        READY     STATUS              RESTARTS   AGE       IP           NODE
database-7744fc794c-67pwd   0/1       ContainerCreating   0          45m       <none>       test-k8s-master-2
database-7744fc794c-r7qt8   1/1       Unknown             0          1h        10.32.0.9    test-k8s-master-1
elasticsearch-4hwzh         0/1       ContainerCreating   0          45m       <none>       test-k8s-master-0
elasticsearch-wq656         1/1       Unknown             0          1h        10.32.0.8    test-k8s-master-1
es-deamon-set-4g546         1/1       Running             0          1h        10.40.0.6    test-k8s-master-2
es-deamon-set-9v9sz         1/1       NodeLost            0          1h        10.32.0.6    test-k8s-master-1
es-deamon-set-lr49d         1/1       Running             0          1h        10.38.0.5    test-k8s-master-0
fluentd-jvq6s               1/1       Running             0          1h        10.38.0.4    test-k8s-master-0
fluentd-r6kwf               1/1       NodeLost            0          1h        10.32.0.7    test-k8s-master-1
fluentd-s8rzw               1/1       Running             0          1h        10.40.0.5    test-k8s-master-2
hashtags-74464cffbd-w5tpr   1/1       Running             0          1h        10.40.0.7    test-k8s-master-2
kibana-djkm7                1/1       Running             0          45m       10.40.0.8    test-k8s-master-2
kibana-xx4xh                1/1       Unknown             0          1h        10.32.0.5    test-k8s-master-1
site-67db6bd859-cggqz       1/1       Unknown             0          1h        10.32.0.10   test-k8s-master-1
site-67db6bd859-h7dbn       0/1       CrashLoopBackOff    9          45m       10.38.0.6    test-k8s-master-0
```
But pods using PVs are not getting up (database and elasticsearch). If I describe the pod, it doesn't know how to attach the volume:
```  Normal   Scheduled              46m                default-scheduler           Successfully assigned database-7744fc794c-67pwd to test-k8s-master-2
  Warning  FailedAttachVolume     46m                attachdetach-controller     Multi-Attach error for volume "test-k8s-database-volume" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulMountVolume  46m                kubelet, test-k8s-master-2  MountVolume.SetUp succeeded for volume "default-token-p8lwg"
  Normal   SuccessfulMountVolume  46m                kubelet, test-k8s-master-2  MountVolume.SetUp succeeded for volume "cert-volume"
  Warning  FailedMount            1m (x20 over 44m)  kubelet, test-k8s-master-2  Unable to mount volumes for pod "database-7744fc794c-67pwd_default(bc55f43d-7dd2-11e8-89eb-ca608e939198)": timeout expired waiting for volumes to attach/mount for pod "default"/"database-7744fc794c-67pwd". list of unattached/unmounted volumes=[database-volume]
```
Controller manager repeats this log:
`W0702 09:22:06.306239       1 plugin-defaults.go:32] flexVolume driver external-storage/digitalocean: using default GetVolumeName for volume test-k8s-database-volume`

Can you help me understand why pods that use DO PV can't recover from node down and what am I doing wrong?

**Comment by bjg2** [comment]
If I change to ReadWriteMany, I get the issue with storage already being bound to droplet id X. Can I somehow give the storage to newly created pod?

**Comment by wongma7** [comment]
In DO does the node need to be on for disks to be detached from it? The disk can only be attached to one node at a time so maybe kubernetes is trying to detach then re-attach the disk but failing, is there any indication of that? I am not too familiar with k8s attach/detach logic, I am not sure what it does when a pod enters state 'Unknown', maybe it thinks it is too dangerous to detach the disk even though the disk is obviously needed elsewhere

cc @klausenbusk

**Comment by klausenbusk** [comment]
> I am not sure what it does when a pod enters state 'Unknown', maybe it thinks it is too dangerous to detach the disk even though the disk is obviously needed elsewhere

Correct, k8s won't detach the PV as long it is in "use" by some pod.

Similar issue: https://github.com/rook/rook/issues/1507

**Comment by bjg2** [comment]
Is that exclusively k8s decision or DO flex plugin has anything to say to it? Is there any configuration to any of those two to change this behavior?

If that's official k8s code, can you point me to the place where I can make official feature request for configuration that makes this possible, as it really hard for me to believe that this is intended usage, and that there's not even way to change the behavior via configuration...

Thanks!

**Comment by klausenbusk** [comment]
> Is that exclusively k8s decision or DO flex plugin has anything to say to it?

It is k8s decision (https://github.com/kubernetes/kubernetes/issues/57531#issuecomment-355139769). The flex plugin only do what it told.

> Is there any configuration to any of those two to change this behavior?

According to https://groups.google.com/forum/m/#!topic/kubernetes-sig-storage/GlVxSM4tD34 a solution could be `TaintBasedEvictions`.

> If that's official k8s code, can you point me to the place where I can make official feature request for configuration that makes this possible, as it really hard for me to believe that this is intended usage, and that there's not even way to change the behavior via configuration...

I'm pretty sure it is the intended behaviour at the moment. You can report issues here: https://github.com/kubernetes/kubernetes/issues, I would ask on #sig-storage on Slack first though.

**Comment by bjg2** [comment]
Thank you very much for your help! Closing issue now.
