### ISSUE TITLE
Add Azure managed disk snapshot functionality

### ISSUE THREAD

**Issue by TamasKormendiMAT** [kubernetes-incubator/external-storage#839]
Snapshot functionality for Azure managed disks is not implemented yet. As far as I can tell similar functionality was planned in rootfs/snapshot#4 but could not find any other forks/issues/PRs that would have dealt with Azure snapshot support, so I am planning to implement it myself. Any advice and suggestions are more than welcome!

/area snapshot

**Comment by tsmetana** [comment]
I don't have an Azure account and have no experience with it either. Any contributions would be welcome.

**Comment by TamasKormendiMAT** [comment]
Work is ongoing, however, instead of (unmanaged) page blobs focus has shifted to managed disks, which is the recommended and more up-to-date way of using Azure Disks. Look here for more info: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/faq-for-disks and https://docs.microsoft.com/en-us/azure/virtual-machines/linux/about-disks-and-vhds#managed-disks

Updated the issue name and message accordingly.

**Comment by TamasKormendiMAT** [comment]
Update for @wongma7 and @tsmetana: snapshots for managed disks on our Azure cluster have been up and running for a few weeks now, I'll try to prepare a formal pull request shortly.
