### ISSUE TITLE
[flex-provisioner] PVC pending state in Retain

### ISSUE THREAD

**Issue by jwpark74** [kubernetes-incubator/external-storage#844]
Hello,

I have been testing the creation and deletion of pv several times using the flex provisioner.

There is no problem when the reclaimPolicy value of the StorageClase is set to Delete,
With Retain, the PVC is pending for several tens of minutes

If you look at the flex provisioner container log when you are in the pending state
The following logs are still visible

I0706 12:18:09.042984       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-12[5b5a9e15-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.048473       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-11[5b546caf-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.133689       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-3[5b77d552-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.161432       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-3[5b77d552-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.250441       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-6[5b8a127c-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.254159       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-5[5b85e02a-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.272978       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-6[5b8a127c-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.289618       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-7[5b8ee378-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.294985       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-5[5b85e02a-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:09.308111       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-7[5b8ee378-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934520       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-12[5b5a9e15-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934627       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-6[5b8a127c-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934655       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-1[5b4a7caa-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934688       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-11[5b546caf-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934717       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-7[5b8ee378-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934743       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-3[5b77d552-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934761       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-5[5b85e02a-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:19.934780       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-10[5b4e07b5-810e-11e8-9bf5-005056a3aa94]]
I0706 12:18:22.640711       1 controller.go:1167] scheduleOperation[lock-provision-default/prometheus-volume-9[5b9abfcf-810e-11e8-9bf5-005056a3aa94]]

The test was as follows

Create 12 pv files in the test directory
kubectl apply -f test
I have run.

After confirming that it was created, click again.
kubectl delete -f test

If you continue this test,

I0706 12: 18: 22.640711 1 controller.go: 1167] scheduleOperation [lock-provision-default / prometheus-volume-9 [5b9abfcf-810e-11e8-9bf5-005056a3aa94]]

This kind of log continues to be pvc pending.

And after about 20 to 30 minutes, pv generation begins.

https://github.com/kubernetes-incubator/external-storage/tree/master/flex/deploy
I have not implemented any of the provision () and delete () functions in flex-provision.sh.

The file was used as is.

Any help would be appreciated.
Thanks

Kubernetes v1.10.2 (installed with kubeadm)
fles-provisioner built from master

**Comment by pictolearn** [comment]
I came across the same issue using KOPS.  I have followed whatever was specified here https://medium.com/@while1eq1/using-amazon-efs-in-a-multiaz-kubernetes-setup-57922e032776 but my pod file look different with an nginx instance trying to mount to the EFS cluster

```
$ kubectl describe pvc efs
Name:          efs
Namespace:     default
StorageClass:  aws-efs
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"aws-efs"},"name":"efs","namespa...
               volume.beta.kubernetes.io/storage-class=aws-efs
               volume.beta.kubernetes.io/storage-provisioner=example.com/aws-efs
Finalizers:    []
Capacity:      
Access Modes:  
Events:
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  ExternalProvisioning  3m (x203 over 54m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "example.com/aws-efs" or manually created by system administrator
```
here is a sample nginx yaml which i used to test
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: efs
          mountPath: /usr/share/nginx/html
      volumes:
        - name: efs
          persistentVolumeClaim:
            claimName: efs
```
