### ISSUE TITLE
local volume provisioner does not scrub data on pvc deletion

### ISSUE THREAD

**Issue by smanpathak** [kubernetes-incubator/external-storage#845]
Cluster details:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

local volume provisioner was manually deployed, with feature gates enabled for K8S processes.
Image:  quay.io/external_storage/local-volume-provisioner:v2.0.0

The reclaim policy is set to "Delete" for discovered volumes. However, when associated pvc is deleted the volume data is not scrubbed out. I have to manually delete the freed volume in order to ensure it does not have any data when connected to a new Pod.

**Comment by wongma7** [comment]
Please provide logs from the provisioner & output of `kubectl describe $PV`. It should not recreate a PV unless cleaning of the Released one succeeded
/area local-volume

**Comment by msau42** [comment]
If you still have problems, please open an new issue under https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
/close
