### ISSUE TITLE
possible to connect to multiple kubernetes cluster with one nfs server binary deployment?

### ISSUE THREAD

**Issue by KinOSurvival** [kubernetes-incubator/external-storage#85]
Hi I'm wondering that whether I can run multiple nfs-provisioner binary process, to connection to multiple k8s clusters? I try that, pvc and pv are created separately for different cluster, but somehow pv seems not working. Or are there other ways to do that?

**Comment by KinOSurvival** [comment]
I'm using outside of kubernetes binary deployment

**Comment by wongma7** [comment]
No, it won't work because every instance assumes it has exclusive ability to assign fsids which have to be unique. What failures with the PV do you see? Can you inspect the /etc/exports and see if there are duplicate fsids or other problems?

I don't know/remember what the consequences of reusing fsid for different exports are.

One possible solution would be to allow you to specify a range of ids for an instance to allocate from

**Comment by KinOSurvival** [comment]
pv created but somehow I got IOException for my java process. I'll check /etc/exports later.

BTW  would it work, if I build nfs-provisioner with different export folder? say cluster1 point to /export1  and cluster2 point to /export2?

**Comment by KinOSurvival** [comment]
and how can I specify a range of ids?seems there is no option for the binary privisioner to do that. Thanks a lot

**Comment by wongma7** [comment]
I'm not sure how IOException could occur.

No, using different export folders shouldn't solve it. Even if they're all touching the same /export they should be writing to unique child directories, I think UUID generation guarantees that. You can certainly try it though...

Sorry, I meant setting ranges as a potential *future* solution for me to implement. Just in general I have never considered this use-case, so I need some time to think about it I guess. Any other info you can give about your setup is helpful too

**Comment by KinOSurvival** [comment]
I'll see whether I can assign different fsid by building different binary, each hard coding with a specific range.

Thanks for all the helpful info
