### ISSUE TITLE
Cross project usage of snapshots on GCP

### ISSUE THREAD

**Issue by stiller-leser** [kubernetes-incubator/external-storage#850]
Hi everybody,

I just wanted to ask if it will be or already is possible to use snapshots from one project in a K8S cluster in another project? The scenario would - for example - be a CI/CD project where the snapshots are stored and a production project, in whose clusters the snapshots from the CI/CD project will be used? I could not find any documentation for this in the GCE examples.

Using the Google SDK (e.g. for Ruby), this is already possible, see https://stackoverflow.com/a/29609358/1994642 for a basic description.

**Comment by msau42** [comment]
cc @jingxu97

**Comment by stiller-leser** [comment]
Concept has been explained here: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/224 - Closing this issue
