### ISSUE TITLE
[flex-provisioner]  How can interface from flex-provision.sh?

### ISSUE THREAD

**Issue by moonek** [kubernetes-incubator/external-storage#868]
If I print `$*` from the `doprovision()` function, there is only `kubernetes.io/pvOrVolumeName` and `parameters` of `StorageClass`.

Can't get pvc `capacity` information from `doprovision()`?

And Can I set the value of the parameter in the `doprovision()` function and return it?

**Comment by wongma7** [comment]
https://github.com/kubernetes-incubator/external-storage/blob/master/flex/pkg/volume/provision.go#L110 only passes `PVName`, we will need to make it pass capacity as well, manually

For return value, I think the only thing you can do is return some json stdout and change the code to parse it https://github.com/kubernetes-incubator/external-storage/blob/master/flex/pkg/volume/provision.go#L114 .

I have not used flex myself

**Comment by moonek** [comment]
OK, After all, I knew I had to modify the `provision.go`.
I was able to import it in any way I wanted by referring to other sources.

Like this..
```
capacity := volumeOptions.PVC.Spec.Resources.Requests[v1.ResourceName(v1.ResourceStorage)]
requestBytes := capacity.Value()
requestGiB := int(util.RoundUpSize(requestBytes, 1024*1024*1024))
extraOptions["capacity"] = strconv.Itoa(requestGiB) + "G"
```
I felt that I needed to study golang.
Thank you.
