### ISSUE TITLE
Implementation of `LabelSelector` for snapshots

### ISSUE THREAD

**Issue by alpe** [kubernetes-incubator/external-storage#875]
This is more a question why they are [disabled](https://github.com/kubernetes-incubator/external-storage/blob/master/snapshot/cmd/snapshot-pv-provisioner/snapshot-pv-provisioner.go#L98)? And is there an alternative solution to this?

In my scenario I create snapshots on GCP by a `cronjob` every x hours. These snapshots are supposed to be used by a **StatefulSet** `volumeClaimTemplates` when spanning new Pods to speed up startup time (dramatically). 
Unfortunately I can not modify the `volumeClaimTemplates` to match the new snapshot name due to k8s restrictions or reuse the snapshot name as I don't want to mess with the CRDs. I am keeping a history of y-versions.

So it feels very natural to me to use the `LabelSelector` within the `volumeClaimTemplate` to select by a label rather than a name.
I could have some definition like this in my STS:
```yaml
...
  volumeClaimTemplates:
  - metadata:
      name: mydir
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: snapshot-promoter
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          group: "my_group"
        matchExpressions:
        - {key: approved, operator: Exists}
```

A modification to the provisioner could load the snapshot via Selector. With priority to the `SnapshotPVCAnnotation` and for multiple matches to the `snapshotMetadataTimeStamp`:
```go
func (p *snapshotProvisioner) loadSnapshot(options controller.VolumeOptions) (crdv1.VolumeSnapshot, error) {
	var snapshot crdv1.VolumeSnapshot
	snapshotName, ok := options.PVC.Annotations[crdclient.SnapshotPVCAnnotation]
	if ok { // by name first
		err := p.crdclient.Get().
			Resource(crdv1.VolumeSnapshotResourcePlural).
			Namespace(options.PVC.Namespace).
			Name(snapshotName).
			Do().Into(&snapshot)

		if err != nil {
			return snapshot, fmt.Errorf("failed to retrieve VolumeSnapshot %s: %v", snapshotName, err)
		}
	} else {
		// by selector
		selector := options.PVC.Spec.Selector
		if selector == nil {
			return snapshot, errors.New("no claim selector nor snapshot annotation found on PV")
		}
		if len(selector.MatchLabels) == 0 || len(selector.MatchExpressions) == 0 {
			return snapshot, errors.New("label selector must not be empty")
		}
		var snapshots crdv1.VolumeSnapshotList
		err := p.crdclient.Get().
			Resource(crdv1.VolumeSnapshotResourcePlural).
			Param("labelSelector", metav1.FormatLabelSelector(selector)).
			Do().Into(&snapshots)
		if err != nil {
			return snapshot, err
		}
		var latestTimestamp int64
		for _, s := range snapshots.Items {
			if item, ok := s.Metadata.Labels[snapshotMetadataTimeStamp]; ok {
				if newTimestamp, err := strconv.ParseInt(item, 10, 64); err == nil {
					if latestTimestamp < newTimestamp {
						snapshot = s
						latestTimestamp = newTimestamp
					}
				}
			}
		}
		if latestTimestamp == 0 {
			return snapshot, errors.New("not found")
		}
	}
	return snapshot, nil
}

```

**Comment by alpe** [comment]
Any chance to get an answer on this? I am running the provisioner with a label selector for some time now and I would like to contribute back to the project if it makes sense.

**Comment by wongma7** [comment]
@tsmetana ping, do you recall why? IMO there is no harm in propagating the claim.selector to the pv.labels. IIRC we disabled it at the time because of troubles re: how to reconcile labelselector & storageclass being set at the same time but that conversation ended a long time ago

**Comment by wongma7** [comment]
I will accept a PR that implements this

**Comment by msau42** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
The main reason why most provisioners don't support label selector is because labels have meanings. Consider PVC with this selector:

```
selector:
  matchExpressions: 
    key: zone
    operator: NotIn
    values: ["east", "west"]
```
The provisioner must be smart enough to know what "zone" means, what zones are there and choose e.g. "north".

In this particular case matching with selector has more sense. However, `pvc.spec.selector` specifies PVs considered for binding, not Snapshots considered for restoring! Does PV inherit labels from Snapshot during provisioning? If so, then it is probably fine to use the selector to select Snapshots too, because we're sure that a provisioned PV will have required labels. If the provisioned PV gets different or no labels then no, you need to find a better place to put snapshot selector. Perhaps `pvc.spec.dataSource`?

**Comment by jingxu97** [comment]
cc @xing-yang 
With the new CSI volume snapshot support, we can think about this as a feature request.
