### ISSUE TITLE
[nfs-client] Missing setup step in docs

### ISSUE THREAD

**Issue by jonaskello** [kubernetes-incubator/external-storage#887]
The readme for nfs-client has these setup steps:

1. Editing
2. Authorization

AFAICS there is no step or commands listed that creates the objects for the deployment, but there are commands to create the authorization objects under step 2.

So I think it should be something like this:

1. Editing
2. Create deployment & storage class
3. Authorization

Where step 2 "Create deployment & storage class" would be something like this:

```
kubectl apply -f deploy/deployment.yaml
kubectl apply -f deploy/class.yaml
```

Maybe this could be added to the readme?

**Comment by ShaneMalachow** [comment]
for Openshift the following commands need run as well
```
oc create -f deploy/deployment.yaml
oc create -f deploy/class.yaml
```

**Comment by ShaneMalachow** [comment]
I added the commands to the nfs-client/readme.md in PR #954 

https://github.com/kubernetes-incubator/external-storage/pull/954
