### ISSUE TITLE
Unable to provision PVC using nfs-client provisioner (read-only file system) 

### ISSUE THREAD

**Issue by platten** [kubernetes-incubator/external-storage#889]
Hello,

I have installed the nfs-client provisioner and am running into problems when trying to provision a new PVC for the test pod. Any ideas?

`I0728 15:48:45.979529       1 controller.go:615] Starting provisioner controller b6259031-927d-11e8-80f3-7ee6eeadc776!
I0728 15:48:45.989298       1 controller.go:652] Started provisioner controller b6259031-927d-11e8-80f3-7ee6eeadc776!
I0728 15:53:16.986898       1 leaderelection.go:156] attempting to acquire leader lease...
I0728 15:53:16.997395       1 leaderelection.go:178] successfully acquired lease to provision for pvc default/test-claim
I0728 15:53:17.019275       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-claim", UID:"d3ececeb-927d-11e8-912c-94c6911e2fd2", APIVersion:"v1", ResourceVersion:"3159876", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-claim"
E0728 15:53:17.021413       1 controller.go:1074] Failed to provision volume for claim "default/test-claim" with StorageClass "managed-nfs-storage": unable to create directory to provision new pv: mkdir /persistentvolumes/default-test-claim-pvc-d3ececeb-927d-11e8-912c-94c6911e2fd2: read-only file system
I072`

**Comment by wongma7** [comment]
the provisioner doesn't have write access to /persistentvolumes/. What are the permissions on this directory?

**Comment by omalley** [comment]
I had a related problem with nfs-client. In particular, I had changed the 

```volumeMounts:
  - name: nfs-client-root
     mountPath: /my-path
```

which created the new PVCs in /persistentvolumes, but the nfs mount point was /my-path. Changing the mountPath to /persistentvolumes fixed the problem.
