### ISSUE TITLE
rbd-provisioner: cannot create image in format 1 against jewel cluster with mimic rbd

### ISSUE THREAD

**Issue by cofyc** [kubernetes-incubator/external-storage#895]
I am running a ceph cluster of jewel cluster. 
rbd-provisioner is able to create image in format 1 with luminous rbd, after [upgrading to mimic](https://github.com/kubernetes-incubator/external-storage/pull/841), it fails to create image in format 1.

```
rbd: create error: 2018-07-31 04:07:44.792 7fcae8a44900 -1 librbd: Format 1 image creation unsupported. 
```

From [minic docs](http://docs.ceph.com/docs/mimic/man/8/rbd/), image format 1 is supported (although deprecated). 

I don't know if this is bug or expected behavior (may be broken if client/server not match), I created a ceph issue too: https://tracker.ceph.com/issues/25187.

Probably, we can build rbd/cephfs provisioner for different ceph releases, e.g.

- rbd-provisioner-jewel
- rbd-provisioner-luminious
- rbd-provisioner-minic

Users can choose provisioner with ceph packages same as server-side.

/cc @wongma7 
What do you think?

**Comment by wongma7** [comment]
sure, let's do it, we just need 3 dockerfiles. And I guess I will write some script so i don't have to build-push each on my local machine and I can make travis do it instead
