### ISSUE TITLE
In transit encryption

### ISSUE THREAD

**Issue by rafael-azevedo** [kubernetes-incubator/external-storage#901]
Hello, 

I dug through the documentation and do not see this referenced anywhere. Does this support in transit encryption for EFS mounts on the pods ?

**Comment by wongma7** [comment]
No, not at the moment. We won't be able to use the "mount helper" that does `mount -t efs...` (which must be a recent development...) but the stunnel method may be feasible. https://docs.aws.amazon.com/efs/latest/ug/encryption.html
/area aws/efs

**Comment by rafael-azevedo** [comment]
Thanks for the info !
