### ISSUE TITLE
[RBD Volume Provisioner] Ceph Volumes Unmount fails with reboot of the node and pods fail due to already claimed PV that has not been released

### ISSUE THREAD

**Issue by gokulpch** [kubernetes-incubator/external-storage#903]
#### Environment:

* Kubernetes HA Cluster with three Masters and the same serving as Nodes (tainted-master)

```
[root@cvim-mgmt1 ~]# kubectl get nodes -o wide
NAME         STATUS    ROLES     AGE       VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                      KERNEL-VERSION               CONTAINER-RUNTIME
cvim-mgmt1   Ready     master    3d        v1.11.1   172.29.86.34   <none>        Red Hat Enterprise Linux Server 7.4 (Maipo)   3.10.0-693.25.7.el7.x86_64   docker://18.6.0
cvim-mgmt2   Ready     master    3d        v1.11.1   172.29.86.36   <none>        Red Hat Enterprise Linux Server 7.4 (Maipo)   3.10.0-693.25.7.el7.x86_64   docker://18.6.0
cvim-mgmt3   Ready     master    3d        v1.11.1   172.29.86.37   <none>        Red Hat Enterprise Linux Server 7.4 (Maipo)   3.10.0-693.25.7.el7.x86_64   docker://18.6.0
```
* Kubernetes Version: 1.11.1-0
* Rbd_Provisioner version:  rbd-provisioner:v0.1.1(Jewel - quay.io/external_storage/rbd-provisioner:v0.1.1)
* OS: RHEL Enterprise

#### Issue:

As part of failover testing whenever a node in the cluster is rebooted, Kubernetes tries to schedule/shift the pods on the node with NodeLost status to the other nodes in the cluster, With Ceph and RBD Provisioner the volume should be mapped accordingly, but in this scenario the pod remains in Init state with the following error:

```
Aug 03 19:50:14 mgmt2 kubelet[2152]: E0803 19:50:14.576955    2152 
 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/rbd/kube:kubernetes-dynamic-pvc- 
 cc678f9c-9507-11e8-bc18-4e2db687a350\"" failed. No retries permitted until 2018-08-03 
  19:50:22.576915875 -0700 PDT m=+9808.484006754 (durationBeforeRetry 8s). Error: "Volume not 
  attached according to node status for volume \"pvc-cc028a45-9507-11e8-a125-0cc47ada5f76\" 
  (UniqueName: \"kubernetes.io/rbd/kube:kubernetes-dynamic-pvc-cc678f9c-9507-11e8-bc18- 
  4e2db687a350\") pod \"coiling-orangutan-prometheus-server-778d97f6b4-rqwpk\" (UID: 
  \"18452e29-9791-11e8-b55d-0cc47a8eb348\") "
```

In this case mgmt1 was rebooted and the status of the pod is shown as unknown, Kubelet tries to schedule the pod on mgmt2 which remains in Init state as it fails to claim the volume which has not bee released, as ceph only supports ```access_mode:RWO```, pod fails with a Multi-Attach error as shown below:

```
default       coiling-orangutan-prometheus-server-778d97f6b4-ql27p              2/2       Unknown             0          2h        192.168.0.77   mgmt1
default       coiling-orangutan-prometheus-server-778d97f6b4-rqwpk              0/2       Init:0/1            0          1m        <none>         mgmt2
```
##### Describe pod Output:

```
Events:
  Type     Reason              Age   From                     Message
  ----     ------              ----  ----                     -------
  Normal   Scheduled           1m    default-scheduler        Successfully assigned default/coiling-orangutan-prometheus-server-778d97f6b4-rqwpk to cvim-mgmt2
  Warning  FailedAttachVolume  1m    attachdetach-controller  Multi-Attach error for volume "pvc-cc028a45-9507-11e8-a125-0cc47ada5f76" Volume is already used by pod(s) coiling-orangutan-prometheus-server-778d97f6b4-ql27p
```

Once the rebooted node comes up the Init container gets terminated and the old container runs as before on the same node as before(rebooted-node).

##### Behavior with Cordon and Drain

When the same node is Cordoned and Drained the functionality works properly where the pods are evicted to a different hosts and correctly mapped with the volumes.

Are there any parameters/configuration or a cron-job that should be used to release the volumes in case of reboot?

**Comment by wongma7** [comment]
kubernetes won't be able to delete the original pod or detach the volume when the node is in `NodeLost` because it can't know if the pod is still running and reading/writing to the volume. I would raise this issue with upstream kubernetes/kubernetes because you are not the first to encounter this problem and it might be possible for kubernetes to be more intelligent about this, or at least they/we should document this behaviour.

**Comment by gokulpch** [comment]
@wongma7 Thanks for the detailed information. Need your expertise in understanding this :  Kubernetes-Controller Manager has certain flags that prompt faster discovery of nodes that are in NodeLost state (node-monitor-period, node-monitor-grace-period, pod-eviction-timeout )and when the same was observed, Kubernetes tries to schedule the pods that are in Unknown state to the other active nodes on the cluster, in this scenario should the rbd client decouple the volumes on the lost node? and is there a flag that drains the node that is lost (terminating the pod in unknown state)?

When the host is rebooted as part of functional (HA) testing i am seeing that the reboot pauses at the stage below and requires a complete power on and power off:

<img width="1031" alt="screen shot 2018-08-05 at 4 19 35 pm" src="https://user-images.githubusercontent.com/18540565/43812207-f9ffa65c-9a74-11e8-9fd5-29d5e7c19192.png">

And lastly, Kubernetes still assumes that the pod in Unknown state has a claim over the pod in lost node (Volume is already used by pod(s)) is this due to RWO access_mode support with Ceph and RWX is not supported?

**Comment by wongma7** [comment]
> in this scenario should the rbd client decouple the volumes on the lost node?

if kubernetes deletes the pods then yeah it should tell rbd to detach the volumes. 
>and is there a flag that drains the node that is lost (terminating the pod in unknown state)?

I am not aware of one. What kubernetes is supposed to do (disclaimer: from briefly looking at code, not from my own experience) is delete all the pods when/before evicting them. But I am not sure what it means for a pod to be in Unknown state, maybe that prevents the pod from being fully deleted, since its containers may still be running. And I guess if the node is in state `Lost` a `drain` command could do nothing if it is unresponsive.
> is this due to RWO access_mode support with Ceph and RWX is not supported?

Yeah, rbd cannot be attached to two nodes at once. Even if kubernetes did not throw a pre-emptive multi-attach error and tried to attach it it would fail, I think.

One common issue I have seen related to this is when `deployments` have a `Rolling` strategy instead of `Recreate`. IMO better documentation is needed upstream about these kinds of things, I am not sure it can be fixed in code.

**Comment by wongma7** [comment]
FYI @gokulpch upstream is working on this issue where volumes can't get detached from shutdown nodes. If you are in the sig-storage google group you can view https://docs.google.com/document/d/1P5dpcmqbl98z8k4Y9xM5BGTdzrsG9ZH0MPIN_wSHC-E/edit?usp=sharing_eil&ts=5b886840

**Comment by dcleric** [comment]
Hey guys,
We suffer same issue with:
ceph version 13.2.2 (02899bfda814146b021136e9d8e80eba494e1126) mimic (stable)
Kuberenetes v1.11.3
Does it have any progress except info "upstream is working on it" from the previous message?
Thanks,

**Comment by utkuozdemir** [comment]
Having the same issue.

**Comment by wtgops** [comment]
This issue is big for us now. It 's been a year and a half since last reply. Are there any news on this?
