### ISSUE TITLE
efs-provisioner keeps crashing and restarting

### ISSUE THREAD

**Issue by AMelacini** [kubernetes-incubator/external-storage#910]
Running on AWS
Using EKS for to access Kubernetes - hence RBAC for authorisation

I follow the instructions on readme: efs-provisioner keeps crashing and re-starting.

Events messages:

Successfully assigned efs-provisioner-56b989b4db-wjsnc to ip-192-168-236-223.ec2.internal
MountVolume.SetUp succeeded for volume "efs-provisioner-token-sc6f5"
MountVolume.SetUp succeeded for volume "pv-volume"
pulling image "quay.io/external_storage/efs-provisioner:latest"
Successfully pulled image "quay.io/external_storage/efs-provisioner:latest"
Created container
Started container
* Back-off restarting failed container

And then back to start

Any idea?  How shall I troubleshoot?

Cheers, Alberto

**Comment by wongma7** [comment]
Try to catch/watch its logs “kubectl logs $PODNAME”

**Comment by wongma7** [comment]
it will insta crash if:
1) FILE_SYSTEM_ID is not set
2) AWS_REGION is not set
3) it cannot find the nfs mountpoint where you mounted EFS into the pod
all should leave a log message though.

We can check the deployment yaml for errors

**Comment by AMelacini** [comment]
This is the entire deployed objects

The interesting fact is that when the container is up, I can log into efs-provisioner pod and see that efs has been mounted correctly!
Then the container crashes.... :-(

  Thanx
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
data:
  file.system.id: fs-xxxxxxxx
  aws.region: us-east-1
  provisioner.name: example.com/aws-efs
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:latest
          env:
            - name: FILE_SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: file.system.id
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: aws.region
            - name: PROVISIONER_NAME
              valueFrom:
                configMapKeyRef:
                  name: efs-provisioner
                  key: provisioner.name
            - name: AWS_ACCESS_KEY_ID
              value: XXXXXXXXXXXXXX
            - name: AWS_SECRET_ACCESS_KEY
              value: YYYYYYYYYYYYYYY
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      serviceAccount: efs-provisioner
      volumes:
        - name: pv-volume
          nfs:
            server: fs-xxxxxxxx.efs.us-east-1.amazonaws.com
            path: /
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs
provisioner: example.com/aws-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
