### ISSUE TITLE
Cache Node objects in external PVController library

### ISSUE THREAD

**Issue by verult** [kubernetes-incubator/external-storage#912]
#902 introduces topology plumbing through the library, which includes a Node get call for every volume provision operation. Since CSI depends on this library and all volumes will go through CSI in the future, we need to consider caching Node objects.

https://github.com/kubernetes-incubator/external-storage/blob/2db4446614545ef4ca87fd69ba81d24b1de390ca/lib/controller/controller.go#L1002

/assign

**Comment by wongma7** [comment]
would a (shared)informer be overkill or do you intend to roll your own caching?

**Comment by verult** [comment]
Yeah it would probably just be an informer

**Comment by msau42** [comment]
Is this issue still valid?

**Comment by verult** [comment]
Yep, the TODO is still there though the code has been moved to lib-external-provisioner. Will move this issue there.
