### ISSUE TITLE
[nfs-provisioner] Current Deployment Appears Broken

### ISSUE THREAD

**Issue by Queuecumber** [kubernetes-incubator/external-storage#913]
The yaml files for deploying the NFS provisioner appear to be broken as of d46083d75be3c046c5313c03c0b4b5f29d9b2ec2 by @wongma7 . Unless I am missing something there are many references to a service account called `nfs-provisioner` which saw its yaml file deleted and instructions for its creation removed in this commit. Indeed upon doing a fresh redeploy with these instructions I have the error message

> Error creating: pods "nfs-provisioner-" is forbidden: error looking up service account default/nfs-provisioner: serviceaccount "nfs-provisioner" not found

Additionally this commit removes the daemonset instructions for no apparent reason

**Comment by Queuecumber** [comment]
OK I think this was an out-of-date or cached on my end, the service account was moved to the top of `deployment.yaml`. This seems like a rather arbitrary place to keep it.

**Comment by wongma7** [comment]
It is a bit arbitrary, I considered putting it with the clusterroles but it doesn’t make much difference. Somebody said they’d prefer it this way and I’ve seen other yamls distributed like this. Less “kubectl create” commands to run I guess

Re: daemonset the short answer is that as of that pr it will no longer work as advertised so I went ahead and removed it. I’ll maybe add a little note explaining why it’s no longer possible on Monday

**Comment by Queuecumber** [comment]
Fair enough, thanks for the response, my current config uses the daemonset which I downloaded and customized the paths for so I'd like to hear why it wont work (in the middle of a redeploy as I type this)
