### ISSUE TITLE
[nfs-client] Pod fails to mount nfs volume

### ISSUE THREAD

**Issue by preetampvp** [kubernetes-incubator/external-storage#918]
Hi,

When I run the test pod - test-pod.yml in nfs-client, the PVC and PV are created successfully and I do not see any errors in the nfs-client-provisioner. The nfs-client-provisioner is pointing to an external nfs server and Kubernetes is deployed on prem VMs.

The pod fails to start and when I do a kubctl describe <test-pod-name> I see the below error.  I am able to successfully mount the nfs on one of the other VMs.. so not sure what the below error means or how to fix it.

If I exec into the nfs-client-provisioner I can see the nfs mounted at /nfs and any files I write to it can be seen on the other VM where it is mounted. 

The below output says it is trying to run a mounting command.. I am not sure where this mount is happening.

Thanks in advance.

```
 Warning  FailedMount            43s (x6 over 59s)  kubelet, lx-ohbnaas-mdl-01mgd01  MountVolume.SetUp failed for volume "pvc-83851ef3-9eb9-11e8-826f-005056aeaadc" : mount failed: exit status 32

Mounting command: mount
Mounting arguments: -t nfs <nfs-ip-address>:/tools/default-test-claim-pvc-83851ef3-9eb9-11e8-826f-005056aeaadc /var/lib/kubelet/pods/840dc354-9eda-11e8-826f-005056aeaadc/volumes/kubernetes.io~nfs/pvc-83851ef3-9eb9-11e8-826f-005056aeaadc

Output: mount.nfs: access denied by server while mounting <nfs-ip-address>:/tools/default-test-claim-pvc-83851ef3-9eb9-11e8-826f-005056aeaadc
```

**Comment by wongma7** [comment]
The mount is executed by kubelet and happening on the node/VM where the pod using "pvc-83851ef3-9eb9-11e8-826f-005056aeaadc" was scheduled. Does manually mounting by sshing into this VM work? Sounds like there may be some server configuration issue

**Comment by preetampvp** [comment]
@wongma7 : Thanks for the response. Yep I am able to mount the nfs volume on to the node where the pod is being scheduled. I also added securityContext:  fsGroup: 0 (as suggested in one of the stackoverflow questions) to the pod manifest but still get the same error. 

The node is running RHEL with selinux enabled, not sure if this is causing an issue.

**Comment by preetampvp** [comment]
@wongma7 

If I run the below command (the one I see when I do describe pod) directly on the node with -v flag set 

`mount -t nfs 10.32.202.179:/NaaS-Tools/default-test-claim-pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc /var/lib/kubelet/pods/cf3604b0-9f2e-11e8-826f-005056aeaadc/volumes/kubernetes.io~nfs/ -v`

I get the below.

```
mount.nfs: timeout set for Tue Aug 14 05:33:07 2018
mount.nfs: trying text-based options 'vers=4.1,addr=10.32.202.179,clientaddr=10.32.202.180'
mount.nfs: mount(2): Invalid argument
mount.nfs: trying text-based options 'vers=4.0,addr=10.32.202.179,clientaddr=10.32.202.180'
mount.nfs: mount(2): No such file or directory
mount.nfs: trying text-based options 'addr=10.32.202.179'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: trying 10.32.202.179 prog 100003 vers 3 prot TCP port 2049
mount.nfs: prog 100005, trying vers=3, prot=17
mount.nfs: trying 10.32.202.179 prog 100005 vers 3 prot UDP port 1234
mount.nfs: mount(2): Permission denied
mount.nfs: access denied by server while mounting 10.32.202.179:/NaaS-Tools/default-test-claim-pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc
```

Also wondering do I need some package installed on the Node for NFS to work?

Thanks.

**Comment by wongma7** [comment]
as long as you have something like nfs-common/nfs-client it should work.

Is your server exporting the path /NaaS-Tools/default-test-claim-pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc? `No such file or directory` is interesting. In my experience, for some NFS servers it is not sufficient to just export `/NaaS-Tools` then create a subpath `/NaaS-Tools/x` in it. Sometimes you have to explicitly export `/NaaS-Tools/x` as well. I am hazy on the details of this, sorry. https://www.reddit.com/r/linuxquestions/comments/2nmvas/mounting_an_nfs_export_subdirectory/

**Comment by preetampvp** [comment]
@wongma7 : Thanks again!

https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client - this is the one I am using.. is this the right one when you say nfs-common/nfs-client?

**More info:**

* I can create a folder in the nfs and I am able to mount it on the node

* If I manually create the folder in nfs being used by the PV and PVC and then deploy the Pod.. is works fine.. But that defeats the purpose as we want the provisioner to created the subfolder automatically before it can be assigned to the PVC and PV (in the above case the subfolder - default-test-claim-pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc).. as we are planning to create dynamic PVs.. is this the expected behaviour when I use the nfs-client.. or do I have to create the PV and PVC before I can claim it?
 
Thanks again for your time!

**Comment by wongma7** [comment]
Do you have logs of the provisioners? Kubectl logs $provisionerpodname. You’re right about the workflow: you create a pvc, the provisioner creates a unique directory on the server, then it creates a pv. Then your pod should be able to consume the pv. The provisioner is skipping the “create a subdir” step right? It should be reporting an error rather than proceeding to create a pv, the log may have some info

**Comment by preetampvp** [comment]
@wongma7: 

Good to know how it works.. Yep it looks like it is skipping the create sub dir bit.

below are the logs for the provisioner and I do not see any errors in the log. 

```
I0813 22:04:55.967042       1 controller.go:615] Starting provisioner controller e98bdf0c-9f44-11e8-b71d-dec025eeb026!
I0813 22:04:55.967182       1 controller.go:652] Started provisioner controller e98bdf0c-9f44-11e8-b71d-dec025eeb026!
W0813 22:04:55.979734       1 provisioner.go:100] path /persistentvolumes/default-test-claim-pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc does not exist, deletion skipped
I0813 22:04:55.979769       1 controller.go:1325] volume "pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc" deleted
I0813 22:04:55.982968       1 controller.go:1336] volume "pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc" deleted from database
W0813 22:04:55.985396       1 provisioner.go:100] path /persistentvolumes/default-test-claim-pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc does not exist, deletion skipped
I0813 22:04:55.985416       1 controller.go:1325] volume "pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc" deleted
I0813 22:04:55.987786       1 controller.go:1336] volume "pvc-6a56cd5d-9edd-11e8-826f-005056aeaadc" deleted from database
I0813 22:07:32.742423       1 leaderelection.go:156] attempting to acquire leader lease...
I0813 22:07:32.753002       1 leaderelection.go:178] successfully acquired lease to provision for pvc default/test-claim
I0813 22:07:32.758024       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-claim", UID:"42faea11-9f45-11e8-826f-005056aeaadc", APIVersion:"v1", ResourceVersion:"2191094", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/test-claim"
I0813 22:07:32.758081       1 controller.go:1079] volume "pvc-42faea11-9f45-11e8-826f-005056aeaadc" for claim "default/test-claim" created
I0813 22:07:32.770183       1 controller.go:1096] volume "pvc-42faea11-9f45-11e8-826f-005056aeaadc" for claim "default/test-claim" saved
I0813 22:07:32.770209       1 controller.go:1132] volume "pvc-42faea11-9f45-11e8-826f-005056aeaadc" provisioned for claim "default/test-claim"
I0813 22:07:32.770273       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"test-claim", UID:"42faea11-9f45-11e8-826f-005056aeaadc", APIVersion:"v1", ResourceVersion:"2191094", FieldPath:""}): type: 'Normal' reason: 'ProvisioningSucceeded' Successfully provisioned volume pvc-42faea11-9f45-11e8-826f-005056aeaadc
I0813 22:07:34.764453       1 leaderelection.go:198] stopped trying to renew lease to provision for pvc default/test-claim, task succeeded
```

Thanks!

**Comment by preetampvp** [comment]
Just for reference below is the manifest I am using to deploy the nfs-client.. may be I am missing something here that is causing the issue

`lx-ohbnaas-mdl-01jkn01.in.telstra.com.au:5000/nfs-client-provisioner:latest` image is just a local copy of - `quay.io/external_storage/nfs-client-provisioner:latest`

*nfs-manifest.yml*
```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: lx-ohbnaas-mdl-01jkn01.in.telstra.com.au:5000/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /nfs
          env:
            - name: PROVISIONER_NAME
              value: naas.com/nfs 
            - name: NFS_SERVER
              value: 10.32.202.179
            - name: NFS_PATH
              value: /NaaS-Tools/nfs
      nodeSelector:
        compute: "true"
        tier3: "true"
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.32.202.179
            path: /NaaS-Tools/nfs

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: naas.com/nfs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs-client-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "list", "update", "patch", "watch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---  

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: run-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
```

**Comment by preetampvp** [comment]
@wongma7 : Sorry to annoy you again.

I pulled the latest image from: https://quay.io/repository/external_storage/nfs-client-provisioner?tab=tags and still have the same issue.

when I exec into the nfs-provisioner pod I see a `/nfs` folder where the nfs is mounted too and I see a `/persistentvolumes` where I can see a subfolder for the PVC created. Wondering if the /nfs and /persistentvolumes should be the same.. what creates them? the nfs-client-provisioner binary?

Thanks!

**Comment by wongma7** [comment]
@preetampvp double sorry. Obviously our documentation is deficient if even I cannot figure out what ish appening without reading the code! Please read my last comment edited: spec.containers.volumesmounts.mountPath must be /persistentvolumes as it is hardcoded, everything else in your spec looks okay to me.

**Comment by preetampvp** [comment]
@wongma7 : Awesome!! thanks for that.. that works!! 

Just on a different note.. what happens if I scale the nfs-client deployment to 2 or more pods.. will that still work? or will that cause issue with all the pods trying to create the same PV?

Thanks again for the help.. much appreciated!!

**Comment by wongma7** [comment]
As of the latest version (3.x.x) the replicas will do leader election so only one is active at a time. In previous versions they randomly raced to lock pvc then only one would try to create a pv

**Comment by preetampvp** [comment]
Sweet thanks for the info.
