### ISSUE TITLE
The func `info` not mistake, instead of Infof

### ISSUE THREAD

**Issue by zouyee** [kubernetes-incubator/external-storage#927]
`
I0815 11:01:08.390755   24494 snapshot.go:74] snapshot %v created successfullyvol_da5621b7c6e854beb24d86063c3cd1e5_37c0f11b-1278-4d52-87f2-21c734664a82
`
1、The func `info` not mistake, instead of Infof
2、insert command args for detect

**Comment by wongma7** [comment]
thanks, merged
