### ISSUE TITLE
[NFS-Client] nfs-provisioner refuses to mount more than one nfs mount when running on the same worker

### ISSUE THREAD

**Issue by lordfolken** [kubernetes-incubator/external-storage#928]
Hello 

I'm having funky issues with the nfs-client-provisioner.  When I make a pvc and hook it to a pod all is fine. This works well, as long as i have one pod per worker. As soon as i have more pods per worker, it works fine on all the workers that are not running the nfs-client-provisoner container. The one worker with the nfs-client-provisioner mounts 1 pod. But all other pods on that node are stuck in ContainerCreating and dump the following error: Unkown error 521

even when i try to mount from the shell: 
valcaasworker01:/tmp # mount -t nfs 10.16.80.27:/k8spoc/default-nfs-gold-claim-01-pvc-e8fda661-9c99-11e8-8ba3-506b8dd6140b /tmp/mnt2
mount.nfs: Unknown error 521

As soon as I move the nfs-provisioner container away, the same mount succeeds as many times as i want. 

I randomly suspect some issue with a shared resource between container and host.

At the moment I use a node selector to move the nfs-provisioner to the master. That way it works for the moment.

**Comment by wongma7** [comment]
What is the output with `-v` added to your mount command?

**Comment by IlanStark** [comment]
Here the error message with the mount command and option -v:

valcaasworker03:~ # mount -v -t nfs 10.16.80.27:/k8spoc/default-nfs-viohello-claim-pvc-dcb481e9-a095-11e8-b25b-506b8dd6140b /mnt/
mount.nfs: timeout set for Fri Aug 17 15:49:11 2018
mount.nfs: trying text-based options 'vers=4,addr=10.16.80.27,clientaddr=10.16.80.149'
mount.nfs: mount(2): Unknown error 521
mount.nfs: Unknown error 521

**Comment by wongma7** [comment]
Hm, nothing useful unfortunately.

Could you share info about the nfs server config? Is it a typical /etc/exports? What settings does the /k8spoc export have?

There is nothing different about *how* the nfs shares are mounted, in either case kubelet is doing the same thing. The only difference is the path. So something in the nfs server config OR some setting on the worker is preventing
/a
and any subdirectory
/a/b
from being mounted on the worker at the same time.

**Comment by IlanStark** [comment]
Hi 
We found the root cause. It was the configuration of the nfs server.
Thanks for your advice.

**Comment by mjura** [comment]
@IlanStark: can please explain what was root cause of this problem? Was it secure option in `/etc/exports` ?

**Comment by IlanStark** [comment]
We use Nutanix AFS as a nfs Server. Here you have no access to the file "exports". We use the Nutanix Prism Web Console and here we missunderstood the settings. You can chouse between two option
non-sharded-Directories (this we set bevor) and 
Sharded-Directories (is now the correct setting)
