### ISSUE TITLE
cephfs storage class create pvc error 

### ISSUE THREAD

**Issue by mgxian** [kubernetes-incubator/external-storage#934]
the erro message is as followed
```sh
cannot create secrets in the namespace "default"
```

I think the cluster rule should add secret resource operate permission
```sh
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-provisioner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]
```
modify the clusterrole.yaml

I get my test pass

**Comment by MartinForReal** [comment]
+1

**Comment by wongma7** [comment]
the idea is to configure secretNamespace and create a role/rolebinding so that the secret permissions are limited to that namespace: https://github.com/kubernetes-incubator/external-storage/pull/523

Documentation might need updating.

/area ceph/cephfs

**Comment by MartinForReal** [comment]
Newly created secret is used for pvc mounting. And it is very convenient for end user to use cephfs pv

**Comment by ktpktr0** [comment]
I have tested that it is possible to create a pv in the default namespace.

The following files need to be modified to default to namespace.
Ceph-secret.yaml
Cephfs-storageclass.yaml

**Comment by mgxian** [comment]
I deploy the `cephfs provisioner` in the `kube-system` namespace, then create pvc in `default` namespace, if I did not add permission of `secrets` in the cluster role yaml file, I got the error that I describe before

**Comment by ktpktr0** [comment]
Add a secret at the end of ClusterRole.yaml，You can successfully create

- apiGroups: [""]
     Resources: ["secrets"]
     Verbs: ["create", "get", "delete"]

**Comment by mgxian** [comment]
got it. thanks !

**Comment by wongma7** [comment]
would these steps work instead https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/cephfs/deploy#install-with-rbac-roles
