### ISSUE TITLE
Cephfs-provisioner cannot create a pv using a user other than admin

### ISSUE THREAD

**Issue by ktpktr0** [kubernetes-incubator/external-storage#941]
For example: k8s
step:
1, create k8s users and authorize
Ceph auth get-or-create client.k8s mon 'allow r' osd 'allow rwx pool=k8s, allow rw pool=cephfs_data' mds 'allow rw' -o ceph.client.k8s.keyring

2. Copy ceph.client.k8s.keyring to the k8s node

3, create ceph-k8s-secret.yaml

4, modify cephfs-storageclass.yaml for k8s users

Have the following logs:

[root@k8s-master1 ~]# kubectl describe pvc
Name: claim
Namespace: default
StorageClass: cephfs
Status: Pending
Volume:
Labels: <none>
Annotations: volume.beta.kubernetes.io/storage-class=cephfs
               Volume.beta.kubernetes.io/storage-provisioner=ceph.com/cephfs
Finalizers: [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
Events:
  Type Reason Age From Message
  ---- ------ ---- ---- -------
  Normal Provisioning 1m ceph.com/cephfs_cephfs-provisioner-f5c484678-slgdl_7131ac2f-a41f-11e8-8afb-0a580af4024b External provisioner is provisioning volume for claim "default/claim"
  Normal ExternalProvisioning 7s (x9 over 1m) persistentvolume-controller waiting for a volume to be created, either by external provisioner "ceph.com/cephfs" or manually created by system administrator
[root@k8s-master1 ~]# kubectl get pvc
NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGECLASS AGE
Claim Pending cephfs 13m

[root@k8s-master2 ~]# kubectl logs -f cephfs-provisioner-f5c484678-slgdl -n kube-system
I0820 02:19:18.481942 1 cephfs-provisioner.go:411] Creating CephFS provisioner ceph.com/cephfs with identity: cephfs-provisioner-1, secret namespace:
I0820 02:19:18.482409 1 leaderelection.go:185] attempting to acquire leader lease kube-system/ceph.com-cephfs...
I0820 02:19:36.112583 1 leaderelection.go:194] successfully acquired lease kube-system/ceph.com-cephfs
I0820 02:19:36.114808 1 controller.go:597] Starting provisioner controller ceph.com/cephfs_cephfs-provisioner-f5c484678-slgdl_7131ac2f-a41f-11e8-8afb-0a580af4024b!
I0820 02:19:36.114893 1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"ceph.com-cephfs", UID:"cbaf28f9-a1ed- 11e8-9ee3-000c294d0fb7", APIVersion:"v1", ResourceVersion:"3018535", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' cephfs-provisioner-f5c484678-slgdl_7131ac2f-a41f-11e8-8afb- 0a580af4024b became leader
I0820 02:19:36.215440 1 controller.go:646] Started provisioner controller ceph.com/cephfs_cephfs-provisioner-f5c484678-slgdl_7131ac2f-a41f-11e8-8afb-0a580af4024b!
I0820 02:20:18.989953 1 controller.go:948] provision "default/claim" class "cephfs": started
I0820 02:20:18.995540 1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim", UID:"953e2322-a41f-11e8-a3ef-000c294d0fb7" , APIVersion:"v1", ResourceVersion:"3018627", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/claim"

Setting all permissions is also unsuccessful

Client.k8s
         Key: AQAvF2hbVTeJLRAAMiJo36aXvnWHtK0qA39LLQ==
         Caps: [mds] allow rwx
         Caps: [mon] allow rwx
         Caps: [osd] allow rwx pool=k8s, allow rwx pool=cephfs_data

**Comment by wongma7** [comment]
is that where the pod logs end?

**Comment by ktpktr0** [comment]
Cephfs-provisioner and pvc logs。
When I set this permission, it succeeded.

client.k8s
        key: AQAvF2hbVTeJLRAAMiJo36aXvnWHtK0qA39LLQ==
        caps: [mds] allow *
        caps: [mon] allow *
        caps: [osd] allow rwx pool=k8s, allow rwx pool=cephfs_data

But this is not safe for ceph

**Comment by ktpktr0** [comment]
I solved this problem

The StorageClass method requires the following permissions due to the need to authorize dynamically created users:
Ceph auth caps client.k8s mon 'allow rwx' osd 'allow rw pool=cephfs_data' mds 'allow rwp'
which is:
Client.k8s
Caps: [mds] allow rwp
Caps: [mon] allow rwx
Caps: [osd] allow rw pool=cephfs_data

But still feels that the permissions are relatively large

**Comment by kaybinwong** [comment]
@ktpktr0 i still cannot fix this problem. what had i done wrongly? plz help.
here is the pod logs.
```
W0905 05:54:22.966822       1 controller.go:746] Retrying syncing claim "default/claim1" because failures 14 < threshold 15
E0905 05:54:22.966858       1 controller.go:761] error syncing claim "default/claim1": failed to provision volume with StorageClass "cephfs": exit status 1
I0905 05:54:22.967359       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim1", UID:"36b0663f-b0ae-11e8-a824-00163e0c28ae", APIVersion:"v1", ResourceVersion:"109067", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": exit status 1
I0905 06:11:02.967090       1 controller.go:987] provision "default/claim1" class "cephfs": started
I0905 06:11:02.970022       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim1", UID:"36b0663f-b0ae-11e8-a824-00163e0c28ae", APIVersion:"v1", ResourceVersion:"109067", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/claim1"
E0905 06:16:03.131154       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-77868e04-b0d2-11e8-915b-bacb3dacbf8f" for "kubernetes-dynamic-user-77868e4d-b0d2-11e8-915b-bacb3dacbf8f", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 364, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 358, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 228, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
  File "/usr/local/bin/cephfs_provisioner", line 112, in volume_client
    self._volume_client.connect(None)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 471, in connect
    self.fs.mount()
  File "cephfs.pyx", line 548, in cephfs.LibCephFS.mount (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/cephfs/pyrex/cephfs.c:5648)
cephfs.Error: (110, 'error calling ceph_mount: error code 110')
```

**Comment by ktpktr0** [comment]
@kaybinwong If the permissions are correct, delete the pvc and storageclass, and the storageclass namespace must be the same as the secret.

**Comment by kaybinwong** [comment]
@ktpktr0 ns & secret are already in the same namespace, but still got the same error.
here is my yaml config  https://github.com/kaybinwong/k8s-cephfs

**Comment by ktpktr0** [comment]
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cephfs-provisioner
  namespace: cephfs
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "delete"]

resources: ["secrets"] This part is newly added

**Comment by kaybinwong** [comment]
the same. logs are below.
```
I0906 03:32:38.905045       1 cephfs-provisioner.go:411] Creating CephFS provisioner ceph.com/cephfs with identity: cephfs-provisioner-1, secret namespace: 
I0906 03:32:38.906609       1 leaderelection.go:185] attempting to acquire leader lease  cephfs/ceph.com-cephfs...
I0906 03:32:38.917862       1 leaderelection.go:194] successfully acquired lease cephfs/ceph.com-cephfs
I0906 03:32:38.918038       1 controller.go:631] Starting provisioner controller ceph.com/cephfs_cephfs-provisioner-7b96c69b7c-kjctl_8112b792-b185-11e8-a79e-8ae7e73f3091!
I0906 03:32:38.918565       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"cephfs", Name:"ceph.com-cephfs", UID:"8113daee-b185-11e8-a824-00163e0c28ae", APIVersion:"v1", ResourceVersion:"265527", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' cephfs-provisioner-7b96c69b7c-kjctl_8112b792-b185-11e8-a79e-8ae7e73f3091 became leader
I0906 03:32:39.025270       1 controller.go:680] Started provisioner controller ceph.com/cephfs_cephfs-provisioner-7b96c69b7c-kjctl_8112b792-b185-11e8-a79e-8ae7e73f3091!
I0906 03:32:45.277053       1 controller.go:987] provision "default/claim1" class "cephfs": started
I0906 03:32:45.279506       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim1", UID:"7d72f6fc-b185-11e8-a824-00163e0c28ae", APIVersion:"v1", ResourceVersion:"265544", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/claim1"
E0906 03:37:45.482958       1 cephfs-provisioner.go:158] failed to provision share "kubernetes-dynamic-pvc-84dfca5b-b185-11e8-a79e-8ae7e73f3091" for "kubernetes-dynamic-user-84dfca94-b185-11e8-a79e-8ae7e73f3091", err: exit status 1, output: Traceback (most recent call last):
  File "/usr/local/bin/cephfs_provisioner", line 364, in <module>
    main()
  File "/usr/local/bin/cephfs_provisioner", line 358, in main
    print cephfs.create_share(share, user, size=size)
  File "/usr/local/bin/cephfs_provisioner", line 228, in create_share
    volume = self.volume_client.create_volume(volume_path, size=size, namespace_isolated=not self.ceph_namespace_isolation_disabled)
  File "/usr/local/bin/cephfs_provisioner", line 112, in volume_client
    self._volume_client.connect(None)
  File "/lib/python2.7/site-packages/ceph_volume_client.py", line 471, in connect
    self.fs.mount()
  File "cephfs.pyx", line 548, in cephfs.LibCephFS.mount (/home/jenkins-build/build/workspace/ceph-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/13.2.1/rpm/el7/BUILD/ceph-13.2.1/build/src/pybind/cephfs/pyrex/cephfs.c:5648)
cephfs.Error: (110, 'error calling ceph_mount: error code 110')
W0906 03:37:45.483080       1 controller.go:746] Retrying syncing claim "default/claim1" because failures 0 < threshold 15
E0906 03:37:45.483122       1 controller.go:761] error syncing claim "default/claim1": failed to provision volume with StorageClass "cephfs": exit status 1
I0906 03:37:45.483233       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim1", UID:"7d72f6fc-b185-11e8-a824-00163e0c28ae", APIVersion:"v1", ResourceVersion:"265544", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "cephfs": exit status 1
I0906 03:38:00.483281       1 controller.go:987] provision "default/claim1" class "cephfs": started
I0906 03:38:00.485966       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"claim1", UID:"7d72f6fc-b185-11e8-a824-00163e0c28ae", APIVersion:"v1", ResourceVersion:"265544", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/claim1"
```

**Comment by kaybinwong** [comment]
with rbd by using the ceph osd pool k8s is working. dose the sc.yaml should use the pool ?

**Comment by kaybinwong** [comment]
in the end, i create the ceph pool manually. and it works.
```
[root@a-docker-cluster01 ceph-cluster]# ceph-deploy mds create a-docker-cluster02 a-docker-cluster03
....
[root@a-docker-cluster01 ceph-cluster]# ceph -s
    cluster 7ac7585e-4ce8-4688-bff2-bd2db8541d88
     health HEALTH_OK
     monmap e2: 3 mons at {a-docker-cluster01=172.18.88.200:6789/0,a-docker-cluster02=172.18.88.201:6789/0,a-docker-cluster03=172.18.88.202:6789/0}
            election epoch 14, quorum 0,1,2 a-docker-cluster01,a-docker-cluster02,a-docker-cluster03
     osdmap e16: 3 osds: 2 up, 2 in
            flags sortbitwise,require_jewel_osds
      pgmap v1414: 320 pgs, 2 pools, 0 bytes data, 1 objects
            222 MB used, 186 GB / 196 GB avail
                 320 active+clean
[root@a-docker-cluster01 ceph-cluster]# ceph fs ls
No filesystems enabled
[root@a-docker-cluster01 ceph-cluster]# ceph osd pool create cephfs_data 128
pool 'cephfs_data' created
[root@a-docker-cluster01 ceph-cluster]# ceph osd pool create cephfs_metadata 128
pool 'cephfs_metadata' created
[root@a-docker-cluster01 ceph-cluster]#  ceph fs new cephfs cephfs_metadata cephfs_data
new fs with metadata pool 3 and data pool 2
[root@a-docker-cluster01 ceph-cluster]# ceph fs ls
name: cephfs, metadata pool: cephfs_metadata, data pools: [cephfs_data ]
[root@a-docker-cluster01 ceph-cluster]# ceph mds stat 
e6: 1/1/1 up {0=a-docker-cluster02=up:active}, 1 up:standby
[root@a-docker-cluster01 ceph-cluster]# kubectl get pvc
NAME      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
claim1    Bound     pvc-cec53eed-b193-11e8-a824-00163e0c28ae   1Gi        RWX            cephfs         26m
```

**Comment by ktpktr0** [comment]
The mds service is a necessary condition for cephfs, and the next step is to create a cephfs file system. You have not done the necessary steps before, of course, you can't succeed.
