### ISSUE TITLE
Can anyone release a new version with `Retain` Reclaim Policy  support?

### ISSUE THREAD

**Issue by weekface** [kubernetes-incubator/external-storage#944]
With this [pr](https://github.com/kubernetes-incubator/external-storage/pull/776), we can use `Retain` reclaim policy. But there is no docker image released in [quay.io](https://quay.io/repository/external_storage/local-volume-provisioner?tab=tags).

Can anyone release a new version image with this feature support?

**Comment by weekface** [comment]
@wongma7

**Comment by wongma7** [comment]
@msau42 time for `v2.2.0`?

**Comment by msau42** [comment]
"latest" image has been pushed, validating e2e before tagging 2.2.0

**Comment by msau42** [comment]
2.2.0 has been tagged

**Comment by msau42** [comment]
@wongma7 can you tag "local-volume-provisioner-v2.1.0" in github after these have been merged:
https://github.com/kubernetes-incubator/external-storage/pull/951
https://github.com/kubernetes-incubator/external-storage/pull/952

**Comment by msau42** [comment]
new container image has been push, and github has been tagged. Thanks!

/close

**Comment by innovia** [comment]
label should be `v2.1.0-k8s1.11`
https://quay.io/repository/external_storage/efs-provisioner?tab=tags

**Comment by msau42** [comment]
The fix for the local volume provisioner is tagged at: local-volume-provisioner-v2.2.0
