### ISSUE TITLE
RBAC: tell people to use upstream system: bindings+roles when possible, limit endpoints permissions

### ISSUE THREAD

**Issue by wongma7** [kubernetes-incubator/external-storage#948]
I added endpoints permissions to clusterroles. These are excessive. Since the endpoints object is hardcoded to live in kube-system, better would be to copy upstream's "leader-lock-" role+rolebinding pattern to limit the permissions to kube-system https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/namespace-roles.yaml#L57

Moreover, once the upstream bootstrap `system:` roles are updated for this leaderelection stuff we should tell people to use those instead of distributing our own RBAC objects, where possible (e.g. nfs-provisioner needs extra permissions...most others don't)

**Comment by wongma7** [comment]
maybe make the namespace for the endpoints object configurable eventually. That would be even more secure, in some sense, since we could isolate the provisioner's permissions over endpoints to its own namespace.

**Comment by whereisaaron** [comment]
@wongma7 note that the `cephfs-provisioner` RBAC is missing the ClusterRole permission for the default behavior to manage the Ceph per-PVC secrets in the same namespace as the PVCs. Also, the README example suggests storing the admin secret in `kube-system` which the `cephfs-provisioner` then can't get with the sample RBAC.
