### ISSUE TITLE
[local-volume] Add e2es against local cluster

### ISSUE THREAD

**Issue by msau42** [kubernetes-incubator/external-storage#950]
Similar to the nfs provisioner tests, we should add some e2es for the local volume provisioner to make it easier to validate changes without needing to update the kubernetes/kubernetes e2e tests every time.  We may even want to consider moving the provisioner tests there to this repo.

/area local-volume

**Comment by wongma7** [comment]
Happy to help with this. Until https://github.com/kubernetes/kubernetes/issues/66649 is resolved, running tests out of tree will be a pain. Travis is good enough for basic validation, <20 mins to build and run e2e tests

**Comment by cofyc** [comment]
I'm working on some tasks on local volume provisioner. I'll take a look.
/assign

**Comment by msau42** [comment]
Moving issue to new repo: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/4
/close
