### ISSUE TITLE
Consolidate local provisioner spec examples with helm examples

### ISSUE THREAD

**Issue by msau42** [kubernetes-incubator/external-storage#958]
After #946 is done.

Also requires coordination to update the GKE docs to point to the new location.

/assign
/area local-volume

**Comment by cofyc** [comment]
/unassign
It seems like you need to update the GKE docs which is beyond my ability.

**Comment by msau42** [comment]
Migrating to new repo: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/7
