### ISSUE TITLE
 nfs-client-provisioner mount failed

### ISSUE THREAD

**Issue by lizhiyong2000** [kubernetes-incubator/external-storage#960]
Hello

I'm having issues with the nfs-client-provisioner. When a POD with a PVC created with the NFS storage, the PV status is bound, but the POD 
is always in pending status for mounting failure.

PV status:

pvc-7d6877db-a73c-11e8-ac32-64006a90f782   1Mi        RWX            Delete           Bound     default/test-claim  

Pod :

  Warning  FailedMount       13s (x6 over 30s)  kubelet, lizhiyong-pc  MountVolume.SetUp failed for volume "pvc-7d6877db-a73c-11e8-ac32-64006a90f782" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 192.168.2.42:/opt/data/k8s/default-test-claim-pvc-7d6877db-a73c-11e8-ac32-64006a90f782 /var/lib/kubelet/pods/7d6eae7b-a73c-11e8-ac32-64006a90f782/volumes/kubernetes.io~nfs/pvc-7d6877db-a73c-11e8-ac32-64006a90f782
Output: mount.nfs: mounting 192.168.2.42:/opt/data/k8s/default-test-claim-pvc-7d6877db-a73c-11e8-ac32-64006a90f782 failed, reason given by server: No such file or directory

the NFS server (192.168.2.42) exports /opt/data/k8s to remote.

I'm not sure this is a nfs-client-provisioner 's bug or a Kubernetes (using Rancher)'s bug, but sever days ago it worked, yestordy I updated the Rancher version, and redeployed the container.

My question is mounting nfs diretory /opt/data/k8s/storage-mongo-persistent-storage-mongodb-2-pvc-d15762d0-a73a-11e8-ac32-64006a90f782 is correct ? the directory storage-mongo-persistent-storage-mongodb-2-pvc-d15762d0-a73a-11e8-ac32-64006a90f782 does not exist in NFS server directory /opt/data/k8s/, why not mount /opt/data/k8s/ and mkdir storage-mongo-persistent-storage-mongodb-2-pvc-d15762d0-a73a-11e8-ac32-64006a90f782?

Thanks for helping.

**Comment by Zer0-bit** [comment]
Hi, same for me, i download the manifest file,add the fs-id, aws zone and the DNS to the appropriate fields and kubectl apply the file.
The pod fails to mount the volume, the bellow msg is thrown after a bit:

> Unable to mount volumes for pod "efs-provisioner-5f6fbcf8db-nbrls_qa(628a00ad-a969-11e8-b849-02276bad7b68)": timeout expired waiting for volumes to attach or mount for pod "qa"/"efs-provisioner-5f6fbcf8db-nbrls". list of unmounted volumes=[pv-volume]. list of unattached volumes=[pv-volume token_name] 


Tried multiple times with different EFS volumes as well, i always make sure the EFS volume is in the same zone as the pod.

**Comment by lizhiyong2000** [comment]
yaml files for your information, it worked previously, directory like storage-mongo-persistent-storage-mongodb-2-pvc-d15762d0-a73a-11e8-ac32-64006a90f782 was automatically created ever, but now it was not created.



[NFS.zip](https://github.com/kubernetes-incubator/external-storage/files/2322081/NFS.zip)

**Comment by wongma7** [comment]
@lizhiyong2000 can you try changing
```
          volumeMounts:
            - name: nfs-client-root
              mountPath: /opt/data/k8s
```
to
```
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
```
because the path is hardcoded. I cannot explain from looking at git history why it worked previously and not now but I think that is what's wrong.

**Comment by lizhiyong2000** [comment]
@wongma7  I tried and it worked, thanks for your help
