### ISSUE TITLE
AliCloud Provisioner

### ISSUE THREAD

**Issue by asakapab0i** [kubernetes-incubator/external-storage#965]
I can't help but noticed there is no provisioner for Alicloud? Can we add this? Is there a way I can help in adding this feature?

**Comment by jia-jerry** [comment]
I happened to find this repo https://github.com/AliyunContainerService/alicloud-storage-provisioner. It seems to be opensourced several days ago.

**Comment by asakapab0i** [comment]
Awesome thanks!
