### ISSUE TITLE
Not clear how data could be pre-loaded to a local PV

### ISSUE THREAD

**Issue by nyurik** [kubernetes-incubator/external-storage#972]
I described this issue in the [stackoverflow post](https://stackoverflow.com/questions/52214353/pre-populating-local-ssd-disk-in-gcp-kubernetes-for-readonly-multipods-usage):

There seems to be no easy way to have multiple pods (could be multiple instances of the same pod, or different), share the same local SSD drive in a read-only mode. The drive would need to be initialized somehow with a large dataset, but that initialization cannot be easily orchestrated by k8s.

Thanks!

**Comment by msau42** [comment]
Hi @nyurik does the init container approach mentioned in that post work?  Instead of using a hostpath volume, just replace it with a local PV.

**Comment by nyurik** [comment]
@msau42 the init container approach would work, but has one issue - I cannot get multiple-read-only persisted google disks mounted "temporarily", so that I can copy their data to the local SSD and detach them.  Despite marking it as "readonly" everywhere, and requesting pvc to attach as readonlymany, the system is extremelly unstable. It seems like despite the settings, it attaches it as RW to the first node, thus refusing to attach more copies to others :(

**Comment by msau42** [comment]
Have you tried these instructions to mount GCE PDs as read only many?
https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/readonlymany-disks

**Comment by msau42** [comment]
Note that for GCE PDs, all users of the PD have to mount it as read only.  Even if you have one user mount it as writable, then nobody else can mount it.

**Comment by nyurik** [comment]
@msau42 thanks for the link, but I think I did exactly that. And yes, somehow the first instance ends up as RW, thus causing all these problems.  I will try it again to make sure, it is always possible i had a typo somewhere.

**Comment by msau42** [comment]
Let me know if that doesn't work.  As long as you set volumeMount.persistentVolumeClaim.readOnly = true on all your pods using GCE PD, then it should be attachable across multiple nodes.
