### ISSUE TITLE
How to create a hostPath with specific uid:gid with local-volume-provisioner?

### ISSUE THREAD

**Issue by kuznero** [kubernetes-incubator/external-storage#975]
If it is not currently possible through configuration, can you please guide me in the local-volume code base such that I properly determine where I can change it to achieve `chown -R uid:gid $host_path` effect.

**Comment by msau42** [comment]
Hi can you clarify the issue you are seeing?  Is it that you're running the local-volume-provisioner as a non-root user and so it doesn't have permissions to read the discovery directories?

**Comment by kuznero** [comment]
@msau42 no, the scenario is typical in the sense that local-volume-provisioner is actually running as root (which is typical). But as a result it create folders with `root:root` ownership attributes. Now, imagine you are trying to run Elasticsearch cluster that is not running as root, but as `1000:1000`. It will simply be unable to right to the folder with `root:root` attributes.

**Comment by msau42** [comment]
The local volume provisioner does not create folders for use by local PVs.  It only discovers mount points that have been placed underneath the discovery directories.  So it shouldn't matter to the workload what permissions the discovery directory has, only the permissions of the mounts inside them will matter.

**Comment by kuznero** [comment]
It actually does create folders. Tested.

**Comment by msau42** [comment]
Can you give an example your local PV spec and the config of your local provisioner?

**Comment by kuznero** [comment]
PV is not created at the time when `local-volume-provisioner` is deployed. The point was to auto-create required directories before deploying app definitions, including PVs, etc.

**Comment by kuznero** [comment]
Sounds interesting! That was a long path to figure this out :) Is it possible for you to give an example for `hostPath` volume that will create the folder if it does not exist? Last time I tested PV that points to non-existing path it complained.

**Comment by msau42** [comment]
Here's an example of a pod using hostpath volumes:
https://kubernetes.io/docs/concepts/storage/volumes/#example-pod-2

**Comment by kuznero** [comment]
```
In addition to the required path property, user can optionally specify a type for a hostPath volume.
The supported values for field type are: DirectoryOrCreate, ...
```

Excellent! Thanks a lot! Will stop (mis-)using `local-volume-provisioner` for that.

**Comment by kuznero** [comment]
But perhaps I was a bit too fast. Will `hostPath` allow to specify `uid:gid` for the path to be created?

**Comment by msau42** [comment]
No, hostpath volumes do not perform any permissions management.  You can use an init container to set the appropriate permissions as needed.

> the files or directories created on the underlying hosts are only writable by root. You either need to run your process as root in a privileged Container or modify the file permissions on the host to be able to write to a hostPath volume

**Comment by kuznero** [comment]
That is a much better option! Thanks for help, @msau42! Closing.
