### ISSUE TITLE
Problems building the go stuff

### ISSUE THREAD

**Issue by rhugga** [kubernetes-incubator/external-storage#976]
I'm new to go and trying to build this on OEL7 and getting this error:

[root@2c0a6a0a01eb flex]# make
CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o flex-provisioner ./cmd/flex-provisioner
_/root/external-storage/flex/cmd/flex-provisioner
cmd/flex-provisioner/main.go:86:43: cannot use clientset (type *"k8s.io/client-go/kubernetes".Clientset) as type "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes".Interface in argument to volume.NewFlexProvisioner:
        *"k8s.io/client-go/kubernetes".Clientset does not implement "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes".Interface (wrong type for Admissionregistration method)
                have Admissionregistration() "k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1".AdmissionregistrationV1beta1Interface
                want Admissionregistration() "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1".AdmissionregistrationV1beta1Interface
cmd/flex-provisioner/main.go:89:41: cannot use clientset (type *"k8s.io/client-go/kubernetes".Clientset) as type "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes".Interface in argument to controller.NewProvisionController:
        *"k8s.io/client-go/kubernetes".Clientset does not implement "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes".Interface (wrong type for Admissionregistration method)
                have Admissionregistration() "k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1".AdmissionregistrationV1beta1Interface
                want Admissionregistration() "github.com/kubernetes-incubator/external-storage/vendor/k8s.io/client-go/kubernetes/typed/admissionregistration/v1beta1".AdmissionregistrationV1beta1Interface
make: *** [all] Error 2

**Comment by wongma7** [comment]
have you cloned the repository into your GOPATH?
