### ISSUE TITLE
rbd support

### ISSUE THREAD

**Issue by kfox1111** [kubernetes-incubator/external-storage#99]
Currently, I have to build a custom version of the kube-controler-manager to add the correct version of ceph rbd tools to support dynamic rbd provisioning.

Ideally the code would be moved out to function like the external cephfs provisioner so that a prebacked kube-rbd-jewel container can be added too.

**Comment by wongma7** [comment]
Initial move has completed: at https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/rbd and the initial version has been pushed to "quay.io/external_storage/rbd-provisioner:v0.1.0"
