### ISSUE TITLE
reclaimPolicy Retain leads to deletion

### ISSUE THREAD

**Issue by flah00** [kubernetes-incubator/external-storage#998]
When I [create](https://gist.github.com/flah00/a5e35357529ceac782b6220c0ca4f21e) an efs-provisioner, I set the `reclaimPolicy` to `Retain`. However, when I delete my PVCs, the directories are deleted. Am I misunderstanding the intent or is this a bug?

**Comment by wongma7** [comment]
I think efs-provisioner:v0.1.2 is too old

**Comment by flah00** [comment]
derp! my eyes flipped it, so i read v1.0.2... i'll look into upgrading, thanks!
